### ISSUE TITLE
Configurable value of `preferred_username` claim

### ISSUE THREAD

**Issue by theSuess** [kanidm/kanidm#1023]
**Is your feature request related to a problem? Please describe.**

When connecting to external systems using OIDC, the preferred_username attribute equals the full spn, including `@idm.example.com`. In my opinion, this results in "ugly" usernames for third party applications, so I would like to have this set to just the name.

**Describe the solution you'd like**
Either introducing a configuration option or changing the default for the claim.

**Describe alternatives you've considered**
Introducing a claim-mapping system (seen for example in KeyCloak) using either a key<->value mapping or embedded scripting language. This seems too much for the issue at hand though

**Comment by yaleman** [comment]
I could see a two-step lifecycle for implementation of this feature:

1. config file option for the server `oidc_short_preferred_username` (bool) which sets `preferred_username` to `name` when it's true, and `spn` when it's false.
2. A claim-mapping system which can apply to either global config or on a per-RS basis allowing `oidc_field=kanidm_field` settings.


Embedded scripting? oh noooooooo 😄

**Comment by Firstyear** [comment]
I'd rather the bool than embedded scripting. Too much surface area for testing.

**Comment by theSuess** [comment]
Then I'll work on implementing the option first and take a look on how to structure claim-mapping second. Will have to familiarize myself with the backend code anyway.

**Comment by Firstyear** [comment]
I don't think a claim mapping is needed if we have the bool method? Anyway, @theSuess the code you want is likely in kanidmd/idm/src/idm/oauth2.rs which defines how an oauth2 config is parsed and handled, and kanidmd/idm/src/constants/schema.rs line 1272 which defines the database schema of a oauth2 description. You'll probably need to chuck in a new bool similar to JSON_SCHEMA_ATTR_OAUTH2_ALLOW_INSECURE_CLIENT_DISABLE_PKCE . The uuid's are from kanidmd/idm/src/constants/uuids.rs. 

There is a plan to clean these definitions up soon, but that shouldn't affect anything you do here. :)
