### ISSUE TITLE
OAuth2 API endpoints return secrets by default

### ISSUE THREAD

**Issue by yaleman** [kanidm/kanidm#1063]
### Short description of issue

The following endpoints are query-able and return the `oauth2_basic_secret` field to users with permission.

* `/v1/oauth2`
* `/v1/oauth2/:id` (Where `:id` is currently the string-type `oauth_rs_name`)

I suggest this should require an explicit call to an API endpoint (such as `/v1/oauth2/:id/secret`, or `/v1/oauth2/:id/_attr/oauth2_basic_secret`) to get it. 

The driver for this is that I'm querying the current endpoints to return basic information for UI things, and... getting the secret should be an explicit call.

The only current dependency on this API element (I hope!) is the CLI, where it'd have to make an extra call in `kanidm system oauth2 get <name>` - and I suggest an invocation flag be added to *that* to return the key as well.

### Kanidm version (and git commit)

Current as of 2022-09-19

### Operating System / Version

All

**Comment by Firstyear** [comment]
At the moment the ability to see that secret is pretty tightly locked to oauth2 administration roles however. So it's not a "huge" risk.

I think it could be good to split this to an api that you have to explicitly request the secret from, but if you have that permission you can just request the secret anyway, what makes that different to current where you need that permission? Is it more just about "don't get it unless you really want it?"

**Comment by yaleman** [comment]
>  Is it more just about "don't get it unless you really want it?"

Pretty much - to display a list of the OAuth2 RP's in the UI, I need just their descriptive information (id, name, origin), not the secret keys behind them. We should only pull/transmit secrets when absolutely necessary.

**Comment by Firstyear** [comment]
Okay, we need to change `JSON_SCHEMA_ATTR_OAUTH2_RS_BASIC_SECRET` from UTF8STRING to SECRET_UTF8STRING, we need to add a migration task to do the change, and then we need the extra api. That should do it.

**Comment by yaleman** [comment]
I'll have a go at it to see if I can work it out based on that last change. 😇 Or do the API bits and cry when I get to the perms. 🙄

**Comment by Firstyear** [comment]
Doing this today
