### ISSUE TITLE
Extend testing of default entries

### ISSUE THREAD

**Issue by Firstyear** [kanidm/kanidm#108]
We have some testing of the default entries, but having more around things like asserting who can do what, a test of the bootstrap process, and even things like ensuring anonymous can't self write would be great. While I trust the server is currently implementing all of this correctly, having more tests of some of these assumptions from the default entries would be great!

**Comment by pando85** [comment]
Hi @Firstyear, I'm working on this and I'm trying to understand all well while I'm learning about Rust.
All comments are going to help me so if you want to review my code and make some comments, I will appreciate it.
I started testing users read/write capabilities and I don't know how to modify self `name` and self `displayname`. [This](https://github.com/pando85/kanidm/blob/fec793d7af246a7bb6dc3d1cc8e0c4ab6f63d3f7/kanidm_client/tests/proto_v1_test.rs#L22) is the commit were I'm already working on.
Thanks and I'm glad to read your code. I like it. Great job.

**Comment by Firstyear** [comment]
Hey there, thanks for looking into this! I'm glad you like the code, and happy to help.

First piece of advice, is that maybe for this test it's a good idea to break it out to another file, and import the "run_test" fn into the new test case.

With the writes, there are a few paths to consider, that create, modify and delete of entries are all seperate in the access control system, and that modifies are able to define present/delete controls, as well as extra controls on which classes may be defined on an entry. So as you probably know, the proto test is using the front end http api, which requires the client library here https://github.com/kanidm/kanidm/blob/master/kanidm_client/src/lib.rs so if there are missing api end points, you may need to add them to the client (but I think I have defined them all already?). 

The first way to do a modify is via the raw modify call here: https://github.com/kanidm/kanidm/blob/master/kanidm_client/src/lib.rs#L494 this takes a filter of what entries to affect, and a list of "modifications" that define states you want present. So an example of changing name would be in pseudo code:

```
rsclient.modify(
    filter!(eq("name", "testaccount")),
    ModifyList::new_list(vec![
        Modify::Purged("name"),
        Modify::Present("name", "testaccount_new_name")
    ])
);
```

Keep in mind the "raw" apis, are really that, raw. They represent the internal DB model of how to alter and affect entries, so that's what it's a little bit unpolished - every rest api end point translates to this model underneath, but the rest end points exist to help define higher level operations.

Anyway, the other option is to look at this api end point:

https://github.com/kanidm/kanidm/blob/master/kanidm_client/src/lib.rs#L612

Notice the rest url? This is a rest version of the above, where any attribute you put/patch/delete etc, it translates to those modifies underneath. Right now, that's hardcoded to only change the displayname, but a generic version could be made that allows "any attribute" to be altered, and probably is a good idea rather than the hardcoded version. Have a look at: https://github.com/kanidm/kanidm/blob/master/kanidmd/src/lib/core/mod.rs#L1558 which defines these end points.

Saying that, this does highlight that improving the client docs, and the rest api docs is a good idea ... I wonder if there is an api doc generator or something for this? 

Anyway, hope that helps!

**Comment by pando85** [comment]
Thanks for your advices! They are very useful. After starting to bring new ideas I want to know 100% about the code. I come from Python and DevOps world, that's my main field (but I liked typed and async Python). I will make the changes that you propose to me.

For REST APIs I think that the best approach is something like [this](https://github.com/zalando/connexion), first definition and then code from definition without repeating information from documentation. But I dunno nothing like that in Rust.

**Comment by Firstyear** [comment]
Yeah, I don't know of anything like that for Rust yet ... I'd be open to adding it but for now we need to struggle instead :) 

I'm glad your excited about the code, and I'm happy to help, I'm looking forward to seeing what you contribute! 

You are welcome to email me at any time (wbrown at suse.de) if you want to ask anything instead of relying on issues - it's probably a good idea that I setup some kind of communication system for the project I guess at some stage ....

**Comment by pando85** [comment]
Hi @Firstyear ! I continue working in this issue and I don't know if this is an expected behaviour: an account manager which belongs to `idm_account_manage_priv` group could change `email` attribute from users.

My code is right [here](https://github.com/pando85/kanidm/blob/6ea920df020a404f09fe4f8f88666ab30aed05d6/kanidm_client/tests/default_entries.rs#L223)

As always, any comment is welcome.

Thanks!

**Comment by Firstyear** [comment]
It looks like in `kanidmd/src/lib/constants/entries.rs` JSON_IDM_ACCOUNT_WRITE_PRIV_V1 has a member, which is `00000000-0000-0000-0000-000000000014`, aka JSON_IDM_ACCOUNT_MANAGE_PRIV_V1, and JSON_IDM_ACP_ACCOUNT_WRITE_PRIV_V1 from `kanidmd/src/lib/constants/acp.rs` allows modify removed/present to mail. So I think the unclear part here is why I didn't add mail to JSON_IDM_ACP_ACCOUNT_MANAGE_PRIV_V1 in acp_create_attr :)

**Comment by Firstyear** [comment]
Thinking about it, I know that the uuid for member is sometimes a bit hard to use internally and match up, so I wonder how to get it to be able to resolve. I'm not sure you know yet, but internally every reference type is stored as a uuid, but then it's translated to a name on the proto resolution, so that for users it's a name/spn. So I'm wondering if there could be a way to make these names instead to make it clearer in these templates ....

**Comment by pando85** [comment]
Uf, thanks for that comments, right now it is clearer for me. But I don't know what to say. I'm not at that level yet, hehe.

**Comment by Firstyear** [comment]
Every question brings you a step closer to that level though :) So I am happy you are wanting to ask so much!

To read more about reference types have a look at: https://github.com/kanidm/kanidm/blob/master/designs/schema_reference_types.rst

**Comment by Firstyear** [comment]
PS: I think that you could validly add "mail" to acp_create_attr in the manage priv into your change :)

**Comment by Firstyear** [comment]
Also, sorry I have been not contributing much to kanidm, this last week I have been working on a related project to develop a cache that can be included to kanidm later. I think next I want to look at webauthn though ...

**Comment by pando85** [comment]
Ok, great! I think that I will work intense in the next 2 weeks in this. Until know I only use to do it on weekends or some afternoons. I hope I finish my PR soon. I want to write some useful code too but it takes time for me to learn this.
