### ISSUE TITLE
Cookies and Tokens are a bit ambiguous in usage

### ISSUE THREAD

**Issue by Firstyear** [kanidm/kanidm#1082]
We currently issue both. The reason is a number of rust libraries don't properly support cookies, or rather persisting them in some fashion. As a result we use tokens in these cases. We extended that to tokens in browser, but that may expose us to xss attacks.

To resolve this we need clearer patterns about cookie and token issuance. This is tied into #406 because the ability to have sessions in the DB will allow us to create session cookies that are MUCH smaller which avoids the size limits we have previously worried about.

That would leave:

* Tokens as the primary method for auth for CLI/rust based client tools and utils
* Tokens as the primary auth for python
* Cookies for wasm based authentication in the UI (which also makes that code a lot simpler too). 

We will need a "reflector" that allows the wasm to get a non-signed UAT for replacing the lack of client side token introspection now.

**Comment by yaleman** [comment]
There's no reason not to use tokens as auth in requests from the WASM side either, TBH. That'd remove all the server-side handling of cookies, and we just use cookies/localstorage as the storage for the tokens instead of `~/.cache/kanidm` 😃

**Comment by Firstyear** [comment]
The reason to consider cookies-only for wasm is that using tokens opens us to potentially XSS attacks :(

**Comment by yaleman** [comment]
I probably should understand the entire attack surface better, but the Content-Security-Policy headers *should* save us from those kinds of things.

**Comment by Firstyear** [comment]
Content Security Policy I think protects from external resources being added, but not scripts being embedded into content. A risk is something like kani has a lot of surface area for "user controlled values", so there is a risk these *may* be able to inject js into the page. Generally this isn't a problem with Yew because of how it renders DOM nodes and we never actually allow values to be directly added, but we aren't perfect and it *could* happen. So killing the class of attack is a good idea.

**Comment by Firstyear** [comment]
Actualy you're right, CSP might defend here?

**Comment by yaleman** [comment]
It does include provisions for embedded scripts - that's all the work I did with nonces and stuff, but due to the WASM I think we can't block *everything*.

I'm still not sure how using cookies saves us more than token-in-headers, since surely the embedded content would have the same access to the cookies in that case.

**Comment by Firstyear** [comment]
IIRC JS can't access the cookies *content*, it can transmit it via a fetch, and the the same-site policy prevents that. Where as JS can access a tokens content and do whatever it wants.

**Comment by Firstyear** [comment]
The other reason for cookies vs tokens is it removes a *lot* of token passing/handling code from the wasm, which overall simplifies the developer fetch api usage.

**Comment by yaleman** [comment]
> The other reason for cookies vs tokens is it removes a _lot_ of token passing/handling code from the wasm, which overall simplifies the developer fetch api usage.

I was going to macro some of that because it's pretty icky, but yeah, I guess fetch automagically sends the cookies which would preclude having to deal with it at all.

**Comment by Firstyear** [comment]
Yep. And for the flaws of cookies, they are a more "understood problem" for security, where tokens are not. So I think it's worth it for those reasons.
