### ISSUE TITLE
Have a reccomended CLI-Tools distribution for most platforms

### ISSUE THREAD

**Issue by 9SMTM6** [kanidm/kanidm#1176]
**Is your feature request related to a problem? Please describe.**
As it stands the only reccomended way to get the cli tools is to use opensuse tumbleweed.
Many people might think of docker, but perhaps not all, and in any case giving your reccomendation for some way to have client tools would make entry easier and provide validation of it working by virtue of prople doing it and raising issues if it doesnt work.

Thats not put well, but I'm tired ;-P.

**Describe the solution you'd like**
Either clear up the packaging situation which seems difficult, or provide a cli container, or at least reccomend that one use the opensuse/tumbleweed container to install the tools.

**Describe alternatives you've considered**
cant think of anything rn

**Additional context**
-

**Comment by yaleman** [comment]
Oh, I wouldn't list the commands, maybe just link to the package links the same way they are in the docs? I'm not sure documenting "how to use the package manager on your chosen distribution" is something we can take responsibility for. 

It's nice to be helpful, but at some point it's up to the person to understand how to use the OS, we're here to help use Kanidm?

**Comment by Firstyear** [comment]
That's true too.
