### ISSUE TITLE
docs for oauth2 token inspection seem wrong

### ISSUE THREAD

**Issue by yaleman** [kanidm/kanidm#1183]
### I did this

Went looking for the token introspection URL Here: https://kanidm.github.io/kanidm/master/integrations/oauth2.html

### I expected the following

A route that exists, I found - https://idm.example.com/oauth2/inspect

Should it be 'https://idm.example.com/oauth2/token/introspect' instead?

### Kanidm version (and git commit)

Current master

### Operating System / Version

n/a

**Comment by Firstyear** [comment]
It's fixed in a PR I'm just about to make 🤣 I'm currently finishing oauth2 logout and it has the introspect url fix.

**Comment by yaleman** [comment]
Is there any scope for that endpoint to be included in the discovery response? For context, I'm using kanidm_proto's `OidcDiscoveryResponse` in another project and it doesn't seem to be included... thought I haven't gone looking for RFCs which define what's supposed to be *in* that response yet 😄

**Comment by Firstyear** [comment]
Oidc doesn't use rfc7662 token introspection, which is why it's not in the discovery url.

**Comment by Firstyear** [comment]
Resolved
