### ISSUE TITLE
Group Memberships on profile page - should be sorted alphabetically

### ISSUE THREAD

**Issue by yaleman** [kanidm/kanidm#1198]

**Comment by czzrr** [comment]
Hi, I'm currently looking into this.
Is the issue referring to the data returned to the client (`memberof` values?) or a page in the web gui?

**Comment by yaleman** [comment]
Yes, whenever we're looking at a user's information on the web UI, the group membership should be sorted alphabetically,

**Comment by Firstyear** [comment]
There are some "gotchas" here though. If you want to attempt this, you'll need to setup an instance for developing against, create a test user to login as, and add that test user to the group `idm_ui_enable_experimental_features` which unlocks viewing of the user profile page.
