### ISSUE TITLE
Windows: kanidm_tools doesn't fall back to IPv4

### ISSUE THREAD

**Issue by micolous** [kanidm/kanidm#1205]
### I did this

I ran Kanidm with a slightly modified `insecure_example.toml` on a machine with IPv4 and link-local IPv6, and which has mDNS.  I've configured Kanidm to only listen on IPv4:

```
bindaddress = "0.0.0.0:8443"
domain = "myhostname.local"
origin = "https://myhostname.local:8443"
```

Then I try to run `kanidm_tool` on a Windows box (which also has IPv4 and link-local IPv6):

```ps1
.\target\debug\kanidm login -H https://myhostname.local:8443 -C ..\ca.pem
```

I then get an error: `No connection can be made because the target actively refused it.`

If I configure the server to listen on IPv6 (`bindaddress = "[::]:8443"`), then everything works fine.

`ping /4 myhostname.local` and `ping /6 myhostname.local` both work fine.

### I expected the following

Kanidm falls back to using IPv4, and I get: `Login Success for anonymous` after a short delay.

### Kanidm version (and git commit)

kanidm 1.1.0-alpha.11-dev fef364f (PR #1203 on top of 40dd911d1062d10849164dc2aa57ec77b7535914; but the PR's changes aren't relevant)

### Operating System / Version

* Windows 10 22H2 x86_64
* Windows 11 22H2 arm64

### Any other comments

I suspect the issue is in `hyper` or `reqwest` rather than Kanidm.

On macOS, it looks like `hyper` is hedging by opening both a IPv6 and IPv4 connection, and not even waiting for failure. When connecting to a machine which is dropping traffic on `tcp/8443`, I can see this with `RUST_LOG="trace"`:

```
2022-11-20T04:08:39.298858Z DEBUG hyper::client::connect::dns: resolving host="otherhost.local"
2022-11-20T04:08:39.631483Z DEBUG hyper::client::connect::http: connecting to [fe80::REDACTED%6]:8443
2022-11-20T04:08:39.631979Z TRACE mio::poll: registering event source with poller: token=Token(1), interests=READABLE | WRITABLE    
2022-11-20T04:08:39.932525Z DEBUG hyper::client::connect::http: connecting to 10.XXX.XXX.XXX:8443
2022-11-20T04:08:39.932845Z TRACE mio::poll: registering event source with poller: token=Token(2), interests=READABLE | WRITABLE    
```

**Comment by Firstyear** [comment]
Yes I think you're right it's hyper. Our client is based on "reqwest" which wraps hyper, so you could probably could make a small reproducer with that to see if it's the lower levels.

**Comment by yaleman** [comment]
Ima close this for now, if someone finds it's a problem again we can reopen it.
