### ISSUE TITLE
insecure_generate_tls.sh generates bad certificates when CERT_NAME != localhost

### ISSUE THREAD

**Issue by micolous** [kanidm/kanidm#1206]
### I did this

I attempted to make a certificate for my dev install running commit https://github.com/kanidm/kanidm/commit/40dd911d1062d10849164dc2aa57ec77b7535914 with:

`CERT_NAME="myhostname.local" ./insecure_generate_tls.sh`

However connecting to it with Windows fails with:

`ERROR kanidm_cli::session: Error during authentication init phase: Transport(reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("myhostname.local")), port: Some(8443), path: "/v1/auth", query: None, fragment: None }, source: hyper::Error(Connect, Os { code: -2146762481, kind: Uncategorized, message: "The certificate's CN name does not match the passed value." }) })`

It also fails on macOS – I don't have the error string handy, but it was fairly opaque (and different).

When `CERT_HOSTNAME != localhost`; they both appear to need the `CERT_HOSTNAME` to appear in the `alt_names` (SAN) list.  I was able to make it work with a small change to `insecure_generate_tls.sh`:

```
[alt_names]
DNS.1 = ${CERT_HOSTNAME}
DNS.2 = localhost
IP.1 = 127.0.0.1
```

It might be that OpenSSL accepts this (#655); but [RFC 6125 says that a client should _only_ check `subjectAlternativeNames` when that field is present, and ignore the `cn`](https://www.rfc-editor.org/rfc/rfc6125#section-6.4.4):

> As noted, a client MUST NOT seek a match for a reference identifier
> of CN-ID if the presented identifiers include a DNS-ID, SRV-ID,
> URI-ID, or any application-specific identifier types supported by the
> client.

**Comment by yaleman** [comment]
Yeah, the change you listed matches the current standards for cert generation, it was just missed in a rewrite. If you can run a pull request for it, that'd be the fix - thanks 😄

**Comment by Firstyear** [comment]
Yeah, I think the cn has to match the first subject alt name. I was planning/hoping to rewrite the tls gen to an internal setup with openssl inside of kanidmd, just to clean up the repo a bit, given how often we use these insecure certs.

**Comment by yaleman** [comment]
The effective standard is that CN's are irrelevant and SANs are the ones that are checked

**Comment by Firstyear** [comment]
But can we omit the CN then?

**Comment by Firstyear** [comment]
> The effective standard is that CN's are irrelevant and SANs are the ones that are checked

Unless you're ldap, then you refuse and only check the CN and all kinds of chaos.

**Comment by yaleman** [comment]
> But can we omit the CN then?

Nope, because 🌟 standards 🌟 

> > The effective standard is that CN's are irrelevant and SANs are the ones that are checked
> 
> Unless you're ldap, then you refuse and only check the CN and all kinds of chaos.

🤮 yes, there is that I guess... That explains the issues I'm having elsewhere, now I think of it.

So, my understanding is that for you need a common name either way, but if the cert has SANs then they're the ones primarily checked (other than LDAPS because LDAP).
