### ISSUE TITLE
Improve Documentation concerning LDAP and Mail attributes

### ISSUE THREAD

**Issue by 9SMTM6** [kanidm/kanidm#1207]
**Is your feature request related to a problem? Please describe.**
When I tried to make Kanidms LDAP integration work with a few services I stumbled upon a few issues.

A few functional ones which will likely become separate issues, but a few just need improvements in the documentation, I've spent some time debugging these on my own.

**Describe the solution you'd like**
Kanidm book suggests using bind to user anonymous, but doesnt highlight the limited read access that provides, and doesnt mention ways to improve that access. Also some tools (eg. authelia) really don't like passwordless ldap binds - I'm not certain thair reasoning applies but its a compatibility issue.

Both of the above issues can be solved with a service account that has a generated token, AND that is part of the right group, that last of which took the longest time to find out.

Concretely for mail, and presumably all future attribute access too, the service account needs to be part of idm_people_read_priv as I've found out by reading the comments of https://github.com/kanidm/kanidm/issues/990.

**Describe alternatives you've considered**
-

**Additional context**
https://kanidm.github.io/kanidm/stable/integrations/ldap.html#ldap
https://kanidm.github.io/kanidm/stable/accounts_and_groups.html#using-api-tokens-with-service-accounts

**Comment by yaleman** [comment]
Thanks for the report - from memory you can use the api token (which is just a password) for authenticating LDAP, per the [example here](https://kanidm.github.io/kanidm/stable/accounts_and_groups.html#using-api-tokens-with-service-accounts).

The LDAP docs need a little updating once we validate the correct path to success though!

**Comment by Firstyear** [comment]
Might move some of that to the LDAP chapter though.
