### ISSUE TITLE
improve signal handling

### ISSUE THREAD

**Issue by Firstyear** [kanidm/kanidm#1221]
I think that docker is sending sigterm and we aren't trapping that.

**Comment by yaleman** [comment]
That'd explain my broken indexes 🤔 

And yeah it'll send SIGTERM to start with, wait 10 seconds and then SIGKILL - https://docs.docker.com/engine/reference/commandline/stop/

It can be customised but catching it's probably better...

> The main process inside the container will receive SIGTERM, and after a grace period, SIGKILL. The first signal can be changed with the STOPSIGNAL instruction in the container’s Dockerfile, or the --stop-signal option to docker run.

**Comment by Firstyear** [comment]
Yeah, I have been wondering for ages why db wasn't cleanly stopping, I thought it was working. Anyway, it's not a hard fix, I'll do it today. We can also trap a few other signals here too.
