### ISSUE TITLE
FAQ Item: what rights does anonymous have

### ISSUE THREAD

**Issue by yaleman** [kanidm/kanidm#1222]
and how to get access to common things (eg mail)

**Comment by Firstyear** [comment]
I think a problem with this is that the definitions of access controls aren't fully stable yet, and I want to reset/redo all the base access controls for a bit better privilege seperation soon. 

There is a feature req for doing "discovery" of "who can access what" with a cli tool, but I want to improve our general access control admin situation first.

**Comment by yaleman** [comment]
For sure, but "hey I can't access the mail attribute through LDAP" has come up publicly a few times and it *might* save that confusion for folks that are having it..?

**Comment by Firstyear** [comment]
I think if we create a "read_mail" privilege seperate to the current "people read", that would resolve because we won't change it over the upgrade to the revamped access rules I'm considering. We can add it and then give people a release cycle to move over.
