### ISSUE TITLE
ldap bind with dn=token doesn't work

### ISSUE THREAD

**Issue by jceb** [kanidm/kanidm#1265]
### I did this

I created a service account and set up an API token for it:

```bash
kanidm service-account create my-service "my-service account" --name admin
kanidm service-account credential generate my-service --name admin
kanidm service-account api-token generate my-service --name admin "ldap access" | sed -e 1d > token
kanidm service-account api-token status my-service --name admin
```
Then, tried to bind to the ldap service:

```bash
ldapwhoami -D dn=token -y token -x

dd94d258-4dc6-4087-8e31-7308f369fa71 INFO     ldap-request [ 177µs | 9.80% / 100.00% ]
dd94d258-4dc6-4087-8e31-7308f369fa71 INFO     ┝━ ｉ [info]: LDAP client | event_tag_id: 9 | client_ip: ::ffff:10.199.0.1 | client_port: 42802
dd94d258-4dc6-4087-8e31-7308f369fa71 INFO     ┕━ handle_ldaprequest [ 160µs | 90.20% ]
dd94d258-4dc6-4087-8e31-7308f369fa71 INFO        ┝━ ｉ [info]: Attempt LDAP Bind for dn=token | event_tag_id: 9
dd94d258-4dc6-4087-8e31-7308f369fa71 ERROR       ┕━ 🚨 [error]: Error resolving rdn to target | event_tag_id: 4 | err: NoMatchingEntries | rdn: "token"
```

### I expected the following

Successful ldap bind.

### Kanidm version (and git commit)

kanidm 1.1.0-alpha.10
2022-12-15T15:33:28.649526Z DEBUG kanidm: Using 16 worker threads

kanidmd 1.1.0-alpha.10

### Operating System / Version

Linux torch 6.0.10-arch2-1 #1 SMP PREEMPT_DYNAMIC Sat, 26 Nov 2022 16:51:18 +0000 x86_64 GNU/Linux

kanidm is running in docker

### Any other comments

The error message seems to come from this line: https://github.com/kanidm/kanidm/blob/a611fa101a3586983fdb1b3f7b8b70b969b8a93c/kanidmd/lib/src/ldap.rs#L412
I suspect that something with the DN detection is wrong since the code should've gone down this route and never reached the line of the error message: https://github.com/kanidm/kanidm/blob/a611fa101a3586983fdb1b3f7b8b70b969b8a93c/kanidmd/lib/src/ldap.rs#L383

**Comment by Firstyear** [comment]
@jceb I think that the dn=token syntax was added as part of the .11 cycle? 

```
commit a611fa101a3586983fdb1b3f7b8b70b969b8a93c
Author: Firstyear <william@blackhats.net.au>
Date:   Wed Nov 23 16:02:11 2022 +1000

    Add ability to bind with token with a dn=token marker (#1225)

```

.10 was release nov 1st.

Are you looking at the dev/master docs? Or the stable docs? @yaleman

**Comment by yaleman** [comment]
uhhh... I think the docs are being weird again. we need a better way of deploying them as it's a real pain to debug.

**Comment by Firstyear** [comment]
@yaleman Yeah that's why I cced you, I guessed it might be some doc weirdness. Honestly I'd be for something as simple as copy-paste of the book folder to stable/dev and then on releases we just copy dev -> stable. That way it's all in the same git tree rather than needing branches.

Otherwise I'm open to other ideas that could improve it :)

**Comment by jceb** [comment]
> @jceb I think that the dn=token syntax was added as part of the .11 cycle?

Ah, thank you for the hint. I got it to work on the development image.

Just for future reference: directly piping the token into a file will add a newline which will mess up the attempt to decode it in kanidm. The following command properly writes the token into the file:

```bash
kanidm service-account api-token generate my-service --name admin "ldap access" | sed -e 1d | xargs printf "%s" > token
```
