### ISSUE TITLE
Support for mail attribute on groups

### ISSUE THREAD

**Issue by jceb** [kanidm/kanidm#1299]
**Is your feature request related to a problem? Please describe.**

I'd like to use kanidm as the IDM for a mail system. One feature that I'm currently missing is to be able to send mails to a group of people via one email address.

**Describe the solution you'd like**

I'd like to manage email addresses for group objects.

**Describe alternatives you've considered**

Such group mail addresses could be maintained directly in the mail system. This has the disadvantage that group information becomes scattered across multiple system.

**Additional context**

None.

**Comment by Firstyear** [comment]
I had a think about this and I'm certainly not opposed to this, but I also worry this might end up being "jceb specific". Different mail servers have different ways of expanding groups and such. So I'm wondering how to make this work in a nice way that could be compatible to various mail systems. The other big issue is Kanidm does nested groups, but classic ldap doesn't do this and may not know how to chase and resolve the groups.

So I think the big question is "how will your mail system look up mail groups". That I think will affect how we design and implement this is a correct way. It may not be as simple as just putting the mail attribute on groups.

**Comment by yaleman** [comment]
If you're not managing multiple domains, you might be able to make the group name the "mailbox" of the distribution list, (ie, the `example` in `example.com`) and have the mail system remap from `mailbox@<your_kanidm_domain>` to `mailbox@<your_mail_domain>`. That'd save having the mail address in the details of the group etc. It does depend on the mail system 🤔

**Comment by Firstyear** [comment]
Our group name rules are more restrictive than what is allowed in a mail address though.

**Comment by yaleman** [comment]
There's levels of "working" which work for everyone I guess? 😄

**Comment by Firstyear** [comment]
@jceb Do you still need this? Can you provide some more info?

**Comment by jceb** [comment]
Please excuse the late reply. Yes, I'm still interested and in need of this feature.

**Comment by Firstyear** [comment]
@jceb We need to know more about how your mail server is setup I think. How does your mail system currently route groups? Is it using "member" or "memberof"?

**Comment by jceb** [comment]
Hi @Firstyear, okay, I'm back at my kanidm setup. Just updated to 1.1.0-rc.16 :-)
In my mail setup I could use either. Currently, it's not configured and I don't have a preference.

**Comment by jceb** [comment]
It would be great if I could add multiple mail addresses to a group, similarly to person with `mail`, `mail;primary` and `mail;alternative` addresses.

**Comment by Firstyear** [comment]
@jceb What we need to understand is how your mailserver expands groups. Some mail systems expect the mail adder of all members to be present on the group, some can chase the group memberships to actually get all the addrs they need to send to. We need to understand this, else simple adding mail to a group may not do much.

**Comment by jceb** [comment]
Okay, I understand. Well, I use postfix. Postfix is able to look up the address of the group, then fetch the members via the `member` attribute and then lookup the mail address of the member. See second query in the group example https://www.postfix.org/LDAP_README.html#example_group

**Comment by Firstyear** [comment]
@jceb Can postfix do recursive group lookups? 🤔

Anyway, adding the mail attr now.

**Comment by jceb** [comment]
Thank you!

**Comment by Firstyear** [comment]
@jceb I'm sorry it took so long! Please let us know how it goes, especially with recursive group expansion :)
