### ISSUE TITLE
Serval questions about ubuntu packaging

### ISSUE THREAD

**Issue by leoleoasd** [kanidm/kanidm#1329]
I finally got kanidm works on ubuntu. Here are some problems I found during the process. If they are confirmed, I'll be glad to write a PR to fix these.

1. in https://github.com/kanidm/kanidm/blob/master/platform/debian/simple_pkg.sh#L16, `kanidm-ssh` isn't built
2. In https://github.com/kanidm/kanidm/blob/master/platform/debian/kanidm-unixd/rules#L11, `bindir` is `/usr/sbin`, however, in https://github.com/kanidm/kanidm/blob/master/examples/systemd/kanidm-unixd.service, it uses `/usr/local/sbin/kanidm_unixd`
   should I update `bindir` in deb or `kanidm-unixd.service`?
4. pam and nss lib not built or installed in https://github.com/kanidm/kanidm/blob/master/platform/debian/kanidm-unixd/rules#L47

**Comment by yaleman** [comment]
Somehow we ended up with multiple build paths in that folder, which can be a little confusing for sure. It'd be great if you would be interested in writing up the PR. 

1) It seems sensible to add the ssh tools, yes!
2) I'd say `/usr/local/sbin` should be the destination for the package
3) I'm not sure if this needs to be in a separate package - they are built, just not added - @Firstyear what's your thoughts on the PAM/NSS modules being separate to `kandim-unixd`? 

As an aside to Q3, I know when I've tried to package these in the past, it's a nightmare to automagically install the .so's into the right directory depending on the distribution release version, is there some magic to this that dh/autobuild/whatever it's called can help with?

**Comment by leoleoasd** [comment]
it seems that we have a `dh_installpam` for installing pam configs.
https://launchpad.net/ubuntu/+source/pam-ssh-agent-auth/0.10.3-3.1ubuntu2 uses the following code:
```
#!/usr/bin/make -f

# Uncomment this to turn on verbose mode.
#export DH_VERBOSE=1

%:
        dh $@

override_dh_auto_configure:
        dh_auto_configure -- \
                --libexecdir=/lib/${DEB_HOST_MULTIARCH}/security \
                --with-mantype=man \
                --without-openssl-header-check
```
but I'm not sure if it works for debian.

**Comment by Firstyear** [comment]
> Somehow we ended up with multiple build paths in that folder, which can be a little confusing for sure. It'd be great if you would be interested in writing up the PR.
> 
> 1. It seems sensible to add the ssh tools, yes!
> 2. I'd say `/usr/local/sbin` should be the destination for the package
> 3. I'm not sure if this needs to be in a separate package - they are built, just not added - @Firstyear what's your thoughts on the PAM/NSS modules being separate to `kandim-unixd`?

As in moving the pam/nss modules down in the source tree? No issue with it :)  If you mean packaging so that the pam/nss modules are seperate to unixd, that I'm a bit opposed to because they are useless without each other (mostly, ssh key auth excepted).

**Comment by leoleoasd** [comment]
It seems that both Debian and ubuntu use `/lib/${DEB_HOST_MULTIARCH}/`:
```
root@8fcca5afbe07:/# find . -name pam_*.so
./lib/x86_64-linux-gnu/security/pam_env.so
./lib/x86_64-linux-gnu/security/pam_localuser.so
./lib/x86_64-linux-gnu/security/pam_debug.so
./lib/x86_64-linux-gnu/security/pam_sepermit.so
./lib/x86_64-linux-gnu/security/pam_keyinit.so
./lib/x86_64-linux-gnu/security/pam_filter.so
./lib/x86_64-linux-gnu/security/pam_time.so
./lib/x86_64-linux-gnu/security/pam_timestamp.so
./lib/x86_64-linux-gnu/security/pam_faillock.so
./lib/x86_64-linux-gnu/security/pam_permit.so
./lib/x86_64-linux-gnu/security/pam_mail.so
./lib/x86_64-linux-gnu/security/pam_selinux.so
./lib/x86_64-linux-gnu/security/pam_pwhistory.so
./lib/x86_64-linux-gnu/security/pam_listfile.so
./lib/x86_64-linux-gnu/security/pam_issue.so
./lib/x86_64-linux-gnu/security/pam_wheel.so
./lib/x86_64-linux-gnu/security/pam_shells.so
./lib/x86_64-linux-gnu/security/pam_stress.so
./lib/x86_64-linux-gnu/security/pam_unix.so
./lib/x86_64-linux-gnu/security/pam_succeed_if.so
./lib/x86_64-linux-gnu/security/pam_deny.so
./lib/x86_64-linux-gnu/security/pam_limits.so
./lib/x86_64-linux-gnu/security/pam_securetty.so
./lib/x86_64-linux-gnu/security/pam_access.so
./lib/x86_64-linux-gnu/security/pam_rootok.so
./lib/x86_64-linux-gnu/security/pam_xauth.so
./lib/x86_64-linux-gnu/security/pam_usertype.so
./lib/x86_64-linux-gnu/security/pam_rhosts.so
./lib/x86_64-linux-gnu/security/pam_tty_audit.so
./lib/x86_64-linux-gnu/security/pam_nologin.so
./lib/x86_64-linux-gnu/security/pam_warn.so
./lib/x86_64-linux-gnu/security/pam_loginuid.so
./lib/x86_64-linux-gnu/security/pam_faildelay.so
./lib/x86_64-linux-gnu/security/pam_mkhomedir.so
./lib/x86_64-linux-gnu/security/pam_exec.so
./lib/x86_64-linux-gnu/security/pam_userdb.so
./lib/x86_64-linux-gnu/security/pam_motd.so
./lib/x86_64-linux-gnu/security/pam_lastlog.so
./lib/x86_64-linux-gnu/security/pam_setquota.so
./lib/x86_64-linux-gnu/security/pam_echo.so
./lib/x86_64-linux-gnu/security/pam_ftp.so
./lib/x86_64-linux-gnu/security/pam_group.so
./lib/x86_64-linux-gnu/security/pam_namespace.so
./lib/x86_64-linux-gnu/security/pam_umask.so
root@8fcca5afbe07:/# find . -name libnss*
./lib/x86_64-linux-gnu/libnss_compat-2.31.so
./lib/x86_64-linux-gnu/libnss_hesiod-2.31.so
./lib/x86_64-linux-gnu/libnss_hesiod.so.2
./lib/x86_64-linux-gnu/libnss_compat.so.2
./lib/x86_64-linux-gnu/libnss_dns-2.31.so
./lib/x86_64-linux-gnu/libnss_dns.so.2
./lib/x86_64-linux-gnu/libnss_files-2.31.so
./lib/x86_64-linux-gnu/libnss_files.so.2
```

**Comment by leoleoasd** [comment]
Actually, in ubuntu, it is `/usr/lib/xxx`, however `/lib` is just a symbol link for `usr/lib`, so I think we can just use `/lib/${DEB_HOST_MULTIARCH}`.

**Comment by Firstyear** [comment]
Even though it's a link, I think there are still distros that prefer you to specify /usr/lib?

**Comment by leoleoasd** [comment]
In ubuntu 16.04, `/lib` is not a symbol link, and all pam modules are placed inside it. In 20.04, `/lib` becomes a symbol link.

I think we can provide initial support for ubuntu and debian for now? If other dpkg-based distros aren't using `/lib/x86_64-linux-gnu` (as we currently don't have any examples and testing environment), can we support them later?

**Comment by Firstyear** [comment]
16.04 and 20.04 are pretty old though at this point aren't they? What is the latest debian doing with /lib?

I'm not really bothered either way if we use /lib or /usr/lib, I think @yaleman is the person who would be best to ask as they are the dpkg creator.

**Comment by leoleoasd** [comment]
![image](https://user-images.githubusercontent.com/37735580/213959891-f57faa43-9c05-4394-b7e9-6247f4e5550c.png)
In the latest Debian, `/lib` is a normal directory. So it seems to me that using `/lib/${DEB_HOST_MULTIARCH}` will support all Debian and all recent ubuntu versions.

**Comment by leoleoasd** [comment]
![image](https://user-images.githubusercontent.com/37735580/213960023-3b3fbd73-5c78-408e-845e-9c759306a777.png)

**Comment by leoleoasd** [comment]
https://wiki.debian.org/UsrMerge
Debian is planning the merge too. It hasn't been released though

**Comment by yaleman** [comment]
Yep, across the various versions of Ubuntu/Debian that I support personally, it's all over the place. If the variable makes it work on the current automatic build thing, then that sounds good to me.

**Comment by yaleman** [comment]
> > Somehow we ended up with multiple build paths in that folder, which can be a little confusing for sure. It'd be great if you would be interested in writing up the PR.
> > 
> > 1. It seems sensible to add the ssh tools, yes!
> > 2. I'd say `/usr/local/sbin` should be the destination for the package
> > 3. I'm not sure if this needs to be in a separate package - they are built, just not added - @Firstyear what's your thoughts on the PAM/NSS modules being separate to `kandim-unixd`?
> 
> As in moving the pam/nss modules down in the source tree? No issue with it :) If you mean packaging so that the pam/nss modules are seperate to unixd, that I'm a bit opposed to because they are useless without each other (mostly, ssh key auth excepted).

Sounds sensible to me, PAM/NSS modules into the kanidm-unixd package.

**Comment by leoleoasd** [comment]
Should we merge the current `kandim-ssh` deb into `kandim-unixd` as well? `kandim-ssh` relies on `kandim-unixd`, right?

**Comment by Firstyear** [comment]
yes, kanidm-ssh relies on unixd too right now (with the exception of kanidm_ssh_authorizedkeys_direct ). But to prevent confusion, I'd keep it all together.
