### ISSUE TITLE
User get user_auth_token_session field contains Debug values.

### ISSUE THREAD

**Issue by trissylegs** [kanidm/kanidm#1359]
### I did this

Ran `kanidm person show nirya`

The output of fields regarding the user `nirya` with:
```
user_auth_token_session: 804f61db-4742-4799-8b21-fc7ecba51b4f: Session { label: "Auth Session", expiry: Some(OffsetDateTime { utc_datetime: PrimitiveDateTime { date: Date { year: 2023, ordinal: 35 }, time: Time { hour: 4, minute: 55, second: 54, nanosecond: 309616627 } }, offset: UtcOffset { seconds: 0 } }), issued_at: OffsetDateTime { utc_datetime: PrimitiveDateTime { date: Date { year: 2023, ordinal: 35 }, time: Time { hour: 3, minute: 55, second: 54, nanosecond: 309616627 } }, offset: UtcOffset { seconds: 0 } }, issued_by: User(db2342d3-f2f6-4cf0-bf68-f7fa17b5ea8f), scope: ReadWrite }
```

### I expected the following

An output of normal looking values:

Perhaps:
```
user_auth_token_session: Auth Session: id 804f61db-4742-4799-8b21-fc7ecba51b4f, expiry <UTC date>, issued at <UTC date>
```

### Kanidm version (and git commit)

kanidm 1.1.0-alpha.11
(release)

### Operating System / Version

Darwin misato.local 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000 arm64

But also appears on Linux machines.

### Any other comments

None

**Comment by yaleman** [comment]
Yep, at the moment it's just a debug print which could use some prettiness, thanks for logging this!
