### ISSUE TITLE
QueryDe(Error("missing field `response_type`"))

### ISSUE THREAD

**Issue by AffogatoAlCaffe** [kanidm/kanidm#1373]
### I did this
I would like to login for an oauth2 ressource using the user (gui) flow using client credentials grant in 1.1.0-alpha.11
### I expected the following
Im not able to login with an user.
In 1.1.0-alpha.10 it was working fine with the same user but now im getting an error if i try to login.

Browser Error:
       Failed to load resource: the server responded with a status of 401 (Unauthorized)
       kanidmd_web_ui.js:475 
       lstorage error -> QueryDe(Error("missing field `response_type`"))
        

Could this be the reason?
 Oauth2Msg::LoginProceed 

1.1.0-alpha.10
```
                ctx.link()
                    **.history()**
                    .expect_throw("failed to read history")
                    .push(Route::Login);
```

1.1.0-alpha.11
```
                ctx.link()
                    **.navigator()**
                    .expect_throw("failed to read history")
                    .push(&Route::Login);
```
### Kanidm version (and git commit)

[kanidm(d) --version]
1.1.0-alpha.11

### Operating System / Version
Debian Container

**Comment by Firstyear** [comment]
I don't think that change is what would cause this. That change was just about how the yew framework that we use locates and directs to different pages. 

More likely give that the error is coming up with lstorage, that means it's going to be in serialisation / deserialisation of the data here:

https://github.com/kanidm/kanidm/blob/master/kanidmd_web_ui/src/oauth2.rs#L224

This is coming from the requested location, which is where the relying service should be redirecting you to Kanidm with a set of URL parameters including "response_type". It may be that the response type is incorrect now for some reason from the relying server side. 

So I think you should check what the URL is that you are being redirected to and ensure it has the correct parameters. Nothing in the authorisation request is "private" so feel free to share it here, or redact if you wish :) That's the first thing to check IMO.

**Comment by AffogatoAlCaffe** [comment]
The state is sucessfully stored in the sessionstorage of the browser.

Here an example working with version 10 
`{
  "response_type": "code",
  "client_id": "demo2",
  "state": "P2wPLqpV82dg6H7a3eN9Sw",
  "code_challenge": "7eFnfPfq0j3LD1G6u6zsnHJnb-GWbmbKkQ5PMBH8URA",
  "code_challenge_method": "S256",
  "redirect_uri": "http://localhost:8080/auth/verify",
  "scope": "access"
}
`

**Comment by AffogatoAlCaffe** [comment]
Thanks for your help i think i found the problem kanidm-session=example; HttpOnly; SameSite=Strict; Secure; Path=/; **Domain=idm.example.com** and im currently on localhost so the cookie wont be set.

**Comment by Firstyear** [comment]
Ahhhh yep, that would do it. I wonder how we could make the error clearer here though, that was a confusing one.

**Comment by Firstyear** [comment]
@yaleman Given this was an incorrect domain in the cookie so it wouldn't set, do you have any ideas what we could do here to help diagnose that and reveal this error more obviously to users?

**Comment by Firstyear** [comment]
@AffogatoAlCaffe In addition, were you seeing an infinite loop between oauth2 and the login page? Or something else?

**Comment by AffogatoAlCaffe** [comment]
Yes it was an infinite loop on the login screen with some console errors and i focused on the errors not on the cookie :)

**Comment by AffogatoAlCaffe** [comment]
Now im running into **Failed to decrypt token introspection request**  in check_oauth2_token_introspect using Base64UrlSafeData

**Comment by AffogatoAlCaffe** [comment]
An url decoded token works fine :)

**Comment by Firstyear** [comment]
> Yes it was an infinite loop on the login screen with some console errors and i focused on the errors not on the cookie :)

Okay, that gives me some ideas on how to handle this better. 

> Now im running into Failed to decrypt token introspection request

Well, it's telling the truth, it means something is wrong with the token content or has been altered. The access_token in the token field isn't just base64, it's fernet encrypted and hmacced with a relying service specific key, so a failure to decrypt means:

* The content has been tampered with or is not sent in the correct format
* The wrong clientid / secret are being used causing the wrong key to be selected
* The relying service private keys have been rotated

This error specifically occurs after the server has correctly parsed the introspection request, so there must be something else going on. 

What oauth2 relying service library are you using? Is it possible it's changing the access_token at all? It's important the access_token when sent to the api is *exactly* as it was returned to you.

**Comment by AffogatoAlCaffe** [comment]
Thanks for your help, advices and improvemnets it works fine.

**Comment by Firstyear** [comment]
Ahh okay. I think that the token is already provided in a url safe encoding. Anyway, I'll close this now, as we have some other improvements on the way
