### ISSUE TITLE
Source Tree Cleanup

### ISSUE THREAD

**Issue by Firstyear** [kanidm/kanidm#1399]
Kanidm has become a chomnky crabben over the last few years, and that has led to the source tree feeling messy. Growing pains are a thing! 

Currently the source tree is laid out as:

```
.
├── artwork
│   └── stickers
├── designs
│   └── diagrams
├── ethics
├── examples
│   ├── apache_oauth
│   └── systemd
├── iam_migrations
│   └── freeipa
│       └── src
├── kanidm_book
│   ├── src
│   │   ├── developers
│   │   │   └── designs
│   │   ├── examples
│   │   ├── images
│   │   ├── integrations
│   │   ├── sync
│   │   ├── templates
│   │   └── troubleshooting
│   └── theme
├── kanidm_client
│   └── src
├── kanidm_proto
│   └── src
├── kanidm_rlm_python
│   ├── mods-available
│   ├── sites-available
│   └── test_data
├── kanidm_tools
│   └── src
│       ├── cli
│       │   └── webauthn
│       └── opt
├── kanidm_unix_int
│   ├── nss_kanidm
│   │   └── src
│   ├── pam_kanidm
│   │   └── src
│   │       └── pam
│   ├── src
│   │   └── opt
│   └── tests
├── kanidmd
│   ├── core
│   │   └── src
│   │       ├── actors
│   │       └── https
│   ├── daemon
│   │   └── src
│   ├── lib
│   │   ├── benches
│   │   └── src
│   │       ├── be
│   │       ├── constants
│   │       ├── credential
│   │       ├── idm
│   │       ├── plugins
│   │       ├── repl
│   │       ├── server
│   │       │   └── access
│   │       └── valueset
│   ├── lib-macros
│   │   └── src
│   ├── testkit
│   │   ├── src
│   │   └── tests
│   └── testkit-macros
│       └── src
├── kanidmd_web_ui
│   ├── pkg
│   │   ├── external
│   │   └── img
│   ├── src
│   │   ├── components
│   │   ├── credential
│   │   ├── external
│   │   ├── img
│   │   ├── models
│   │   └── views
│   └── tests
├── orca
│   ├── example_profiles
│   │   └── small
│   └── src
│       └── runner
├── platform
│   ├── debian
│   │   ├── kanidm
│   │   ├── kanidm-unixd
│   │   ├── kanidmd
│   │   ├── packaging
│   │   │   ├── source
│   │   │   └── templates
│   │   └── systemd
│   └── opensuse
├── profiles
│   └── src
├── project_docs
├── pykanidm
│   ├── docs
│   ├── kanidm
│   │   └── radius
│   └── tests
└── sketching
    └── src

```

Some obvious issues:

* Support libraries like sketching are at the top level
* Some libraries are hidden/nested like pam/nsswitch for kanidm unixd
* Some crates have a lot of provided binaries like kanidm_unixd.
* kanidmd's web ui is at the top level, but other kanidmd crates are deeply nested
* a lot of "kanidm" prefixes everywhere

To clean this up I think we should re-layout some files.

My initial thinking is:

```
.
├── artwork
├── book
│   ├── designs
│   └── examples
├── libs
│   ├── junkdrawer
│   └── sketching
├── platform
│   └── unix
│       ├── int
│       ├── nsswitch
│       └── pam
├── server
│   ├── daemon
│   ├── idm
│   ├── testkit
│   └── web_ui
└── tools
    ├── cli
    ├── iam_migrations
    │   └── freeipa
    └── orca

```

This keeps nesting, but moves things to be more orderly with "what" they relate to.

The other option is flatten everything.

```
.
├── lib_client
├── lib_proto
├── lib_sketching
├── server_daemon
├── server_lib
├── tool_cli
├── tool_freeipa_sync
├── tool_orca
├── unix_int
├── unix_nsswitch
└── unix_pam

```

Regardless of which way we go, to make linking/builds faster we need to make a junk drawer library that has our platform specific file/user checks as well as pw hashing. That will prevent the current kanidm_unix_int dep on kanidmd.

**Comment by Firstyear** [comment]
It's also likely as part of this at the very least, I'll flatten a lot of the internals of the server_lib too.

**Comment by Firstyear** [comment]
Oh and to make _ vs - consistent in our clis.

**Comment by Firstyear** [comment]
internal_apply_writeable should be over an iter of tuple or a vec of tuple rather than two vec.

**Comment by yaleman** [comment]
The "nested" one above seems the cleanest to me, are we going to go to a single `Cargo.toml` in the root that does all the things?

**Comment by Firstyear** [comment]
I think we leave it as is with the current workspace setup, where the root cargo.toml defines all the members and package versions, and then each nested bit just has their cargo.toml to drive their little part of the world.
