### ISSUE TITLE
Combine unix tools into single program

### ISSUE THREAD

**Issue by cuberoot74088** [kanidm/kanidm#1414]
Based on the discussion in #1408.

- Which tools would be in scope?
- How do we want do have the cli structured? Maybe like sugested below?

> On a side note: As I went trough the 4 unix tools, I thought, some of them could also be combined and it would be more like commands for that unified tool:
> 
> `unix-util <command>`
> 
> with `<command>` being one of:
> 
> * cache-clean
> * cache-invalidate
> * unixd-status
> 
> or is there some special reason, why there should be separate binaries?

I think they can be combined yes :) 

I'm just about to do a re-org of some of the source code and don't want to break any PR's, so I might merge this as is and we continue it in a follow up once I do the reorg.

_Originally posted by @Firstyear in https://github.com/kanidm/kanidm/pull/1408#issuecomment-1449081162_

**Comment by Firstyear** [comment]
Yeah, I think it's just the kanidm_unixd_cache tools that need combination if I'm not mistake?

**Comment by cuberoot74088** [comment]
Cool, I will give it a try after the code reorg.

**Comment by Firstyear** [comment]
Reorg is done, so please feel free to go ahead :)

**Comment by Firstyear** [comment]
@cuberoot74088 Did you still want to work on this? I'm thinking to just get this done in the next 2 days or so :)

**Comment by cuberoot74088** [comment]
Hi @Firstyear, 

in principle yes, but I won't manage within the next 2 days. :-(  Sorry.

But feel free to do it and thanks for checking back with me.
