### ISSUE TITLE
Enforce MFA on persons by default

### ISSUE THREAD

**Issue by Firstyear** [kanidm/kanidm#1435]
Currently we have two account classes (service accounts and persons). For service accounts they authenticate with a high entropy server side generated password, or an api-token. These tend to be very strong authentication mechanisms so aren't a concern today.

However, persons can have either:

* Password
* Password + TOTP
* Webauthn (Passkey)

I am considering if we want to shift our baseline for persons such that Password-Only is not allowed on their accounts. This would represent a significant improvement to user security.

Initially we would still allow password only auth, but we would issue a warning on authentication that this will be disallowed in the future. Users can then update to have password + totp and/or password. 

At a later time we can then fully and outright remove password as a singular auth type, and enforce that a password must always be paired with totp.

Thoughts? Is this a good improvement?

**Comment by yaleman** [comment]
As long as it's a default that can be modified by policy later for specific use cases that need password-only, then that seems legit for me. 

Secure-by-default-with-escape-hatches is a good practice.

**Comment by Firstyear** [comment]
Doing it the way you suggest is actually easier from a technical standpoint than my suggestion. I'll defer to your input here :)

**Comment by yaleman** [comment]
As long as we don't break accounts that already exist, or ones reset using `recover_password` etc...

**Comment by Firstyear** [comment]
It won't break that, because recover_password currently bypasses account policy in how it works. It's the "break glass in emergency" to access an account.

**Comment by yaleman** [comment]
But then will they be able to auth, if the auth policy is upset with them for not having MFA?

**Comment by Firstyear** [comment]
for now the auth policy will only apply to credential changes. I think that we should only lock out accounts from auth if their credentials are inconsistent to policy if the admin makes that choice.
