### ISSUE TITLE
kanidm group add_members needs to check for a minimum number of usernames

### ISSUE THREAD

**Issue by yaleman** [kanidm/kanidm#1451]
### I did this

`kanidm group add-members <groupname>` without a list of users.

### I expected the following

It to go "hey you need to specify at least one user", but it sent a request and the server was like "hey empty request".

### Kanidm version (and git commit)

- `kanidm` - 1.1.0-alpha.11
- `kanidmd` - 1.1.0-alpha.11-dev

### Operating System / Version

macOS Monterey, not that it matters :)

**Comment by Firstyear** [comment]
I think this is a pretty easy fix, but it relates to https://github.com/kanidm/kanidm/issues/267 which really would help a lot here since we could use non-empty vec to enforce this in many places.
