### ISSUE TITLE
Update server daemon logging and exit codes

### ISSUE THREAD

**Issue by MinhPhan8803** [kanidm/kanidm#1472]
**Is your feature request related to a problem? Please describe.**

The main server daemon looks outdated compared to the unixd daemon (use of `eprintln!`'s instead of log macros, and of course force shut down instead of returning exit codes).

**Describe the solution you'd like**

A slight rewrite of course.

**Describe alternatives you've considered**

Leave it be if the daemon is earmarked for rewrite at some point.

**Additional context**

**Comment by Firstyear** [comment]
This was a legacy thing, from previous where tracing subscriber wasn't installed to later. Now it's there very early on we could clean this up yes.
