### ISSUE TITLE
ldapsearch with service account failed with "19 Constraint violation" server log "invalid basedn"

### ISSUE THREAD

**Issue by NexZhu** [kanidm/kanidm#1483]
### I did this

(Note: I've replaced my real domain with `mydomain.com`, and bind DN to `dc=mydomain,dc=com` only for security concern.)

```sh
ldapsearch -H ldaps://idm.mydomain.com:3636 -x -D "dn=token" -w "my token" '(name=username)'
ldapsearch -H ldaps://idm.mydomain.com:3636 -x -D "dn=token" -w "my token" -b "dc=mydomain,dc=com"  '(name=username)'
```

With or without `-b` argument, I got the same error:
```
# extended LDIF
#
# LDAPv3
# base <dc=mydomain,dc=com> with scope subtree
# filter: (name=username)
# requesting: ALL
#

# search result
search: 2
result: 19 Constraint violation

# numResponses: 1
```

Server log:
```
kanidm  | f611c379-a905-41ba-b593-06d18148520d INFO     ldap-request [ 378µs | 6.44% / 100.00% ]
kanidm  | f611c379-a905-41ba-b593-06d18148520d INFO     ┝━ ｉ [info]: LDAP client | event_tag_id: 9 | client_ip:  | client_port: 59242
kanidm  | f611c379-a905-41ba-b593-06d18148520d INFO     ┕━ handle_ldaprequest [ 353µs | 93.56% ]
kanidm  | f611c379-a905-41ba-b593-06d18148520d INFO        ┝━ ｉ [info]: Attempt LDAP Bind for dn=token | event_tag_id: 9
kanidm  | f611c379-a905-41ba-b593-06d18148520d INFO        ┝━ ｉ [info]: allowed 1 entries ✅  | event_tag_id: 10
kanidm  | f611c379-a905-41ba-b593-06d18148520d INFO        ┕━ ｉ [info]: ✅  LDAP Bind success | event_tag_id: 9 | dn: dn=token
kanidm  | 03b9613e-e850-4424-93e6-ec7bf5126974 INFO     ldap-request [ 19.5µs | 46.49% / 100.00% ]
kanidm  | 03b9613e-e850-4424-93e6-ec7bf5126974 INFO     ┝━ ｉ [info]: LDAP client | event_tag_id: 9 | client_ip: ::ffff:114.254.1.173 | client_port: 59242
kanidm  | 03b9613e-e850-4424-93e6-ec7bf5126974 INFO     ┕━ handle_ldaprequest [ 10.4µs | 53.51% ]
kanidm  | 03b9613e-e850-4424-93e6-ec7bf5126974 INFO        ┝━ ｉ [info]: Attempt LDAP Search for gitea@idm.mydomain.com | event_tag_id: 3
kanidm  | 03b9613e-e850-4424-93e6-ec7bf5126974 ERROR       ┕━ 🚨 [error]: LDAP Search failure - invalid basedn | event_tag_id: 4
kanidm  | b221b8d7-3520-4a93-adda-7e5387db8d8d INFO     ldap-request [ 11.9µs | 81.21% / 100.00% ]
kanidm  | b221b8d7-3520-4a93-adda-7e5387db8d8d INFO     ┝━ ｉ [info]: LDAP client | event_tag_id: 9 | client_ip: ::ffff:114.254.1.173 | client_port: 59242
kanidm  | b221b8d7-3520-4a93-adda-7e5387db8d8d INFO     ┕━ handle_ldaprequest [ 2.24µs | 18.79% ]
```

# extended LDIF

### Kanidm version (and git commit)

Note: Kanidm is running inside Docker container

[kanidm(d) --version]
```
WARNING: This is running as uid == 0 (root) which may be a security risk.
kanidmd 1.1.0-alpha.12-dev
```

### Operating System / Version

```
Linux internal-001 4.18.0-383.el8.x86_64 #1 SMP Wed Apr 20 15:38:08 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by Firstyear** [comment]
If you do `ldapsearch -H ldaps://idm.mydomain.com:3636 -x -D "dn=token" -w "my token" -s base -b ''` you should get something like:

```
dn:
objectClass: top
vendorName: Kanidm Project
vendorVersion: kanidm_ldap_1.0.0
supportedLDAPVersion: 3
supportedExtension: 1.3.6.1.4.1.4203.1.11.3
supportedFeatures: 1.3.6.1.4.1.4203.1.5.1
defaultnamingcontext: dc=localhost
```

Does that defaultnamingcontext match what you expect for your basedn? 

When I do the same, both ldapwhoami and ldapsearch work with the same commands as you demonstrate here.

**Comment by NexZhu** [comment]
No what I expect is `dc=mydomain,dc=com`, what I got is `dc=idm,dc=mydomain.com`

```
# extended LDIF
#
# LDAPv3
# base <> with scope baseObject
# filter: (objectclass=*)
# requesting: ALL
#

#
dn:
objectClass: top
vendorName: Kanidm Project
vendorVersion: kanidm_ldap_1.0.0
supportedLDAPVersion: 3
supportedExtension: 1.3.6.1.4.1.4203.1.11.3
supportedFeatures: 1.3.6.1.4.1.4203.1.5.1
defaultnamingcontext: dc=idm,dc=mydomain.com

# search result
search: 2
result: 0 Success

# numResponses: 2
# numEntries: 1
```

**Comment by Firstyear** [comment]
The default naming context is derived from `domain = "idm.example.com"` in server.toml. So if the domain is idm.example.com then it will be dc=idm,dc=example,dc=com. So I think this is expected and correct because the ldap dn is reflecting your domain name here.

**Comment by Firstyear** [comment]
Ahh the doc changes from idm.example.com to example.com. the doc should be consistent.

**Comment by NexZhu** [comment]
Maybe the LDAP base DN should be configurable in some extent.
I think the root domain name like `company.com` is often used for organization homepage, so second level domain like `idm.company.com` will be used for the LDAP server. But LDAP base DN is commonly just the organization root domain name like `dc=company,dc=org`

**Comment by Firstyear** [comment]
I think the LDAP base dn could be configurable yes. :)

**Comment by NexZhu** [comment]
OK. Thank's for the clarification! I'm testing out Kanidm as a replacement for my current OpenLDAP + Authelia setup, and I (and probably many exisiting LDAP users) need LDAP base DN to be configurable so I can keep the original base DN with Kanidm. Looking forward to this option being available :D

**Comment by Firstyear** [comment]
Can you please open a new issue for the configurable basedn? That way it's not forgotten, but I'll try to do it this week :)
