### ISSUE TITLE
Update the docs pipeline

### ISSUE THREAD

**Issue by yaleman** [kanidm/kanidm#1538]
**Is your feature request related to a problem? Please describe.**

The docs generation is janky.

**Describe the solution you'd like**

The workflow might work like:

1. find all the tags
2. fan out action calls based on this, plus one for master, which write to artifact cache
3. collect it all and upload it to pages

**Describe alternatives you've considered**

Leave it as-is, but it's a little broken currently.

**Additional context**

**Comment by Firstyear** [comment]
I think we just do "latest tag" and "master" for stable/dev docs. I don't think we need all the ancient doc versions.
