### ISSUE TITLE
Link on official website to ethics is broken

### ISSUE THREAD

**Issue by turboMaCk** [kanidm/kanidm#1552]
This is just a minor thing but [link from official website](https://kanidm.com/community/) to ethics document is broken.

Correct url is now https://github.com/kanidm/kanidm/blob/master/project_docs/ethics/README.md

![image](https://user-images.githubusercontent.com/2130305/233140248-52ff1c11-ab44-45b4-be3c-f0128d7976d0.png)

Seems like a minor thing but I think it would be good to fix it so it doesn't seem like project stopped caring about these values.

Thanks <3

**Comment by Firstyear** [comment]
I went to go fix this but it looks like @yaleman was faster! Thanks for letting us know :)
