### ISSUE TITLE
Check badlist on login

### ISSUE THREAD

**Issue by Firstyear** [kanidm/kanidm#159]
We could consider checking if on login if a password is in the badlist representing that the account *has* potentially been compromised and should have their account immediately locked.

**Comment by victorcwai** [comment]
Hi, I am interested in working on the issue. Could you please point out where I should look to get started?

**Comment by Firstyear** [comment]
I'd have a look at these two files:

https://github.com/kanidm/kanidm/blob/master/kanidmd/src/lib/idm/authsession.rs

https://github.com/kanidm/kanidm/blob/master/kanidmd/src/lib/idm/server.rs

The best place to start is to probably write a test in 
 https://github.com/kanidm/kanidm/blob/master/kanidmd/src/lib/idm/server.rs  that attempts to use a password from the badlist. The badlist is stored in a configuration entry, so you should be able to set a known value for the test into the badlist so that the test is reliable :) Once you have the test "reliably failing" because you tried to use a badlisted password during an authentication, then you can move to actualy doing the feature! 

You can see the badlist being used in a password change here:

https://github.com/kanidm/kanidm/blob/master/kanidmd/src/lib/idm/server.rs#L892

It would be a similar process to this check, but would need to occur either within the auth-session or the credential handling code.

https://github.com/kanidm/kanidm/tree/master/kanidmd/src/lib/credential

Given how frequently the badlist will be accessed, we should consider transforming it into a cache in memory later, but for now, you should simply be able to pass the badlist entry to the auth session when it starts up or similar.

**Comment by victorcwai** [comment]
Hello again, I got some questions regarding this:
- By locking do you mean returning a AuthState::Denied or changing the softlock?
- What would be a proper way to get badlist passwords in https://github.com/kanidm/kanidm/blob/master/kanidmd/src/lib/idm/authsession.rs?

I wanted to retrieve it like this, but I don't have a reference to `IdmServer` in `authsession.rs`:
```
    let badlist_entry = idms.proxy_write(duration_from_epoch_now())
        .qs_write
        .internal_search_uuid(au, &UUID_SYSTEM_CONFIG)
        .map_err(|e| {
            ladmin_error!(au, "Failed to retrieve system configuration {:?}", e);
            e
        })?;
```
Or I could pass `IdmServerWriteTransaction` as `&self` via https://github.com/kanidm/kanidm/blob/master/kanidmd/src/lib/idm/server.rs#L512?

**Comment by Firstyear** [comment]
I think that the best way to do this would be changing line 470 of authsession.rs - when you create the new auth session you pass (for now) the system config entry (which is what contains the badlist). That way the authsession doesn't need any subsequent transactions to complete it's operation. 

It also means you can create a "mock" badlist entry and pass it into the authsession tests in authsession.rs as well to check this process :) 

Alternately, you could use `badlist_entry.get_ava_set("badlist_password").cloned()` which will give you an Option<Set<Value>> of all the badlist entries that you could cache instead. 

Does that help? 

Later to optimise this, we can keep a cached map of the badlist, and pass by reference rather than by value, but for now, lets do it the simple/dumb way and we can improve it later. (correct, simple, fast).
