### ISSUE TITLE
Document that you need to tell Nginx or other proxies to use HTTP 1.1 or later.

### ISSUE THREAD

**Issue by trissylegs** [kanidm/kanidm#1591]
**Is your feature request related to a problem? Please describe.**

A problem I've seen twice now is that Nginx will send HTTP 1.0 requests by default. This will fail as tide will immediately drop the connection without logging it.

**Describe the solution you'd like**

Well Tide could probably do something about logging dropped requests.

For kanidm I'd suggest a reverse proxy article in the docs.

**Describe alternatives you've considered**

Change upstream so it just treats 1.0 as http 1.1 (the differences aren't huge)

**Additional context**

My comment I made several years ago that mentions it. (Kinda)

https://github.com/kanidm/kanidm/issues/191#issuecomment-895955297

Support comment of a user running into the same issue.

https://matrix.to/#/!fzbFDgtoaOQXSSxOZc:gitter.im/$mHxO_cupAfdJVIv39S0nz6ny91ThNEJIS7rN8KlOdLU?via=gitter.im&via=matrix.org&via=tako.mx

**Comment by Firstyear** [comment]
I think this is also a good reminder that we need to prioritise the move to axum sooner than later.
