### ISSUE TITLE
Lock accounts if the password appears in the badlist

### ISSUE THREAD

**Issue by Firstyear** [kanidm/kanidm#160]
As admins update and extend the pw badlist in response to "new data", we should check if any password at login appears in the badlist (since we have the cleartext). If it does, the account should be immediately locked and the login denied as there is a high risk the account could be then compromised.

**Comment by OttoHollmann** [comment]
I'm interested in this issue, but it looks similar to #159. Can you please explain me where is difference between these issues?

**Comment by Firstyear** [comment]
I think it's a bit of a subtle difference. Once #159 has occured, and we reject the authentication, the account is in a way "locked". But that only locks that *single* credential, which is the password in use. This would lock the whole ACCOUNT and all it's associated credentials, since there is now a risk that *any* of it's credentials/access could have been compromised. 

does that make sense?

**Comment by Firstyear** [comment]
@yaleman Do you think this is worth? I think we are moving away from pw's, and we try not to let people set bad passwords anyway, I'm also not sure how many people are updating their badlists aggressively either so this has less relevance .

**Comment by yaleman** [comment]
Maybe change it to just throwing a warning on login (and an admin alert), which suggests the user changes their password / auth method?

**Comment by Firstyear** [comment]
It actually looks like this was done in 8a2f3b65ec so I think we can close this.
