### ISSUE TITLE
Cannot reauth idm_admin due to deprecated security keys

### ISSUE THREAD

**Issue by cuberoot74088** [kanidm/kanidm#1621]
**Is your feature request related to a problem? Please describe.**

I have used "security keys" before to secure login to accounts. Seems I have missed to migrate them to passkey; at least for my idm_admin account. 

I am running on alpha12.

I can still login with backup code + password; but I cannot do a reauth to unlock security settings.

Here is the error message:

```
as  idm_admin
---
uuid: a...
password: set
totp: disabled
backup_code: enabled
 ⚠️  warning - security keys are deprecated.
 ⚠️  you should re-enroll these to passkeys.
security keys:
 * solo-black
 * solo-red
```

How can I recover from that "deadlock"? Maybe do some sort of "reset"?!

I have also not found a hint where and how to add or modify advanced login methods on the cli and the book. Can you give some pointers here as well? 

Thanks for you help in advance!

**Comment by Firstyear** [comment]
@cuberoot74088 you can use the admin account to trigger a credential reset on the idm_admin. idm_admin is now a service account though, so it should only have a generated password.

So you should do something like:

```
kanidm login -D admin
kanidm service-account credential generate idm_admin -D admin
```

From there you can use the idm_admin to trigger a credential reset on other accounts with:

```
kanidm person credential create-reset-token target_user -D idm_admin
```

**Comment by cuberoot74088** [comment]
@Firstyear luckily I can still login as admin and **the reset worked**. Thank you very much! :+1: 

Let me see, if I am able to add a passkey to it now...

**Comment by Firstyear** [comment]
@cuberoot74088 idm_admin and admin are now not *persons*, they are service accounts, so they can't have passkeys. You can now add a new person, and make them a member of the idm_admins group, and then give them a passkey instead.

This is because service-accounts on login gain a token that has "unlimited write". Where as with a person when you login your token is read-only, and on re-auth it upgrades to read-write for 5 - 10 minutes and then gives up the permissions. This way it's now safe to assign users to high-access groups like idm_admin since you need a re-authentication to access the permissions.

Does that help?

**Comment by cuberoot74088** [comment]
Thanks for the explanation. Does that mean, these service accounts work only via password and nothing else? Even, if I cannot do it for idm_admin now (from the ui or cli), I still have a second factor (passkey?) in place for my admin account. Are you saying, this is now no longer possible to create?! :thinking: 

```
kanidm service-account credential status admin -D admin    
---
uuid: 44e0226d-60da-4a86-80ea-927af344a87f
password: set
totp: disabled
backup_code: enabled
 ⚠️  warning - security keys are deprecated.
 ⚠️  you should re-enroll these to passkeys.
security keys:
 * solo-red
 * solo-black
---

```

**Comment by cuberoot74088** [comment]
Understood and agreed. I was not aware of this new concept. Cool.

Would you recommend that I remove the second factors and stuff from the admin account then and just go with a fresh password (for future compatibility) ?

**Comment by Firstyear** [comment]
Yep, I'd say that's the way to go! Alternately, once you have your new mfa admin accounts setup, you can just do a "generate-password" and throw it away - you can always recover the account passwords with the kanidm recover-account process if you need it in emergency. 

And we are only going to continue to improve some of these dynamic auth options as we proceed.

**Comment by cuberoot74088** [comment]
btw, it is not possible to access this page for the idm_admin
