### ISSUE TITLE
Account recovery (backup) mfa codes

### ISSUE THREAD

**Issue by Firstyear** [kanidm/kanidm#163]
We should support having backup mfa codes so that single-device accounts can be restored.

**Comment by Firstyear** [comment]
https://techcommunity.microsoft.com/t5/azure-active-directory-identity/temporary-access-pass-is-now-in-public-preview/ba-p/1994702

Also useful for initial setup and onboarding.

**Comment by victorcwai** [comment]
Some simple ideas on how to implement it based on the Microsoft temporary access pass:
- Add a new class/object: Backup code policy
  - Each Kanidm has a Backup code policy, which defines who can use the Backup code, and parameters like max/min lifetime, one-time use, length, etc. 
  - Only ``idm_hp_account_manage_priv`` can modify it
- Add a new class/object: Backup code
  - Issue and save the Backup code, the behaviors of which must adhere to Backup code policy
  - ``idm_account_manage_priv`` can CRUD it for normal users, but not themselves
  - ``idm_hp_account_manage_priv`` can CRUD it for ``idm_account_manage_priv`` users and normal users
- Add Backup code as a new AuthCredential
  - Check if input matches the Backup code saved in database, similar to how password-login is implemented
- The Backup code could be generated by TOTP/HOTP, or a cryptographically secure pseudorandom number generator

**Comment by Firstyear** [comment]
@victorcwai Could you write this up as a PR to a design document in https://github.com/kanidm/kanidm/tree/master/designs ? 

It' would also be good to have some citations to MS TAP, but also in this case, I was considering that these backup mfa codes would be similar to the github implementation - IE you have lost your TOTP/Webauthn token and need a backup to get in.

**Comment by victorcwai** [comment]
Sure!
