### ISSUE TITLE
WASM builds failing due to stdweb v0.4.20

### ISSUE THREAD

**Issue by yaleman** [kanidm/kanidm#1640]
### I did this

`cd server/web_ui && ./build_wasm.sh`

### I expected the following

It to build

### Kanidm version (and git commit)

Current commit, not sure which one broke it, but was recent.

### Any other comments

See https://github.com/rustwasm/wasm-bindgen/issues/3415 for details, looks like `stdweb` isn't maintained anymore, and was removed from `time` - which pulls it in - in 0.3.0.

So, we need to update ... something. I originally said `time` but that doesn't work. 😄

**Comment by Firstyear** [comment]
Yeah, we can't update time in most of the library because time after 2 doesn't allow accessing local time for certain UI elements. So we just simply can't update this.

**Comment by yaleman** [comment]
Siiiiigh, and it's a dependency somewhere in tide? I think.

**Comment by yaleman** [comment]
Welp, that sucks, because it relies on a long-dead package. 😢 It seems... weird that there's no functional replacement for `time v0.2.x`
