### ISSUE TITLE
kanidm-unixd-tasks should relabel new user home dirs on SELinux systems

### ISSUE THREAD

**Issue by 0xC0ncord** [kanidm/kanidm#1655]
**Is your feature request related to a problem? Please describe.**

I'm working on integrating `kanidm-unixd` onto my infrastructure which is all SELinux-enabled, but I've hit a bit of a snag. Policy-writing aside, I notice that after `kanidm_unixd_tasks` creates a new user's home directory, there doesn't seem to be a way to also set the new home directory's SELinux user. On the system I am testing with, I see these contexts on the home directory after its created:
```
# ls -lZd /home/14f4a2c1-4541-4018-9e7d-9b81010ece6c/
drwxr-x---. 1 concord concord system_u:object_r:user_home_dir_t:s0 64 May 24 22:17 /home/14f4a2c1-4541-4018-9e7d-9b81010ece6c/
```
The problem here is that the home dir's contexts should match the SELinux user of the user which we are creating the home directory for, e.g. `staff_u` or `unconfined_u`:
```
# ls -lZd /home/14f4a2c1-4541-4018-9e7d-9b81010ece6c/
drwxr-x---. 1 concord concord staff_u:object_r:user_home_dir_t:s0 64 May 24 22:17 /home/14f4a2c1-4541-4018-9e7d-9b81010ece6c/
```

This is problematic especially on systems with UBAC enforced, as the user would not be able to access their home directory at all under these conditions.

**Describe the solution you'd like**

Ideally in the future kanidm could gain full support for SELinux, but in the interim the ability to specify the path to a script file or command (with arguments) in the config file would suffice. Such an option may allow for more advanced configurations, although I cannot think of any that would fit my use case.

As far as my use case goes, a simple `restorecon -RF` on the newly created home directory by this config option would get the job done.

**Describe alternatives you've considered**

There might be a way to do this same effect in PAM (`pam_exec` maybe?).

**Additional context**

N/A

**Comment by Firstyear** [comment]
Hmmm, well this is coming from the fact that the tasks daemon itself would be running in a system_u context, which is why it creates the user component of the label as such. While scripting could be a solution to this problem, I think the better option is to either make tasksd selinux aware to create the right extended attributes on the directories, or to change the selinux policy to influence the resultant label from the tasks daemon. 

It would probably be worth see how pam_oddjobd does this or how it's selinux policy works because that may help guide us to this. While the script idea is nice, I'd rather just fix the problem with selinux directly.

**Comment by 0xC0ncord** [comment]
> or to change the selinux policy to influence the resultant label from the tasks daemon.

Unfortunately that won't work because the policy doesn't support manipulating SELinux users itself.

Most applications that handle this problem will use the SELinux API to compute or lookup the user's default SELinux context and extract the SELinux user from there, create the object, and then set its label.

**Comment by yaleman** [comment]
Good thing there's a related crate then 😄 
https://crates.io/crates/selinux

**Comment by Firstyear** [comment]
I think that's the way to go. We should also write the needed policy for Kanidm too since there will likely be quite a few extra permissions needed for tasks to make this work. @0xC0ncord Did you want to take a look at working on this, or would you be okay to wait for us to implement it?

**Comment by 0xC0ncord** [comment]
> We should also write the needed policy for Kanidm too since there will likely be quite a few extra permissions needed for tasks to make this work.

I have been writing a policy so far targeting [refpolicy](https://github.com/SELinuxProject/refpolicy) that has been working thus far. I intend to upstream it there once it's done and I can also submit a PR for a note to the Kanidm docs about it for systems using that policy. Not sure how you want to proceed with Fedora/RHEL systems using fedora-selinux though.

> Did you want to take a look at working on this, or would you be okay to wait for us to implement it?

I don't mind taking a stab at it! :)
