### ISSUE TITLE
Make POSIX password requirements for LDAP more clear

### ISSUE THREAD

**Issue by ShaddyDC** [kanidm/kanidm#1675]
**Is your feature request related to a problem? Please describe.**

I had some trouble getting the LDAP interface working a couple of days ago.
In hindsight, the solution was really simple: I didn't have a POSIX password set for the account I was testing with, and it worked fine after setting one.
Knowing the issue, the documentation is also clear about it.
I'll still suggest some ways how I might have found the issue more quickly or where I was confused.
Because this has become a wall of text (sorry), I have bolded the potential suggestions.

**Describe the solution you'd like**

Firstly, the most obvious and maybe most objective issue.
When trying to log into an account without a set POSIX password via LDAP, Kanidm logs the error `Account is softlocked. | event_tag_id: 9`.
This message seems misleading and could instead be **a message along the lines of "Account does not have POSIX features enabled."**.
I think with that alone, I would have found the issue more quickly.

**Describe alternatives you've considered**

See the Additional context section for some background on these.
It's possible that just an improved log error message would have already prevented this issue for me.
Alternatively, or maybe additionally, maybe you could **leave a note in the LDAP documentation that it requires POSIX enabled and an explicit POSIX password set**.
Currently, the webui just doesn't have a section for POSIX when the feature is not enabled for an account, which is nice in that it's simple.
However, if instead it had **a greyed out section along the lines of "Cannot set POSIX password as the feature is not enabled for your account"**, that would have given me another hint to the problem.
I don't know if it's worth the tradeoff.

**Additional context**

Next, some vague thoughts about how I missed it in the documentation.
I read the whole page on LDAP in Kanidm multiple times while trying to debug the issue, so I was aware that a POSIX password was required.
I'd at least skimmed all the pages in the Administration section, including the POSIX page.
I didn't plan on actually using the POSIX features themselves, so I didn't play around with them or enabled them.
After that, I figured I was done with that section and wouldn't need to refer back to it.
I did most of the actual configuration through the web UI, ie configure passwords etc, and I only used the cli when I noticed I needed to use it.
Without having POSIX enabled for an account, I didn't see an option to set a POSIX password.
Thus, when attempting to use LDAP, it wasn't obvious to me that that was a password separate from those I'd already set, and it wasn't obvious to me why it wasn't working with those.
Coupled with that error message about the softlocked account, I wasn't looking in the right places to fix the issue.

**Comment by Firstyear** [comment]
I think you're right there are a few places we can improve here. To summarise them:

* LDAP section should note that the posix attributes are required with a password set for an account to bind.
* Disable the posix password set dialog if the account isn't posix capable - we may consider moving the posix creds into the main cred update session which is better suited for this kind of thing.
* Log the difference between an account lacking a posix PW vs a true softlock.
* (Optional) return a different error message via ldap when posix pw is missing. 

I need to think more about the risks/benefits to showing a unique error when the posix pw is missing via ldap since that kind of info could aid an attacker. So I need to think about if it's actually a risk or not.

Does that seem like a reasonable set of improvements?

**Comment by ShaddyDC** [comment]
That does seem reasonable, thanks a bunch!

There's one thing I'm confused about:
> Disable the posix password set dialog if the account isn't posix capable

As far as I can tell, there already is no such dialogue if the account doesn't have it enabled, or am I misunderstanding?
I was more thinking about giving an indicator that it's a separate thing that exists even when it is disabled.
Rest sounds good to me!

**Comment by Firstyear** [comment]
Ahhh I see what you mean. I'll think about how best to incorporate that into the design, but I'll start on the other elements soon. Currently I have to follow up on some other priorities sadly, but I do think your issue you raised is a good one and I will resolve it when I can. :)
