### ISSUE TITLE
UI design for non-admin users

### ISSUE THREAD

**Issue by leoleoasd** [kanidm/kanidm#1685]
**Is your feature request related to a problem? Please describe.**

Non-admin users should be able to do whatever they can do with command line on the WebUI, such as editing their name and display names, uploading ssh keys, right? Is the designing of user's WebUI done? Is there any checklist / kanban on the implementation status? This would allow potential contributors (like me) to help.

**Comment by yaleman** [comment]
It's definitely in the early stages, and we'd definitely appreciate some help lining up the features between the two UI's.

**Comment by yaleman** [comment]
I've [started a project here](https://github.com/orgs/kanidm/projects/3/views/1) and have added some tasks I could think of off-hand, I'm sure there's plenty more things to line up.

Feel free to log issues for any missing features, no need to (initially) write up a full spec / design document for each feature.

I'll assign them to the project and we can keep track.

**Comment by leoleoasd** [comment]
I got 404 on the above link. Is the project ``public''?

**Comment by yaleman** [comment]
Whoops, should be sorted now.

**Comment by Firstyear** [comment]
@leoleoasd there is a group in your instance that unlocks the ui features too `idm_ui_enable_experimental_features`. If you add users to that it will unlock some of these extra parts in the webui for this.
