### ISSUE TITLE
401 response on failed login attempt

### ISSUE THREAD

**Issue by dlrobson** [kanidm/kanidm#1710]
**Is your feature request related to a problem? Please describe.**

I currently have kanidm proxied by nginx and the access log returns a 404 on wrong usernames (which is good), but a 200 response on failed password attempts. I would think that a 401 would make sense here, and maybe in the wrong username case as well. Here's some example nginx logs, where the 404 was from an incorrect username, and the final 200 response was from an invalid password:
```
10.0.0.231 - - [07/Jun/2023:01:18:58 +0000] "POST /v1/auth HTTP/2.0" 404 19 "https://idm.example.com/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/113.0"
10.0.0.231 - - [07/Jun/2023:01:19:06 +0000] "POST /v1/auth HTTP/2.0" 200 84 "https://idm.example.com/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/113.0"
10.0.0.231 - - [07/Jun/2023:01:19:06 +0000] "POST /v1/auth HTTP/2.0" 200 86 "https://idm.example.com/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/113.0"
10.0.0.231 - - [07/Jun/2023:01:19:10 +0000] "POST /v1/auth HTTP/2.0" 200 92 "https://idm.example.com/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/113.0"
```
Here's the kanidm logs to match the failed username:
```
6f87c797-d578-43f6-b382-da6a77c8bd03 INFO     ┝━ auth [ 273µs | 65.14% ]
6f87c797-d578-43f6-b382-da6a77c8bd03 INFO     │  ┝━ ｉ [info]: Begin auth event | event_tag_id: 9 | sessionid: None | req: AuthRequest { step: Init2 { username: "a", issue: Cookie } }
6f87c797-d578-43f6-b382-da6a77c8bd03 INFO     │  ┕━ ｉ [info]: Sending auth result | event_tag_id: 9 | res: Err(NoMatchingEntries)
6f87c797-d578-43f6-b382-da6a77c8bd03 WARN     ┕━ 🚧 [warn]: Client error --> Response sent | event_tag_id: 5 | status: 404 - Not Found
```
Failed password:
```
dd8e8822-ea5d-4880-b89f-3deef68cb9e8 INFO     ┝━ auth [ 17.7ms | 99.34% ]
dd8e8822-ea5d-4880-b89f-3deef68cb9e8 INFO     │  ┝━ ｉ [info]: Begin auth event | event_tag_id: 9 | sessionid: Some(00000000-647f-db0a-0b27-de21991ea811) | req: AuthRequest { step: Cred(Password(_)) }
dd8e8822-ea5d-4880-b89f-3deef68cb9e8 ERROR    │  ┝━ 🚨 [error]: Handler::Password -> Result::Denied - incorrect password | event_tag_id: 11
dd8e8822-ea5d-4880-b89f-3deef68cb9e8 INFO     │  ┝━ ｉ [info]: Credentials denied | event_tag_id: 9 | reason: incorrect password
dd8e8822-ea5d-4880-b89f-3deef68cb9e8 INFO     │  ┕━ ｉ [info]: Sending auth result | event_tag_id: 9 | res: Ok(AuthResult { sessionid: 00000000-647f-db0a-0b27-de21991ea811, state: AuthState::Denied("incorrect password") })
dd8e8822-ea5d-4880-b89f-3deef68cb9e8 INFO     ┕━ ｉ [info]: --> Response sent | event_tag_id: 6 | status: 200 - OK
```

**Describe the solution you'd like**

Return a 401 (or something more appropriate) on failed authentication. There maybe something I'm overlooking, but this would make it super easy to parse for bad attempts, and then I can configure fail2ban to match.

**Describe alternatives you've considered**

An access log would be also great, similar to what is described in https://github.com/kanidm/kanidm/issues/22. I could parse that with fail2ban, and then ban malicious IP addresses.

**Additional context**

I have a oauth2-proxy communicating with kanidm oauth2/oidc to validate login requests using the `auth_request` directive in nginx. I want to expose some webservers publicly, but want to be able to block malicious IP addresses with fail2ban, since I was planning to have kanidm be the first intercepted service

**Comment by Firstyear** [comment]
I think the current way that we are using the http codes is strictly on the level op the operation. We use 401 in other areas to show that you aren't authorised to access some resource for example. But here, technically 200 is correct because the operation DID succeed, even though the "higher level" result is a denial. 

I think the better option as you indicate is #22, having the event queue that actually feeds out failed authentication attempts into something that can then process these. 

@yaleman If we were to do the event audit system, should it be a structured log file? A socket? Or something like mqtt? Or configurable as to the possible outputs? It's probably going to be something we need sooner than later I think ...

**Comment by yaleman** [comment]
Ah, the API-gives-me-a-200 thing 😄 I'ma (mostly) stay out of that one, but as long as we're indicating the failure happened in the response then that's fine.

I'll put my comments on the audit log over in #22 to save them getting lost.

**Comment by Firstyear** [comment]
> Ah, the API-gives-me-a-200 thing 😄 I'ma (mostly) stay out of that one, but as long as we're indicating the failure happened in the response then that's fine.

Both options kinda-suck and are kinda-right. Giving a 401 indicates that you aren't authorised to a resource, but also it indicates an error when there isn't one. Where the 200 indicates that the operation as a whole worked even if the inner content isn't a success. It's not one where we can win either way. 

> 
> I'll put my comments on the audit log over in #22 to save them getting lost.

Sounds good. I think if @dlrobson is okay with it, we can close this and move over to #22. I am tempted to smash out a minimal version of this for auth success/failure at least so they can proceed.

**Comment by yaleman** [comment]
Yeah, that's something I was going to raise again recently because a single annotated event per attempt in the logs should be a thing :D

**Comment by dlrobson** [comment]
Sounds good with me! I think that's the best solution. I'll close this and move to #22.
