### ISSUE TITLE
how to start the web_ui website? please help me on this, thanks

### ISSUE THREAD

**Issue by aseuler** [kanidm/kanidm#1712]
how to start the web_ui website? please help me on this, thanks

**Comment by yaleman** [comment]
Hi, how are you running the server? The docker containers should include all the requirements, but other methods have their own needs.

**Comment by aseuler** [comment]
thanks for you response.

I use this command to start the service, all the key.pem and chain.pem and dns has been configurated in the $DATA_PATH, login and session check  all are right. I want start the web_ui but don't know how to start it. thanks.
```
docker run -itd --restart=always \
        -p 8443:8443 \
        -p 3636:3636 \
        -v $DATA_PATH:/data \
        --name kanidm_docker \
        kanidm/server:latest
```

so if the docker has already include the web ui, what's the url route?
thanks again...

**Comment by aseuler** [comment]
![image](https://github.com/kanidm/kanidm/assets/128762630/5aef76bd-e821-442c-b0e4-cedf782f5bba)

the root url is ok, application list is null, i already understand the design, thanks again.

**Comment by yaleman** [comment]
Looks like it's working now, applications will show up as you add oauth2 end points.

**Comment by Firstyear** [comment]
Likely we need a "You don't have any applications available" when list.is_empty().
