### ISSUE TITLE
unable to process remote addr in auth/reauth

### ISSUE THREAD

**Issue by yaleman** [kanidm/kanidm#1714]
Thanks @Firstyear! Sorry to keep bugging you. I just pulled the latest build, and I think there might be a small bug. This is what I'm seeing:
```
7ae454b3-4d25-4236-93bd-67ba26b60426 INFO     tide-request [ 103µs | 100.00% ]
7ae454b3-4d25-4236-93bd-67ba26b60426 INFO     ┝━ ｉ [info]: Request received | event_tag_id: 9 | remote_addr: "72.24.19.178" | http.host: "idm.example.com" | http.method: "POST" | path: "/v1/auth"
7ae454b3-4d25-4236-93bd-67ba26b60426 ERROR    ┝━ 🚨 [error]: Unable to process remote addr, refusing to proceed
7ae454b3-4d25-4236-93bd-67ba26b60426 ERROR    ┕━ 🚨 [error]: Internal error -> Response sent | event_tag_id: 4 | message: unable to validate peer address | error_type: "?" | status: 500 - Internal Server Error
```

Which I think is [here](https://github.com/kanidm/kanidm/pull/1711/files#diff-fb54b766a3ec8982eedf95e36742687d4532625889784056c547dafdd03bd256R1102) in the PR. I don't think it's my nginx conf since the log above shows the expected IP address. I think it's just not always getting passed around properly?

Also, would you like me to make a proper issue ticket for this, or is it okay to have this conversation here?

_Originally posted by @dlrobson in https://github.com/kanidm/kanidm/issues/1711#issuecomment-1584474324_

**Comment by yaleman** [comment]
@dlrobson have you got `trust_x_forward_for` set to true in your server config file?

**Comment by Firstyear** [comment]
I would assume that what is occuring is that trust_x_forward_for is set, but isn't actually being set, which is why we can't find it from the header. But I can look more into it later.

**Comment by yaleman** [comment]
yeah I was playing around with various adding/removing headers and couldn't get it to trigger so will need more info

**Comment by dlrobson** [comment]
Thanks for looking into it. I do have the `trust_x_forward_for` tag set. I've attached my configuration below. I was testing with the latest devel image. I'm just confused as to why the logs specify the remote IP address, but then can't process that same IP address later in the request?
```
7ae454b3-4d25-4236-93bd-67ba26b60426 INFO     tide-request [ 103µs | 100.00% ]
7ae454b3-4d25-4236-93bd-67ba26b60426 INFO     ┝━ ｉ [info]: Request received | event_tag_id: 9 | remote_addr: "72.24.19.178" | http.host: "idm.example.com" | http.method: "POST" | path: "/v1/auth"
7ae454b3-4d25-4236-93bd-67ba26b60426 ERROR    ┝━ 🚨 [error]: Unable to process remote addr, refusing to proceed
7ae454b3-4d25-4236-93bd-67ba26b60426 ERROR    ┕━ 🚨 [error]: Internal error -> Response sent | event_tag_id: 4 | message: unable to validate peer address | error_type: "?" | status: 500 - Internal Server Error
```

This is my server.toml config:
```
bindaddress = "[::]:443"
ldapbindaddress = "[::]:3636"
trust_x_forward_for = true
db_path = "/data/kanidm.db"
tls_chain = "/certs/conf/live/example.com/fullchain.pem"
tls_key = "/certs/conf/live/example.com/privkey.pem"
domain = "idm.example.com"
origin = "https://idm.example.com"
```
nginx.conf
```
# /etc/nginx/sites-available/idm.example.com

server {
    server_name idm.example.com;
    proxy_pass_request_headers on;

    listen 80;
    listen [::]:80;

    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    if ($scheme = "http") {
        return 301 https://$host$request_uri;
    }

    # HTTPS server
    ssl_certificate /etc/letsencrypt/live/example.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem;

    location / {
        proxy_http_version 1.1;

        proxy_set_header    Host                $host;
        proxy_set_header    X-Forwarded-Scheme  $scheme;
        proxy_set_header    X-Forwarded-Proto   $scheme;
        proxy_set_header    X-Forwarded-For     $remote_addr;
        proxy_set_header    X-Real-IP           $remote_addr;

        proxy_pass https://kanidm:443;
    }
}
```

**Comment by yaleman** [comment]
Aha, I figured it out - xff headers don't have a port on them so they're failing to parse as SocketAddr's. Patch incoming.

**Comment by dlrobson** [comment]
Thanks @yaleman! I'll try it out and confirm it's working once a new image is published :)

**Comment by Firstyear** [comment]
@dlrobson Images updated, thanks for your patience and feedback :)

**Comment by dlrobson** [comment]
Confirmed that it's working for me. Thanks guys!

**Comment by Firstyear** [comment]
@dlrobson If you have other feedback or ideas, please let us know. We'd be happy to hear them, and if you want to contribute too, we'd love that also. Thanks!
