### ISSUE TITLE
LDAP import failed because users share same gid

### ISSUE THREAD

**Issue by mweinelt** [kanidm/kanidm#1737]
### I did this

All our users currently roll with the `users` group (gid 100) and apparently this leads to this conflict:

```
[error]: ava already exists -> "gidnumber": 6ffa937c-bea6-1034-8e86-056bb39acfc1 conflicts to "example@accounts-test.darmstadt.ccc.de" | event_tag_id: 1
[error]: failed to get cand attr set | event_tag_id: 1 | err: Plugin(AttrUnique("ava already exists")) | attr: "gidnumber"
[error]: Pre-Modify operation failed (plugin), Plugin(AttrUnique("ava already exists")) | event_tag_id: 1
```

### I expected the following

This is something we plan to change, but it shouldn't be a showstopper for importing.

### Kanidm version (and git commit)

https://github.com/kanidm/kanidm/pull/1736/commits/04de09649332b891a5866f8d32cffafdac56d2ac

### Operating System / Version

NixOS 22.11

**Comment by Firstyear** [comment]
We have updated the sync tool to use uidnumber, not gidnumber to avoid this. Have you got the latest version of the ldap sync? Is your config listing uidnumber for persons?

Or is the issue that a users gid number is conflicting to a groups gid number? In that case we'll need a way to remap this in the config. What is the details of entryUUID=6ffa937c-bea6-1034-8e86-056bb39acfc1 in ldap?

Worth also pointing out gid numbers below 1000 can conflict to system accounts so this could be problematic to have a gid number of 100.

**Comment by mweinelt** [comment]
Indeed, the uid of the user maps to the gid of that group and that is causing the conflict. Good to know. Let me renumber that.

**Comment by Firstyear** [comment]
Yeah. The problem on unix/linux is that uidnumber and gidnumber are effectively the same in a lot of ways security wise, so that's why we take a very strong view in Kani to preventing these conflicting between users and groups.

**Comment by mweinelt** [comment]
> 2023-06-15T23:02:17.634234Z  INFO kanidm_ldap_sync: Success!

**Comment by Firstyear** [comment]
We'll still need a way to map uid/gid numbers anyway in the tool, so I should add that.
