### ISSUE TITLE
Document that the security tab is unavailable until IAM migration is finalized

### ISSUE THREAD

**Issue by mweinelt** [kanidm/kanidm#1738]
### I did this

Imported from LDAP, we wondered where the security tab went. Turns out it requires finalizing the migration.

### I expected the following

The security tab or a reason why it is unavailable.

### Kanidm version (and git commit)

n/a

### Operating System / Version

NixOS 22.11

**Comment by Firstyear** [comment]
This is similar to, if not a duplicate of #1713 where when a user is under the control of an external source we should indicate that and where they go to update their credentials.
