### ISSUE TITLE
Allow account locking with expire-at epoch

### ISSUE THREAD

**Issue by KenMacD** [kanidm/kanidm#1755]
Currently the `expire-at` option allows for `never` to disable locking, but doesn't include an 'always'-like option. Being able to specify something like `epoch` would make it easier to disable an account entirely. This would be especially useful in the case of the pseudo-account 'anonymous'.

**Comment by yaleman** [comment]
How about a "now" option, so it's flagged when the change was made?

**Comment by Firstyear** [comment]
I think we should have both "epoch" and "now". Though I do consider "now" to be sufficient, some admins may be worried about clock roll backs.

**Comment by Firstyear** [comment]
PS: Also in this PR we should probably actually fix the doc comments for the CLI options with examples of the timestamps etc.
