### ISSUE TITLE
Consider redb instead of sqlite 

### ISSUE THREAD

**Issue by Firstyear** [kanidm/kanidm#1780]
https://www.redb.org/post/2023/06/16/1-0-stable-release/

This actually fits our goals and architecture really well, and could be a great altenative in the future if we wanted.

**Comment by yaleman** [comment]
Cuuuurious. 🤔

**Comment by Firstyear** [comment]
We only use sqlite as a key-value store anyway, so this logically makes more sense. But, sqlite also is extremely good wrt to durability and crash resistance, and we don't have performance issues so this is more of a future idea.

**Comment by yaleman** [comment]
Yeah, SQLite's *so* well understood and stable that it's a solid choice until there's a clear reason to move.

**Comment by Firstyear** [comment]
I think you're right, I think sqlite is good for what we do so lets not worry too much.
