### ISSUE TITLE
cached tokens show username not matching the target domain when accessing multiple systems

### ISSUE THREAD

**Issue by yaleman** [kanidm/kanidm#1783]
### I did this

Logged into one domain (user@foo.com), then logged into a second one (user@bar.com).

### I expected the following

Auth to fail and not be prompted to log in with user@foo.com

### Kanidm version (and git commit)

Current HEAD

### Operating System / Version

Any 😄 

### Any other comments

Yeah, I know it's unlikely but it's a kooky bug that causes dev fail.

**Comment by Firstyear** [comment]
It's not a security issue fyi - because the tokens will never validate across the domains.

But I do agree it's a bit annoying and unclear. I think we can simply change the cli tools to use spn instead of name for the token cache. What do you think?

**Comment by yaleman** [comment]
Yeah, on second thought it's less a security issue, more a usability one, showing the full SPN for a token when it's only going to be sending the username to the instance.
