### ISSUE TITLE
OIDC with SPA (Owncloud OCIS)

### ISSUE THREAD

**Issue by Phynecs** [kanidm/kanidm#1792]
**Is your feature request related to a problem? Please describe.**

Owncloud OCIS (a next gen Owncloud Server written in Golang) uses an SPA as a frontend.
Because of that it does auth without a secret (could otherwise just be copied from the js frontend) and only uses client id and pkce

**Describe the solution you'd like**

- allow CORS to https://id.DOMAIN/oauth2/openid/CLIENT_ID/.well-known/openid-configuration from the configured `oauth2_rs_origin`?
- support /oauth2/token endpoint with only pkce/client_id and no secret 

**Additional context**

Here are the steps to "reproduce"/the current info I was able to gather
`id.DOMAIN` is kanidm and `ocis.DOMAIN` is Owncloud OCIS

- start login
- access ocis
- the ocis SPA start the login process by getting `openid-configuration` from kanidm as a cors request
![image](https://github.com/kanidm/kanidm/assets/29746892/f58cbf5c-d999-43ef-b7cd-4fba74b0bc27)
- this fails so I added a temporary allow origin header `Access-Control-Allow-Origin: *` in nginx
- now the frontend can get the openid-configuration and redirects to the login in kanidm
- login works and I get redirected back to ocis
- to finish the auth, the frontend tries to get the token which fails:
![image](https://github.com/kanidm/kanidm/assets/29746892/690f6dc5-e2f9-44c9-b355-994bbf91108e)
- the error kanidm prints in the log is:
```
f4858b06-b5ba-4600-8016-ac99307d0901 INFO     tide-request [ 164µs | 52.93% / 100.00% ]
f4858b06-b5ba-4600-8016-ac99307d0901 INFO     ┝━ ｉ [info]: Request received | event_tag_id: 9 | remote_addr: "[::ffff:10.0.0.101]:49606" | http.host: "id.DOMAIN" | http.method: "POST" | path: "/oauth2/token"
f4858b06-b5ba-4600-8016-ac99307d0901 INFO     ┝━ handle_oauth2_token_exchange [ 77.3µs | 47.07% ]
f4858b06-b5ba-4600-8016-ac99307d0901 INFO     │  ┕━ ｉ [info]: Invalid oauth2 authentication - no basic auth or missing auth post data | event_tag_id: 9
f4858b06-b5ba-4600-8016-ac99307d0901 WARN     ┕━ 🚧 [warn]: Client error --> Response sent | event_tag_id: 5 | status: 401 - Unauthorized
```
- I don't know what I could do now

configuration ocis

```
OCIS_URL="https://ocis.DOMAIN"

OCIS_BASE_DATA_PATH="/opt/ocis/data"
OCIS_CONFIG_DIR="/opt/ocis/config"
OCIS_INSECURE="true"
PROXY_TLS=false
PROXY_HTTP_ADDR=0.0.0.0:9200

STORAGE_USERS_DRIVER="s3ng"
STORAGE_SYSTEM_DRIVER="ocis"
STORAGE_USERS_S3NG_ENDPOINT="https://file.DOMAIN"
STORAGE_USERS_S3NG_REGION="default"
STORAGE_USERS_S3NG_ACCESS_KEY="***REDACTED***"
STORAGE_USERS_S3NG_SECRET_KEY="***REDACTED***"
STORAGE_USERS_S3NG_BUCKET="ocis"

PROXY_AUTOPROVISION_ACCOUNTS="true"
PROXY_ROLE_ASSIGNMENT_DRIVER="oidc"
OCIS_OIDC_ISSUER="https://id.DOMAIN/oauth2/openid/ocis/"
PROXY_OIDC_REWRITE_WELLKNOWN="true"
WEB_OIDC_CLIENT_ID="ocis"
#PROXY_OIDC_ACCESS_TOKEN_VERIFY_METHOD=none

OCIS_EXCLUDE_RUN_SERVICES="idm,idp"
```

client config kanidm

```
class: oauth2_resource_server
class: oauth2_resource_server_basic
class: object
displayname: OCIS
es256_private_key_der: private_binary
oauth2_rs_basic_secret: hidden
oauth2_rs_name: ocis
oauth2_rs_origin: https://ocis.DOMAIN/
oauth2_rs_scope_map: idm_all_persons@id.DOMAIN: {"email", "openid", "profile"}
oauth2_rs_token_key: hidden
uuid: c2471b44-b7a9-4b65-9b12-8a36e41358c2
```

**Additional Links**
- [setup guid ocis with authentik](https://helgeklein.com/blog/owncloud-infinite-scale-with-openid-connect-authentication-for-home-networks/)
- [docker compose ocis deployment with keycloak](https://github.com/owncloud/ocis/tree/master/deployments/examples/ocis_keycloak)
- [explanation of the used flow](https://github.com/owncloud/ocis/issues/2445#issuecomment-907392492)
- [ocis docs, a bit convoluted](https://doc.owncloud.com/ocis/next/deployment/services/s-list/web.html)
- [conversation start matrix](https://matrix.to/#/!fzbFDgtoaOQXSSxOZc:gitter.im/$SrzW698_jEUdEJfvZ3kDrWEItFTkgH9J5xdPXtmlueg?via=gitter.im&via=matrix.org&via=infosec.exchange)

**Comment by yaleman** [comment]
Can you grab the POST that's being sent to the server in that `http.method: "POST" | path: "/oauth2/token"` call? It should be on the "payload" tab - I'd be interested to see if it's parsing the response properly etc.

**Comment by Firstyear** [comment]
I think my first step here will be to try to reproduce this myself in an isolated/smaller project to try and understand it better :)

**Comment by Firstyear** [comment]
Hey @yaleman, I dug into this a bunch and found where we might need these cors changes.

Looks like on oauth2_openid_userinfo_get and oauth2_token_post in server/core/src/https/oauth2.rs are missing the header Access-Control-Allow-Origin - the hard part here is how to *get* that data back to those locations. I think we'll need to bubble up Oauth2RS::origin from server/lib/src/idm/oauth2.rs in the response to .handle_oauth2_token_exchange and .handle_oauth2_openid_userinfo for example. I wouldn't want a seperate call to a .handle function here because that would require a second transaction, and because then we need to double handle the client_id. Annoyingly this also means touching a fair bit of *test* surface area since token_exchange especially is heavily used in tests. 

With this in mind, this still doesn't sorlve the client_secret changes needed - that will be another block of work in future. For now I'm being a naughty and stuffed my oauth2 client_secret into the SPA i'm testing with, but I don't think that's an option for Phynecs here.

**Comment by yaleman** [comment]
Yep, double-transactions would suck - the [OWASP OAuth2 testing page here](https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/05-Authorization_Testing/05-Testing_for_OAuth_Weaknesses) seems to imply that allowing a * response would be fine if we're enforcing PKCE.

If we *did* want to respond with the origin, we could modify the response objects with an additional field, but just set it not to serialise since there's fairly heavy yolo-JSONing.

**Comment by Firstyear** [comment]
Yeah, we are enforcing pkce in *almost* all cases - the only cases it can be disabled is because the admin disabled it after reading the scary "insecure don't do this for the love of all that is good" warning. Annoyingly, the issue is openid attempts to use a nonce in place of pkce sometimes and so a lot of openid clients *don't* have pkce even though they *should*. 

Anyway, I think we *can't* stuff uris into those types because we also need to deserialise them in tests and then they wouldn't have a valid value. I think we just set this to '*' and move on.

**Comment by Firstyear** [comment]
So, I now have a SPA working with Kanidm and passing CORS policy. Hooray! 

We are currently in the middle of replacing tide with axum, so once that's done, we can look at touching the oauth2 code since it may affect some of those PR's. I had the forethought in the past to include the ability to switch over different types of possible Oauth2RS authentication types, so I think we have to simply move some schema attrs from oauth2 rs to basic, then we adjust Oauth2RS to have a client-auth-policy which encapsulates the values of client_secret, enable_pkce and the type of auth. That way we can switch on them during all the needed parts.

**Comment by Phynecs** [comment]
(as discussed on gitter)
I think CORS went missing again (in the rewrite), I had to configure it in nginx, otherwise there was the following error:
![image](https://github.com/kanidm/kanidm/assets/29746892/c5c4bc9f-11a0-4db2-96fe-be27c6bacf31)

**Comment by Phynecs** [comment]
(as discussed on gitter)

I'm not sure what to do, but the public client fails on the permit request:
![image](https://github.com/kanidm/kanidm/assets/29746892/bdd69f41-3063-46f4-9988-a50a08daf882)

with the following public client configuration:
```
class: oauth2_resource_server
class: oauth2_resource_server_public
class: object
displayname: ocis
es256_private_key_der: private_binary
oauth2_rs_name: ocis
oauth2_rs_origin: https://ocis.DOMAIN/
oauth2_rs_scope_map: idm_all_persons@id.DOMAIN: {"email", "openid", "profile"}
oauth2_rs_token_key: hidden
```

the following errors are printed during auth and until the permit request:
```
d74fee6c-b43e-4f10-ba3c-7a0f5b9fb43f INFO     request [ 129µs | 52.69% / 100.00% ]
d74fee6c-b43e-4f10-ba3c-7a0f5b9fb43f INFO     ┕━ handle_oauth2_openid_discovery [ 61.1µs | 47.31% ]
00000000-0000-0000-0000-000000000000 ERROR    🚨 [error]: Failed to complete connection: hyper::Error(Shutdown, Os { code: 107, kind: NotConnected, message: "Transport endpoint is not connected" })
3e87431d-c1e1-4842-85b3-24443c1a82be INFO     request [ 272µs | 88.83% / 100.00% ]
3e87431d-c1e1-4842-85b3-24443c1a82be INFO     ┕━ get_domain_display_name [ 30.4µs | 11.17% ]
00000000-0000-0000-0000-000000000000 ERROR    🚨 [error]: Failed to complete connection: hyper::Error(Shutdown, Os { code: 107, kind: NotConnected, message: "Transport endpoint is not connected" })
24c13647-f674-4c75-9d1c-83fac3345c3d INFO     request [ 123µs | 100.00% ]
efed118d-d28f-487d-8eb7-281448bca977 INFO     request [ 138µs | 100.00% ]
637d04ea-0e93-4998-8ad3-b3d014a6c8b0 INFO     request [ 99.6µs | 100.00% ]
00000000-0000-0000-0000-000000000000 ERROR    🚨 [error]: Failed to complete connection: hyper::Error(Shutdown, Os { code: 107, kind: NotConnected, message: "Transport endpoint is not connected" })
ce802cf8-b68d-4671-83e5-a3ad4124fc4c INFO     request [ 83.7µs | 100.00% ]
00000000-0000-0000-0000-000000000000 ERROR    🚨 [error]: Failed to complete connection: hyper::Error(Shutdown, Os { code: 107, kind: NotConnected, message: "Transport endpoint is not connected" })
00000000-0000-0000-0000-000000000000 ERROR    🚨 [error]: Failed to complete connection: hyper::Error(Shutdown, Os { code: 107, kind: NotConnected, message: "Transport endpoint is not connected" })
1a1ff716-74e4-4a54-a6e1-f9ee9041809e INFO     request [ 79.9µs | 100.00% ]
00000000-0000-0000-0000-000000000000 ERROR    🚨 [error]: Failed to complete connection: hyper::Error(Shutdown, Os { code: 107, kind: NotConnected, message: "Transport endpoint is not connected" })
00000000-0000-0000-0000-000000000000 ERROR    🚨 [error]: Failed to complete connection: hyper::Error(Shutdown, Os { code: 107, kind: NotConnected, message: "Transport endpoint is not connected" })
108eee29-67e6-46d1-99e8-befc6f13faf0 INFO     request [ 109µs | 100.00% ]
00000000-0000-0000-0000-000000000000 ERROR    🚨 [error]: Failed to complete connection: hyper::Error(Shutdown, Os { code: 107, kind: NotConnected, message: "Transport endpoint is not connected" })
22717336-0109-47dd-9d91-8915f74ff9c6 INFO     request [ 73.5µs | 100.00% ]
f9f765be-e6cc-4515-8eb2-a3c1e4565ef9 INFO     request [ 272µs | 88.48% / 100.00% ]
f9f765be-e6cc-4515-8eb2-a3c1e4565ef9 INFO     ┕━ get_domain_display_name [ 31.3µs | 11.52% ]
00000000-0000-0000-0000-000000000000 ERROR    🚨 [error]: Failed to complete connection: hyper::Error(Shutdown, Os { code: 107, kind: NotConnected, message: "Transport endpoint is not connected" })
00000000-0000-0000-0000-000000000000 ERROR    🚨 [error]: Failed to complete connection: hyper::Error(Shutdown, Os { code: 107, kind: NotConnected, message: "Transport endpoint is not connected" })
ea57d977-cd98-452e-af25-707d3f459aa7 INFO     request [ 93.5µs | 100.00% ]
00000000-0000-0000-0000-000000000000 ERROR    🚨 [error]: Failed to complete connection: hyper::Error(Shutdown, Os { code: 107, kind: NotConnected, message: "Transport endpoint is not connected" })
badd0fe7-d18c-4181-9f13-4a7998c3e822 INFO     request [ 70.7µs | 100.00% ]
00000000-0000-0000-0000-000000000000 ERROR    🚨 [error]: Failed to complete connection: hyper::Error(Shutdown, Os { code: 107, kind: NotConnected, message: "Transport endpoint is not connected" })
12995a14-20c0-49bd-8481-267e8b7e4fb3 INFO     request [ 108µs | 100.00% ]
00000000-0000-0000-0000-000000000000 ERROR    🚨 [error]: Failed to complete connection: hyper::Error(Shutdown, Os { code: 107, kind: NotConnected, message: "Transport endpoint is not connected" })
7fbda422-820b-490a-b5d3-04234094710f INFO     request [ 126µs | 100.00% ]
30b38a45-c69a-40b7-b4b5-0fa6cc78c033 INFO     request [ 400µs | 11.72% / 100.00% ]
30b38a45-c69a-40b7-b4b5-0fa6cc78c033 INFO     ┕━ handle_auth_valid [ 353µs | 88.28% ]
30b38a45-c69a-40b7-b4b5-0fa6cc78c033 INFO        ┕━ ｉ [info]: A valid session value exists for this token | event_tag_id: 10
00000000-0000-0000-0000-000000000000 ERROR    🚨 [error]: Failed to complete connection: hyper::Error(Shutdown, Os { code: 107, kind: NotConnected, message: "Transport endpoint is not connected" })
00000000-0000-0000-0000-000000000000 ERROR    🚨 [error]: Failed to complete connection: hyper::Error(Shutdown, Os { code: 107, kind: NotConnected, message: "Transport endpoint is not connected" })
678a593a-cff2-4fe4-a27f-738f6b122987 INFO     request [ 378µs | 20.62% / 100.00% ]
678a593a-cff2-4fe4-a27f-738f6b122987 INFO     ┕━ handle_oauth2_authorise [ 300µs | 79.38% ]
678a593a-cff2-4fe4-a27f-738f6b122987 INFO        ┕━ ｉ [info]: A valid session value exists for this token | event_tag_id: 10
00000000-0000-0000-0000-000000000000 ERROR    🚨 [error]: Failed to complete connection: hyper::Error(Shutdown, Os { code: 107, kind: NotConnected, message: "Transport endpoint is not connected" })
2ce75609-5eda-48de-9fda-1227222c72f3 INFO     request [ 181µs | 38.20% / 100.00% ]
2ce75609-5eda-48de-9fda-1227222c72f3 INFO     ┝━ handle_oauth2_authorise_permit [ 112µs | 61.80% ]
2ce75609-5eda-48de-9fda-1227222c72f3 ERROR    │  ┕━ 🚨 [error]: Invalid identity: NotAuthenticated | event_tag_id: 1
2ce75609-5eda-48de-9fda-1227222c72f3 ERROR    ┕━ 🚨 [error]: response failed | classification: Status code: 500 Internal Server Error | latency: 0 ms
00000000-0000-0000-0000-000000000000 ERROR    🚨 [error]: Failed to complete connection: hyper::Error(Shutdown, Os { code: 107, kind: NotConnected, message: "Transport endpoint is not connected" })
```

**Comment by Phynecs** [comment]
I pulled the new :devel, it looks like it gets further, but there is still a problem that even with `Access-Control-Allow-Origin: *` is still throwing an error:
![image](https://github.com/kanidm/kanidm/assets/29746892/a13026a9-e9c2-4bc1-b946-40c60bbbbebb)

kanidm server log:
```
b1b7c584-dd13-45f3-adc5-4f098a310c32 INFO     request [ 115µs | 59.59% / 100.00% ]
b1b7c584-dd13-45f3-adc5-4f098a310c32 INFO     ┕━ handle_oauth2_openid_discovery [ 46.6µs | 40.41% ]
14d70fa8-f992-498f-a745-6a90611359b7 INFO     request [ 340µs | 87.71% / 100.00% ]
14d70fa8-f992-498f-a745-6a90611359b7 INFO     ┕━ get_domain_display_name [ 41.8µs | 12.29% ]
00000000-0000-0000-0000-000000000000 ERROR    🚨 [error]: Failed to complete connection: hyper::Error(Shutdown, Os { code: 107, kind: NotConnected, message: "Transport endpoint is not connected" })
e7a6025f-fead-4554-acdd-77dc98bf17ce INFO     request [ 498µs | 100.00% ]
229e2572-0300-42cf-bdfe-77f3112c1afd INFO     request [ 122µs | 100.00% ]
e6d409f5-3856-4739-976c-80823d7c398a INFO     request [ 200µs | 100.00% ]
8e616dbe-03b3-4e93-bbeb-d2d75eaabcee INFO     request [ 161µs | 100.00% ]
00000000-0000-0000-0000-000000000000 ERROR    🚨 [error]: Failed to complete connection: hyper::Error(Shutdown, Os { code: 107, kind: NotConnected, message: "Transport endpoint is not connected" })
00000000-0000-0000-0000-000000000000 ERROR    🚨 [error]: Failed to complete connection: hyper::Error(Shutdown, Os { code: 107, kind: NotConnected, message: "Transport endpoint is not connected" })
00000000-0000-0000-0000-000000000000 ERROR    🚨 [error]: Failed to complete connection: hyper::Error(Shutdown, Os { code: 107, kind: NotConnected, message: "Transport endpoint is not connected" })
5ee3a66e-9891-4e72-872f-b3916e98bde7 INFO     request [ 99.2µs | 100.00% ]
00000000-0000-0000-0000-000000000000 ERROR    🚨 [error]: Failed to complete connection: hyper::Error(Shutdown, Os { code: 107, kind: NotConnected, message: "Transport endpoint is not connected" })
00000000-0000-0000-0000-000000000000 ERROR    🚨 [error]: Failed to complete connection: hyper::Error(Shutdown, Os { code: 107, kind: NotConnected, message: "Transport endpoint is not connected" })
5eeada51-3174-411a-b30c-401af7c0d1d4 INFO     request [ 89.0µs | 100.00% ]
00000000-0000-0000-0000-000000000000 ERROR    🚨 [error]: Failed to complete connection: hyper::Error(Shutdown, Os { code: 107, kind: NotConnected, message: "Transport endpoint is not connected" })
38ae7b6a-9ab9-45e5-beb9-e3c6f635778b INFO     request [ 88.7µs | 100.00% ]
00000000-0000-0000-0000-000000000000 ERROR    🚨 [error]: Failed to complete connection: hyper::Error(Shutdown, Os { code: 107, kind: NotConnected, message: "Transport endpoint is not connected" })
00960cac-69e0-4f97-9fa9-59b9faffab74 INFO     request [ 389µs | 12.07% / 100.00% ]
00960cac-69e0-4f97-9fa9-59b9faffab74 INFO     ┕━ handle_auth_valid [ 342µs | 87.93% ]
00960cac-69e0-4f97-9fa9-59b9faffab74 INFO        ┕━ ｉ [info]: A valid session value exists for this token | event_tag_id: 10
00000000-0000-0000-0000-000000000000 ERROR    🚨 [error]: Failed to complete connection: hyper::Error(Shutdown, Os { code: 107, kind: NotConnected, message: "Transport endpoint is not connected" })
7f8bc698-e1ff-473a-aa72-570a918c1a34 INFO     request [ 540µs | 22.31% / 100.00% ]
7f8bc698-e1ff-473a-aa72-570a918c1a34 INFO     ┕━ handle_oauth2_authorise [ 420µs | 77.69% ]
7f8bc698-e1ff-473a-aa72-570a918c1a34 INFO        ┝━ ｉ [info]: A valid session value exists for this token | event_tag_id: 10
7f8bc698-e1ff-473a-aa72-570a918c1a34 INFO        ┕━ ｉ [info]: User has previously consented, permitting. {"email", "openid", "profile"} | event_tag_id: 3
00000000-0000-0000-0000-000000000000 ERROR    🚨 [error]: Failed to complete connection: hyper::Error(Shutdown, Os { code: 107, kind: NotConnected, message: "Transport endpoint is not connected" })
d0a21684-0335-49e4-9167-96f313fe7e34 INFO     request [ 115µs | 100.00% ]
b8c70f13-4478-49f4-a722-42cf67be5e7b INFO     request [ 128µs | 100.00% ]
00000000-0000-0000-0000-000000000000 ERROR    🚨 [error]: Failed to complete connection: hyper::Error(Shutdown, Os { code: 107, kind: NotConnected, message: "Transport endpoint is not connected" })
00000000-0000-0000-0000-000000000000 ERROR    🚨 [error]: Failed to complete connection: hyper::Error(Shutdown, Os { code: 107, kind: NotConnected, message: "Transport endpoint is not connected" })
e933a890-ca7d-4b3e-adf4-7052a4d66fbd INFO     request [ 69.0µs | 100.00% ]
00000000-0000-0000-0000-000000000000 ERROR    🚨 [error]: Failed to complete connection: hyper::Error(Shutdown, Os { code: 107, kind: NotConnected, message: "Transport endpoint is not connected" })
165ee740-35d6-444e-ab55-822057229db9 INFO     request [ 126µs | 60.72% / 100.00% ]
165ee740-35d6-444e-ab55-822057229db9 INFO     ┕━ handle_oauth2_openid_discovery [ 49.5µs | 39.28% ]
00000000-0000-0000-0000-000000000000 ERROR    🚨 [error]: Failed to complete connection: hyper::Error(Shutdown, Os { code: 107, kind: NotConnected, message: "Transport endpoint is not connected" })
8bf49ece-53e3-45b1-bf4a-d0a856e4b05c INFO     request [ 18.4ms | 0.65% / 100.00% ]
8bf49ece-53e3-45b1-bf4a-d0a856e4b05c INFO     ┕━ handle_oauth2_token_exchange [ 18.3ms | 4.63% / 99.35% ]
8bf49ece-53e3-45b1-bf4a-d0a856e4b05c INFO        ┕━ commit [ 17.4ms | 94.72% ]
00000000-0000-0000-0000-000000000000 ERROR    🚨 [error]: Failed to complete connection: hyper::Error(Shutdown, Os { code: 107, kind: NotConnected, message: "Transport endpoint is not connected" })
c9deaf28-7ee9-47d9-87ff-93146c90abda INFO     request [ 28.7µs | 100.00% ]
00000000-0000-0000-0000-000000000000 ERROR    🚨 [error]: Failed to complete connection: hyper::Error(Shutdown, Os { code: 107, kind: NotConnected, message: "Transport endpoint is not connected" })
```

**Comment by Firstyear** [comment]
Oh it got preflighted, my test spa didnt trigger this so i missed it.

**Comment by Phynecs** [comment]
fyi cors an preflight work now without setting nginx options
I'm now just struggling with OCIS complaining about the token:
```json
{"level":"error","service":"proxy","error":"failed to verify access token: token contains an invalid number of segments","authenticator":"oidc","path":"/ocs/v1.php/cloud/user","time":"2023-07-14T13:03:38.322627809Z","message":"failed to authenticate the request"}
```
the kanidm logs look ok (when excluding "Failed to complete connection"):
```
0669e496-8a62-446c-a809-b4f3e46a9208 INFO     request [ 126µs | 72.51% / 100.00% ]
0669e496-8a62-446c-a809-b4f3e46a9208 INFO     ┕━ get_domain_display_name [ 34.7µs | 27.49% ]
1878472e-6e18-4193-96d6-1ad2d693a294 INFO     request [ 158µs | 100.00% ]
78340505-fe2c-4084-b6ea-c26090ab1475 INFO     request [ 106µs | 100.00% ]
37b83e76-0d6b-4135-b0a3-c23ce97c1874 INFO     request [ 91.5µs | 100.00% ]
52eeb743-d7b9-40f9-9dce-f0ed1b641404 INFO     request [ 118µs | 100.00% ]
bf77fd9f-db94-4e15-8754-e4c90c05f0d4 INFO     request [ 89.2µs | 100.00% ]
f6332c67-cd55-450e-af45-f120b03fd521 INFO     request [ 83.8µs | 100.00% ]
c40791cd-a169-4ff5-9aa6-ae3db94ea88d INFO     request [ 73.3µs | 100.00% ]
94bea679-9b69-4ecb-ab08-a456f0b98fc3 INFO     request [ 282µs | 19.30% / 100.00% ]
94bea679-9b69-4ecb-ab08-a456f0b98fc3 INFO     ┕━ handle_auth_valid [ 227µs | 80.70% ]
94bea679-9b69-4ecb-ab08-a456f0b98fc3 INFO        ┕━ ｉ [info]: A valid session value exists for this token | event_tag_id: 10
ab215d81-77b2-417a-b6a3-2d208daa009c INFO     request [ 501µs | 19.53% / 100.00% ]
ab215d81-77b2-417a-b6a3-2d208daa009c INFO     ┕━ handle_oauth2_authorise [ 403µs | 80.47% ]
ab215d81-77b2-417a-b6a3-2d208daa009c INFO        ┝━ ｉ [info]: A valid session value exists for this token | event_tag_id: 10
ab215d81-77b2-417a-b6a3-2d208daa009c INFO        ┕━ ｉ [info]: User has previously consented, permitting with scopes: email,openid,profile | event_tag_id: 3
91226f76-20d7-46e0-ab38-c127a525c6bb INFO     request [ 85.4µs | 100.00% ]
3ba7f2a3-fe52-410b-bedb-2b3e9906e417 INFO     request [ 103µs | 100.00% ]
cf34a206-819c-4d40-9cd3-d2e875bac323 INFO     request [ 112µs | 64.38% / 100.00% ]
cf34a206-819c-4d40-9cd3-d2e875bac323 INFO     ┕━ handle_oauth2_openid_discovery [ 39.9µs | 35.62% ]
e39f989c-b882-406b-9f46-19a1ee57691f INFO     request [ 8.07ms | 1.33% / 100.00% ]
e39f989c-b882-406b-9f46-19a1ee57691f INFO     ┕━ handle_oauth2_token_exchange [ 7.97ms | 11.91% / 98.67% ]
e39f989c-b882-406b-9f46-19a1ee57691f INFO        ┕━ commit [ 7.00ms | 86.76% ]
3c75a6ee-b6e4-4e46-b1b7-6964ffef0025 INFO     request [ 42.4µs | 100.00% ]
32895356-4d06-4603-a45a-33e62f10e2f0 INFO     request [ 257µs | 23.48% / 100.00% ]
32895356-4d06-4603-a45a-33e62f10e2f0 INFO     ┕━ handle_oauth2_openid_userinfo [ 197µs | 76.52% ]
32895356-4d06-4603-a45a-33e62f10e2f0 INFO        ┕━ ｉ [info]: The token grace window is in effect. Assuming valid. | event_tag_id: 10
```

my next tries are either trying a different SPA or a different OIDC server and comparing requests/responses

**Comment by Firstyear** [comment]
> fyi cors an preflight work now without setting nginx options I'm now just struggling with OCIS complaining about the token:
> 
> ```json
> {"level":"error","service":"proxy","error":"failed to verify access token: token contains an invalid number of segments","authenticator":"oidc","path":"/ocs/v1.php/cloud/user","time":"2023-07-14T13:03:38.322627809Z","message":"failed to authenticate the request"}
> ```
> 
> the kanidm logs look ok (when excluding "Failed to complete connection"):
> 
> ```
> 0669e496-8a62-446c-a809-b4f3e46a9208 INFO     request [ 126µs | 72.51% / 100.00% ]
> 0669e496-8a62-446c-a809-b4f3e46a9208 INFO     ┕━ get_domain_display_name [ 34.7µs | 27.49% ]
> 1878472e-6e18-4193-96d6-1ad2d693a294 INFO     request [ 158µs | 100.00% ]
> 78340505-fe2c-4084-b6ea-c26090ab1475 INFO     request [ 106µs | 100.00% ]
> 37b83e76-0d6b-4135-b0a3-c23ce97c1874 INFO     request [ 91.5µs | 100.00% ]
> 52eeb743-d7b9-40f9-9dce-f0ed1b641404 INFO     request [ 118µs | 100.00% ]
> bf77fd9f-db94-4e15-8754-e4c90c05f0d4 INFO     request [ 89.2µs | 100.00% ]
> f6332c67-cd55-450e-af45-f120b03fd521 INFO     request [ 83.8µs | 100.00% ]
> c40791cd-a169-4ff5-9aa6-ae3db94ea88d INFO     request [ 73.3µs | 100.00% ]
> 94bea679-9b69-4ecb-ab08-a456f0b98fc3 INFO     request [ 282µs | 19.30% / 100.00% ]
> 94bea679-9b69-4ecb-ab08-a456f0b98fc3 INFO     ┕━ handle_auth_valid [ 227µs | 80.70% ]
> 94bea679-9b69-4ecb-ab08-a456f0b98fc3 INFO        ┕━ ｉ [info]: A valid session value exists for this token | event_tag_id: 10
> ab215d81-77b2-417a-b6a3-2d208daa009c INFO     request [ 501µs | 19.53% / 100.00% ]
> ab215d81-77b2-417a-b6a3-2d208daa009c INFO     ┕━ handle_oauth2_authorise [ 403µs | 80.47% ]
> ab215d81-77b2-417a-b6a3-2d208daa009c INFO        ┝━ ｉ [info]: A valid session value exists for this token | event_tag_id: 10
> ab215d81-77b2-417a-b6a3-2d208daa009c INFO        ┕━ ｉ [info]: User has previously consented, permitting with scopes: email,openid,profile | event_tag_id: 3
> 91226f76-20d7-46e0-ab38-c127a525c6bb INFO     request [ 85.4µs | 100.00% ]
> 3ba7f2a3-fe52-410b-bedb-2b3e9906e417 INFO     request [ 103µs | 100.00% ]
> cf34a206-819c-4d40-9cd3-d2e875bac323 INFO     request [ 112µs | 64.38% / 100.00% ]
> cf34a206-819c-4d40-9cd3-d2e875bac323 INFO     ┕━ handle_oauth2_openid_discovery [ 39.9µs | 35.62% ]
> e39f989c-b882-406b-9f46-19a1ee57691f INFO     request [ 8.07ms | 1.33% / 100.00% ]
> e39f989c-b882-406b-9f46-19a1ee57691f INFO     ┕━ handle_oauth2_token_exchange [ 7.97ms | 11.91% / 98.67% ]
> e39f989c-b882-406b-9f46-19a1ee57691f INFO        ┕━ commit [ 7.00ms | 86.76% ]
> 3c75a6ee-b6e4-4e46-b1b7-6964ffef0025 INFO     request [ 42.4µs | 100.00% ]
> 32895356-4d06-4603-a45a-33e62f10e2f0 INFO     request [ 257µs | 23.48% / 100.00% ]
> 32895356-4d06-4603-a45a-33e62f10e2f0 INFO     ┕━ handle_oauth2_openid_userinfo [ 197µs | 76.52% ]
> 32895356-4d06-4603-a45a-33e62f10e2f0 INFO        ┕━ ｉ [info]: The token grace window is in effect. Assuming valid. | event_tag_id: 10
> ```
> 
> my next tries are either trying a different SPA or a different OIDC server and comparing requests/responses

It's possible that your service doesn't support ECC signatures since you are getting a failure to authenticate the request? 

From the kani side, this all looks valid here.

**Comment by Phynecs** [comment]
thx for the tip, you're probably right, I unfortunately haven't had time to test any of the mentioned options yet
will try to test with keyclaok (if I'm not mistaken I should be able to remove all keys apart from ECC there) if I get the same error I can then open an issue at owncloud about this

**Comment by Firstyear** [comment]
@Phynecs There is a way in kani to use rsa keys - see https://kanidm.github.io/kanidm/stable/integrations/oauth2.html#extended-options-for-legacy-clients

**Comment by Phynecs** [comment]
so i finally found the problem OCIS expects the token to be a jwt by default, which it isn't with kanidm: https://github.com/owncloud/ocis/issues/4895#issuecomment-1293136653

solution set the following OCIS env:
```
PROXY_OIDC_ACCESS_TOKEN_VERIFY_METHOD=none
```

now there is a new error in OCIS, no hurry in replying, it took me forever to get back to you

error in OCIS:
```
Jul 29 21:17:24 ocis ocis[12414]: {"level":"error","service":"proxy","request-id":"43be0cad-1368-4b02-ac0e-5316166eade9","userid":"bb3ffa5a-fe4c-48ae-b337-fbc323493503","rolesClaim":"roles","time":"2023-07-29T21:17:24.243560206Z","message":"No roles in user claims"}
Jul 29 21:17:24 ocis ocis[12414]: {"level":"error","service":"proxy","error":"no roles in user claims","time":"2023-07-29T21:17:24.244071633Z","message":"Could not get user roles"}
```

"No roles in user claims", this sounds to me like it's just a configuration issue/a knowledge gap in oauth2 on my side

**Comment by yaleman** [comment]
Yeah looks like you'll need to configure the role mappings on the OCIS side

**Comment by Phynecs** [comment]
had to remove, or set to default the following env: `PROXY_ROLE_ASSIGNMENT_DRIVER="oidc"`
otherwise I have to set `PROXY_ROLE_ASSIGNMENT_OIDC_CLAIM` to the claim used to create the users role assignment

docs for this and the last change: https://doc.owncloud.com/ocis/next/deployment/services/s-list/proxy.html

**Comment by Phynecs** [comment]
well they made an, in my opinion, strange decisions for their desktop/mobile clients, a hard coded client id an secret, documented in their docs...: https://doc.owncloud.com/server/next/admin_manual/configuration/user/oidc/oidc.html#client-ids-secrets-and-redirect-uris

**Comment by Firstyear** [comment]
> ```
> PROXY_OIDC_ACCESS_TOKEN_VERIFY_METHOD=none
> ```

This is not strictly a violation of the OIDC spec, but a huge misuse of it at the least. Access tokens are *opaque* and are never intended for the client to verify. So I'm a bit worried about their overall OIDC implementation now ...

> a hard coded client id an secret,

I wonder if this is to avoid the pkce issues we had before? 🤔

Regardless, I'm glad it's all working for you know. Your patience and communication was really appreciated, and it's helped to make Kanidm a better IDM. Thank you!
