### ISSUE TITLE
Look at supporting RFC8414 - OAuth 2.0 AS Metadata

### ISSUE THREAD

**Issue by yaleman** [kanidm/kanidm#1796]
**Describe the solution you'd like**

Support for https://www.rfc-editor.org/rfc/rfc8414.txt

It looks neat.

**Describe alternatives you've considered**

Just... not

**Additional context**

>   This specification defines a metadata format that an OAuth 2.0 client
>   can use to obtain the information needed to interact with an
>   OAuth 2.0 authorization server, including its endpoint locations and
>   authorization server capabilities.

**Comment by Firstyear** [comment]
I'm okay to support this in theory, since it's so similar to what we already have with openid. My only concern is do *clients* actually support it? I haven't see much evidence that they do ...

**Comment by adamcstephens** [comment]
Soju for one is using RFC 8414 for oauth2. https://soju.im/doc/soju.1.html#CONFIG_FILE

**Comment by Firstyear** [comment]
Good enough for me :)
