### ISSUE TITLE
Add tests for X-Forwarded-For header things

### ISSUE THREAD

**Issue by yaleman** [kanidm/kanidm#1818]
Integration tests, need to test for the following:

- trust_xff is on, sending header
- trust_xff is on, don't send header
- the above two, but trust_xff off

**Comment by Seba-T** [comment]
I think I've managed to write the four cases and get them working, but after playing with it for a bit I began to wonder what should the expected behavior be. If we have trust_xff on, is the server supposed to send to the leftmost address? Should it just ignore the header if trust_xff is off or should it return an error?

**Comment by Seba-T** [comment]
I was banging my head around the specs (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For) but looks like everyone can do whatever they want basically

**Comment by scabrero** [comment]
Hi @Seba-T, I was also looking at this and had the same question. To my understanding, the server always has to reply to request's source IP but if this header is present it must be used to identify the client internally for logs, access controls, etc.

So IMO the behavior should be:

If trust_xff is ON:
- If header is present use the left-most address in the header to identify the client
- If the header is not present use the request's source IP to identify the client

If trust_xff is OFF:
- Ignore the header if preset and always use request's source IP to identify the client, maybe printing a warning if present.

What I am missing is how to check the xff address is actually used internally. Maybe `whoami` returns the client IP?

**Comment by yaleman** [comment]
One of the main uses is for logging, once we figure out how to hold axum/tide's logging propertly 😄

**Comment by Seba-T** [comment]
hold on so we can't test it properly as of now correct?

**Comment by scabrero** [comment]
> hold on so we can't test it properly as of now correct?

At least we can test that if trust_xff is enabled and the header contains an invalid IP address the auth request returns 400 right?

**Comment by yaleman** [comment]
> > hold on so we can't test it properly as of now correct?

The routes that use it are `/v1/auth` and `/v1/reauth`, I *believe* they might be making use of it deep in the internals somewhere.
 
> At least we can test that if trust_xff is enabled and the header contains an invalid IP address the auth request returns 400 right?

That's a test which we should be doing, yes.

**Comment by Seba-T** [comment]
Uh makes sense I'm gonna try that out
