### ISSUE TITLE
Add Strict-Transport-Security headers to responses

### ISSUE THREAD

**Issue by yaleman** [kanidm/kanidm#1823]
**Is your feature request related to a problem? Please describe.**

[HSTS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security) responses with `max-age=86400` should be included in all 
responses from at least `/`, `/ui*`, `/pkg*` but it doesn't hurt for it to be global.

**Describe the solution you'd like**

Add the header to all responses.

**Describe alternatives you've considered**

Sitting on the couch playing Zelda or something.

**Additional context**

**Comment by Seba-T** [comment]
Playing Zelda wasn't an option :p

**Comment by yaleman** [comment]
I guess you might not have a copy of any of the Zelda games, so something else is an option, but thanks for the PR 💟

**Comment by Firstyear** [comment]
@yaleman Feel free to open an issue to donate a copy of zelda to seb then :)

**Comment by Seba-T** [comment]
the lack of Zelda is starting to hit real hard up here :p
