### ISSUE TITLE
precompute + deliver brotli compressed WASM package

### ISSUE THREAD

**Issue by yaleman** [kanidm/kanidm#1827]
- **Is your feature request related to a problem? Please describe.**

A bit of a skunkworks idea - but we can precompress the WASM package and save 1/3 of the size, delivering it if they send an `Accept-Encoding` header 
which includes `br`.

**Describe the solution you'd like**

- Include a build step that uses `brotli` to compress the WASM package (testing shows this takes ~2 seconds and reduces the release package from 1.4MB to 
400KB)
- For requests to the WASM package, check for the header and return a different file

**Describe alternatives you've considered**

Enabling the `brotli` feature on `axum-compress`, but this introduces *significant* response time delays as it's doing it on the fly.

**Additional context**

2/3 less bytes, 50% more snappy. :crab:

**Comment by Firstyear** [comment]
Couldn't we also consider zstd too? Because then we can pre-compress them to whatever level we want too.

**Comment by yaleman** [comment]
I can't find any reference to browsers natively supporting zstd? `br` is part of the spec/community standards.

Ref:

- [MDN Accept-Encoding](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Encoding)
- [CanIUse](https://caniuse.com/?search=accept-encoding)

**Comment by Firstyear** [comment]
Isn't this done now? i can see our br files in wasm :)

**Comment by yaleman** [comment]
There's no handling for the accept header and subsequent file-yeeting yet - I'll do that next week when I'm back unless someone wants to in the meantime.

**Comment by Seba-T** [comment]
I was trying to give it a shot but I kinda got confused on how to provide the already compressed .br file without using something like `.layer(middleware::compression::new()) // TODO: this needs to be configured properly` (which wasn't working anyway). With a little help I think I can get it sorted out!

**Comment by Seba-T** [comment]
I suspected that but I found no documentation on how to make it work :/. I expected it to just work if I provided the .br file instead of the original but it doesn't decompress it out of the box

**Comment by yaleman** [comment]
I envision there'll need to be:

- a route for the WASM file, which checks for the `accept` header, and delivers the brotli file based on that, or just the normal file. If the brotli's sent, set a response header like "x-brotli-redirected".
- a [Predicate](https://docs.rs/tower-http/latest/tower_http/compression/predicate/trait.Predicate.html) in the compression layer which tells it not to do any compression, if that header's set
- one of the "outer" layers needs to strip that x-brotli-redirected header (because the predicate can't)

**Comment by Seba-T** [comment]
Thanks!! I'll try to give it a shot later today then :)
