### ISSUE TITLE
service-accounts are not members of posix enabled groups on kanidm client machines

### ISSUE THREAD

**Issue by matthew-salerno** [kanidm/kanidm#1830]
### I did this
I created a Kanidm setup on NixOS:
**On the server:**
Related nix config:
(my domain replaced with example.com)
```nix
services.kanidm = {
        enableServer = true;
        serverSettings.tls_key = "/var/lib/kanidm-certs/privkey.pem";
        serverSettings.tls_chain = "/var/lib/kanidm-certs/fullchain.pem";
        serverSettings.origin = "https://idm.example.com";
        serverSettings.domain = "example.com";
      };
```
Generated files:
server.toml
```toml
bindaddress = "192.168.1.4:433"
db_path = "/var/lib/kanidm/kanidm.db"
domain = "example.com"
log_level = "default"
origin = "https://idm.example.com"
role = "WriteReplica"
tls_chain = "/var/lib/kanidm-certs/fullchain.pem"
tls_key = "/var/lib/kanidm-certs/privkey.pem"
```
This is on a raspberry pi 4 8gb running NixOS stable, same kanidm commit as clients.
Firewall is open, certs are readable, most functionality works as expected.
Certs are rotated every day, hopefully not relevant to this problem but worth putting out there. 

**On the clients:**
Related nix config:
```nix
services.kanidm = {
      enableClient = true;
      clientSettings = {
        uri = "https://idm.example.com:433";
        enablePam = true;
        verify_ca = true;
        verify_hostnames = true;
        ca_path = /path/to/certificate/in/nix/store;
      };
      unixSettings = {
        pam_allowed_login_groups = ["posix_group" "posix_admin"];
        default_shell = "/var/run/current-system/sw/bin/fish";
        home_prefix = "/home/";
        home_attr = "uuid";
        home_alias = "spn";
        use_etc_skel = false;
        uid_attr_map = "spn";
        gid_attr_map = "spn";
        selinux = false;
      };
      enablePam = true;
    };
```
Generated files:
/etc/nssswitch.conf
```
passwd:    files kanidm systemd
group:     files kanidm [success=merge] systemd
shadow:    files

hosts:     mymachines files myhostname dns
networks:  files

ethers:    files
services:  files
protocols: files
rpc:       files
```
/etc/pam.d/login
```
# Account management.
account sufficient /nix/store/5v8329m2nm4cizrykj7mkqqcvr9rcpx4-kanidm-1.1.0-alpha.12/lib/pam_kanidm.so ignore_unknown_user
account required pam_unix.so

# Authentication management.
auth optional pam_unix.so nullok  likeauth
auth optional /nix/store/gmxx1nbh1vqgxcv4z9hs0cpx24p3w3yi-kwallet-pam-5.27.6/lib/security/pam_kwallet5.so kwalletd=/nix/store/f718fk50zizawlrwhy5rdsnsmyh24wik-kwallet-5.106.0-bin/bin/kwalletd5
auth sufficient pam_unix.so nullok  likeauth try_first_pass
auth sufficient /nix/store/5v8329m2nm4cizrykj7mkqqcvr9rcpx4-kanidm-1.1.0-alpha.12/lib/pam_kanidm.so ignore_unknown_user use_first_pass
auth required pam_deny.so

# Password management.
password sufficient pam_unix.so nullok yescrypt
password sufficient /nix/store/5v8329m2nm4cizrykj7mkqqcvr9rcpx4-kanidm-1.1.0-alpha.12/lib/pam_kanidm.so

# Session management.
session required pam_env.so conffile=/etc/pam/environment readenv=0
session required pam_unix.so
session required pam_loginuid.so
session required /nix/store/adhvlxv9vqqkqdjm8xlvqp1c1brhbrwb-linux-pam-1.5.2/lib/security/pam_lastlog.so silent
session optional /nix/store/5v8329m2nm4cizrykj7mkqqcvr9rcpx4-kanidm-1.1.0-alpha.12/lib/pam_kanidm.so
session optional /nix/store/8lgs0dqh9ks1164fp4g14gq7w1ihjbf0-systemd-253.5/lib/security/pam_systemd.so
session optional /nix/store/gmxx1nbh1vqgxcv4z9hs0cpx24p3w3yi-kwallet-pam-5.27.6/lib/security/pam_kwallet5.so kwalletd=/nix/store/f718fk50zizawlrwhy5rdsnsmyh24wik-kwallet-5.106.0-bin/bin/kwalletd5
```

**After configuring client and server, I ran the following commands:**
Create a service-account and group, then check membership on client:
(command line somewhat truncated, $ is command, # is comment, > is output)
```bash
$ kanidm group create posix_group
$ kanidm group posix set posix_group
$ kanidm service-account create testunix "test unix"
$ kanidm group add-members posix_group testunix
$ kanidm service-account posix set testunix
# login
$ sudo su testunix
# enter login info
# check groups (also tried id command with the same results)
$ groups
> testunix@example.com
```
Create a person and group, then check membership on client:
```bash
$ kanidm person create testperson "test person"
$ kanidm group add-members posix_group testperson
$ kanidm person posix set testperson
# login
$ sudo su testperson
# enter login information
# check groups (also tried id command with the same results)
$ groups
> testperson@example.com posix_group@example.com
```
Person returns the expected groups (`testperson` and `posix_group`), but service-account only returns `testunix` group
this has been validated by trying to read a file owned by `root` user and `posix_group` group, with `770` permissions. The person account could read it but the service-account could not.
### I expected the following
I expect the service-account, in a posix system, to belong to all posix enabled groups it is a member of in Kanidm  
### Kanidm version (and git commit)

kanidm 1.1.0-alpha.12:
- [kanidm commit](https://github.com/kanidm/kanidm/tree/bcdbb1837adc8e18064b93cb0bc3ed15c27e7702)

### Operating System / Version
NixOS stable:
- [nixpkgs commit](https://github.com/NixOS/nixpkgs/tree/9790f3242da2152d5aa1976e3e4b8b414f4dd206)
- [nixpkgs kanidm package](https://github.com/NixOS/nixpkgs/blob/9790f3242da2152d5aa1976e3e4b8b414f4dd206/pkgs/servers/kanidm/default.nix)
- [nixpkgs kanidm service](https://github.com/NixOS/nixpkgs/blob/9790f3242da2152d5aa1976e3e4b8b414f4dd206/nixos/modules/services/security/kanidm.nix)
- `uname -a`:
`Linux nixos 6.4.0 #1-NixOS SMP PREEMPT_DYNAMIC Sun Jun 25 23:29:58 UTC 2023 x86_64 GNU/Linux`

### Any other comments
Service account shows correct membership when querying kanidm. 
When running `getent passwd testunix@example.com` the testunix user is returned.
When running `getent group posix_group@example.com` the group is returned.
if `getent passwd testunix@example.com` was run within 15 seconds before `getent group posix_group@example.com`, `getent group posix_group@example.com` will return testunix as a member, otherwise it will not.
Running `getent passwd testunix@example.com` does not change the results of `groups` or allow reading a group owned file with `770` permissions, regardless of time frame.

**Comment by Firstyear** [comment]
I've reproduced this locally and will investigate.
