### ISSUE TITLE
Selinux library enabled but not running causes home dirs to fail to be created

### ISSUE THREAD

**Issue by Firstyear** [kanidm/kanidm#1846]
```
Jul 10 21:28:12 cream.firstyear.id.au kanidm_unixd_tasks[1183]: 00000000-0000-0000-0000-000000000000 TRACE    📍 [trace]: attempting to decode a frame
Jul 10 21:28:12 cream.firstyear.id.au kanidm_unixd_tasks[1183]: 00000000-0000-0000-0000-000000000000 TRACE    📍 [trace]: frame decoded from buffer
Jul 10 21:28:12 cream.firstyear.id.au kanidm_unixd_tasks[1183]: 00000000-0000-0000-0000-000000000000 DEBUG    🐛 [debug]: Received task -> HomeDirectory(HomeDirectoryInfo { gid: 654401105, name: "886b45ce-98b2-4d79-9069-c9ff25bc0232", aliases: ["william"] })
Jul 10 21:28:12 cream.firstyear.id.au kanidm_unixd_tasks[1183]: 00000000-0000-0000-0000-000000000000 DEBUG    🐛 [debug]: Attempting to send request -> Error("Failed getting handle for SELinux labeling") ...
Jul 10 21:28:12 cream.firstyear.id.au kanidm_unixd_tasks[1183]: 00000000-0000-0000-0000-000000000000 TRACE    📍 [trace]: flushing framed transport
```

**Comment by Firstyear** [comment]
@0xC0ncord When I have the kanidm-unixd setup with selinux but selinux libraries not installed, the tasks daemon fails to create the home dir.

So I think we should consider how we approach this. If we can't get the labeler should we:

* Error out as we currently do and prevent the home dir being created. selinux=false doesn't appear to stop the labeler being requested though.
* If a labeler can't be found, proceed and don't label.

I think we should do the latter since that way if a system has selinux, we'll label properly, and if it doesn't we still create the unlabeled homedir. What do you think?

**Comment by 0xC0ncord** [comment]
> When I have the kanidm-unixd setup with selinux but selinux libraries not installed, the tasks daemon fails to create the home dir.

Ah, I didn't consider this case.

> So I think we should consider how we approach this. If we can't get the labeler should we:

>Error out as we currently do and prevent the home dir being created. selinux=false doesn't appear to stop the labeler being requested though.
>If a labeler can't be found, proceed and don't label.

First I think that setting `selinux = false` *should* disable this. If it doesn't already (checking the code I believe this isn't the case) this should be considered a bug. One of my original design goals was to be able to set this to `false` even when SELinux was available on the host system for testing, but it seems that got lost somewhere in development. This looks like an easy fix though.

As for how to handle this going forward, I think the current behavior of erroring immediately is best. If a handle to the labeler cannot be obtained then that is indicative of a broken SELinux userspace (such as when the libraries are not installed) and possibly problems much larger than what Kanidm should be expected to deal with.

**Comment by Firstyear** [comment]
I think I agree - it's better to "fail noisy" in these cases to say "hey something is wrong" rather than keep going and silently fail to correctly label things.

I think I should be able to fix this pretty easily in this case then :)

**Comment by 0xC0ncord** [comment]
I don't mind working on the patch unless you need it sooner than tomorrow. ;)

Jul 10, 2023 23:52:44 Firstyear ***@***.***>:

**Comment by Firstyear** [comment]
I'm already half way finished it :)

**Comment by 0xC0ncord** [comment]
No worries. Thanks. :)

Jul 11, 2023 00:12:00 Firstyear ***@***.***>:
