### ISSUE TITLE
kanidm/radius docker image is not compatible with aarch64/arm64

### ISSUE THREAD

**Issue by ashhhleyyy** [kanidm/kanidm#1854]
The radiusd docker image is built for `amd64` and `arm64` using `freeradius/freeradius-server` as it's base image, however attempting to launch it on an arm64 device (such a Raspberry Pi 4) results in an `exec format error`, suggesting that one of the used binaries is not compiled for the correct architecture. From looking at the freeradius-server image [on Docker hub](https://hub.docker.com/layers/freeradius/freeradius-server/latest/images/sha256-1ca67fbd54c319029750051671341f5ea96b9bb5ea76198e81548593b4d41a70?context=explore), it seems that this image is only built for `amd64`, which means that the `arm64` kanidm/radius image is based on an image for the wrong architecture.

## Extra info
`uname -a` output:
```
Linux kylie 5.15.32-v8+ #1538 SMP PREEMPT Thu Mar 31 19:40:39 BST 2022 aarch64 GNU/Linux
```

Docker container logs:
```
ash@kylie in ~> docker logs -n 100 -f kanidm-radius
exec /docker-entrypoint.sh: exec format error
exec /docker-entrypoint.sh: exec format error
exec /docker-entrypoint.sh: exec format error
exec /docker-entrypoint.sh: exec format error
exec /docker-entrypoint.sh: exec format error
exec /docker-entrypoint.sh: exec format error
(my configured restart-policy gives up restarting the container)
ash@kylie in ~>
```

**Comment by yaleman** [comment]
@Firstyear I'm not sure how you're building the docker-hosted ones?

**Comment by Firstyear** [comment]
@yaleman Same as everything else - make buildx/radiusd. My guess is that docker is doing something cursed underneath us here and taking arm64 being absent to try to run an amd64 build in some way. 

We might need to swap back to our own build process reverting the use of the freeradius container I think if they are limited to amd64 only.

**Comment by yaleman** [comment]
Ah curious I thought this one had an ARM build... seems weird I'd have moved it across like that 🤔

**Comment by Firstyear** [comment]
Anyway, I think we either:

* ask freeradius to make an arm image
* rollback to the suse based arm + x86_64 build

I'm going to preference the latter only because that way we have complete control of what's going on, and we have resolve a lot of the build/mirror issues you had previously.

**Comment by ashhhleyyy** [comment]
Building the freeradius docker image from scratch on an arm64 VM (I encountered a weird error to do with make/jobserver when using buildx, and didn't have the energy to try and troubleshoot), and then building the kanidm image on top of that using the regular buildx command seems to work as a temporary stand in, and I was able to produce an image that worked correctly on the Raspberry Pi 4: https://git.ashhhleyyy.dev/ash/-/packages/container/kanidm-radius/1.1.0-alpha.12

**Comment by Firstyear** [comment]
I think if we are going to be building our own images again then I'd rather we control the process. I think the solution here is to rollback to our own radius image rather than using the freeradius one. I'll organise it today.
