### ISSUE TITLE
Support x-forwarded-for header (pending actix-web 3.0 upgrade)

### ISSUE THREAD

**Issue by Firstyear** [kanidm/kanidm#191]
We should support this header for logging/setting the client IP if required.

**Comment by pando85** [comment]
After some research I could say that more appropriate solution could be similar to [this](https://github.com/dani-garcia/bitwarden_rs/issues/600).

Set up a configurable header for origin IP address, try to pick ip from there and if that does not work return connection IP.

`X-Forwarded-For` is not a standard but it is widely used. Some other projects uses `X-Real-IP`, `Forwarded` which has its own [RFC7239](https://tools.ietf.org/html/rfc7239) and could be more.

**Comment by pando85** [comment]
After more research... I found that Nginx has the most professional solution in [ngx_http_realip_module](https://nginx.org/en/docs/http/ngx_http_realip_module.html).
But for Kanidm this could be over complicated... I propose to just make [actix_web log format](https://docs.rs/actix-web/0.5.8/actix_web/middleware/struct.Logger.html) configurable and delegate in system administrator the proper audit information.
If we need a more complex solution we could implement it in [actix-web formatter](https://github.com/actix/actix-web/blob/d5ceae20740837bddef85053c3354452b437877a/src/middleware/logger.rs#L298).
Using default configuration without trusted IPs and headers could be an audit problem :S

**Comment by pando85** [comment]
Ok, we could have an audit problem already. I continue investigating about this and by default actix-web log [this](https://github.com/actix/actix-web/blob/d5ceae20740837bddef85053c3354452b437877a/src/info.rs#L158) as remote IP.

Basically by default we are logging as remote IP:
- Forwarded
- X-Forwarded-For
- peer name of opened socket

So this is not valid for auditing anything because any client that could reach Kanidm could send any of that headers and audit log are going to lie...

**Comment by Firstyear** [comment]
Ohhh it already supports x-forwarded-for? Wow ... but you are right, any client could just set this header. It might be worth a PR to actix-web then to have this feature as a config to tthe app server to enable-disable header IP processing instead of just doing it by default ... but that also probably means it's less work for us here because they already support it, and we just need to improve that support in actix-web.  So maybe we should pivot this ticket to be about hardening actix-web's x-forwarded-for handling? What do you think?

**Comment by pando85** [comment]
Yes, I did a PR to actix-web to remove that behaviour and respond with the IP by default. We must update (to 3.0) or backport (to 2.X) and fix this. After that I will make all access log configurable and just use client IP by default.

**Comment by Firstyear** [comment]
Okay, how about we leave this open until we update to actix-web 3.0, which I think it is currently still alpha at the moment.

**Comment by Firstyear** [comment]
Relates to #450

**Comment by Firstyear** [comment]
https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt

for ldap/binary protos

**Comment by trissylegs** [comment]
Just while passing this the nginx setup I have. Mostly copy-pasted from gitlab's example config. 


```nginx
# /etc/nginx/sites-avaliable/idm.example.com

server {
    server_name idm.example.com;
    proxy_pass_request_headers on;

    location / {
        # Very important Tide won't accept HTTP 1.0 which is the default.        
        proxy_http_version 1.1;

        proxy_set_header    Host                $http_host;
        proxy_set_header    X-Real-IP           $remote_addr;
        proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;
        proxy_set_header    X-Forwarded-Proto   $scheme;
        # Needed if Websockets are supported.
        proxy_set_header    Upgrade             $http_upgrade;

        proxy_pass http://127.0.0.1:9001;
    }

    # Just default certbot setup.
    listen 443 ssl http2;
    listen [::]:443 ssl http2; # Listen on IPv6
    ssl_certificate /etc/letsencrypt/live/idm.example.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/idm.example.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf;
}
```

**Comment by Firstyear** [comment]
Thanks this is a good example! I'll be hopefully doing this soon since we've just started some work to improve headers and logging handling :)

**Comment by yaleman** [comment]
XFF is currently supported by the tide config as-is:

```shell
curl -H "X-Forwarded-For: 1.2.3.4" https://kanidm.example.com/fooooooo
```

Slightly reformatted logs:

```
[security.info]: Request received | 
src: "1.2.3.4" | 
http.host: "kanidm.example.com" | 
http.method: "GET" | 
path: "/fooooooo"
```

It's probably a little trusting - typically there should be a trust list for these kinds of things - so every random on the network can't just say "I'm bob from accounting"

**Comment by Firstyear** [comment]
Aaaaaaaaa okay, I didn't realise it was "already working" as is, so we need to look into that and has a trust list as you say.
