### ISSUE TITLE
Refresh token scope list format

### ISSUE THREAD

**Issue by tumbl3w33d** [kanidm/kanidm#1929]
### I did this

I send a `POST` to `/oauth2/token` to refresh the access token. The payload looks like this:
```python
{'grant_type': 'refresh_token', 'scope': 'admin email profile displayname preferred_username', 'refresh_token': 'someverylongtoken=='}
```

### I expected the following

A refreshed token to be returned, but I got a 400 and the server log
```
[error]: atr parse error - invalid type: string "admin email profile displayname preferred_username", expected a sequence
```

Am I using the wrong endpoint? I didn't find any other in the documentation. This format seems correct according to spec.

### Kanidm version (and git commit)

kanidmd 1.1.0-alpha.12

### Operating System / Version

official container

**Comment by Firstyear** [comment]
@tumbl3w33d Are you running on a stable branch or dev? We can backport this since it's a bug fix to stable.

**Comment by tumbl3w33d** [comment]
@Firstyear stable. I can keep developing my stuff vs. local dev deployment for now, but a backport would be great, thanks. :)

**Comment by Firstyear** [comment]
Okay, I'll do the backport now. What distro are you using? Or are you using the official containers?

**Comment by tumbl3w33d** [comment]
Thank you, I just use the container.
