### ISSUE TITLE
Add a way to specify different server configs when using the `#[kanidmd_testkit::test]` macro

### ISSUE THREAD

**Issue by Seba-T** [kanidm/kanidm#1934]
**Is your feature request related to a problem? Please describe.**

Currently the `#[kanidmd_testkit::test]` macro doesn't provide a way to set the server configuration, making it impossible to test behaviors related to the server configuration.

**Describe the solution you'd like**

I envision something like `#[kanidmd_testkit::test(role = ReadOnlyReplica, maximum_request = 23)]` and so forth,
providing all the fields we want to customize and their respective values.

A description of what you'd expect to happen.

For all the provided configurations I expect them to replace the default alternatives, in order to test configuration-specific behavior 

Are there any alternative solutions or features you've considered.

Who needs to test configurations, real man test in production

**Comment by Seba-T** [comment]
Basically I was trying to look at #1818 but I couldn't figure out how to change the server config inside the testkit so here we are

**Comment by yaleman** [comment]
That does seem like a good idea to me 😄

**Comment by Firstyear** [comment]
Yeah, I was avoiding this for a bit because proc macros, but I think I have them worked out so we can add this. We'll need it soon for upgrade tests anyway.

**Comment by Seba-T** [comment]
> We'll need it soon for upgrade tests anyway.

So should I avoid to get involved with this stuff and get it working for now?
