### ISSUE TITLE
Unable to remove passkey from service-account

### ISSUE THREAD

**Issue by tumbl3w33d** [kanidm/kanidm#1938]
### I did this
I was using a passkey to authenticate as admin. The latest release changed that you can do that (from what I read, it was not wanted in the first place). Now I updated and I am left with an admin account that has the passkey as attribute yet.

```bash
kanidm service-account get admin
[…]
passkeys: blue yubikey
[…]
```

### I expected the following

I expected an automatic migration, i. e. this attribute being removed, when updating. I wouldn't know of any other way to remove this passkey now than downgrading to previous kanidm. I could do that because I'm still playing around and can just discard all kanidm state and start over, however, others who work differently with it probably would not want to risk downgrading to not corrupt the database.

### Kanidm version (and git commit)

`kanidmd version`: kanidmd 1.1.0-beta.13
`kanidm version`: kanidm 1.1.0-beta.13

### Operating System / Version

official container

### Any other comments

Writing this just made me wonder – do you have a version written to the database that you check when kanidmd boots, to avoid incompatibility when switching back and forth?

**Comment by tumbl3w33d** [comment]
I was told in the chat that `kanidmd recover-account admin` fixes this and I can confirm it as workaround.

**Comment by tumbl3w33d** [comment]
I'd be fine with closing this. If anyone else encounters it, the workaround is documented here.

**Comment by yaleman** [comment]
Thanks for logging it either way ❤️  

The recover-account flow is probably the easiest/most consistent way to clean out the credentials on the account (and should only affect old platforms) so that works 😄

**Comment by Firstyear** [comment]
Yeah, we could also write a migration to purge it but I didn't want to incase it was the ONLY way a person could get into their account. So  Ithink recover-account is the right process here.
