### ISSUE TITLE
Error during testing orca: unable to acquire writer_ticket

### ISSUE THREAD

**Issue by yaleman** [kanidm/kanidm#1961]
### I did this

Ran `orca setup`, and it failed due to a panic:

```
thread 'tokio-runtime-worker' panicked at 'unable to acquire writer_ticket for qsw: NoPermits', server/lib/src/server/mod.rs:1121:18
```

This can be reproduced by repeating the action.

### I expected the following

No errors

### Kanidm version (and git commit)

https://github.com/yaleman/kanidm/commit/3d2cd6863c46a43a25dd583905b308871f05a957

No changes in the server code on this one...

### Operating System / Version

macos

### Any other comments

I suspect that it's just trying to do too much too quickly for the poor server in debug mode?

**Comment by Firstyear** [comment]
In test mode there is only a single db ticket available, and we have an alert to check for stalls/deadlocks in tests by panicking when the ticket isn't available. So that's very likely what you are hitting here. Is the ticket check in debug_assertion or cfg test?

**Comment by yaleman** [comment]
Yeah it's in a `cfg!` test, could we make it try a few times, maybe?

```rust
 let write_ticket = if cfg!(debug_assertions) {
            self.write_ticket
                .try_acquire()
                .expect("unable to acquire writer_ticket for qsw")
        } else {
            self.write_ticket
                .acquire()
                .await
                .expect("unable to acquire writer_ticket for qsw")
        };
```

as a side note, I wonder if this could be sped up by removing the test entirely at compile time (because cfg!() makes it an `if true`) ... then again hopefully something in the build chain should be compiling it out anyway 😄

**Comment by Firstyear** [comment]
The intent of this was to find places where we accidentally double-transaction with the in-memory sqlite during tests. So there wasn't a need to poll this because one failure == 100 failures. It's locked or it's not. 

But because this is debug_assertions it's affecting when you just run the server in debug mode. So I think this should be cfg!(test) not cfg!(debug_assertions).

**Comment by yaleman** [comment]
Can confirm this wasn't the issue I thought it was.

**Comment by Firstyear** [comment]
Oh? What was it then?

**Comment by yaleman** [comment]
Dunno, seems not to be an issue now 😄

**Comment by Firstyear** [comment]
Okay, I'll close this now then :)
