### ISSUE TITLE
Missing content-type header in token response

### ISSUE THREAD

**Issue by tumbl3w33d** [kanidm/kanidm#1966]
### I did this

Tried to connect an application to kanidm via OIDC.

### I expected the following

To be able to login to the application.

### What actually happened

The application threw an error and some digging turned out that a nullpointer exception happened which was caused by a missing content-type header in the token response from kanidm. [It wants to check](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/oidc/OpenIdConnectAuthenticator.java#L621) that to refuse working with anything that's not `application/json`.

### Kanidm version (and git commit)

`kanidmd 1.1.0-beta.13`

### Operating System / Version

official container

### Any other comments

I checked which headers are included in the kanidm response:
```
access-control-allow-origin, content-length, cache-control, pragma, content-security-policy, x-content-type-options, permissions-policy, referrer-policy, x-kanidm-version, strict-transport-security, x-kanidm-opid, date
```

From Matrix I know that @yaleman also has an issue with an OIDC connection with a different app and this could be related.

**Comment by trissylegs** [comment]
Watching this as I just hit it too:

From Proxmox PVE:

> OpenID redirect failed.
> Server returned invalid response: Unexpected response Content-Type: "text/plain", should be `application/json` (500)

PVE is just defaulting to `text/plain` as checking the endpoint it has no content-type at all.
