### ISSUE TITLE
Oauth2 displayname exposed as name in JWT

### ISSUE THREAD

**Issue by pando85** [kanidm/kanidm#1968]
Hello folks. Finally, I'm setting this awesome project as my persona IDM for home and I found this curious thing setting up Nextcloud.

**Is your feature request related to a problem? Please describe.**

While setting up [OpenID Connect user backend for Nextcloud](https://github.com/nextcloud/user_oidc) plugin I found that it can configure multiple mapping attributes. In the case of `name` and `displayname` I found that we cannot associate both of them.

I know that the perfect way to proceed in this case could be to use the `uuid` or the `spn` for the user ID but I come from an LDAP auth based and I would like to match those IDs (user names). 

I'm seeing [here](https://github.com/kanidm/kanidm/blob/054b580fe650f012063240ba6f951c99f3c13ddc/server/lib/src/idm/oauth2.rs#L1486-L1491) that we are mapping `user.displayname` to `name` in JWT. Is that intended? Is there a way of exposing `displayname` and `name` or even custom attributes?

**Describe the solution you'd like**

It is more a question about how this should be and if it is intended to be in this way. One solution could be to expose `name` and `displayname`.

**Describe alternatives you've considered**

Modify the Kanidm installation to avoid users changing the `displayname`:

```bash
cat << EOF> /tmp/modify.json
[
    { "removed": ["acp_modify_removedattr", "displayname"] },
    { "removed": ["acp_modify_presentattr", "displayname"] }
]
EOF
kanidm raw modify '{"eq": ["name", "idm_self_acp_write"]}'  /tmp/modify.json
```

And use the `displayname` exposed as ID in Nextcloud.

**Comment by pando85** [comment]
I found the answer myself, sorry for causing some noise.

I will use the `kanidm system oauth2 prefer-short-username` option in the CLI and I will map the `name`.

**Comment by Firstyear** [comment]
The issue here is that oidc "name" means "display name" per:

` End-User's full name in displayable form including all name parts, possibly including titles and suffixes, ordered according to the End-User's locale and preferences. `

Where as "sub" is what you need to use to actually act as a user static identifier. 

And finally "preferred_username" from oidc should be from the name OR spn depending on your prefer-short-username setting.

Does that help?

**Comment by Firstyear** [comment]
https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims

**Comment by pando85** [comment]
Yep, totally clear. Thanks. I cannot use `sub` because if not it will not match the old user ID used by the LDAP auth but this workaround will work for my home setup.

**Comment by Firstyear** [comment]
No problem. The issue here is openid spec uses it's own language that doesn't line up to the expectations of most other systems.
