### ISSUE TITLE
IP info/debug endpoints

### ISSUE THREAD

**Issue by yaleman** [kanidm/kanidm#1981]
* A new rest route, only enabled when `cfg(debug_assertions)`: `/v1/debug` 
* with `/ipinfo` responding with a JSON blob of the IP info we know about (xff, xff-trust, real IP etc)
* add the parsed `Forwarded` header information to the existing whoami endpoint

> William:
> I wonder if what we should have here is when cfg(debug_assertions) are present, we have an extra route that reflects the result of xff so that these tests can actually see/test what was decoded by the server. Heck it might even be good to have an ip reflector in general when the user is authorised? What do you think @yaleman ?
> 
> @yaleman:
> A set of debug route paths isn't a bad idea, something like `/v1/debug/ipinfo`
> 
> We could probably do the IP reflector thing on the `whoami` endpoint <snip>

_Originally posted by @yaleman in https://github.com/kanidm/kanidm/issues/1957#issuecomment-1676490897_

**Comment by yaleman** [comment]
It's not matching on forwarded headers.

```
curl -4k -H "Forwarded: for=192.0.2.60;proto=http;by=203.0.113.43" https://localhost:8443/v1/debug/ipinfo
["::ffff:127.0.0.1"]
```

**Comment by Firstyear** [comment]
I'll fix this today

**Comment by Firstyear** [comment]
@yaleman It is working - you're using Forwarded, not X-Forward-For. We don't support Forwarded. 

```
curl -4k -H "X-Forwarded-For: 203.0.113.195, 2001:db8:85a3:8d3:1319:8a2e:370:7348" https://localhost:8443/v1/debug/ipinfo
["203.0.113.195"]%
```

**Comment by yaleman** [comment]
We really should support the not-deprecated version 😡

**Comment by Firstyear** [comment]
I think the reason we did this was that there wasn't very much that used the new one.
