### ISSUE TITLE
Admin-configurable theming

### ISSUE THREAD

**Issue by tumbl3w33d** [kanidm/kanidm#1996]
**Is your feature request related to a problem? Please describe.**

It would be nice to be able to customize some of kanidm's UI elements like logos and messages and replace them with own elements.

**Describe the solution you'd like**

I would like a section in the admin area where I can upload (examples):
* company logo that shows on on landing pages (e.g., `/ui/login`, but also during OAuth2 roundtrip)
* the text below this logo
* the nav bar "logo" (at the moment it is only the text "kanidm", marked with css class `navbar-brand`)

**Describe alternatives you've considered**

Guess I could replace at least the logo files in the container. With patching texts it already gets quite ugly.

**Why?**

I don't mean to hide that I'm using kani and appreciate having crabs all over the place. However, it's desirable to distinguish between instances for different purposes (e.g. to show our operators clearly that they are on production or staging etc.). In addition, it makes my endusers feel warm and cozy when this central app they use for authenticating looks familiar, like the rest of the infrastructure.

I see a connection to #1596 and #1955 because I would expect to configure the overall look and feel in one place.

**Comment by Firstyear** [comment]
Yep, this is certainly something we want to prioritise sooner than later too.

**Comment by Firstyear** [comment]
@yaleman Now that we have image storage, I wonder if we could do this with the domain struct and have a landing page image or similar?

**Comment by yaleman** [comment]
Yep, that was one of the targets for that change. 😄

**Comment by TimoKramer** [comment]
Just to check if I am correct: To customize the appearance (css/html) I have to checkout the source code make my changes and compile it myself? Would it be possible to at least make the style.css to be loaded from disk (or something comparable)?

**Comment by yaleman** [comment]
To edit the HTML you'd need to be editing the rust/html code, but style.css is loaded direct from disk so you can tweak that.

**Comment by tacerus** [comment]
Hi,

is there maybe already a way to override the logo? I tried bind mounting a custom SVG file over /usr/share/kanidm/ui/pkg/img/logo-square.svg but it would still serve the original one.

**Comment by yaleman** [comment]
> Hi,
> 
> is there maybe already a way to override the logo shown on the login screen? I tried bind mounting a custom SVG file over /usr/share/kanidm/ui/pkg/img/logo-square.svg but it would still serve the original one (also with a fresh browser instance where it served with 200 instead of 304).

Mounting it into the pkg path should do it, since you're overlaying the files - was this in a container or elsewhere?


> ... don't worry, my custom logo still contains a Kani crab ;-)

🤣

**Comment by tacerus** [comment]
Thanks for confirming! This is in a regular openSUSE VM, not a container.
Is this "/usr/share/kanidm/ui/pkg/img/logo-square.svg.br" file in some way relevant?

**Comment by yaleman** [comment]
Yes, it's the brotli pre-compressed version that'll be served if it's there, so either remove it or brotli-compress your image and put it there too.

**Comment by tacerus** [comment]
Thank you! That was the missing pointer! Looks great now:

![image](https://github.com/kanidm/kanidm/assets/5121046/d8a5d255-c6f5-403f-a069-b8ad20b9e31f)

The files under /usr/share/kanidm/ are owned by the Kanidm package, hence I recommend to not modify/remove them, they would get overwritten/replaced with the next package update. I bind-mounted both the `.svg` and the `.svg.br` now. :)

**Comment by xyhhx** [comment]
it might be worthwhile changing the shipped css to make it easier to config. off the top of my head, i'm thinking:

- use css variables for all fonts and colors, and have them defined in their own `vars.css` file. that way, users can overwrite those with bindmounts without having to overwrite the entire `style.css`
- shipping an empty `overrides.css` that users can bind mount to, well, override existing styles (again to avoid having to overwrite the entire shipped stylesheet)

**Comment by Firstyear** [comment]
Sounds good to me, I think that can be part of htmx work we have ongoing. The other option is we allow the user css to be uploaded into the DB so it replicates, that way the user doesn't need to bind mount on all their instances, it just replicates for them.

**Comment by boogiewoogit** [comment]
It'd be helpful if the kanidm's search path(s) for these theming files from could be configured in `server.toml`, allowing for equally simple editing in nonstandard filesystem layouts (e.g. NixOS).

**Comment by yaleman** [comment]
I'd support database-level config for this one, for consistency, as long as we validity-checked the CSS on upload

**Comment by coopbri** [comment]
Beyond theming, I would love if completely custom UIs could be integrated (connecting to kanidm "headless"). Such as how the Ory ecosystem does (https://www.ory.sh/docs/kratos/bring-your-own-ui/custom-ui-overview)

Not sure if this warrants a dedicated issue or is even feasible for kanidm especially re security.

**Comment by yaleman** [comment]
The API is there, with full functionality available

**Comment by coopbri** [comment]
Cool, I just wasn't sure if there were security risks with that (building external web UI and connecting to API completely headless)

**Comment by yaleman** [comment]
No real difference to using the API for anything else, TBH - there's ways to do it poorly for sure, but that's the same with any frontend 😄 You might run into CORS issues depending on how you do things, but see how you go and raise issues if you want to discuss changing things.

**Comment by coopbri** [comment]
Hah! Fair enough. Thanks @yaleman, will do and happy to report any experiences that are helpful, thanks for the leads :handshake:

**Comment by boogiewoogit** [comment]
Will there be documentation on how one can now, as per the issue, upload logos and text shown in the web ui from the admin api?

**Comment by Firstyear** [comment]
Oppos sorry about that.

For now look at these commands (output trimmed for brevity/clarity)

```
# kanidm system domain --help
Configure and display domain configuration

Usage: kanidm system domain <COMMAND>

Commands:
  set-display-name                   Set the domain display name
  set-image                          The image presented as the instance logo
  remove-image                       The remove the current instance logo, reverting to the default

Options:
  -h, --help  Print help
```

And 

```
# kanidm system oauth2 --help
Configure and display oauth2/oidc client configuration

Usage: kanidm system oauth2 <COMMAND>

Commands:
  set-displayname                       Set a new displayname for a client
  set-name                              Set a new name for this client. You may need to update your integrated applications after this so that they continue to function correctly
  set-image                             The image presented on the Kanidm Apps Listing page for an OAuth2 resource server
  remove-image                          Removes the custom image previously set

Options:
  -h, --help  Print help
```

**Comment by boogiewoogit** [comment]
To customize the login screen logo, would bind-mounting an image over `/usr/share/kanidm/ui/pkg/img/logo-square.svg` and `/usr/share/kanidm/ui/pkg/img/logo-square.svg.br` still be the suggested method?

**Comment by tacerus** [comment]
`kanidm system domain set-image` worked fine for me, I don't think the mount workaround should still be used.

**Comment by boogiewoogit** [comment]
It's even in the docs, I somehow missed that. Thank you!

However, `kanidm system domain set-display-name` doesn't affect the login screen for me (still says "Kanidm" here), while it does update the name showing in the top left on the apps screen. Is this to be expected or should I file a bug?

**Comment by yaleman** [comment]
Please raise it as a new issue to ensure the configured domain name's displayed in the login flow. I'm not saying we'll remove Kanidm as it's still the *application* name.
