### ISSUE TITLE
Investigate and change from sqlite to sled

### ISSUE THREAD

**Issue by Firstyear** [kanidm/kanidm#20]
The sled db project plans to add mvcc as an option. We require this style of transactions so if they support mvcc, we should change from sqlite to sled in our idl layer.

**Comment by Firstyear** [comment]
After some discussion with the author of SLED, it may be a long time before SLED supports the transaction functions we need, so this may not be possible for some time.

**Comment by NiryaAestus** [comment]
Currently no CI for Windows either.

**Comment by Firstyear** [comment]
Good to know. I'm currently not in a rush to change, so we'll see if we need to change from sqlite to something else, or if it's possible to support two idl layers. I think it won't be too dificult to support differnt idl providers in the future.

**Comment by Firstyear** [comment]
I think it's not going to be possible as sled transaction model is too-different from what we required today.
