### ISSUE TITLE
Write windows gina module for kanidm

### ISSUE THREAD

**Issue by Firstyear** [kanidm/kanidm#200]
It could be possible to write a windows gina module for kanidm. But I'm not sure if it's worth the effort vs AD sync ....

**Comment by Firstyear** [comment]
https://learn.microsoft.com/en-us/windows/win32/secauthn/custom-security-packages

**Comment by Water261** [comment]
I'll attempt to implement this

**Comment by Water261** [comment]
Probably should leave some clarification, winlogon & GINA don't need to be changed but rather a custom security support package and authorisation package (SSP/AP) should be implemented instead.

**Comment by Water261** [comment]
Relevant PR: #1498

**Comment by yaleman** [comment]
Is this still relevant since we worked out #1498 couldn't get done?

**Comment by Firstyear** [comment]
I think it may not actually be possible. :(

**Comment by yaleman** [comment]
I'll close this until someone works out how it can be done in a supportable way then.
