### ISSUE TITLE
certificates? 

### ISSUE THREAD

**Issue by todd1794** [kanidm/kanidm#2047]
**Is your feature request related to a problem? Please describe.**

Yes if I do this:
```
/usr/local/sbin/kanidmd healthcheck --config=/etc/kanidm/server.toml
00000000-0000-0000-0000-000000000000 WARN     🚧 [warn]: This is running as uid == 0 (root) which may be a security risk.
00000000-0000-0000-0000-000000000000 WARN     🚧 [warn]: permissions on /etc/kanidm/server.toml may not be secure. Should be readonly to running uid. This could be a security risk ...
00000000-0000-0000-0000-000000000000 WARN     🚧 [warn]: WARNING: /etc/kanidm/server.toml has 'everyone' permission bits in the mode. This could be a security risk ...
00000000-0000-0000-0000-000000000000 WARN     🚧 [warn]: WARNING: /etc/kanidm/server.toml owned by the current uid, which may allow file permission changes. This could be a security risk ...
00000000-0000-0000-0000-000000000000 WARN     🚧 [warn]: WARNING: DB folder permissions on /var/lib/private/kanidm indicate it may not be RW. This could cause the server start up to fail!
00000000-0000-0000-0000-000000000000 WARN     🚧 [warn]: WARNING: DB folder /var/lib/private/kanidm has 'everyone' permission bits in the mode. This could be a security risk ...
00000000-0000-0000-0000-000000000000 ERROR    🚨 [error]: Failed to parse /etc/letsencrypt/live/idm.milford.se/cert.pem as a valid certificate!
Error: reqwest::Error { kind: Builder, source: Normal(ErrorStack([Error { code: 75497574, library: "PEM routines", function: "get_header_and_data", reason: "bad end line", file: "../crypto/pem/pem_lib.c", line: 831 }])) }`
```

I would expect this:
```
/usr/local/sbin/kanidmd server --config=/etc/kanidm/server.toml
00000000-0000-0000-0000-000000000000 WARN     🚧 [warn]: This is running as uid == 0 (root) which may be a security risk.
00000000-0000-0000-0000-000000000000 WARN     🚧 [warn]: permissions on /etc/kanidm/server.toml may not be secure. Should be readonly to running uid. This could be a security risk ...
00000000-0000-0000-0000-000000000000 WARN     🚧 [warn]: WARNING: /etc/kanidm/server.toml has 'everyone' permission bits in the mode. This could be a security risk ...
00000000-0000-0000-0000-000000000000 WARN     🚧 [warn]: WARNING: /etc/kanidm/server.toml owned by the current uid, which may allow file permission changes. This could be a security risk ...
00000000-0000-0000-0000-000000000000 WARN     🚧 [warn]: WARNING: DB folder permissions on /var/lib/private/kanidm indicate it may not be RW. This could cause the server start up to fail!
00000000-0000-0000-0000-000000000000 WARN     🚧 [warn]: WARNING: DB folder /var/lib/private/kanidm has 'everyone' permission bits in the mode. This could be a security risk ...
00000000-0000-0000-0000-000000000000 INFO     ｉ [info]: Running in server mode ...
00000000-0000-0000-0000-000000000000 WARN     🚧 [warn]: permissions on /etc/letsencrypt/live/idm.milford.se/cert.pem may not be secure. Should be readonly to running uid. This could be a security risk ...
00000000-0000-0000-0000-000000000000 WARN     🚧 [warn]: permissions on /etc/letsencrypt/live/idm.milford.se/privkey.pem may not be secure. Should be readonly to running uid. This could be a security risk ...
00000000-0000-0000-0000-000000000000 INFO     ｉ [info]: Starting kanidm with configuration:  address: [::]:443, domain: idm.milford.se, ldap address: disabled, admin bind path: /tmp/kanidmd.sock, thread count: 8, dbpath: /var/lib/private/kanidm/kanidm.db, arcsize: AUTO, max request size: 262144b, trust X-Forwarded-For: false, with TLS: true, online_backup: ena
bled, role: write replica, integration mode: false, console output format: Text log_level: info
00000000-0000-0000-0000-000000000000 INFO     ｉ [info]: DB tickets -> 8
00000000-0000-0000-0000-000000000000 INFO     ｉ [info]: Profile -> developer
00000000-0000-0000-0000-000000000000 INFO     ｉ [info]: CPU Flags -> native
6730d6a0-9192-4abd-9732-254c7974e3f9 INFO     system_initialisation [ 134ms | 62.82% / 100.00% ]
6730d6a0-9192-4abd-9732-254c7974e3f9 INFO     ┕━ commit [ 49.8ms | 37.18% ]
00000000-0000-0000-0000-000000000000 INFO     ｉ [info]:  | pbkdf2_cost: 10000 | argon2id_m: 8192 | argon2id_p: 1 | argon2id_t: 2
00000000-0000-0000-0000-000000000000 INFO     ｉ [info]: Starting query server v1 worker ...
00000000-0000-0000-0000-000000000000 INFO     ｉ [info]: Starting query server v1 worker ...
00000000-0000-0000-0000-000000000000 INFO     ｉ [info]: Provided online backup schedule is: 00 22 * * *, now being transformed to: 0 00 22 * * * *
00000000-0000-0000-0000-000000000000 INFO     ｉ [info]: Online backup schedule parsed as: 0 00 22 * * * *
00000000-0000-0000-0000-000000000000 INFO     ｉ [info]: Online backup next run on 2023-08-30 22:00:00 UTC, wait_time = 59259s
a3d37ba0-fc97-4f05-bde1-28ed4ca79a51 INFO     router [ 627µs | 100.00% ]
00000000-0000-0000-0000-000000000000 INFO     ｉ [info]: Starting the web server...
00000000-0000-0000-0000-000000000000 INFO     ｉ [info]: ready to rock! 🪨  UI available at: https://idm.milford.se:8443 | event_tag_id: 3
00000000-0000-0000-0000-000000000000 INFO     ｉ [info]: Stopped WebAcceptorActor
582ea492-38a9-46ef-825c-68c3eb6e2ba8 INFO     handle_purgetombstoneevent [ 28.8ms | 0.51% / 100.00% ]
582ea492-38a9-46ef-825c-68c3eb6e2ba8 INFO     ┝━ ｉ [info]: Tombstone purge operation success | event_tag_id: 3
582ea492-38a9-46ef-825c-68c3eb6e2ba8 INFO     ┝━ commit [ 28.6ms | 99.49% ]
582ea492-38a9-46ef-825c-68c3eb6e2ba8 INFO     ┕━ ｉ [info]: Purge tombstones result | event_tag_id: 3 | res: Ok(())
1ce8c1d4-cebc-4bdc-9988-3c70552ae859 INFO     handle_purgerecycledevent [ 33.7ms | 0.41% / 100.00% ]
1ce8c1d4-cebc-4bdc-9988-3c70552ae859 INFO     ┝━ ｉ [info]: No recycled items present - purge operation success | event_tag_id: 3
1ce8c1d4-cebc-4bdc-9988-3c70552ae859 INFO     ┝━ commit [ 33.5ms | 99.59% ]
1ce8c1d4-cebc-4bdc-9988-3c70552ae859 INFO     ┕━ ｉ [info]: Purge recycled result | event_tag_id: 3 | res: Ok(())`
```

To not work.  This is really only a problem for me because on the first run when I made the certificates with `caddy` the `kanidm server` just worked. I pointed my web browser to the URL and I got a cool UI and I was happy. (It does not take much) But soon there after it did not work. The web browser stopped working. Because the certificate was bad. So I tried making certificates with `certbot` instead of `caddy` because I noticed they should be `.pem` files instead of `.csr` files. Nope that did not work either. I then noticed that the `kanidm heathcheck` actually tells me that the certificate can not be parsed. 

**Describe the solution you'd like**

I would like to know how to build a certificate that `kanidm healthcheck` can parse and more importantly one that `kanidm server` will work with. 

**Additional context**

Awesome start! I have had a lot of fun working with this project so far. (Not sarcasm) I am looking forward to having a cool UI/LDAP/Oauth2 all in one place. Years I have been wanting this and it is written in Rust!

**Comment by Firstyear** [comment]
Thanks for the kind words about Kanidm! I'm glad you are enjoying the project.

Sadly, the error here kani is raising is correct - it means there is a problem with your certificates as they are *not* in a PEM format. This points to a problem with certbot or caddy. 

A .csr normally is a certificate *request* not an actual signed certificate that is usable.

From your config you will have two files - mine is like this:

```
tls_chain = "/etc/letsencrypt/live/idm.domain/_chain.pem"
tls_key = "/etc/letsencrypt/live/idm.domain/key.pem"
```

the file "tls_chain" you should see contents like:

```
-----BEGIN CERTIFICATE-----
MII.... <base 64 continues>
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MII.... <base 64 continues>
-----END CERTIFICATE-----
// more or less certs based on your chain.
```

For your "tls_key" it should show:

```
-----BEGIN PRIVATE KEY-----
<base 64 here that you should never show anyone ever>
-----END PRIVATE KEY-----
```

So you'll need to investigate this and resolve the cert issue - it's not actually a kani problem sorry :( :(

**Comment by todd1794** [comment]
So it is normal that the `kanidm healthcheck` fails but the `kanidm server` does not? I would like the server to fail as well if the certificate fails. As to not have a feeling of oh cool `kanidm server` is working when it is not really. 

Both my `tls_chain` and `tls_key` begin way yours do. 

I created with them with a `certbot certonly` command and got no errors during creation and they work in NGINX. I not sure what is wrong. Any ideas?

And wow thank you for the fast response!

**Comment by yaleman** [comment]
Can you check the cert file is parseable with `openssl x509 -in <filename> -noout -text`, that should do similar things to what the health check command does. Also, what version/deployment me this are you running?

**Comment by yaleman** [comment]
There's a lot going on in your report and if caddy is between the container and the user that adds a layer of complication. The health check has a few flags for how it works, and isn't perfect. You're best to check with curl or other tools and work out what specifically is broken.

**Comment by Firstyear** [comment]
Or `openssl s_client -connect hostname:443 -showcerts`

**Comment by Firstyear** [comment]
But yes. Simplify and work backwards one step at a time in your infra to work out which layer is the problem. There are a lot of moving parts here (caddy, letsencrypt etc) so lets work out which one failed.

**Comment by yaleman** [comment]
A multi-cert file from `certbot` *will* make the healthcheck fail while the server will run fine, and this is kinda... expected in how the healthcheck's written at the moment... because parsing these things is a pain.

**Comment by Firstyear** [comment]
did #2059 fix this @yaleman ?

**Comment by yaleman** [comment]
I certainly changed the error message lately but would love to hear feedback from @todd1794 as to where they got up to with troubleshooting!

**Comment by Firstyear** [comment]
Okay, we'll wait to hear from @todd1794 and if they don't respond in the next few weeks I think we re-asses on our own and close it :)

**Comment by todd1794** [comment]
I am not sure what is happening. I have changed nothing and now it is working again. 

![image](https://github.com/kanidm/kanidm/assets/8957018/f51cddb1-3799-42c0-8927-63babe79171e)

The `healthcheck` is still failing but now the `server` launches and I have a UI. I am going to try and add some users and see what I can do with the server. 

`/usr/local/sbin/kanidmd healthcheck --config=/etc/kanidm/server.toml
00000000-0000-0000-0000-000000000000 WARN     🚧 [warn]: This is running as uid == 0 (root) which may be a security risk.
00000000-0000-0000-0000-000000000000 WARN     🚧 [warn]: WARNING: DB folder permissions on /var/lib/private/kanidm indicate it may not be RW. This could cause the server start up to fail!
00000000-0000-0000-0000-000000000000 WARN     🚧 [warn]: WARNING: DB folder /var/lib/private/kanidm has 'everyone' permission bits in the mode. This could be a security risk ...
00000000-0000-0000-0000-000000000000 ERROR    🚨 [error]: Failed to parse /etc/letsencrypt/archive/idm.milford.se/fullchain1.pem as a valid certificate!
Error: reqwest::Error { kind: Builder, source: Normal(ErrorStack([Error { code: 75497574, library: "PEM routines", function: "get_header_and_data", reason: "bad end line", file: "../crypto/pem/pem_lib.c", line: 831 }])) }`

I am going to stick with `Kanidm 1.1.0-beta13` for now.

**Comment by yaleman** [comment]
`/etc/letsencrypt/archive/idm.milford.se/fullchain1.pem` seems weird - normally it should be `/etc/letsencrypt/live/<hostname>/fullchain.pem`

**Comment by Firstyear** [comment]
Yeah, you shouldn't be reaching into archive here with fullchain1 because when it renews you will have to manually reconfig. Normally you use "live" which has a symlink into the archive for current active.

**Comment by Firstyear** [comment]
@todd1794 Do you still have any issues here? Are we able to close this or do you still need assistance?

**Comment by todd1794** [comment]
I am not sure actually. I had to move off of this for a bit. I will close for now.


Thank you for building awesomeness! 

Todd

**Comment by Firstyear** [comment]
No problem @todd1794 let me know if there is anything else we can do to help!
