### ISSUE TITLE
CLI login unclear when no authenticator attached

### ISSUE THREAD

**Issue by yaakov-h** [kanidm/kanidm#2053]
### I did this
1. I set up a person with two authenticators:
    1. Apple Touch/Face ID (iCloud Keychain) PassKey
    2. A Yubikey 5C NFC
2. I unplugged the Yubikey
3. I ran `kanidm login --name <user_name>`
4. The CLI printed:
    > Your authenticator will now flash for you to interact with it.
    
    but there was no flashing to be seen

### I expected the following
Some prompt to log in with one of my two authenticators, or some sort of redirect to a web browser

### Kanidm version (and git commit)
kanidm 1.1.0-beta.13

### Operating System / Version
Darwin Kuat 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:53 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6020 arm64

**Comment by yaleman** [comment]
That'll be because TouchID's not supported on the CLI (because it needs to go through Apple's attestation/packaging).

... but I don't think we can *tell* it's not a supported device? @Firstyear will probably know more about that.

**Comment by Firstyear** [comment]
What's happening is that the event loop in authenticator-rs (we use the same ctap2 code as firefox, but we may change that soon) is waiting for a device to be connected *then* it will flash. So I think that wording can be improved.

But as @yaleman says, iphone/touchid/cable will be difficult to support on the cli if at all.

**Comment by yaakov-h** [comment]
I don't mind if it's not supported / too hard to support, but I agree that the wording can definitely be improved to... gosh I'm gonna sound to businessy here for my own liking, but to better align user expectations (ugh) with what is actually going to occur.

**Comment by Firstyear** [comment]
We need to synergise with the authenticators so that user expectations can align to generate a steady stream of incoming authentication events that allow better return on investment, lowering the total cost of ownership of the kanidm platform in your mixed function hybrid on premise home cloud datacentre.

**Comment by yaleman** [comment]
> We need to synergise with the authenticators so that user expectations can align to generate a steady stream of incoming authentication events that allow better return on investment, lowering the total cost of ownership of the kanidm platform in your mixed function hybrid on premise home cloud datacentre.

That's a paddlin'.
