### ISSUE TITLE
In-system file storage

### ISSUE THREAD

**Issue by yaleman** [kanidm/kanidm#2057]
**Is your feature request related to a problem? Please describe.**

For #1966, #2056 (and other uses) we need to be able to store images and serve them to users via the HTTPS API.

**Describe the solution you'd like**

Images stored in the database as a class type attached to the relevant entry. 

I'd say a max of 256kb? Technically there's no real limit on cell sizes in SQLite but... urgh. 

This requires:

- [x] New EntryClass (Image?)
- [ ] CRUD API endpoints updates for modifying these entries
- [x] Validation of supported file formats (PNG, JPG, WEBP, SVG?) and max filesize/image size
- [ ] CLI management for 
  - [x] oauth2 app images
  - [ ] user images

- [ ] WebUI management
  - [ ] oauth2 app images
  - [ ] user images 
  - [ ] Crop/preview functionality

Access to images can be controlled with the ACP on the entry.

If they're changing regularly (as in the case of user profile images) that could turn into an issue requiring more regular vacuums due to the blob size, but it'll just take some testing.

**Describe alternatives you've considered**

- s3-compatible object storage with [presigned URLs](https://docs.aws.amazon.com/AmazonS3/latest/userguide/using-presigned-url.html) on retrieval.
- File system storage/serving with a modified replication backend (permissions? Access controls? nooooope!)

**Additional context**

**Comment by Firstyear** [comment]
I actually think we should NOT use sqlite blobs here. We don't have any caching mechanism for these at all, so they'd need to always be served from disk.

I'd rather have these blobs stored in entries with a dedicated class type, then on things like the oauth2 applink they can reference the resource id.

This would also allow us to enforce referential integrity that you can't delete a blob if it's still in use somewhere! It also means these blob-entries would be in our in-memory cache and able to be served much quicker, and they automatically gain replicaiton. It also lets admins manage them in the same way as anything else, and we can define acess controls etc. So lots of nice benefits.

**Comment by Firstyear** [comment]
It also means on the blob-serving path we can have a special handler to either allow-all reads of blobs, or we can actually still enforce access controls. They can also be marked as cached then too.

**Comment by Firstyear** [comment]
@yaleman Is this finished now? What's outstanding?

**Comment by yaleman** [comment]
At the moment it's only hacked together to upload things via the API, and no return path for the data to users, so we need to do all the un-ticked things
