### ISSUE TITLE
Drop Ubuntu 18.04 / 20.04 / debian 10/11 testing/package building

### ISSUE THREAD

**Issue by yaleman** [kanidm/kanidm#2075]
### I did this

Tried to build with openssl 1.x, but the webauthn-authenticator-rs v0.5.0-dev  lib requires openssl 3.x now because of dependencies and the following docker images don't support openssl 3.x:

- Ubuntu 18.04 & 20.04
- Debian 10 & 11

Ref: https://github.com/kanidm/kanidm/actions/runs/6080419143/job/16494360088?pr=2071

### I expected the following

It to work

### Kanidm version details

* Output of `kanidm(d) version`: latest
* Are you running it in a container? If so, which image/tag?: n/a
* If not a container, how'd you install it: n/a
* Operating System / Version (On Unix please post the output of `uname -a`): see above

**Comment by Firstyear** [comment]
RIP ancient distro support.
