### ISSUE TITLE
Issue with kanidm client tools

### ISSUE THREAD

**Issue by starship-jr** [kanidm/kanidm#2126]
### I did this
Hello, 

Following kanidm book, I installed the kanidm latest server image with docker and set up domain name and SSL keys.
I did the recover admin account process and I can log in in the web UI through web browser.

My problems arise now with the client tools [section](https://kanidm.github.io/kanidm/stable/installing_client_tools.html), 
I installed the client tool with Cargo, it is currently **kanidm_tools 0.1.1**

I set up the minimal config file, just like in the instructions, to ~/config/kanidm filepath

```
uri = "https://idm.mydomain.com"
verify_ca = true
verify_hostnames = true
```

When I run the command kanidm login --name anonymous
I got the message 
```
error: Found argument 'login' which wasn't expected, or isn't valid in this context

USAGE:
    kanidm <SUBCOMMAND>

For more information try --help
```

So I tried different commands like 

```
 kanidm account list -d --name admin
[2023-09-18T22:38:09Z DEBUG kanidm] Attempting to use config /etc/kanidm/config
[2023-09-18T22:38:09Z DEBUG kanidm_client] Unabled to open config file [Os { code: 2, kind: NotFound, message: "No such file or directory" }], skipping ...
[2023-09-18T22:38:09Z DEBUG kanidm] Attempting to use config /home/user/.config/kanidm
Enter password:
Error during authentication phase: Err(Http(415, None))
```

I installed the kanidm tools, with Cargo, on my Debian vps (where runs kanidm) and on my local Windows (Windows 11, x86-64) desktop, but the result is the same

### I expected the following
Some help or advices please :) 

### Kanidm version details

- Output of `kanidm(d) version`:  **_kanidmd version_ > kanidmd 1.1.0-beta.13** - **_kanidm version_ >  kanidm_tools 0.1.1**
- Are you running it in a container? If so, which image/tag?: **kanidm/server:latest**
- If not a container, how'd you install it:
- Operating System / Version (On Unix please post the output of `uname -a`): **5.18.0-0.deb11.4-cloud-amd64 SMP PREEMPT_DYNAMIC Debian 5.18.16-1~bpo11+1 (2022-08-12) x86_64 GNU/Linux**

**Comment by Firstyear** [comment]
I think the problem here is cargo install kanidm-tools pulls the last 0.1.1 version which was an accidental release that I never intended to make. You need to explicitly list the version

cargo install --version 1.1.0-beta.13 kanidm-tools

Sorry about that.

**Comment by starship-jr** [comment]
No problem :) 

I have some issue with this version  during cargo install 

```
 thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "`PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=\"1\" PKG_CONFIG_ALLOW_SYSTEM_LIBS=\"1\" \"pkg-config\" \"--libs\" \"--cflags\" \"libudev\"` did not exit successfully: exit status: 1\nerror: could not find system library 'libudev' required by the 'libudev-sys' crate\n\n--- stderr\nPackage libudev was not found in the pkg-config search path.\nPerhaps you should add the directory containing `libudev.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package 'libudev' found\n"', /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libudev-sys-0.1.4/build.rs:38:41
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `kanidm_tools v1.1.0-beta.13`, intermediate artifacts can be found at `/tmp/cargo-installnQyI4K`.
```

My current rustc version : 1.72.0

I will try with some previous release.

**Comment by Firstyear** [comment]
`could not find system library 'libudev' required by the 'libudev-sys' `
says right there what the issue is :) you need to make sure you have the dependencies needed for the build to link against.

**Comment by starship-jr** [comment]
Aha, 
Simply as that :) 
It seems to work as intended now and I can run kanidm login command, etc .. 

thanks a lot !
