### ISSUE TITLE
Can't build kanidmd using the Ubuntu docker builder scripts

### ISSUE THREAD

**Issue by daenney** [kanidm/kanidm#2148]
### I did this

* Checkout the repo
* Ran the commands according to https://kanidm.github.io/kanidm/stable/packaging_debs.html

Building `debs/kanidm` succeeds, but `debs/kanidmd` fails:

```
   Compiling kanidmd_web_ui v1.1.0-beta.13 (/root/build/kanidm/server/web_ui)
    Finished release [optimized + debuginfo] target(s) in 31.00s
[INFO]: Installing wasm-bindgen...
Error: Not able to find or install a local wasm-bindgen.
Caused by: Not able to find or install a local wasm-bindgen.
make[2]: *** [debian/rules:33: override_dh_auto_build] Error 1
make[2]: Leaving directory '/root/build/kanidm'
make[1]: *** [debian/rules:22: build] Error 2
make[1]: Leaving directory '/root/build/kanidm'
make: *** [platform/debian/Makefile:15: debs/kanidmd] Error 2
```

<details><summary>full log</summary>
<span><code>
root@ef3f1c00da6d:~/kanidm# make -f platform/debian/Makefile debs/kanidmd
bash ./platform/debian/build_kanidm.sh kanidmd
Building kanidmd
Updating local packages
Hit:1 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:2 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Reading package lists... Done
Installing build dependencies
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
devscripts is already the newest version (2.22.1ubuntu1).
dh-make is already the newest version (2.202102).
fakeroot is already the newest version (1.28-1ubuntu1).
make is already the newest version (4.3-4.1build1).
pkg-config is already the newest version (0.29.2-1ubuntu3).
debmake is already the newest version (4.3.2-1.1).
libpam0g-dev is already the newest version (1.4.0-11ubuntu2.3).
libsqlite3-dev is already the newest version (3.37.2-2ubuntu0.1).
libssl-dev is already the newest version (3.0.2-0ubuntu1.10).
libudev-dev is already the newest version (249.11-0ubuntu3.10).
0 upgraded, 0 newly installed, 0 to remove and 5 not upgraded.
rust already installed!
wasm-pack already installed
Package Version: 1.1.0-beta.13-202309251753689c7c7
Updating package dir
Copying source files to /root/build
Copying the debian-specific build files
Copying debian-specific files for kanidmd
Setting permissions on debian scripts
    89233      4 -rwxr-xr-x   1 root     root          747 Sep 25 17:53 ./debian/preinst
    89234      4 -rwxr-xr-x   1 root     root          424 Sep 25 17:53 ./debian/prerm.ex
    89242      4 -rwxr-xr-x   1 root     root         1841 Sep 25 17:53 ./debian/rules
Updating changelog
Running clean
Running build
make[1]: Entering directory '/root/build/kanidm'
dh build --with systemd
   dh_testdir
   dh_update_autotools_config
   dh_auto_configure
   debian/rules override_dh_auto_build
make[2]: Entering directory '/root/build/kanidm'
KANIDM_BUILD_PROFILE=release_suse_generic dh_auto_build -- release/kanidmd
	make -j1 release/kanidmd
make[3]: Entering directory '/root/build/kanidm'
cargo build -p daemon --bin kanidmd --release
warning: some crates are on edition 2021 which defaults to `resolver = "2"`, but virtual workspaces default to `resolver = "1"`
note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
  Downloaded axum v0.6.19
  Downloaded hashlink v0.8.3
  Downloaded crossbeam-epoch v0.9.15
  Downloaded ldap3_proto v0.3.5
  Downloaded static_assertions v1.1.0
  Downloaded sha1 v0.10.5
  Downloaded byte-tools v0.3.1
  Downloaded unicode-xid v0.2.4
  Downloaded touch v0.0.1
  Downloaded opaque-debug v0.2.3
  Downloaded futures-executor v0.3.28
  Downloaded num-bigint v0.4.3
  Downloaded oid-registry v0.4.0
  Downloaded asn1-rs-derive v0.1.0
  Downloaded lru v0.7.8
  Downloaded webauthn-rs v0.4.8
  Downloaded headers-core v0.2.0
  Downloaded rustversion v1.0.14
  Downloaded tower-layer v0.3.2
  Downloaded sshkeys v0.3.2
  Downloaded argon2 v0.5.1
  Downloaded smolset v1.3.1
  Downloaded data-encoding v2.4.0
  Downloaded crossbeam-queue v0.3.8
  Downloaded memoffset v0.9.0
  Downloaded axum-macros v0.3.8
  Downloaded time v0.1.45
  Downloaded axum-core v0.3.4
  Downloaded subtle v2.5.0
  Downloaded fallible-iterator v0.2.0
  Downloaded zstd v0.12.4
  Downloaded zstd-safe v6.0.6
  Downloaded thiserror v1.0.44
  Downloaded headers v0.3.8
  Downloaded lber v0.4.2
  Downloaded base64ct v1.6.0
  Downloaded webauthn-rs-core v0.4.9
  Downloaded password-hash v0.5.0
  Downloaded futures v0.3.28
  Downloaded axum-server v0.5.1
  Downloaded axum-auth v0.4.0
  Downloaded allocator-api2 v0.2.16
  Downloaded ahash v0.8.3
  Downloaded tower-http v0.4.3
  Downloaded fs2 v0.4.3
  Downloaded dyn-clone v1.0.12
  Downloaded crossbeam-utils v0.8.16
  Downloaded num_cpus v1.16.0
  Downloaded fake-simd v0.1.2
  Downloaded filetime v0.2.21
  Downloaded asn1-rs v0.3.1
  Downloaded smartstring v1.0.1
  Downloaded generic-array v0.12.4
  Downloaded fallible-streaming-iterator v0.1.9
  Downloaded ahash v0.7.6
  Downloaded futures-macro v0.3.28
  Downloaded thiserror-impl v1.0.44
  Downloaded unicase v2.6.0
  Downloaded tracing-serde v0.1.3
  Downloaded tokio-openssl v0.6.3
  Downloaded sptr v0.3.2
  Downloaded serde_path_to_error v0.1.14
  Downloaded rusticata-macros v4.1.0
  Downloaded mime_guess v2.0.4
  Downloaded matchit v0.7.1
  Downloaded tikv-jemalloc-sys v0.5.4+5.3.0-patched
  Downloaded concread v0.4.2
  Downloaded nonempty v0.8.1
  Downloaded http-range-header v0.3.1
  Downloaded digest v0.8.1
  Downloaded sync_wrapper v0.1.2
  Downloaded fernet v0.2.1
  Downloaded scopeguard v1.2.0
  Downloaded sd-notify v0.4.1
  Downloaded tikv-jemallocator v0.5.4
  Downloaded blake2 v0.10.6
  Downloaded zeroize_derive v1.4.2
  Downloaded tokio-stream v0.1.14
  Downloaded cron v0.12.0
  Downloaded asn1-rs-impl v0.1.0
  Downloaded x509-parser v0.13.2
  Downloaded axum-csp v0.0.5
  Downloaded block-padding v0.1.5
  Downloaded iana-time-zone v0.1.57
  Downloaded sha2 v0.8.2
  Downloaded tracing-forest v0.1.6
  Downloaded rusqlite v0.28.0
  Downloaded der-parser v7.0.0
  Downloaded tower v0.4.13
  Downloaded idlset v0.2.4
  Downloaded futures-io v0.3.28
  Downloaded displaydoc v0.2.4
  Downloaded chrono v0.4.26
  Downloaded block-buffer v0.7.3
  Downloaded base64 v0.12.3
  Downloaded synstructure v0.12.6
  Downloaded zstd-sys v2.0.8+zstd.1.5.5
  Downloaded libsqlite3-sys v0.25.2
  Downloaded 98 crates (10.2 MB) in 0.69s (largest was `libsqlite3-sys` at 4.8 MB)
   Compiling once_cell v1.18.0
   Compiling syn v1.0.109
   Compiling tokio v1.29.1
   Compiling serde_json v1.0.104
   Compiling num_cpus v1.16.0
   Compiling ahash v0.8.3
   Compiling futures-channel v0.3.28
   Compiling futures-task v0.3.28
   Compiling futures-util v0.3.28
   Compiling futures-macro v0.3.28
   Compiling futures-io v0.3.28
   Compiling ahash v0.7.6
   Compiling smallvec v1.11.0
   Compiling thiserror v1.0.44
   Compiling thiserror-impl v1.0.44
   Compiling tracing-core v0.1.31
   Compiling openssl v0.10.55
   Compiling subtle v2.5.0
   Compiling rustversion v1.0.14
   Compiling allocator-api2 v0.2.16
   Compiling unicode-xid v0.2.4
   Compiling digest v0.10.7
   Compiling zstd-sys v2.0.8+zstd.1.5.5
   Compiling unicase v2.6.0
   Compiling thread_local v1.1.7
   Compiling rusticata-macros v4.1.0
   Compiling tracing v0.1.37
   Compiling hashbrown v0.12.3
   Compiling hashbrown v0.14.0
   Compiling tracing-log v0.1.3
   Compiling tracing-serde v0.1.3
   Compiling displaydoc v0.2.4
   Compiling num-bigint v0.4.3
   Compiling oid-registry v0.4.0
   Compiling tower-layer v0.3.2
   Compiling crossbeam-utils v0.8.16
   Compiling zstd-safe v6.0.6
   Compiling indexmap v1.9.3
   Compiling indexmap v2.0.0
   Compiling base64urlsafedata v0.1.3
   Compiling tracing-subscriber v0.3.17
   Compiling webauthn-rs-proto v0.4.9
   Compiling libsqlite3-sys v0.25.2
   Compiling generic-array v0.12.4
   Compiling axum-core v0.3.4
   Compiling memoffset v0.9.0
   Compiling byte-tools v0.3.1
   Compiling block-padding v0.1.5
   Compiling crossbeam-epoch v0.9.15
   Compiling toml_edit v0.19.14
   Compiling data-encoding v2.4.0
   Compiling base64ct v1.6.0
   Compiling crossbeam-queue v0.3.8
   Compiling password-hash v0.5.0
   Compiling mime_guess v2.0.4
   Compiling block-buffer v0.7.3
   Compiling digest v0.8.1
   Compiling axum v0.6.19
   Compiling sha1 v0.10.5
   Compiling blake2 v0.10.6
   Compiling scim_proto v0.2.1
   Compiling headers-core v0.2.0
   Compiling zeroize_derive v1.4.2
   Compiling smartstring v1.0.1
   Compiling scopeguard v1.2.0
   Compiling fake-simd v0.1.2
   Compiling opaque-debug v0.2.3
   Compiling tokio-openssl v0.6.3
   Compiling kanidm_lib_crypto v0.1.0 (/root/build/kanidm/libs/crypto)
   Compiling sha2 v0.8.2
   Compiling compact_jwt v0.2.9
   Compiling hashlink v0.8.3
   Compiling native-tls v0.2.11
   Compiling proc-macro-crate v1.3.1
   Compiling argon2 v0.5.1
   Compiling headers v0.3.8
   Compiling synstructure v0.12.6
   Compiling darling_core v0.14.4
   Compiling clap v4.3.19
   Compiling lru v0.7.8
   Compiling zeroize v1.6.0
   Compiling kanidmd_lib v1.1.0-beta.13 (/root/build/kanidm/server/lib)
   Compiling axum-macros v0.3.8
   Compiling lber v0.4.2
   Compiling tokio-util v0.7.8
   Compiling tokio-stream v0.1.14
   Compiling tracing-forest v0.1.6
   Compiling h2 v0.3.20
   Compiling tower v0.4.13
   Compiling tikv-jemalloc-sys v0.5.4+5.3.0-patched
   Compiling serde_path_to_error v0.1.14
   Compiling time v0.1.45
   Compiling kanidm_utils_users v1.1.0-beta.13 (/root/build/kanidm/libs/users)
   Compiling sptr v0.3.2
   Compiling fallible-streaming-iterator v0.1.9
   Compiling base64 v0.12.3
   Compiling matchit v0.7.1
   Compiling iana-time-zone v0.1.57
   Compiling fallible-iterator v0.2.0
   Compiling static_assertions v1.1.0
   Compiling sync_wrapper v0.1.2
   Compiling sshkeys v0.3.2
   Compiling chrono v0.4.26
   Compiling concread v0.4.2
   Compiling ldap3_proto v0.3.5
   Compiling futures-executor v0.3.28
   Compiling asn1-rs-impl v0.1.0
   Compiling asn1-rs-derive v0.1.0
   Compiling darling_macro v0.14.4
   Compiling num_enum_derive v0.5.11
   Compiling tokio-native-tls v0.3.1
   Compiling fernet v0.2.1
   Compiling clap_complete v4.3.2
   Compiling kanidmd_core v1.1.0-beta.13 (/root/build/kanidm/server/core)
   Compiling smolset v1.3.1
   Compiling idlset v0.2.4
   Compiling nonempty v0.8.1
   Compiling filetime v0.2.21
   Compiling asn1-rs v0.3.1
   Compiling touch v0.0.1
   Compiling http-range-header v0.3.1
   Compiling dyn-clone v1.0.12
   Compiling daemon v1.1.0-beta.13 (/root/build/kanidm/server/daemon)
   Compiling cookie_store v0.16.2
   Compiling axum-auth v0.4.0
   Compiling darling v0.14.4
   Compiling cron v0.12.0
   Compiling derive_builder_core v0.12.0
   Compiling futures v0.3.28
   Compiling kanidm_lib_file_permissions v0.1.0 (/root/build/kanidm/libs/file_permissions)
   Compiling fs2 v0.4.3
   Compiling sd-notify v0.4.1
   Compiling num_enum v0.5.11
   Compiling der-parser v7.0.0
   Compiling kanidm_proto v1.1.0-beta.13 (/root/build/kanidm/proto)
   Compiling sketching v1.1.0-beta.13 (/root/build/kanidm/libs/sketching)
   Compiling derive_builder_macro v0.12.0
   Compiling x509-parser v0.13.2
   Compiling hyper v0.14.27
   Compiling derive_builder v0.12.0
   Compiling zxcvbn v2.2.2
   Compiling webauthn-rs-core v0.4.9
   Compiling webauthn-rs v0.4.8
   Compiling hyper-tls v0.5.0
   Compiling axum-server v0.5.1
   Compiling axum-csp v0.0.5
   Compiling zstd v0.12.4
   Compiling async-compression v0.4.1
   Compiling tower-http v0.4.3
   Compiling reqwest v0.11.18
   Compiling tikv-jemallocator v0.5.4
   Compiling rusqlite v0.28.0
    Finished release [optimized + debuginfo] target(s) in 3m 15s
make[3]: Leaving directory '/root/build/kanidm'
./platform/debian/fix_wasm_opt.sh
cargo install wasm-pack --force
    Updating crates.io index
  Downloaded wasm-pack v0.12.1
  Downloaded 1 crate (423.6 KB) in 0.42s
  Installing wasm-pack v0.12.1
    Updating crates.io index
  Downloaded cc v1.0.83
  Downloaded cargo-platform v0.1.3
  Downloaded hmac v0.12.1
  Downloaded is_executable v0.1.2
  Downloaded glob v0.3.1
  Downloaded time-core v0.1.2
  Downloaded os_info v3.7.0
  Downloaded tempfile v3.8.0
  Downloaded memchr v2.6.3
  Downloaded gimli v0.28.0
  Downloaded rustls v0.21.7
  Downloaded addr2line v0.21.0
  Downloaded clap_derive v4.4.2
  Downloaded chrono v0.4.31
  Downloaded bzip2 v0.4.4
  Downloaded bitflags v2.4.0
  Downloaded same-file v1.0.6
  Downloaded dirs-next v2.0.0
  Downloaded spin v0.5.2
  Downloaded quote v1.0.33
  Downloaded rustc-demangle v0.1.23
  Downloaded deranged v0.3.8
  Downloaded sha1 v0.10.6
  Downloaded serde_spanned v0.6.3
  Downloaded bzip2-sys v0.1.11+1.0.8
  Downloaded unicode-ident v1.0.12
  Downloaded dirs-sys-next v0.1.2
  Downloaded filetime v0.2.22
  Downloaded camino v1.1.6
  Downloaded clap_lex v0.5.1
  Downloaded anstream v0.5.0
  Downloaded siphasher v0.3.11
  Downloaded serde_ignored v0.1.9
  Downloaded rustls-webpki v0.100.3
  Downloaded untrusted v0.7.1
  Downloaded unicode-width v0.1.11
  Downloaded thiserror-impl v1.0.48
  Downloaded thiserror v1.0.48
  Downloaded which v4.4.2
  Downloaded xattr v1.0.1
  Downloaded walkdir v2.4.0
  Downloaded cipher v0.4.4
  Downloaded smallvec v1.11.1
  Downloaded zstd-safe v5.0.2+zstd.1.5.2
  Downloaded home v0.5.5
  Downloaded password-hash v0.4.2
  Downloaded lock_api v0.4.10
  Downloaded zstd v0.11.2+zstd.1.5.2
  Downloaded parking_lot v0.12.1
  Downloaded errno v0.3.3
  Downloaded sct v0.7.0
  Downloaded serde_json v1.0.107
  Downloaded typenum v1.17.0
  Downloaded tar v0.4.40
  Downloaded serde_derive v1.0.188
  Downloaded serde v1.0.188
  Downloaded flate2 v1.0.27
  Downloaded zip v0.6.6
  Downloaded toml_edit v0.19.15
  Downloaded time v0.3.29
  Downloaded url v2.4.1
  Downloaded ureq v2.7.1
  Downloaded syn v2.0.37
  Downloaded winnow v0.5.15
  Downloaded rustix v0.38.14
  Downloaded webpki-roots v0.23.1
  Downloaded object v0.32.1
  Downloaded clap_builder v4.4.4
  Downloaded backtrace v0.3.69
  Downloaded rustls-webpki v0.101.6
  Downloaded base64 v0.21.4
  Downloaded aes v0.8.3
  Downloaded libc v0.2.148
  Downloaded env_logger v0.10.0
  Downloaded clap v4.4.4
  Downloaded proc-macro2 v1.0.67
  Downloaded log v0.4.20
  Downloaded anyhow v1.0.75
  Downloaded cargo_metadata v0.15.4
  Downloaded parking_lot_core v0.9.8
  Downloaded binary-install v0.2.0
  Downloaded constant_time_eq v0.1.5
  Downloaded atty v0.2.14
  Downloaded linux-raw-sys v0.4.7
  Downloaded pbkdf2 v0.11.0
  Downloaded inout v0.1.3
  Downloaded human-panic v1.2.0
  Downloaded fastrand v2.0.1
  Downloaded toml v0.7.8
  Downloaded semver v1.0.19
  Downloaded anstyle v1.0.3
  Downloaded ring v0.16.20
  Downloaded 92 crates (12.9 MB) in 0.95s (largest was `ring` at 5.1 MB)
   Compiling libc v0.2.148
   Compiling proc-macro2 v1.0.67
   Compiling unicode-ident v1.0.12
   Compiling cfg-if v1.0.0
   Compiling serde v1.0.188
   Compiling version_check v0.9.4
   Compiling typenum v1.17.0
   Compiling pkg-config v0.3.27
   Compiling autocfg v1.1.0
   Compiling spin v0.5.2
   Compiling subtle v2.5.0
   Compiling once_cell v1.18.0
   Compiling untrusted v0.7.1
   Compiling adler v1.0.2
   Compiling log v0.4.20
   Compiling tinyvec_macros v0.1.1
   Compiling crc32fast v1.3.2
   Compiling cpufeatures v0.2.9
   Compiling tinyvec v1.6.0
   Compiling miniz_oxide v0.7.1
   Compiling rustix v0.38.14
   Compiling serde_json v1.0.107
   Compiling utf8parse v0.2.1
   Compiling zstd-safe v5.0.2+zstd.1.5.2
   Compiling anstyle-parse v0.2.1
   Compiling hashbrown v0.14.0
   Compiling itoa v1.0.9
   Compiling generic-array v0.14.7
   Compiling equivalent v1.0.1
   Compiling rustls v0.21.7
   Compiling linux-raw-sys v0.4.7
   Compiling anstyle v1.0.3
   Compiling base64ct v1.6.0
   Compiling rand_core v0.6.4
   Compiling percent-encoding v2.3.0
   Compiling ryu v1.0.15
   Compiling anstyle-query v1.0.0
   Compiling unicode-bidi v0.3.13
   Compiling colorchoice v1.0.0
   Compiling bitflags v2.4.0
   Compiling password-hash v0.4.2
   Compiling anstream v0.5.0
   Compiling form_urlencoded v1.2.0
   Compiling flate2 v1.0.27
   Compiling lock_api v0.4.10
   Compiling quote v1.0.33
   Compiling indexmap v2.0.0
   Compiling unicode-normalization v0.1.22
   Compiling num-traits v0.2.16
   Compiling syn v2.0.37
   Compiling camino v1.1.6
   Compiling jobserver v0.1.26
   Compiling anyhow v1.0.75
   Compiling parking_lot_core v0.9.8
   Compiling semver v1.0.19
   Compiling time-core v0.1.2
   Compiling cc v1.0.83
   Compiling thiserror v1.0.48
   Compiling memchr v2.6.3
   Compiling winnow v0.5.15
   Compiling gimli v0.28.0
   Compiling deranged v0.3.8
   Compiling idna v0.4.0
   Compiling filetime v0.2.22
   Compiling dirs-sys-next v0.1.2
   Compiling getrandom v0.2.10
   Compiling xattr v1.0.1
   Compiling fastrand v2.0.1
   Compiling rustc-demangle v0.1.23
   Compiling heck v0.4.1
   Compiling object v0.32.1
   Compiling url v2.4.1
   Compiling crypto-common v0.1.6
   Compiling block-buffer v0.10.4
   Compiling inout v0.1.3
   Compiling lazy_static v1.4.0
   Compiling constant_time_eq v0.1.5
   Compiling digest v0.10.7
   Compiling cipher v0.4.4
   Compiling byteorder v1.4.3
   Compiling scopeguard v1.2.0
   Compiling time v0.3.29
   Compiling base64 v0.21.4
   Compiling unicode-width v0.1.11
   Compiling hmac v0.12.1
   Compiling sha2 v0.10.7
   Compiling aes v0.8.3
   Compiling sha1 v0.10.6
   Compiling strsim v0.10.0
   Compiling ring v0.16.20
   Compiling zstd-sys v2.0.8+zstd.1.5.5
   Compiling bzip2-sys v0.1.11+1.0.8
   Compiling backtrace v0.3.69
   Compiling pbkdf2 v0.11.0
   Compiling clap_lex v0.5.1
   Compiling smallvec v1.11.1
   Compiling clap_builder v4.4.4
   Compiling tempfile v3.8.0
   Compiling console v0.15.7
   Compiling addr2line v0.21.0
   Compiling tar v0.4.40
   Compiling uuid v1.4.1
   Compiling dirs-next v2.0.0
   Compiling fs2 v0.4.3
   Compiling siphasher v0.3.11
   Compiling same-file v1.0.6
   Compiling zeroize v1.6.0
   Compiling hex v0.4.3
   Compiling iana-time-zone v0.1.57
   Compiling shell-words v1.1.0
   Compiling is_executable v0.1.2
   Compiling either v1.9.0
   Compiling home v0.5.5
   Compiling chrono v0.4.31
   Compiling dialoguer v0.10.4
   Compiling which v4.4.2
   Compiling walkdir v2.4.0
   Compiling parking_lot v0.12.1
   Compiling atty v0.2.14
   Compiling env_logger v0.10.0
   Compiling glob v0.3.1
   Compiling serde_derive v1.0.188
   Compiling thiserror-impl v1.0.48
   Compiling clap_derive v4.4.2
   Compiling rustls-webpki v0.101.6
   Compiling rustls-webpki v0.100.3
   Compiling sct v0.7.0
   Compiling bzip2 v0.4.4
   Compiling clap v4.4.4
   Compiling webpki-roots v0.23.1
   Compiling toml_datetime v0.6.3
   Compiling serde_spanned v0.6.3
   Compiling os_info v3.7.0
   Compiling toml_edit v0.19.15
   Compiling cargo-platform v0.1.3
   Compiling serde_ignored v0.1.9
   Compiling ureq v2.7.1
   Compiling cargo_metadata v0.15.4
   Compiling toml v0.7.8
   Compiling human-panic v1.2.0
   Compiling zstd v0.11.2+zstd.1.5.2
   Compiling zip v0.6.6
   Compiling binary-install v0.2.0
   Compiling wasm-pack v0.12.1
    Finished release [optimized] target(s) in 50.22s
   Replacing /root/.cargo/bin/wasm-pack
    Replaced package `unknown` with `wasm-pack v0.12.1` (executable `wasm-pack`)
cd server/web_ui && ./build_wasm.sh
Cleaning up WASM files before build...
[INFO]: Checking for the Wasm target...
info: downloading component 'rust-std' for 'wasm32-unknown-unknown'
info: installing component 'rust-std' for 'wasm32-unknown-unknown'
 16.8 MiB /  16.8 MiB (100 %)  16.6 MiB/s in  1s ETA:  0s
[INFO]: Compiling to Wasm...
warning: some crates are on edition 2021 which defaults to `resolver = "2"`, but virtual workspaces default to `resolver = "1"`
note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
   Compiling proc-macro2 v1.0.66
   Compiling unicode-ident v1.0.11
   Compiling serde v1.0.180
   Compiling serde_derive v1.0.180
   Compiling once_cell v1.18.0
   Compiling itoa v1.0.9
   Compiling wasm-bindgen-shared v0.2.87
   Compiling cfg-if v1.0.0
   Compiling ryu v1.0.15
   Compiling serde_json v1.0.104
   Compiling autocfg v1.1.0
   Compiling bumpalo v3.13.0
   Compiling log v0.4.19
   Compiling wasm-bindgen v0.2.87
   Compiling futures-core v0.3.28
   Compiling futures-channel v0.3.28
   Compiling syn v1.0.109
   Compiling percent-encoding v2.3.0
   Compiling futures-sink v0.3.28
   Compiling form_urlencoded v1.2.0
   Compiling thiserror v1.0.44
   Compiling pin-project-lite v0.2.10
   Compiling version_check v0.9.4
   Compiling futures-task v0.3.28
   Compiling memchr v2.5.0
   Compiling tinyvec_macros v0.1.1
   Compiling futures-util v0.3.28
   Compiling tinyvec v1.6.0
   Compiling futures-io v0.3.28
   Compiling fnv v1.0.7
   Compiling tracing-core v0.1.31
   Compiling hashbrown v0.14.0
   Compiling rustversion v1.0.14
   Compiling slab v0.4.8
   Compiling num-traits v0.2.16
   Compiling num-integer v0.1.45
   Compiling bytes v1.4.0
   Compiling equivalent v1.0.1
   Compiling pin-utils v0.1.0
   Compiling indexmap v1.9.3
   Compiling regex-syntax v0.6.29
   Compiling anymap2 v0.13.0
   Compiling proc-macro-error-attr v1.0.4
   Compiling proc-macro-error v1.0.4
   Compiling toml_datetime v0.6.3
   Compiling regex-syntax v0.7.4
   Compiling quote v1.0.32
   Compiling http v0.2.9
   Compiling indexmap v2.0.0
   Compiling unicode-bidi v0.3.13
   Compiling winnow v0.5.2
   Compiling prettyplease v0.1.25
   Compiling lazy_static v1.4.0
   Compiling syn v2.0.28
   Compiling unicode-normalization v0.1.22
   Compiling num-rational v0.3.2
   Compiling num-iter v0.1.43
   Compiling base64 v0.21.2
   Compiling idna v0.4.0
   Compiling overload v0.1.1
   Compiling peg-runtime v0.8.1
   Compiling hashbrown v0.12.3
   Compiling tracing-log v0.1.3
   Compiling regex-automata v0.3.4
   Compiling nu-ansi-term v0.46.0
   Compiling peg-macros v0.8.1
   Compiling regex-automata v0.1.10
   Compiling toml_edit v0.19.14
   Compiling sharded-slab v0.1.4
   Compiling thread_local v1.1.7
   Compiling time-core v0.1.1
   Compiling boolinator v2.4.0
   Compiling smallvec v1.11.0
   Compiling implicit-clone v0.3.6
   Compiling matchers v0.1.0
   Compiling color_quant v1.1.0
   Compiling byteorder v1.4.3
   Compiling bytemuck v1.13.1
   Compiling bincode v1.3.3
   Compiling serde_urlencoded v0.7.1
   Compiling url v2.4.0
   Compiling regex v1.9.1
   Compiling deranged v0.3.6
   Compiling uuid v1.4.1
   Compiling image v0.23.14
   Compiling proc-macro-crate v1.3.1
   Compiling wasm-bindgen-backend v0.2.87
   Compiling base64urlsafedata v0.1.3
   Compiling time v0.3.24
   Compiling urlencoding v2.1.3
   Compiling peg v0.8.1
   Compiling base32 v0.4.0
   Compiling checked_int_cast v1.0.0
   Compiling route-recognizer v0.3.1
   Compiling qrcode v0.12.0
   Compiling wasm-bindgen-macro-support v0.2.87
   Compiling wasm-bindgen-macro v0.2.87
   Compiling thiserror-impl v1.0.44
   Compiling pin-project-internal v1.1.2
   Compiling tracing-attributes v0.1.26
   Compiling futures-macro v0.3.28
   Compiling yew-macro v0.20.0
   Compiling num_enum_derive v0.5.11
   Compiling yew-router-macro v0.17.0
   Compiling js-sys v0.3.64
   Compiling console_error_panic_hook v0.1.7
   Compiling pin-project v1.1.2
   Compiling tracing v0.1.37
   Compiling tracing-subscriber v0.3.17
   Compiling num_enum v0.5.11
   Compiling web-sys v0.3.64
   Compiling wasm-bindgen-futures v0.4.37
   Compiling serde-wasm-bindgen v0.5.0
   Compiling gloo-timers v0.2.6
   Compiling serde-wasm-bindgen v0.4.5
   Compiling scim_proto v0.2.1
   Compiling futures v0.3.28
   Compiling pinned v0.1.0
   Compiling gloo-utils v0.1.7
   Compiling gloo-events v0.1.2
   Compiling gloo-render v0.1.1
   Compiling gloo-dialogs v0.1.1
   Compiling webauthn-rs-proto v0.4.9
   Compiling gloo-console v0.2.3
   Compiling gloo-net v0.3.1
   Compiling gloo-storage v0.2.2
   Compiling gloo-history v0.1.5
   Compiling gloo-file v0.2.3
   Compiling gloo-worker v0.2.1
   Compiling gloo v0.8.1
   Compiling prokio v0.1.0
   Compiling yew v0.20.0
   Compiling kanidm_proto v1.1.0-beta.13 (/root/build/kanidm/proto)
   Compiling yew-router v0.17.0
   Compiling kanidmd_web_ui v1.1.0-beta.13 (/root/build/kanidm/server/web_ui)
    Finished release [optimized + debuginfo] target(s) in 31.00s
[INFO]: Installing wasm-bindgen...
Error: Not able to find or install a local wasm-bindgen.
Caused by: Not able to find or install a local wasm-bindgen.
make[2]: *** [debian/rules:33: override_dh_auto_build] Error 1
make[2]: Leaving directory '/root/build/kanidm'
make[1]: *** [debian/rules:22: build] Error 2
make[1]: Leaving directory '/root/build/kanidm'
make: *** [platform/debian/Makefile:15: debs/kanidmd] Error 2
</code></span></details>

I tried this out on both current main, as well as the `v1.1.0-beta.13` tag. The result is the same.

### I expected the following

Successfully build the Debian packages.

**Comment by yaleman** [comment]
What distribution version and architecture are you running this on, and have you tried installing wasm-bindgen manually?

**Comment by daenney** [comment]
I was running this on an Arch box with an amd64 CPU, using podman in my case. Since the [builder scripts](https://github.com/kanidm/kanidm/blob/master/platform/debian/ubuntu_docker_builder.sh) in `platform/debian` use Ubuntu Jammy I did a search for [wasm-bindgen](https://packages.ubuntu.com/search?suite=jammy&section=all&arch=any&keywords=wasm-bindgen&searchon=names) but there's a lot of things there and it's not clear to me which one it would need.

**Comment by yaleman** [comment]
That won't be an apt package, try running:

```shell
cargo install wasm-pack wasm-bindgen-cli
```

There's probably some misalignment between `scripts/install_ubuntu_dependencies.sh` and `platform/debian/install_deps.sh` because ... reasons.

**Comment by daenney** [comment]
Alright, that worked! One thing I noticed, `install_deps` has a specific case for when called with `kanidmd` which seems to do things related to wasm-pack. But it doesn't look like `build_kanidm` ever calls it with the package name.

https://github.com/kanidm/kanidm/blob/c7a269575c7a389a3ed338527d85b72968512737/platform/debian/install_deps.sh#L52-L65

https://github.com/kanidm/kanidm/blob/c7a269575c7a389a3ed338527d85b72968512737/platform/debian/build_kanidm.sh#L28-L36
