### ISSUE TITLE
Anonymous "person get" returns an error

### ISSUE THREAD

**Issue by daenney** [kanidm/kanidm#2151]
### I did this

I was following along with the book: https://github.com/kanidm/kanidm/blob/c7a269575c7a389a3ed338527d85b72968512737/book/src/accounts_and_groups.md?plain=1#L93-L99

That resulted in an error:

```
~ ❯❯❯ kanidm login --name anonymous
Login Success for anonymous@idm.example.com
~ ❯❯❯ kanidm person get test --name anonymous
2023-09-25T12:52:16.240657Z ERROR kanidm_cli::common: Privileges have expired for anonymous@idm.example.com - you need to re-authenticate again.
Would you like to re-authenticate? yes
2023-09-25T12:52:17.768295Z ERROR kanidm_cli::session: Error during reauthentication begin phase: Http(500, Some(InvalidState), "46d5ba68-0fc3-4335-9455-4d7b619908e8")
```

### I expected the following

To see some information about that person.

### Kanidm version details

- Output of `kanidm(d) version`: `kanidm 1.1.0-beta.13`
- Are you running it in a container? If so, which image/tag?:
- If not a container, how'd you install it: Arch AUR package
- Operating System / Version (On Unix please post the output of `uname -a`): `Linux monoceros 6.5.4-arch2-1 #1 SMP PREEMPT_DYNAMIC Thu, 21 Sep 2023 11:06:39 +0000 x86_64 GNU/Linux`

### Any other comments

Based on a comment in #2146, it seems that:
* This might be a docs error, as it shouldn't work on a person?
* The request for privileges is also a bug

**Comment by yaleman** [comment]
I poked around at this, it's not the `person get`, it's actually the reauth that's failing, because Anonymous doesn't need to reauth - I've put in a PR to fix it. Thanks for the report, apologies for taking so long to sort it!

**Comment by daenney** [comment]
No worries, things are going to take the time they're going to take. Thanks for digging into it!
