### ISSUE TITLE
service-account or person validity show returns for non-existing identity

### ISSUE THREAD

**Issue by daenney** [kanidm/kanidm#2152]
### I did this

```
~ ❯❯❯ kanidm person list --name admin
---
class: account
class: memberof
class: object
class: person
displayname: Test
memberof: idm_all_persons@localhost
memberof: idm_all_accounts@localhost
memberof: gotosocial@localhost
name: test
spn: test@localhost
uuid: bdd2f6b6-ded7-4cf5-b1e2-0da0ed1e1e09
```

```
~ ❯❯❯ kanidm person validity show test --name admin
user: test
valid after: any time
expire: never
```

```
~ ❯❯❯ kanidm person validity show doesnotexist --name admin
user: doesnotexist
valid after: any time
expire: never
```

### I expected the following

I expected that for service accounts or persons that do not exist, nothing or an error is returned.

### Kanidm version details

- Output of `kanidm(d) version`: `kanidm 1.1.0-beta.13`
- Are you running it in a container? If so, which image/tag?:
- If not a container, how'd you install it: Arch AUR
- Operating System / Version (On Unix please post the output of `uname -a`): `Linux monoceros 6.5.4-arch2-1 #1 SMP PREEMPT_DYNAMIC Thu, 21 Sep 2023 11:06:39 +0000 x86_64 GNU/Linux`

### Any other comments

This is a follow-up from #2146

**Comment by yaleman** [comment]
Found it, was a bit of a logic flaw in handling things.
