### ISSUE TITLE
Missing permission on upload_to_releases for Debian packages

### ISSUE THREAD

**Issue by daenney** [kanidm/kanidm#2157]
I took a look at the Debian flow, and I think I know [why it fails](https://github.com/kanidm/kanidm/actions/runs/6321269095/job/17165314339). The package builds go fine, but the upload to releases isn't.

I think it's because it's missing a permission here: https://github.com/kanidm/kanidm/blob/034ddd624a5792dc74d27112eb994aee78282180/.github/workflows/debian_package_kanidm.yml#L54-L73

```yaml
permissions:
      contents: write
```

It needs the `contents: write` permission in order to be allowed to upload to GitHub Releases. If I understand it correctly, that's what that action is doing. I think by default that's a permission the token should have, but I suspect you might've changed the repository default to read-only. That would also align with why there's an explicit `packages: write` in https://github.com/kanidm/kanidm/blob/034ddd624a5792dc74d27112eb994aee78282180/.github/workflows/docker_build_kanidm.yml#L39-L48

**Comment by Firstyear** [comment]
@micolous Can you have a look here? I think you understand github actions permissions better than most of us :)
