### ISSUE TITLE
*** v1.1.0-beta.13 known issues ***

### ISSUE THREAD

**Issue by yaleman** [kanidm/kanidm#2158]
- OAuth2 can be broken with some Resource Servers (if they validate the `application/json` content type in responses - fixed in #1967 
- Service accounts can have weird issues due to a typo in some ACPs - fixed in #1985 and was backported

tl;dr if these things affect you please try the current dev build.

**Comment by Firstyear** [comment]
#1985 was backported, so I think the only known issue is the json one.

**Comment by yaleman** [comment]
> #1985 was backported, so I think the only known issue is the json one.

Have updated the post to note this, whoops 😄
