### ISSUE TITLE
Consumers that do not recieve any changes in an extended period will cause replication desync. 

### ISSUE THREAD

**Issue by Firstyear** [kanidm/kanidm#2174]
If a replica is online and performing incremental replication, if that replica does *not* generate a change within the changestate trim interval, then it can lead to the node desyncing. This is because it's ruv min / max converge to a single CID, which then is older than the changestate trim interval. On the next change event, then the ruv would "jump" ahead and cause the servers ruv window to exceed the other replicas ruv window for this server.

Some possible solutions:

* Keepalive (touch) on a schedule, perhaps with the RUV trim events to cause frequent but small changes. 
* Have the RUV add blank CID's during a trim (currently if there are no changes in a write txn then no CID is recorded to the RUV).

Relates #68

**Comment by Firstyear** [comment]
@yaleman This is currently a theoretical issues and I want to write a test for it. And of course, currently it only affects me and you 😅

**Comment by yaleman** [comment]
Just you, so far! 😆 Testing good.
