### ISSUE TITLE
Trim the username input in the web UI login

### ISSUE THREAD

**Issue by tumbl3w33d** [kanidm/kanidm#2176]
**Is your feature request related to a problem? Please describe.**

When you enter your valid username and a space is prepended/appended and try to login, kanidm tells you that there's no such username and you need to start over. Now you might ask - why would you do that? I at least can say for Android auto completion that it automatically appends a space. I know that and manually remove it afterwards, but inexperienced users run into this error and I think it can be avoided without losing any security whatsoever.

**Describe the solution you'd like**

Trim/strip the input from leading and trailing spaces that people might accidentally add when entering their username.

**Describe alternatives you've considered**

Do nothing and let people realize they are entering spaces.

**Additional context**

I know that's really not dramatic, but the cost for doing it seems cheap enough and it improves the user experience for some. It also implicitly happens with the CLI because space is the argument delimiter.

**Comment by Firstyear** [comment]
Should we actually just constrain the input to the chars in the INAME regex to help the user?

**Comment by yaleman** [comment]
Throwing an error in that case is probably worse from a UX perspective.. an `.trim()` when taking the value of the input would solve it.

**Comment by Firstyear** [comment]
More than if we apply the INAME regex as they are inputting we can show that the username isn't correct. We can trim too to resolve the obvious issue, but also we can pre-check the name too.

**Comment by Firstyear** [comment]
We could also consider lowercasing it too to avoid that usererror
