### ISSUE TITLE
openid-configuration is not served as application/json

### ISSUE THREAD

**Issue by pontaoski** [kanidm/kanidm#2179]
### I did this

Use the the `openidconnect` crate to discover kanidm configuration or just get the openid-configuration in a browser/with curl/etc

### I expected the following

Content-Type header is set to application/json

### Kanidm version details

- Output of `kanidm(d) version`: `kanidmd 1.1.0-beta.13`
- Are you running it in a container? If so, which image/tag?: no
- If not a container, how'd you install it: obs fedora repo
- Operating System / Version (On Unix please post the output of `uname -a`): Linux ilo-kulupu 6.4.11-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Aug 16 17:42:12 UTC 2023 x86_64 GNU/Linux

**Comment by Firstyear** [comment]
This is already fixed in latest master
