### ISSUE TITLE
Error while login in using LDAP: failed to create search event -> InvalidAttributeName("uid") | event_tag_id: 1

### ISSUE THREAD

**Issue by bolu61** [kanidm/kanidm#2204]
### I did this

I created a user with posix account enabled. When attempting to login using ldap, I get (domain and username replaced)
```
hao44895462-34c6-470c-a941-7f0541b13700 INFO     ┕━ handle_ldaprequest [ 243µs | 90.17% ]
44895462-34c6-470c-a941-7f0541b13700 INFO        ┝━ ｉ [info]: Attempt LDAP Search for anonymous@idm.example.com | event_tag_id: 3
44895462-34c6-470c-a941-7f0541b13700 INFO        ┝━ ｉ [info]: LDAP Search Request LDAP Attrs | event_tag_id: 3 | attr: ["uidnumber", "cn", "gecos", "uid", "objectclass", "homedirectory", "gidnumber", "loginshell"]
44895462-34c6-470c-a941-7f0541b13700 INFO        ┝━ ｉ [info]: LDAP Search Request Mapped Attrs | event_tag_id: 3 | attr: Some({"class", "gecos", "gidnumber", "homedirectory", "loginshell", "name", "uid"})
44895462-34c6-470c-a941-7f0541b13700 INFO        ┝━ ｉ [info]: LDAP Search Filter | event_tag_id: 3 | filter: And([And([Equality("objectClass", "posixAccount"), Equality("uid", "bob")]), Not(Or([Equality("class", "classtype"), Equality("class", "attributetype"), Equality("class", "access_control_profile")]))])
44895462-34c6-470c-a941-7f0541b13700 ERROR       ┕━ 🚨 [error]: failed to create search event -> InvalidAttributeName("uid") | event_tag_id: 1
```

### I expected the following

User to login.

### Kanidm version details

- Output of `kanidm(d) version`: `kanidm 1.1.0-beta.13-dev`
- Are you running it in a container? If so, which image/tag?: yes `server:latest`
- If not a container, how'd you install it:
- Operating System / Version (On Unix please post the output of `uname -a`): `Linux durian 5.15.0-83-generic #92-Ubuntu SMP Mon Aug 14 09:30:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

### Any other comments

Results of `ldapsearch`:
```
# extended LDIF
#
# LDAPv3
# base <dc=sense,dc=eng,dc=uwaterloo,dc=ca> with scope subtree
# filter: (name=jzhao)
# requesting: +
#

# jzhao@sense.eng.uwaterloo.ca, sense.eng.uwaterloo.ca
dn: spn=bob@idm.example.com,dc=idm,dc=example,dc=com
class: account
class: memberof
class: object
class: person
class: posixaccount
displayname: Bob
gidnumber: 2338972948
loginshell: /bin/bash
memberof: spn=idm_all_persons@idm.example.com,dc=idm,dc=example,dc=com
memberof: spn=idm_all_accounts@idm.example.com,dc=idm,dc=example,dc=com
memberof: spn=lab@idm.example.com,dc=idm,dc=example,dc=com
name: bob
spn: bob@idm.example.com
uuid: cb8f90f1-5f14-4414-b653-83228b69e514
cn: bob
entrydn: spn=bob@idm.example.com,dc=idm,dc=example,dc=com
entryuuid: cb8f90f1-5f14-4414-b653-83228b69e514
objectclass: account
objectclass: memberof
objectclass: object
objectclass: person
objectclass: posixaccount
uidnumber: 2338972948
```

**Comment by Firstyear** [comment]
> When attempting to login using ldap

Is this with pam/nsswitch? Are you using pam_ldap, nslcd, sssd, or kanidm unix? 

For pam/nss, you should be using our native resolver as it properly integrated with Kanidm, it has a working offline cache, and it's much more reliable and secure than the other three (sssd especially likes to do odd things).

**Comment by bolu61** [comment]
> Is this with pam/nsswitch? Are you using pam_ldap, nslcd, sssd, or kanidm unix?
nslcd, but now that you mention it, I think there could be a misconfiguration since I was messing with pam...

> For pam/nss, you should be using our native resolver as it properly integrated with Kanidm, it has a working offline cache, and it's much more reliable and secure than the other three (sssd especially likes to do odd things).

I'm testing on a Ubuntu machine, and I can't build the dep package for some reason.

**Comment by Firstyear** [comment]
@yaleman do we have ubuntu packages somewhere? 

@bolu61 what version of ubuntu are you on?

**Comment by bolu61** [comment]
I'm on 22.04. I see that there are prebuilt packages in releases. I'll try them out.

**Comment by yaleman** [comment]
Yep, packages are in releases and from memory they [automatically configure PAM](https://github.com/kanidm/kanidm/blob/master/platform/debian/kanidm-unixd/kanidm.pam).

**Comment by bolu61** [comment]
`unixd` works well. But to come back to the original topic, is the missing uid a problem with the mapper? or is there a configuration that I missed?

**Comment by yaleman** [comment]
[Looks like we map](https://github.com/kanidm/kanidm/blob/6113190df2f466cafcff6461a4c6d8248bdd8cb7/server/lib/src/idm/ldap.rs#L581) `cn` but not `uid`?

**Comment by Firstyear** [comment]
There is a reason for it. The reason is that uid is specific to user accounts. Since the remaps are generic, this would remap name -> uid on groups which can trip up some bad clients.

In this case, nslcd allows changing the attributes used with `nss_map_attribute <from_attribute> <to_attribute> ` per https://linux.die.net/man/5/nss_ldap (since nslcd is a direct fork/evolution of pam_ldap). So in this case, `nss_map_attribute uid name` would resolve the issue.
