### ISSUE TITLE
Sudo is asking for password twice on Ubuntu.

### ISSUE THREAD

**Issue by bolu61** [kanidm/kanidm#2208]
### I did this

Setup `kanidm-unixd` on Ubuntu 22.04 and logged in using a local account with sudo access. Tried using sudo.

### I expected the following

Using `sudo` with local account should not ask for password twice.

### Kanidm version details

- Output of `kanidm(d) version`: 1.1.0-beta13-dev
- Are you running it in a container? If so, which image/tag?: latest
- If not a container, how'd you install it:
- Operating System / Version (On Unix please post the output of `uname -a`): `Linux pineapple 5.15.0-86-generic #96-Ubuntu SMP Wed Sep 20 08:23:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by bolu61** [comment]
Pam does specify the `try_first_pass` bug pam_kanidm does not support it.

**Comment by bolu61** [comment]
I've submitted a PR using potential solution 2. However, I think that this is just a temporary solution since some people might want `pam_kanidm` to have precedence over `pam_unix`.

**Comment by Firstyear** [comment]
pam_unix should always have precedence over pam_kanidm, so I think the PR is correct.
