### ISSUE TITLE
kanidm_tools not installable via cargo

### ISSUE THREAD

**Issue by myOmikron** [kanidm/kanidm#2212]
```bash
cargo install kanidm_tools
error: could not find `kanidm_tools` in registry `crates-io` with version `*`

cargo install kanidm_tools --version "v1.1.0-beta.13"
error: the `--version` provided, `v1.1.0-beta.13`, is not a valid semver version: cannot parse 'v1.1.0-beta.13' as a semver
```

**Comment by Firstyear** [comment]
Yes, this is because we just yanked the old-broken releases. So now everything on crates is a pre-release version which likely is causing this. We are discussing the best way to proceed, likely we'll make a release to resolve this.

**Comment by yaleman** [comment]
Yeah, I think our version numbers are making crates.io go "oh that's prerelease" and making them problematic.

**Comment by yaleman** [comment]
... and we need to drop the v off the front to make the semver thing happier 🤣

**Comment by yaleman** [comment]
Ok to get around the current eccentricities of installing the various binaries, you can run the following:

```shell
cargo install \
--git https://github.com/kanidm/kanidm kanidm_tools \
--bin kanidm \
--tag  "v1.1.0-beta.13"
```

This chooses the correct tag/package/binary.

**Comment by yaleman** [comment]
This works with the current package - `cargo install kanidm_tools --version "1.1.0-rc.15-dev"`
