### ISSUE TITLE
Enforce MFA via group

### ISSUE THREAD

**Issue by myOmikron** [kanidm/kanidm#2213]
Hey,
I looked through all the built-in groups, but didn't found a group to enforce MFA on my clients.
I'd like to experiment with kanidm in a company related context, so I need my clients to either login using passkeys or password + totp.

If there's no such feature yet, do you plan on adding something similiar?

**Comment by Firstyear** [comment]
@myOmikron This is a duplicate of #1122 which I'm about to start working on in the coming days.
