### ISSUE TITLE
GHSA-jcr6-4frq-9gjj - users crate is unmaintained and has pointer errors

### ISSUE THREAD

**Issue by yaleman** [kanidm/kanidm#2235]
### Short description of issue

Affected versions dereference a potentially unaligned pointer. The pointer is commonly unaligned in practice, resulting in undefined behavior.

In some build modes, this is observable as a panic followed by abort. In other build modes the UB may manifest in some other way, including the possibility of working correctly in some architectures.

The crate is not currently maintained, so a patched version is not available.

Recommended alternatives

[uzers](https://crates.io/crates/uzers) (an actively maintained fork of the users crate)
[sysinfo](https://crates.io/crates/sysinfo)

**Comment by Firstyear** [comment]
I thought we already fixed this?

**Comment by yaleman** [comment]
We still depend on the crate in our Cargo.toml for `unix_integration` and it's in the workspace list

**Comment by Firstyear** [comment]
Oh really? Okay, I'll have to check this. It's likely going to be better for us to just directly call the bits from libc rather than uzers.

**Comment by Firstyear** [comment]
I'm working on this now.
