### ISSUE TITLE
Configuring a service account with read-only permissions

### ISSUE THREAD

**Issue by tumbl3w33d** [kanidm/kanidm#2236]
**Is your feature request related to a problem? Please describe.**

As described [here](https://github.com/kanidm/kanidm/issues/1481#issuecomment-1764633951) I would like to configure a service account to have the minimal set of privileges to achieve the following:

* check if a person exists
* check if a person is in a group

What I manually do to check if my test account can read the necessary information is `kanidm group list`, but it might be misleading, because what I actually do in my app, which is supposed to use this service account, is asking `/v1/person` because that answers both questions described above.

I tried adding privileges, which sound like what I would need, to a fresh service account and the following set is the minimum I found necessary to make `kanidm group list` work:
```
idm_people_read_priv
idm_group_write_priv
idm_account_read_priv
idm_hp_account_read_priv
idm_group_manage_priv
idm_hp_people_read_priv
idm_all_accounts
idm_high_privilege
```
This is bad, because it includes write privileges for groups. It might also be considered problematical that personal information can be accessed (although not necessary for my use case), but I could live with that.

**Describe the solution you'd like**

I would like to just grant something like `idm_group_read_priv` (does not exist), but I understand that currently it's necessary to lookup account information for showing group memberships.

**Describe alternatives you've considered**

Accepting that the account can write groups and hope for #1481 to improve the situation.

**Additional context**

This is probably not reproducible in a common kanidm setup, because there's a default ACP called `idm_all_acp_read` that allows everybody to read a lot of things. I've changed the target group of that ACP to only grant this to my management accounts, however, you might as well just disable this ACP to achieve the same. I will not publicly describe how, because it's evil knowledge from the Kaninomicon and you should not try this at home.

**Comment by Firstyear** [comment]
Yep, I think we should capture this as part of #1481

**Comment by tumbl3w33d** [comment]
I realized (and got it confirmed by the maintainers) that there's already an easy option to assure that only read-only operations are possible: Use an API token (by default read-only, see docs) instead of the username + password of the service account.

**Comment by Firstyear** [comment]
I think this is actually resolved?

**Comment by yaleman** [comment]
Sounds like it, @tumbl3w33d please close if your requirement's sortd.
