### ISSUE TITLE
Improvement of log output 'Invalid oauth2 client_id'

### ISSUE THREAD

**Issue by tumbl3w33d** [kanidm/kanidm#2237]
**Is your feature request related to a problem? Please describe.**

I see the following kanidm log
```
891d303f-37f3-4096-ae3c-648dba76e0ef INFO     request [ 250µs | 57.53% / 100.00% ]
891d303f-37f3-4096-ae3c-648dba76e0ef INFO     ┝━ handle_oauth2_openid_discovery [ 106µs | 42.47% ]
891d303f-37f3-4096-ae3c-648dba76e0ef WARN     │  ┕━ 🚧 [warn]: Invalid oauth2 client_id (have you configured the oauth2 resource server?) | event_tag_id: 2
891d303f-37f3-4096-ae3c-648dba76e0ef ERROR    ┕━ 🚨 [error]: Unable to access discovery info | err: NoMatchingEntries
```
and would like to figure out what is causing this.

**Describe the solution you'd like**

Adding the `client_id` that was contained in the request to the log output would help a lot. If you don't do that for security reasons like avoiding injection of random stuff into logs, maybe you could just show the first x characters or something like that.

**Describe alternatives you've considered**

Fire everybody so no mistakes can be made anymore, because I don't make any.

**Additional context**
The crew is working on connecting several apps to kanidm in parallel so it's easier to track down whom to ask if I see that id. Could also be a pre-update/recovery test clone that's still roaming and wrongly configured.

**Comment by yaleman** [comment]
Which version are you running? It should show the URL for requests, something similar to this:
```
7de3e4c8-245b-4d25-97db-e16858266de3 INFO     handle_request [ 2.74ms | 0.00% / 100.00% ]
7de3e4c8-245b-4d25-97db-e16858266de3 INFO     ┕━ request [ 2.74ms | 18.86% / 100.00% ] method: GET | uri: /oauth2/openid/test_client_id/.well-known/openid-configuration | version: HTTP/1.1
```

**Comment by tumbl3w33d** [comment]
```bash
# docker exec kanidm kanidmd version
kanidmd 1.1.0-beta.13

# docker images
REPOSITORY      TAG       IMAGE ID       CREATED        SIZE
kanidm/server   latest    835e83e35995   2 weeks ago    705M
```
No such output anywhere. 🤔

**Comment by yaleman** [comment]
Yep, it's definitely part of that - and already in the next release (two weeks), so I'll close this one out.
