### ISSUE TITLE
Check incoming replica time

### ISSUE THREAD

**Issue by Firstyear** [kanidm/kanidm#2243]
When a consumer receives data from a supplier, we should check that the incoming maximum CID is not greater than 5 minutes ahead of our clock as this may indicate ongoing clock drift within the topology.

The question becomes "if we detect clock skew, how do we react?"

* Ignore it - because of how we order changes, clock skew even to large amounts doesn't matter for correctness, it just means that one nodes changes will "persist" over others.
* Disable the supplier that is ahead - this would stop replication from that supplier since it has a skew but do we actually need to do this? 

A consideration is that because we use a lamport clock if a server jumps ahead then back, then the maximum CID will remain at the maximum until the true system clock catches up. This could easily occur with a machine clock being in local vs utc and ntp needs to sync.

**Comment by yaleman** [comment]
Since we tend to default to safe I’d probably go with drop it and refuse to sync until they are happy. I’d assume we are doing our best to have time zone aware time values and are only comparing UTC (assuming a backend that can resolve this)

**Comment by Firstyear** [comment]
Yes, all values in the DB are UTC always. They can be presented as local time though. 

The problem I think with this is imagine we have a server that's ahead by ten minutes. But then 5 minutes later they are now only relatively ahead by 5 minutes, so we'd start to accept their changes again. The question becomes if they are persistently ahead by greater than 5 minutes then we'd probably keep them locked out. 

it all gets a bit subtle. I think that generally as it currently stands, event ordering will be correct for now at least even if a server is always ahead - it just means that servers changes always win.

That's why I think it's not urgent to solve, but it's something we should think about. 

If we were to fence a node, we need a mechanism to not just fence it from replication, but stop it serving all queries too to indicate it's data is suspect. Automatic fencing comes with some risks I think. So again, more thought needed.
