### ISSUE TITLE
Lack of debian derivative documentation

### ISSUE THREAD

**Issue by TheRealGramdalf** [kanidm/kanidm#2248]
I'd like to start by saying thank you: kanidm looks like an amazing IDM solution for homelabbers who want good user management and sane, secure defaults. I love the idea, the intent, and the execution of how you've implemented this.

That being said, there are a couple of problems that prevent me, a semi-advanced linux user from deploying this in the way I'd like. Part of it could be user error/lack of knowledge, missing documentation, or any combination of the two. I have some "constructive criticism" if you will, and a couple of questions:

##### Kanidm Book
- As it stands right now, the Kanidm book looks like it's at a great starting point - but it needs some cleanup and clarification before it will be user friendly and accurate.
    - For example, client tools: It wasn't entirely clear to me how the client configuration works, what options exist, and how they work. With my previous knowledge and a little bit of looking, it makes sense (more or less) to me, but changes or clarifications would be helpful.
    - To this effect, I offer to help where I can - I feel like I'm in a good place knowledge wise to write documentation that is technically  accurate (as in, an accurate representation of the code), and I would be willing to take on the role of documentation maintainer. If this offer intrigues you, let me know and I can elaborate.

##### Integration
- I realize that this is primarily due to the project still being in beta - not all features/api endpoints/etc are finalized, and as such writing and maintaining documentation isn't necessarily the best use of dev time. With that in mind, however, the most recent release states that it is a beta, and release candidates should be starting soon™. With _that_ in mind, I have some questions regarding integration with debian and derivatives:
    - My environment (as much as is relative) is as follows:
```
Dell Poweredge R810
├─ OS: Proxmox VE @ v8.x
|     └─ Portainer BE 2.9.x @ Docker
├─ CPU: Intel Xeon E7540 @ 2.00GHz
├─ RAM: (32x4GB) DDR3 @ 1333 MT/s
└─ HBA: LSI SAS 9201-16e @ FW 20.00.07.0
      └─ HP SAS expander 468405-001
          └─ ZFS pools
              └─ 2x 450GB SSD @ Mirror (docker storage)
...
```
    - As it currently stands, I am running docker directly on the proxmox host, using Portainer to manage my containers. 
        - While docker is currently running as root, I fully intend to move to a rootless install once I finish my system prototype
        - I would like to use Kanidm to manage users (persons) for my various services (jellyfin, nextcloud, etc.), as well as unix users (service accounts) on the proxmox host (for managing file permissions as needed for docker rootless and bind mounts)
    - As per the Kanidm book, I was able to:
        - Install Kanidm in docker (through portainer), which covers
            - Setting up a domain
            - Setting up CA certificates
            - Connecting to the server through my client machine (NixOS unstable laptop with the `kanidm` cli utility installed)
        - After some perusing of issues and documentation, build `kanidm-unixd` from the `1.1.0-beta.13` branch (using `./platforms/debian/build_kanidm.sh` in a docker CT launched from the `./platforms/debian/ubuntu-build-docker.sh`)
            - Install and configure `kanidm-unixd` using config files in `/etc/kanidm/` - `config` and `unixd`
...Which is where I hit my roadblock. From what I can tell, Debian integration has not been tested/documented, due to limited developer resources. By browsing the issues, I was able to find this [issue](https://github.com/kanidm/kanidm/issues/1091), which is then linked to a PR which introduces a default config. As of `1.1.0-beta.13`, it seems this has not been utilized - but it looks like it may be introduced into the debian package later on.
So my question here is:
- Is this the correct approach for my environment?
    - Should kanidm (server) be run as a container, directly on the host, or is it a matter of preference (or something else)?
    - Is running `kanidm-unixd` on the proxmox host the correct approach to managing PAM users through kanidm, or is there something else to consider?
    - Assuming using `kanidm-unixd` is the correct approach, in order to get a functional system, would it be fine to use  [this configuration](https://github.com/kalebo/kanidm/blob/master/platform/debian/pam-config-kanidm) in `usr/share/pam-configs/kanidm`, or is there anything else to consider? @kalebo if you wouldn't mind weighing in on this that would be great (you seem to have experience with debian and kanidm)

Though I've most likely missed something crucial, this is all I can remember at the moment - I'll add details or thoughts later on if I remember.
Many thanks!

**Comment by yaleman** [comment]
Yes, the supported method of running the server is [in a container](https://kanidm.github.io/kanidm/master/prepare_the_server.html#software-installation-method). You're welcome to run it however you like, but we try to avoid platform-specific issues through this path.

You need `kanidm-unixd` and `kanidm-unixd-tasks` for client-side auth using the [PAM/NSS integration](https://kanidm.github.io/kanidm/master/integrations/pam_and_nsswitch.html). The config you linked to is used by the Debian installer to modify the local config, but using the generated .deb files should do this for you when you install them. There's "nightly" [deb packages auto generated by Github Actions](https://github.com/kanidm/kanidm/releases/tag/latest) as well.

Unfortunately distro-specific configurations require someone to own them, and as noted, nobody owns them at this time, so we help where we can!

**Comment by Firstyear** [comment]
> I'd like to start by saying thank you: kanidm looks like an amazing IDM solution for homelabbers who want good user management and sane, secure defaults. I love the idea, the intent, and the execution of how you've implemented this.

Thank you! 

> As it stands right now, the Kanidm book looks like it's at a great starting point - but it needs some cleanup and clarification before it will be user friendly and accurate.
> 
>     * For example, client tools: It wasn't entirely clear to me how the client configuration works, what options exist, and how they work. With my previous knowledge and a little bit of looking, it makes sense (more or less) to me, but changes or clarifications would be helpful.

That's always welcome and we would love this feedback. Can you express more what could be improved here? 

> 
>     * To this effect, I offer to help where I can - I feel like I'm in a good place knowledge wise to write documentation that is technically  accurate (as in, an accurate representation of the code), and I would be willing to take on the role of documentation maintainer. If this offer intrigues you, let me know and I can elaborate.

Please! We are always happy to have new contributions. The book source is in the source tree here https://github.com/kanidm/kanidm/tree/master/book/src and we review the PR's here just like any other contribution. 




> Is this the correct approach for my environment?
> 
>     * Should kanidm (server) be run as a container, directly on the host, or is it a matter of preference (or something else)?

We prefer it in the container because generally most distros packaging policies prevent us committing to their official repos. We did previously attempt to have debian / ubuntu packages in OBS as a custom vendor repo, but we had some difficulties there. (for reference @yaleman is our debian person, I'm the rpm person )

> 
>     * Is running `kanidm-unixd` on the proxmox host the correct approach to managing PAM users through kanidm, or is there something else to consider?

I think there is more to this question. If you want to expose your Kanidm users onto the proxmox host so that they can SSH in and perform tasks then absolutely yes, this is the right approach. But if you want to expose users to other services then there may be other ways to approach this. 

> 
>     * Assuming using `kanidm-unixd` is the correct approach, in order to get a functional system, would it be fine to use  [this configuration](https://github.com/kalebo/kanidm/blob/master/platform/debian/pam-config-kanidm) in `usr/share/pam-configs/kanidm`, or is there anything else to consider? @kalebo if you wouldn't mind weighing in on this that would be great (you seem to have experience with debian and kanidm)

don't we have an auth-config / debian pam config in the repo already? https://github.com/kanidm/kanidm/blob/master/platform/debian/kanidm-unixd/kanidm.pam I think?

**Comment by TheRealGramdalf** [comment]
> That's always welcome and we would love this feedback. Can you express more what could be improved here?

Certainly! Perhaps it wasn't initially clear, but I by no means aim to invalidate the work you have already done. 
In any case, let me take this page as an example: https://kanidm.github.io/kanidm/stable/integrations/pam_and_nsswitch.html
_Keep in mind that this is my preference/opinion - feel free to let me know if you disagree._
- The page contains many different "fragment" configurations - configs that apply to specific environments. This leaves you with one long page, which in many cases contains less than 50% applicable information - readers are much more likely to miss something important or misinterpret information as they try to filter out the other text. Here are a couple suggestions on how you could fix that:
    - Using workflows:
        - Rather than having a single page for pam and nsswitch, have a workflow - a top directory(/page) with a short description/overview of what the workflow contains. At the end, it would be similar to a choose your own adventure - links are given at the bottom for each distrobution, taking you to it's respective page (which is a level below your top page). In the end, you might have something like this:
```
pam-nsswitch/
├── kanidm-unixd
│   ├── debian.md
│   ├── suse.md
│   └── ubuntu.md
└── pam-config
    ├── debian.md
    ├── suse.md
    └── ubuntu.md
```

        - One example of this is in the Portainer install documentation: https://docs.portainer.io/start/install
    - Using toggles
        -  Have a dropdown menu or other selection where the user can select their operating system, and the book loads the correct page transparently to the user. This reduces the amount of pages exposed to the user, but could make maintenance and access cumbersome in some cases.

That's just one of the suggestions I have - although architecturally it is a big one. In my opinion, however, the end result is worth it - documentation that is easy to read, easy (ish) to maintain, and helps prevent misconfiguration and poor user experience. 
One of the other things I noticed was that the documentation reads like a book (no pun intended) - it has a flow, and breaking that flow breaks the experience, and therefore the clarity.
Prime example: [client tools](https://kanidm.github.io/kanidm/stable/client_tools.html#kanidm-configuration)
- This page starts with an example configuration, but it doesn't:
    - Explain what the configuration option does
    - Specify that kanidm will accept as a valid value
    - Specify the default value
    - Specify in which cases the default value will be used (i.e. what happens when a value is invalid, which config location takes priority etc)
- And it then proceeds to explain how to log in and use the client tools.
In my opinion, it would make more sense to have a sort of "tech ref" - a short intro going over the logic of how kanidm parses configuration, and then a table with all the possible values for a given configuration file (e.g. `/etc/kanidm/config` or `/etc/kanidm/unixd`). The latter portion can then be split into a separate page about using the client tools, so it remains separate and legible.
If this is too much for a new user, then a more "blog-esque" guide could go through not only an example deployment, but how to understand the documentation. Give a man some fish, feed him for a day. Teach a man to fish, feed him for the rest of his life. Teach the users how to understand what may look at first like complicated and intimidating documentation, which in reality is a well structured and referenceable cheat sheet.

> Please! We are always happy to have new contributions. The book source is in the source tree here https://github.com/kanidm/kanidm/tree/master/book/src and we review the PR's here just like any other contribution.

Sounds good! Though I am quite busy with IRL stuff at the moment, I would be more than happy to help with the documentation later on. I think waiting is the best course of action in any case - as you (seem) to be nearing release candidates, it would make sense to wait until the core of the project will remain relatively unchanged to start investing time in proper documentation.

_Bonus note: It may be a good idea to either "borrow" some of authelia's integration docs/refer users to the authelia docs for integration examples of many services - authelia seems to have many of the self-hostable apps covered in a relatively standard way with Oauth/OIDC or some other cross applicable method_

> I think there is more to this question. If you want to expose your Kanidm users onto the proxmox host so that they can SSH in and perform tasks then absolutely yes, this is the right approach. But if you want to expose users to other services then there may be other ways to approach this.

Perhaps I was, again, unclear. Allow me to clarify:
- With Kanidm Server (KS), I aim to use KS as a source of trust for my self hosted network (aka wannabe datacenter):
    - This includes managing persons (user accounts) in KS, which will provide SSO for my nework
        - _I'm deluding myself that this will be a simple process, and that integration with every single app I want to host won't be a problem. This can be disregarded for the scope of this question._
    - This also includes managing service accounts. In this case, these are service accounts on KS which are part of a POSIX group.
    - To grossly oversimplify this, I need to be able to resolve a service account from KS to a UID and GID (which in the case of kanidm is the same) on the proxmox host, so that ACLs and other benefits of unix permissions can be used.
_I still feel like I wasn't able to quite convey what I meant - let me know if that makes any more or less sense than before._


> don't we have an auth-config / debian pam config in the repo already? https://github.com/kanidm/kanidm/blob/master/platform/debian/kanidm-unixd/kanidm.pam I think?
I did see that, but I wasn't sure whether you simply need to copy that into the correct location, or if there are other steps required. Clarification from kalebo/yaleman would be appreciated here.

One other note regarding this - it wasn't quite clear to me what the differences between pam and nsswitch are - it sort of seemed like pam is used on linux, but nsswitch is used in *bsd - or are **both** pam/nsswitch used in linux and *bsd? it seems like both nsswitch and pam are installed on my proxmox host, so I would assume the latter. If that is the case, do I need both the `/etc/nsswitch.conf` changes _and_ the pam changes?
From yalemans comment:
Both `systemctl status kanidm-unixd|kanidm-unixd-tasks` exist, so I should have those. They were built from the same branch as my KS installation - a version tagged docker compose install. This is probably my inexperience with PAM/IDM in general, but it's still unclear what I need to do to get things working. From what I can tell (it seems like the kanidm book changed while I was figuring this out, so I may have things mixed up a little), I need to add the nsswitch configuration - what was called the "nsswitch libraries":
```
passwd: compat kanidm
group: compat kanidm
```

> There's "nightly" [deb packages auto generated by Github Actions](https://github.com/kanidm/kanidm/releases/tag/latest) as well.

It doesn't look like there's a build for debian 12, which proxmox v8.x (latest version) is based on. Unless I'm misinterpreting and the version listed in the filename refers to what OS it was built _on_. Not sure what to do about that.
Will nightly builds always be backwards compatible, or would they need to be kept in lockstep with the KS version I have deployed?

**Comment by TheRealGramdalf** [comment]
- https://askubuntu.com/questions/486083/pam-module-nsswitch-conf could be used as a resource for the kanidm book

**Comment by yaleman** [comment]
> PAM / NSSwitch

PAM and NSSwitch are both used on Linux systems, and complement one another. you need to configure both. 

You're right, the docs for that are long and need cleaning up, I'll split them up a little.

> accounts on servers

Regarding accounts on computers, you need to read the [POSIX accounts and groups](https://kanidm.github.io/kanidm/master/posix_accounts.html) docs and posix-enable the accounts you want to use on your VMs, they'll have consistent uid/gid's across all of them. 

Integrations with applications that support OAuth/OIDC is fairly easy, and there looks to be a plugin for jellyfin, and Nextcloud's config is documented.

> .deb packages

Once I fix the automated package generation it'll be pushing Ubuntu 22.04 and Debian 12 (and only those releases, because we require OpenSSL v3). I'll poke at that tonight.

> version compatibility

We try to keep things backwards-compatible, and they'll generally work fine (the client installs on my home servers are *years* old and are OK), but we can't and won't **guarantee** it.

**Comment by TheRealGramdalf** [comment]
Many thanks!

It looks like it was a combination of user error (me just not understanding several things) a well as some of said documentation changing in the middle of me doing some research. In any case, thank you for the prompt help and information.

One last note: Though I am (still) quite busy with IRL things, I fully intend to help with the documentation where I can - I'll be in touch in the near future, perhaps when a couple release candidates are out.

**Comment by Firstyear** [comment]
No problem :) I suspect they'll be coming soon :)
