### ISSUE TITLE
[FR] Debian derivative PPA

### ISSUE THREAD

**Issue by TheRealGramdalf** [kanidm/kanidm#2263]
**Is your feature request related to a problem? Please describe.**

In order to simplify end user installation and keep packaging more unified, it may be worth creating a kanidm PPA. 

**Describe the solution you'd like**

In case you aren't aware, a PPA is a "Personal Package Archive" - a repository that `apt` can consume. This allows you to have a unified source for packages that integrate well with `apt` using systems. 
This would be quite handy for servers - since `kanidm` is intended to be the root of trust in many cases, it is critical that packages are securely, safely, and uniformly distributed. Creating an `apt` repository would allow users to receive timely updates, as it would integrate well with many existing systems (Proxmox's GUI `apt` tool, `apt` cli, etc.). It would also have the added benefit of gpg keys - packages could be signed with a gpg key to ensure that DNS poisoning or other MITM attacks would be much harder to execute.

**Describe alternatives you've considered**

Nothing specifically comes to mind - I think this is most likely the best way to distribute kanidm packages for `apt` using systems. 

**Additional context**

The PPA could be hosted on github with github pages:
https://assafmo.github.io/2019/05/02/ppa-repo-hosted-on-github.html

**Comment by yaleman** [comment]
I really *really* hate blogs that have "oh just do this and it works" 

1. which doesn't work, and 
2. also links to a "working example" that's different to what they list in the post 😡

**Comment by yaleman** [comment]
But it's here and it looks like it works - will update automagically once a day based on the current "master" packages.

https://kanidm.github.io/kanidm_ppa/

**Comment by TheRealGramdalf** [comment]
> I really _really_ hate blogs that have "oh just do this and it works"
> 
>     1. which doesn't work, and
> 
>     2. also links to a "working example" that's different to what they list in the post 😡

Yeah, I've come to hate them as well. I mainly linked it as an example of what _could_ be done, not what _should_ be done. I'll try to be a little more selective next time.

**Comment by yaleman** [comment]
Sorry 'bout the rant, I've spent *months* dealing with that kinda stuff while trying to do packaging 😄 I hope the PPA's working for you!
