### ISSUE TITLE
Release 1.1.1.1.1.1.1.1

### ISSUE THREAD

**Issue by Firstyear** [kanidm/kanidm#2275]
To do this we need to move some internals from v1 in the proto crate. This way we have a minimal supported surface area on the api. 

We also probably want #211 for this. So I guess I need to get busy!

**Comment by Firstyear** [comment]
Probably also want account policy, acp rework, some replication fixes here too.

**Comment by yaleman** [comment]
As long as we're improving over time, nothing's **_mandatory_** for the next release ^_^

I'm aiming for:

- getting OpenTelemetry tracing going
- finishing the image stuff in #2057 
- ??? whatever other random stuff I get distracted by

**Comment by Firstyear** [comment]
Replaced with milestone.
