### ISSUE TITLE
Invalid config attribute 'path' keeps kanidm from starting

### ISSUE THREAD

**Issue by tumbl3w33d** [kanidm/kanidm#2307]
### I did this

Updated from beta 13 to rc 15.

### I expected the following

The server to start.

### What actually happened

The server refused to start and told me
```
unable to parse config Error { inner: ErrorInner { kind: Custom, line: Some(0), col: 0, at: Some(0), message: "unknown field `path`, expected one of `domain`, `origin`, `db_path`, `tls_chain`, `tls_key`, `bindaddress`, `ldapbindaddress`, `role`, `log_level`, `online_backup`, `trust_x_forward_for`, `db_fs_type`, `adminbindpath`, `db_arc_size`, `i_acknowledge_that_replication_is_in_development`, `replication`", key: [] } }
```

### Kanidm version details

I pulled `1.1.0-rc.15` but kanidmd version says `kanidmd 1.1.0-rc.15-dev`

### Any other comments

The [example server.toml](https://github.com/kanidm/kanidm/blob/master/examples/server.toml#L84) still contains this attribute.

**Comment by yaleman** [comment]
The option's there as it's a sub-element of `[online_backup]` - did you comment out one and not the other?

Ref: https://kanidm.github.io/kanidm/master/rustdoc/kanidmd_core/config/struct.OnlineBackup.html#structfield.path

**Comment by tumbl3w33d** [comment]
Oh, good catch, that's indeed the case. I wonder how that worked before, since the template wasn't changed since I introduced it, but I guess some validation was added or you parse differently. Whatever, my bad, thanks for the hint!
