### ISSUE TITLE
Are kanidm/server and kanidm/tools versions in sync?

### ISSUE THREAD

**Issue by tumbl3w33d** [kanidm/kanidm#2308]
**Is your feature request related to a problem? Please describe.**

I updated from beta 13 to rc 15 and my ansible deployment crashed when pulling the tools container `kanidm/tools:1.1.0-rc.15`, because from beta 13 I was used to the versions being in sync, but it turns out there's no such version of tools. I would like to know if that was just a coincidence and if that's the case, I would like to know how to figure out which tools fit with which server version.

**Describe the solution you'd like**

Either keeping them in sync or a maintained matrix which informs about compatibility.

**Describe alternatives you've considered**

Just try to use the latest of everything and hope for it to be compatible.

**Comment by Firstyear** [comment]
This is actually likely a flaw in our release that we didn't publish everything correctly.

**Comment by Firstyear** [comment]
Fixed now
