### ISSUE TITLE
automatic reindex after migrations

### ISSUE THREAD

**Issue by tumbl3w33d** [kanidm/kanidm#2312]
**Is your feature request related to a problem? Please describe.**

It's a minor issue when upgrading from beta 13 to rc 15. I can reproduce it like:

* deploy a beta 13 and fill it with data
* run the same ansible playbook (I'm telling that to let you know there's no manual error involved) with just a changed container image version (rc 15)
* you see the migrations taking place in the container log, but then it tells you that you need to reindex which is a manual intervention

The Logs (first the end of the beta 13 container log, then the beginning of the new rc 15 container's log:
```
00000000-0000-0000-0000-000000000000 INFO     ｉ [info]: Signal received, shutting down
00000000-0000-0000-0000-000000000000 INFO     ｉ [info]: Stopped DelayedActionActor
00000000-0000-0000-0000-000000000000 INFO     ｉ [info]: Stopped WebAcceptorActor
00000000-0000-0000-0000-000000000000 INFO     ｉ [info]: Stopped AdminActor
00000000-0000-0000-0000-000000000000 INFO     ｉ [info]: Stopped IntervalActor
00000000-0000-0000-0000-000000000000 INFO     ｉ [info]: Stopped AuditdActor
00000000-0000-0000-0000-000000000000 INFO     ｉ [info]: Stopped LdapAcceptorActor
00000000-0000-0000-0000-000000000000 INFO     ｉ [info]: Stopped 🛑 
root@myhost /opt/kanidm # docker logs -f kanidm
00000000-0000-0000-0000-000000000000 INFO     ｉ [info]: Running in server mode ...
00000000-0000-0000-0000-000000000000 INFO     ｉ [info]: Starting kanidm with configuration: address: 0.0.0.0:8443, domain: idm.playground.my.domain, ldap address: 0.0.0.0:3636, origin: https://idm.playground.my.domain admin bind path: /data/kanidmd.sock, thread count: 2, dbpath: /data/kanidm.db, arcsize: AUTO, max request size: 262144b, trust X-Forwarded-For: true, with TLS: true, online_backup: disabled, integration mode: false, console output format: Text log_level: inforole: write replica, replication: disabled, 
00000000-0000-0000-0000-000000000000 INFO     ｉ [info]: dbv_id2entry migrated (quarantine) | entry: 7
00000000-0000-0000-0000-000000000000 INFO     ｉ [info]: dbv_id2entry migrated (keyhandles) | entry: 8
00000000-0000-0000-0000-000000000000 INFO     ｉ [info]: dbv_id2entry migrated (dbentryv2 -> dbentryv3) | entry: 9
00000000-0000-0000-0000-000000000000 INFO     ｉ [info]: dbv_id2entry migrated (db_ruv) | entry: 10
be812c74-9f45-4b70-9bae-c94bf0ea99bf INFO     system_initialisation [ 354ms | 94.03% / 100.00% ]
be812c74-9f45-4b70-9bae-c94bf0ea99bf INFO     ┝━ ｉ [info]: allowed create of 1 entries ✅ | event_tag_id: 11
be812c74-9f45-4b70-9bae-c94bf0ea99bf INFO     ┝━ ｉ [info]: allowed create of 1 entries ✅ | event_tag_id: 11
be812c74-9f45-4b70-9bae-c94bf0ea99bf INFO     ┝━ ｉ [info]: allowed create of 1 entries ✅ | event_tag_id: 11
be812c74-9f45-4b70-9bae-c94bf0ea99bf INFO     ┝━ ｉ [info]: allowed create of 1 entries ✅ | event_tag_id: 11
be812c74-9f45-4b70-9bae-c94bf0ea99bf INFO     ┝━ ｉ [info]: allowed create of 1 entries ✅ | event_tag_id: 11
be812c74-9f45-4b70-9bae-c94bf0ea99bf INFO     ┝━ ｉ [info]: allowed create of 1 entries ✅ | event_tag_id: 11
be812c74-9f45-4b70-9bae-c94bf0ea99bf INFO     ┝━ ｉ [info]: allowed create of 1 entries ✅ | event_tag_id: 11
be812c74-9f45-4b70-9bae-c94bf0ea99bf WARN     ┝━ 🚧 [warn]: starting 13 to 14 migration. | event_tag_id: 2
be812c74-9f45-4b70-9bae-c94bf0ea99bf WARN     ┝━ 🚧 [warn]: starting 14 to 15 migration. | event_tag_id: 2
be812c74-9f45-4b70-9bae-c94bf0ea99bf WARN     ┝━ 🚧 [warn]: WARNING: index "id_verification_eckey" Presence was not found. YOU MUST REINDEX YOUR DATABASE
```

**Describe the solution you'd like**

An automatic reindex run after migrations.

**Describe alternatives you've considered**

Manually executing `kanidmd database reindex`.

**Additional context**

I know @yaleman 's view on it is that I had an unclean shutdown, but I don't do anything special other than running ansible's `docker_container` twice in a row with different image version and what it does is shutting down the one container and launching the other, plus, the container shutdown log looks fine to me.

I have no problem with it, but I thought I should bring it to your attention since you're interested in smooth upgrade flows, especially if people run this in k8s, possibly replicated and you want to avoid manual intervention there. If you think it's not an issue for anybody else, feel free to close it right away.

**Comment by Firstyear** [comment]
Normally we actually bump an indexing constant in releases here, but we missed it this time.

In this case I think the key doesn't need indexing anyway, so you can safely ignore this. I'll remove the index today.

**Comment by Firstyear** [comment]
Update - we do need that index, but only for a migration check, so you can safely ignore that it is currently missing. It won't affect performance or operation of your instance.
