### ISSUE TITLE
Custom claims for OIDC tokens

### ISSUE THREAD

**Issue by liamdawson** [kanidm/kanidm#2319]
**Is your feature request related to a problem? Please describe.**

I can't use Kanidm with [Minio](https://min.io/) via OIDC because I can't find a way to return a `policy` claim. Minio states the following in [its OIDC prerequisites](https://min.io/docs/minio/linux/operations/external-iam/configure-openid-external-identity-management.html#openid-connect-oidc-compatible-identity-provider):

> Ensure each user identity intended for use with MinIO has the appropriate claim configured such that MinIO can associate a policy to the authenticated user. An OpenID user with no assigned policy has no permission to access any action or resource on the MinIO cluster.

**Describe the solution you'd like**

I'd like to configure a `policy` claim on user tokens. In my case, I'd be happy to configure this token on a per-user basis, as I have a small number of users.

**Describe alternatives you've considered**

I may choose to integrate Minio using its LDAP support, but I'd definitely prefer to use OIDC.

**Additional context**

I'm guessing this might involve a "custom claim map" as mentioned at https://github.com/kanidm/kanidm/issues/612#issuecomment-1596424088

**Comment by Firstyear** [comment]
So my general thinking with these custom claims is they are going to need to be a mapping from Kanidm groups to claim name + value. That way it enables the kind of workflow you have here where effectively you want kanidm groups to provide a set of policy claims to minio. 

Does that seem right to you?

**Comment by liamdawson** [comment]
That would cover any needs I can anticipate for now, yeah.

**Comment by Firstyear** [comment]
Okay, I'm hoping to get to this sooner than later, but time my attention is getting pulled in a lot of directions right now. But this is important and I do want it to happen.

**Comment by Firstyear** [comment]
I've started work on this.
