### ISSUE TITLE
FR: kanidm system oauth2 set-origin

### ISSUE THREAD

**Issue by yaleman** [kanidm/kanidm#2353]
**Is your feature request related to a problem? Please describe.**

Be able to set the Origin for an OAuth2 RS

**Describe the solution you'd like**

`kanidm system oauth2 set-origin <client_id> <origin_url>`

**Describe alternatives you've considered**

yeah nah

**Additional context**

Suggested by @mweinelt

**Comment by Water261** [comment]
Going to tackle this issue
