### ISSUE TITLE
kanidm-unixd-clients fail to install on rocky linux 9 and centos stream 9  because can't detect installed tpm2-tss and tpm2-tools  

### ISSUE THREAD

**Issue by lanejlanej** [kanidm/kanidm#2365]
### I did this

dnf install kanidm-unixd-clients

### I expected the following

The kanidm_unixd etc. package to install.

But this error was triggered instead
Error:
 Problem: conflicting requests
  - nothing provides system-user-tss needed by kanidm-unixd-clients-1.1.0~rc15~git2.74f5c0f-40.3.x86_64 from network_idm
  - nothing provides tpm2.0-tools needed by kanidm-unixd-clients-1.1.0~rc15~git2.74f5c0f-40.3.x86_64 from network_idm
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)

But, these two packages are installed by default:
tpm2-tss-3.2.2-2.el9.x86_64
tss2-1.6.0-7.el9.x86_64

**Comment by n1ete** [comment]
I had a similiar issue with debian ppa packages on bookworm. The systemd files expected a tss system group. So i just added the group to fix it.

**Comment by Firstyear** [comment]
@lanejlanej 

The spec file clearly states:

```
%package unixd-clients
Summary:        Client nsswitch/pam/ssh integration for consuming kanidm
License:        MPL-2.0
Requires:       %{name}-clients
%if 0%{?rhel} > 7 || 0%{?fedora}
Requires:       tpm2-tss
Requires:       tpm2-tools
%else
Requires:       system-user-tss
Requires:       tpm2.0-tools
%endif
```

This means, to have this situation you are attempting to install the *SUSE* versions of the package on centos/rocky. This will never work.

You must get the centos specific packages from: https://mirrorcache-au.opensuse.org/repositories/network:/idm/CentOS_9_Stream/

**Comment by Firstyear** [comment]
I wonder if this is some kind of OBS bug.

I'll force everything to rebuild and republish now.
