### ISSUE TITLE
Online Backup: Cleanup fails due to wrong RegExp

### ISSUE THREAD

**Issue by cuberoot74088** [kanidm/kanidm#2383]
I am using the Online Backup function and auto cleanup to limit the total amount of files created.
However, the backups are created but not properly cleaned up. This seems to be related to non-match RegExp to detect backup files.

I propose to change the date format as part of the backup-filename and the corresponding RegExp. Details below.

### Filenames and current RegExp

My current backup files are called like this:

> backup-2023-11-15T22:00:00.093868337Z.json
> backup-2023-11-16T22:00:00.102527385Z.json
> backup-2023-11-17T22:00:00.98738Z.json
> backup-2023-11-18T22:00:00.024753283Z.json
> backup-2023-11-19T22:00:00.034786671Z.json

the current RegExp matches to 

`r"^backup-\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z\.json$"`

https://github.com/kanidm/kanidm/blob/77b01e3a315abefcf7ba10c9a74c85221af9e45f/server/core/src/actors/v1_read.rs#L247C29-L247C83

and therefor misses the sub-second digits in the filename. Moreover, we see varying number of digits.

### Time Formatting and new RegExp

As we initially use `now_local()` 
https://github.com/kanidm/kanidm/blob/77b01e3a315abefcf7ba10c9a74c85221af9e45f/server/core/src/actors/v1_read.rs#L211C52-L211C52

I was playing around with the time formatting a bit:

> time now_local ⇒  2023-12-19 20:14:51.483367244 +01:00:00
> time format    ⇒  2023-12-19T20:14:51.483367244+01:00
> time now_utc ⇒  2023-12-19 19:14:51.483329188 +00:00:00
> time format  ⇒  2023-12-19T19:14:51.483329188Z

Thus, depending on the local setting, we might even see offsets in the formatted time string. Thus an even more complicated RegExp.

## Proposal 

Using `now_utc` (in line 211) as timestamp for the backup-filename and format it according to Rfc3999, we can have a new RegExp like this:

```
r"^backup-\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d{1,9)?Z\.json$"
                                             ^^^^^^^^^^^
```

Would you agree to this?

**Comment by yaleman** [comment]
This sounds sensible to me

**Comment by cuberoot74088** [comment]
Thinking of it again, we could also truncate it to

> 2023-12-19T20:14:51

Skipping the subseconds... 

Any opinions/preferences on this?

**Comment by yaleman** [comment]
It's all much of a muchness - I'd rather we just use the RFC3339 formatting and let it be.

James
