### ISSUE TITLE
kanidm-unixd PPA package fails to start on debian12, missing tss group?

### ISSUE THREAD

**Issue by jinnatar** [kanidm/kanidm#2399]
### I did this
On Debian 12:
```
sudo mkdir -p /etc/apt/trusted.gpg.d/
curl -s --compressed "https://kanidm.github.io/kanidm_ppa/KEY.gpg" | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/kanidm_ppa.gpg >/dev/null
sudo curl -s --compressed -o /etc/apt/sources.list.d/kanidm_ppa.list "https://kanidm.github.io/kanidm_ppa/kanidm_ppa.list"
sudo apt update && sudo apt install kanidm-unixd
```
- ... and set up the `/etc/kanidm/config` file.

- `kanidm self whoami --name anonymous` produces valid output.

### I expected the following
Running `sudo systemctl start kanidm-unixd` to either start the daemon, or provide an error.

#### Instead I get
The daemon fails to start and does not output anything as per `journalctl`:
> Dec 27 17:58:40 $hostname systemd[1]: kanidm-unixd.service: Failed with result 'exit-code'.

### Kanidm version details

- Output of `kanidm(d) version`: client `kanidm 1.1.0-rc.15-dev`, server `kanidm 1.1.0-rc.15`
- Are you running it in a container? If so, which image/tag?: Server yes, but N/A for this bug afaik.
- If not a container, how'd you install it: kanidm-ppa.
- Operating System / Version (On Unix please post the output of `uname -a`): `Linux $hostname 6.1.0-15-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.66-1 (2023-12-09) x86_64 GNU/Linux`

### Any other comments
There's many problems here that result in a sad user story, and I'm mostly logging this bug so I can continue exploring and dumping those things here, and in case all of this is just the usual lack of Debian minded folk to work on it, I'm happy to do my best to improve, since I clearly have fallen in love with kanidm. <3

#### Problems I can identify already
1. `platform/debian/kanidm-unixd/postinst` only sets up the pam module, but does not create any of the things necessary to run the daemon. There is no preinst file if that would be more appropriate:
   - A `kanidm` user since it refuses to run as root.
   - Creating `/var/{cache,lib,run}/kanidm-unixd` and setting appropriate permissions.
   - I didn't get further than this in my manual run testing, since for some reason even though I create the expected `/var/run/kanidm-unixd` directory, the daemon silently deletes it and then complains:
   > Failed to bind UNIX socket /var/run/kanidm-unixd/task_sock
2. Startup warnings and errors do not end up in journald. Even with increased verbosity.
   - I can get the errors manually by running it as `sudo -u kanidm /sbin/kanidm_unixd`
   - Adding to the systemd service spec `Environment="RUST_LOG=kanidm=debug"` does not improve things sadly, just more failing with an exit-code.
   - No idea yet how to troubleshoot this, never seen the output just get lost like this.

@yaleman I hear you're the resident Debian user, does any of this ring a bell? From other issues I see people running the daemon on Debian, and it feels a bit weird there isn't any bug I can find about these issues. Is it perhaps just the current crop of the PPA packages that are bad? Although I can't find any postinst / rules / preinst attempts at this.

As mentioned, I'm happy to work on making the package functional, just wanted to touch base first to make sure I'm not missing something obvious.

**Comment by jinnatar** [comment]
Random notes I've found how these should be done "right" for problem 1:
- Creating users should be done in `postinst`, something along `adduser --quiet --system --no-create-home --shell /usr/sbin/nologin kanidm`
- Running a service as a user should be as easy as specifying `User=kanidm`
- The magically dissapearing /var/run dir is probably WAI, and should be managed via an entry in `/usr/lib/tmpfiles.d/kanidm-unixd.conf` consisting of `d /var/run/kanidm 0770 kanidm kanidm -`, or more secure perms if that'll still work (thinking back to the kanidmd hardening guide)
- Creating the other missing dirs is probably as simple as doing a postinst of `mkdir /var/{cache,lib}/kanidm-unixd` ... buuuut, that then requires handling uninstall correctly as well, which needs more investigation.

**Comment by jinnatar** [comment]
And finally I think I find the reason why this is so odd. The systemd service uses `[DynamicUser]` which is new to me! And systemd should be autocreating the cache, runtime and state directories. So that's that mystery solved as well. Modern stuff I didn't now about.

Sadly this makes troubleshooting super hard since you can't just launch the daemon past systemd when systemd is doing something stupid, such as not starting successfully and not logging anything. So I'll pivot back to investigating that part.

**Comment by jinnatar** [comment]
Ok, the error comes from `dm_unixd`, hence why it's not attributed to `kanidm-unixd.service` in journald. More good material for the troubleshooting section!

> Dec 27 19:27:58 $hostname (dm_unixd)[3258325]: kanidm-unixd.service: Failed to determine supplementary groups: No such process                      
Dec 27 19:27:58 $hostname (dm_unixd)[3258325]: kanidm-unixd.service: Failed at step GROUP spawning /usr/sbin/kanidm_unixd: No such process
Dec 27 19:27:58 $hostname sudo[3258280]: pam_unix(sudo:session): session closed for user root                                                       
Dec 27 19:27:58 $hostname systemd[1]: kanidm-unixd.service: Failed with result 'exit-code'.

Since the only supplementary group mentioned is `tss` which is not a group my system has, I'm assuming this is all to do with a missing dependency that the deb fails to call out.

**Comment by jinnatar** [comment]
The missing package seems to have been `tpm-udev` which includes a postinst `adduser` & `addgroup` for `tss`. Pretty sure the server I'm testing on has a TPM, but I guess none of that is autodetected for a server install.

So two things to do here:
1. Add that package, or a more appropriate one as a dependency, taking into account Ubuntu vs. Debian and all that fun.
2. Add more troubleshooting info, so that I wouldn't have gone down the rabbithole that I did.

I can probably do a PR for both, need to just dig a bit deeper if `tpm-udev` is the right one to do this

**Comment by yaleman** [comment]
Sooooo yes. Systemd handles all the user/folder creation stuff. The TPM libs are new so that's probably what's missing...

**Comment by yaleman** [comment]
The `dm_unixd` thing is systemd being weird - if you do `journalctl -u kanidm-unixd` instead of grepping the bare `journalctl` output you'll get the results you need.

**Comment by yaleman** [comment]
@jinnatar can we close this out?

**Comment by yaleman** [comment]
I'll close this until we find out - it looks like this is sorted
