### ISSUE TITLE
SQLite Write-Ahead Logging might make page size immutable

### ISSUE THREAD

**Issue by TheRealGramdalf** [kanidm/kanidm#2404]
The [sqlite](https://sqlite.org/wal.html) documentation for WAL mode says:

> It is not possible to change the [page_size](https://sqlite.org/pragma.html#pragma_page_size) after entering WAL mode, either on an empty database or by using [VACUUM](https://sqlite.org/lang_vacuum.html) or by restoring from a backup using the [backup API](https://sqlite.org/backup.html). You must be in a rollback journal mode to change the page size.

I am aware that Kanidm implements a custom caching method on top of sqlite, and that this may not be an issue, but I figured I would bring it up in case this was missed.

**Comment by yaleman** [comment]
It's [already documented](https://kanidm.github.io/kanidm/stable/database_maint.html?highlight=database#vacuum) that you need to vacuum after changing the db_fs_type, but I've added a PR to note it on the config entry ref too.

**Comment by TheRealGramdalf** [comment]
I did see that, but that's not the part I'm worried about - it says that "**It is not possible to change the [page_size](https://sqlite.org/pragma.html#pragma_page_size)** after entering WAL mode, either on an empty database **or by using [VACUUM](https://sqlite.org/lang_vacuum.html)**"

Unless I'm horribly incorrect, this means that once created (and WAL mode is enabled, which I assume is the case due to the `.db-wal` file), you **cannot** change the page size with a vacuum.

The only exception that I can see (though I am no expert in sql) is "You must be in a rollback journal mode to change the page size."

**Comment by yaleman** [comment]
And that's why we disable the WAL mode journalling on vacuum. ref  https://github.com/kanidm/kanidm/blob/307a66ea29fd99c170c8e06eec888719d0112f6a/server/lib/src/be/idl_sqlite.rs#L1801-L1833
