### ISSUE TITLE
Traefik, Kanidm, and HTTP Header Authentication

### ISSUE THREAD

**Issue by TheRealGramdalf** [kanidm/kanidm#2407]
**Is your feature request related to a problem? Please describe.**

Some server resources (e.g. static web pages, the Traefik dashboard) do not support Oauth2/OpenID authorization, and instead support HTTP header authentication. 

**Describe the solution you'd like**

Things such as [this Traefik middleware](https://github.com/thomseddon/traefik-forward-auth) and [oauth2-proxy(https://github.com/oauth2-proxy/oauth2-proxy) exist, but the former seems unmaintained and the latter is an additional moving part that is external to Kanidm, and thus an increased attack surface. [Authelia](https://www.authelia.com) supports Traefik through the [forwardAuth](https://doc.traefik.io/traefik/v3.0/middlewares/http/forwardauth/) middleware, and it would be nice for Kanidm to do the same.

**Describe alternatives you've considered**

This may be out of scope, insecure, or simply not part of what Kanidm is about, which is completely understandable. I was simply unable to find mention of HTTP header auth, and figured a request was the best way forward.

**Additional context**

In this case, the resource I would like to secure is the [Traefik dashboad](https://doc.traefik.io/traefik/v3.0/operations/dashboard/). Traefik Enterprise (which is expensive for a home user or prosumer) gives access to a first party Oauth2/OpenID middleware, but since that is out of reach for the majority of users, HTTP header authentication is the next logical option.

**Comment by yaleman** [comment]
I don't see a way of supporting this in a way that'd be in ANY way secure - all it sends is the source IP and destination URL and assumes the auth server keeps track of it? Solely-source-IP-based security is literally the least secure method I could imagine implementing, so ... no, this won't get done.

From [the docs on ForwardAuth](https://doc.traefik.io/traefik/v3.0/middlewares/http/forwardauth/#forward-request-headers):

> The ForwardAuth middleware delegates authentication to an external service. **If the service answers with a 2XX code, access is granted, and the original request is performed**. Otherwise, the response from the authentication server is returned.

The following request properties are provided to the forward-auth target endpoint as `X-Forwarded-` headers.

|Property|Forward-Request Header|
|---|---|
|HTTP Method|X-Forwarded-Method|
|Protocol|X-Forwarded-Proto|
|Host|X-Forwarded-Host|
|Request URI|X-Forwarded-Uri|
|Source IP-Address|X-Forwarded-For|

**Comment by TheRealGramdalf** [comment]
There is the ability to set custom headers: 
https://doc.traefik.io/traefik/v3.0/middlewares/http/forwardauth/#authresponseheaders
Here's how Authelia uses it in the Traefik configuration:
```yml
http:
  middlewares:
    authelia:
      forwardAuth:
        address: https://authelia:9091/api/verify?rd=https%3A%2F%2Fauth.example.com%2F
        trustForwardHeader: true
        authResponseHeaders:
          - "Remote-User"
          - "Remote-Groups"
          - "Remote-Email"
          - "Remote-Name"
```
I have no idea how this would work internally, ideally you would be able to create an "internal" Oauth2 RS, which can be used here to some extent - Kanidm would present the usual login flow, and through some magic tomfoolery you can then be authenticated through these headers.

To be completely honest I'm not sure I fully understand how it works (on the technical side), and I may be making some incorrect assumptions because of that.

**Comment by yaleman** [comment]
As far as I can tell, all it's doing is sending a single request from Traefik to the auth backend with a few headers, not redirecting the client or presenting the auth, so there's not enough context for Kanidm to know which user is in play. It's not *redirecting* to the auth backend or using OAuth2, otherwise we likely wouldn't need to have this discussion 😄 

I'd say oauth2-proxy is your best bet TBH.

**Comment by Firstyear** [comment]
You could use something like mod_auth_oidc with apache as a reverse proxy instead (if I'm understanding properly).

**Comment by yaleman** [comment]
Yep, similar idea - I run both (mod_auth_oidc for Nagios, oauth2-proxy for another thing)

**Comment by yaleman** [comment]
Since this isn't doable with the current understanding, I'll be closing this one until someone can identify a way forward.
