### ISSUE TITLE
Allow changing LDAP max_ber_size, especially in syncing from LDAP

### ISSUE THREAD

**Issue by ultinous-kszegi** [kanidm/kanidm#2414]
### I did this

Tried to setup LDAP import sync

### I expected the following

LDAP data gets imported

### Kanidm version details

- Output of `kanidm(d) version`:
  kanidm 1.1.0-rc.15-dev
- Are you running it in a container? If so, which image/tag?:
  no
- If not a container, how'd you install it:
  zypper in from your repo
- Operating System / Version (On Unix please post the output of `uname -a`):
  Linux mail 5.14.21-150500.55.39-default #1 SMP PREEMPT_DYNAMIC Tue Dec 5 10:06:35 UTC 2023 (2e4092e) x86_64 x86_64 x86_64 GNU/Linux

### Any other comments

Output of `kanidm-ldap-sync -d`
```
...
2024-01-04T16:34:19.881031Z DEBUG kanidm_ldap_sync: ldap_sync_base_dn="***,dc=***" cookie=None mode=RefreshOnly filter=Equality("objectclass", "person")
2024-01-04T16:34:19.882547Z  INFO syncrepl: ldap3_client: transport error e=Custom { kind: OutOfMemory, error: "lber request too large" }
```

I found that the max incoming size (`max_ber_size`) is 8KB by default in ldap3 lib, and that is way too small for sync, especially if you have things like jpegImage attribute

**Comment by yaleman** [comment]
Or we could just make it 1024kb or something similarly large?

**Comment by Firstyear** [comment]
Sync probably needs a seperate config here for the ber size, since this could come up in various ways.

**Comment by Samonitari** [comment]
> Or we could just make it 1024kb or something similarly large?

I agree with @Firstyear that sync should have a separate config for this, as jpegImage attribute can easily be larger, but that's not universally used in LDAP directories, so an opt-in to large size would be the best.

BTW, can somebody describe how many "chunks" will have an LDAP sync? One per a single entry, or my whole synced dir as a single LDIF payload?

**Comment by Firstyear** [comment]
LDAP max BER size is the maximum size of each ldap *message*. During a search, each entry is a separate LDAP message. That means the max BER size only needs to accomodate the single largest entry during the search.

**Comment by Samonitari** [comment]
That didn't took long. I don't really have Rust exp. but I did try to solve: I didn't add it as an `Option<usize>`, but as a simple `usize` to config though, and I failed to compile on suse leap due to old OpenSSL, even though I installed openssl-3 package, it always found the 1.x, even if I tweaked the path, renamed the 1.x executable, etc

and thanks for the clarification, so it seems `max _ber_size` needs to be larger than the largest `jpegImage` attribute (base64 encoded if I remember correctly), but not larger then all of them, that's okay

**Comment by yaleman** [comment]
@Firstyear I don't have perms to publish the ldap crates 😝

**Comment by Firstyear** [comment]
> @Firstyear I don't have perms to publish the ldap crates 😝

I'll add you. We need to do an update anyway for LLDAP.

**Comment by Samonitari** [comment]
Works as expected, thanks!
