### ISSUE TITLE
Idea: Rename/alias the client tools (UX)

### ISSUE THREAD

**Issue by TheRealGramdalf** [kanidm/kanidm#2451]
**Is your feature request related to a problem? Please describe.**

Due to the current command-line centric nature of Kanidm as a whole, entering `kanidm` before each command quickly becomes tiring (after ~5 commands or so)

**Describe the solution you'd like**

Shortening the client command from `kanidm` to `kani` (or keeping both at once)

**Describe alternatives you've considered**

Use a shell alias (not as portable)/up to the user

**Additional context**

This would also help distinguish `kanidm` from `kanidmd`, if support for calling the utility with `kanidm` were eventually dropped. One working example of a similar situation in the wild is `docker-compose` compared to `docker compose` - the difference is so minimal that it's often overlooked, which increases the amount of irrelevant bug reports etc. 
- _I realize this isn't a perfect comparison, but at least it gives you an idea._
- _Bonus: `kani` means `crab` (at least according to the readme), which is a fun little easter egg_
- _I double checked, and there doesn't appear to be an existing utility with the same name, so there shouldn't be any conflicts_
- _Renaming to `kani` could introduce confusion because `kani` isn't quite as explicitly related_

**Comment by yaleman** [comment]
As you mentioned, I'd suggest just using a shell alias for this, you could even hit kan<tab> and that'd save the same number of keystrokes 😄

**Comment by Firstyear** [comment]
> Shortening the client command from `kanidm` to `kani` (or keeping both at once)

It's being name squatted, so we can't. https://crates.io/crates/kani 

> 
> **Additional context**
> 
> This would also help distinguish `kanidm` from `kanidmd`, if support for calling the utility with `kanidm` were eventually dropped. 

They are different things, and will never be "dropped". `kanidmd` is the server binary. `kanidm` is the cli tool.

**Comment by Firstyear** [comment]
And yes, just use a shell alias here.

**Comment by TheRealGramdalf** [comment]
Got it - I didn't realize kani was a thing. I do realize that kanidmd and kanidm are two different things - its precisely things like this that I was hoping to avoid. In that specific case I was referring to eventually dropping support for calling the client utility with kanidm, such that the only way to call it was with the shorthand kani. But I digress - its your project, and just a suggestion/idea I had.
