### ISSUE TITLE
Suggested password reset command errors "missing field `primary_can_edit`

### ISSUE THREAD

**Issue by zoechi** [kanidm/kanidm#2454]
### I did this

```sh
❯ kanidm person credential create-reset-token zoechi -D idm_admin
2024-01-24T06:57:14.858123Z  WARN kanidm_client: verify_ca set to false in client configuration - this may allow network interception of passwords!
The person can use one of the following to allow the credential reset

Scan this QR Code:

█████████████████████████████████████████
█████████████████████████████████████████
████ ▄▄▄▄▄ █▄▀▄▀▀ ██▀ ▄███ ███ ▄▄▄▄▄ ████
████ █▄▄▄█ █▀▀▀ ▄ █▄▀▄▀▄▀ ██▄█ █▄▄▄█ ████
████▄▄▄▄▄▄▄█▄▀▄▀▄█ █▄█ █▄█▄▀▄█▄▄▄▄▄▄▄████
...
████▄▄▄▄█▄▄▄ ██ █  ▀▄█▀▀ ██▄ ▄▄▄ ▄█▀▀████
████ ▄▄▄▄▄ █▄█ ▄▄█▄▄███▄██▀▀ █▄█  ▄▀▄████
████ █▄▄▄█ █▄█▄▀  ▀▄▀▄▀▄▄█▄█▄ █  ▀█▄▄████
████▄▄▄▄▄▄▄█▄▄█▄▄███▄███▄███▄▄█▄▄▄██▄████
█████████████████████████████████████████
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀

This link: https://idm.mydomain.eu/ui/reset?token=xvB4J-18GHx-yCZq6-L1qRR
Or run this command: kanidm person credential use-reset-token xvB4J-18GHx-yCZq6-L1qRR


develop in my_app/container on  develop [+] via ❄️  impure (devenv-shell-env)
❯ kanidm person credential use-reset-token xvB4J-18GHx-yCZq6-L1qRR
2024-01-24T06:57:22.323870Z  WARN kanidm_client: verify_ca set to false in client configuration - this may allow network interception of passwords!
2024-01-24T06:57:22.448409Z ERROR kanidm_cli::person: Error starting use_reset_token -> JsonDecode(reqwest::Error { kind: Decode, source: Error("missing field `primary_can_edit`", line: 1, column: 576) }, "95071304-d0ba-4b5b-b606-0d3aff125b35")

```

### I expected the following

I just executed the suggested command, so I'd expect it to work.

### Kanidm version details

- Output of `kanidm(d) version`: 

```
❯ kanidm version
kanidm 1.1.0-rc.15-dev
2024-01-23T15:23:13.572043Z DEBUG kanidm: Using 12 worker threads
```
```
❯ sudo podman exec -ti kanidm kanidmd version
kanidmd 1.1.0-rc.15-dev
```

- Are you running it in a container? If so, which image/tag?: `kanidm/server:1.1.0-rc.15-dev`

- If not a container, how'd you install it:
- Operating System / Version (On Unix please post the output of `uname -a`): `Linux develop 6.1.74 #1-NixOS SMP PREEMPT_DYNAMIC Sat Jan 20 10:50:11 UTC 2024 x86_64 GNU/Linux` (NixOS)

**Comment by Firstyear** [comment]
Yes I think you're right. It was changed in 47bcea7708 from a boolean to an enum of the state for the UI.

@zoechi how did you install the cli tools vs the server? Can you confirm they are the same git revision?

**Comment by zoechi** [comment]
I wondered about that because the version output matches but I got warnings about version mismatch.
The server is from Docker and the client from Nix 23.11.

I assumed no big changes so close to 1.0 and rather expected outdated docs or something like that.
I'm new to Nix and not yet able to track down issues.
I could try client tools from Docker as well as mentioned in the docs.

**Comment by yaleman** [comment]
Yep, try that.

**Comment by zoechi** [comment]
I'm sure it's my setup, but I have no time to verify right now.
I'll close and reopen in case I can still verify later.
Thanks a lot for your support.
