### ISSUE TITLE
Document legacy/insecure resource settings

### ISSUE THREAD

**Issue by adamcstephens** [kanidm/kanidm#2458]
**Is your feature request related to a problem? Please describe.**

As a kanidm administrator, it feels "scary" to enable legacy or insecure options. Unfortunately, many oauth2 clients do not support the kanidm defaults. Further, when communicating with authors of oauth2 client applications, it would be helpful to have information we can provide to justify why we're asking for specific features.

**Describe the solution you'd like**

Please add to the FAQ explanations of the legacy and insecure options (disabling PKCE/crypto) , providing justification on why kanidm chooses these defaults. I would like this to target two audiences, kanidm administrators and oauth2 client developers. 

**Describe alternatives you've considered**

Status quo, no changes.

**Additional context**

**Comment by yaleman** [comment]
To be clear, PKCE is the opposite of legacy/insecure 😄

**Comment by adamcstephens** [comment]
Thank you!
