### ISSUE TITLE
Tool broken: SchemaViolation(MissingMustAttribute(["oauth2_rs_name"]))

### ISSUE THREAD

**Issue by dvv** [kanidm/kanidm#2470]
### I did this

```
$ kanidm system oauth2 create test 'Test' https://test.example.com
ERROR kanidm_cli: HTTP Error: 400 Bad Request SchemaViolation(MissingMustAttribute(["oauth2_rs_name"])) "2cd34330-e202-4d25-8394-febf96340d84"
```

### I expected the following

`Success`

### Kanidm version details

- Output of `kanidm(d) version`:
- Are you running it in a container? If so, which image/tag?:
```
$ docker images | grep kanidm
kanidm/tools                             devel                    6d8d37e85392   About an hour ago   622MB
kanidm/server                            devel                    df43003fb98f   2 hours ago         817MB
```
- Operating System / Version (On Unix please post the output of `uname -a`): `Linux vd 5.4.0-170-generic #188-Ubuntu SMP Wed Jan 10 09:51:01 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`

### Any other comments

This
```
POST /v1/oauth2/_basic

{
  "attrs": {
    "oauth2_rs_name": ["test"],
    "name": ["test"],
    "displayname": ["Test"],
    "oauth2_rs_origin": ["https://test.example.com"]
  }
}
```
works.

**Comment by Firstyear** [comment]
Please pull both images again and re-test - I think they were out of sync (most likely the tools side).

**Comment by Firstyear** [comment]
Actually, I think your server version is what has the issue here, but yes pull both. Also note this is the devel image so it's not guaranteed to be stable.

**Comment by dvv** [comment]
Well I re-pulled the latest "devel" for both before I filed the issue -- please see "Kanidm version details" ^^^
I re-did it again and the error persists.
Shall I check something else?
TIA

**Comment by Firstyear** [comment]
I just setup a git master server and client tools and I get a successful create of the oauth2 client. I also re-checked all the code and it seems to match what it should be doing. 

Docker likes to be silly and cache things some times, and I did only just re-upload all the tools containers "about the time" we had this issue raised. So perhaps there is still something blocking your docker client from updating the image? Could you docker rm on both server/tools and then re-pull to force it to get a newer version?

**Comment by dvv** [comment]
@Firstyear I did, error persisted. Well I'll just keep eye on it for a few days.

**Comment by yaleman** [comment]
They're both built off the same commit, which should mean they should work together...

```
09:03:11 ❯ docker image ls | grep kanidm
kanidm/tools           devel                6d8d37e85392   20 hours ago   622MB
kanidm/server          devel                df43003fb98f   21 hours ago   817MB

➜ docker image inspect 6d8d37e85392 | grep git
                "com.kanidm.git-commit": "8fde121ec70165e445f767d23bb49343ec55deef",

➜ docker image inspect df43003fb98f | grep git
                "com.kanidm.git-commit": "8fde121ec70165e445f767d23bb49343ec55deef",
```

**Comment by dvv** [comment]
Exactly the same here.
But

```sh
$ kanidm system oauth2 create test 'Test' https://test.example.com -D admin
2024-02-03T03:27:00.774627Z ERROR kanidm_cli: HTTP Error: 403 Forbidden AccessDenied "3ed3d569-dfec-419d-bbd0-97975aa3de88"

$ kanidm system oauth2 create test 'Test' https://test.example.com -D idm_admin
2024-02-03T03:27:05.462176Z ERROR kanidm_cli: HTTP Error: 400 Bad Request SchemaViolation(MissingMustAttribute(["oauth2_rs_name"])) "651c8d08-322d-473f-9369-7ec87b8077b3"
```

Shall I somehow refresh the schema?

**Comment by Firstyear** [comment]
I have just pulled both images:

```
# docker image ls
REPOSITORY                                                               TAG               IMAGE ID       CREATED         SIZE
kanidm/tools                                                             devel             69e41dd35a29   25 hours ago    666MB
kanidm/server                                                            devel             f78b56c6916f   25 hours ago    890MB
```

And then I have created a server instance with the steps in the quickstart (but with the devel tag) and used the kanidm tools image to create the oauth2 rs. It works correctly for me.

I have also confirmed both are from the same git commit:

```
# docker image inspect kanidm/tools:devel | grep git
                "com.kanidm.git-commit": "8fde121ec70165e445f767d23bb49343ec55deef",
# docker image inspect kanidm/server:devel | grep git
                "com.kanidm.git-commit": "8fde121ec70165e445f767d23bb49343ec55deef",
```

Can you please check the above to ensure that everything is from the same git commits for you as well? 

> Shall I somehow refresh the schema? 

No, it's done automatically for you. Since this is presumably a new instance of the server, it should "just work". The problem is that the server here expects an oauth2 rs to have "name" not "oauth2_rs_name". But your client tools are the wrong version and are sending the "oauth2_rs_name" value instead.

**Comment by dvv** [comment]
I see. I ended up _dropping the current database_ and recreated it anew. This worked!
The quirk is that I could create oauth2 under idm_admin, not admin (documentation skew?) -- https://github.com/kanidm/kanidm/issues/2470#issuecomment-1925040762.

Thank you!

**Comment by Firstyear** [comment]
Yes, the docs you are reading online are 'stable' not the 'development' verison. If you want the devel version docs you need to read the book source

**Comment by Firstyear** [comment]
> I see. I ended up _dropping the current database_ and recreated it anew. This worked! The quirk is that I could create oauth2 under idm_admin, not admin (documentation skew?) -- [#2470 (comment)](https://github.com/kanidm/kanidm/issues/2470#issuecomment-1925040762).


Also the only thing I can think of here is that you had the unfortunate luck to pull the devel image "half way" through a change, so the migration only triggered once but wasn't complete at that point. The devel image isn't "stable" so sometimes issues like this happen. Maybe we need a better process for testing "master" and "unstable"? I'm sorry you had so many problems though, this is not the usual standard we expect for new users.

**Comment by dvv** [comment]
@Firstyear thank you!

It's not a problem as I believe that tighter onboarding drives one to understand the system deeper )

**Comment by Firstyear** [comment]
```
sh-5.2# kanidm system oauth2 create whoami 'WhoAmI' https://test.example.com
Success
sh-5.2# kanidm system oauth2 create testrs 'Testrs' https://test2.example.com
Success
sh-5.2# kanidm system oauth2 create testrs3 'Testrs3' https://test3.example.com
Success
```

I can't reproduce what you are seeing ... 

At this point from a "clean install" we're gonna need to see every command you run to create the environment and attempt this. That way we can perfectly reproduce what you are seeing.

**Comment by dvv** [comment]
Thank you! I'll collect some statistics and revisit the issue (if any).

**Comment by dvv** [comment]
I tried to rename the domain: `kanidmd domain rename`. It chokes with similar (about oauth2_rs_name) error:
```
[warn]: Validation error, the following required (test@...) (must) attributes are missing - ["oauth2_rs_name"] | event_tag_id: 2
[error]: Schema Violation in validation of modify_pre_apply MissingMustAttribute(["oauth2_rs_name"]) | event_tag_id: 1
```
Will explore further.

**Comment by dvv** [comment]
I have finally narrowed down the probable cause of the issue.
The sequence: start "clean install", stop it, start it, recover idm_admin password, login as idm_admin, then issue
```
kanidm system oauth2 create foo 'Foo' https://foo.example.com
```

**Comment by Firstyear** [comment]
Can you please show precise commands such as:

```
docker volume create <name>
docker run <options> kanidm/server:devel 
docker exec kanidm/tools:devel
tools# kanidm system oauth2 create
```

This way we have a precise set of steps to attempt to reproduce.

**Comment by dvv** [comment]
I got distracted and would leave it so far as is.
AFAICS the bug is activated by the first "reindex" of empty database, if you understand what I mean.
I create clean instance, immediately stop the container, start the container and then can not create app.
If I create clean instance and _not stop_ the container, I can create and manage apps until the first restart.
The images of server and tools are the same for both above routes, so I tend to believe it's database structure that gets slightly corrupted upon restart.

**Comment by Firstyear** [comment]
> The images of server and tools are the same for both above routes, so I tend to believe it's database structure that gets slightly corrupted upon restart.

This is a really serious issue, and why I am taking this matter so seriously.

I have however, finally identified the cause and will be submitting a fix.

**Comment by dvv** [comment]
@Firstyear excellent job, thank you!
