### ISSUE TITLE
Object graph view

### ISSUE THREAD

**Issue by ToxicMushroom** [kanidm/kanidm#2487]
**Is your feature request related to a problem? Please describe.**
Currently the only way to know what the inheritance is between groups and persons is to look at text output.

**Describe the solution you'd like**
By presenting the kanidm objects in a graph admins can easily see what is a member of what and spot things that seem out of place or verify by comparing the kanidm graph to a graph they're using as reference.

This could be implemented using mermaidjs as a tab in the webUI for admins to view.
Or this could be a cli option to print the graph source files.

**Additional context**
![image](https://github.com/kanidm/kanidm/assets/32853531/0276d288-6fb0-4597-80ea-897793c61c58)

I've had troubles with mermaid in the past where it'd generated broken graphs, and it often generates worse graphs than graphviz. Mermaidjs probably has easier browser integration though.

It is also probably a good idea to show different objects as different shapes/colors/or prefix with a symbol ?

**CLI Ideas**
Since graph can output multiple objects or should perhaps integrate many objects into a single graph, it would not make sense to put it under person or group, putting it toplevel also feels a little bit like bloating the interface but maybe it can be moved into a more fitting category in the future
`kanidm graph <mermaid|graphviz> [filters]`

**Web UI ideas**
Some options I'd think are useful:
 - A filter dropdown to choose which objects to show (groups, builtin_groups, accounts, builtin_accounts, persons, maybe more/less ?)
 - A button to copy or view the graph source
 - Maybe just have multiple graph renderers (mermaidjs and graphviz are the 2 I know) but this might be a little overkill.
 
 Feedback is welcome, sorry if this is too much of an information dump (I'm not good at this :p).

**Comment by ToxicMushroom** [comment]
First testing output of the graph output with mermaid via cli: 
![image](https://github.com/kanidm/kanidm/assets/32853531/39ddb4ab-081a-4b46-8ff4-8ebd744f2817)

**Comment by Firstyear** [comment]
Oh dang, that looks really nice! Great work!
