### ISSUE TITLE
Move service-account signing key to primary dedicated key

### ISSUE THREAD

**Issue by Firstyear** [kanidm/kanidm#2490]
Currently each service account gets it's own JWT signing key. This was intended to prevent damage of key disclosure, but it generally just causes key lookup complexity and other issues. 

We should have service-accounts moved to use a dedicated service-account signing key, or share these token signatures with the primary UAT key. 

Requires https://github.com/kanidm/kanidm/issues/2513

**Comment by yaleman** [comment]
TBH this feels like an *added* complexity, special-casing service accounts?

**Comment by Firstyear** [comment]
The goal is to undo that complexity :)

**Comment by yaleman** [comment]
Aha! So, to make sure it's noted here - it's to move it back to having it the same as other accounts, where a single key's used for signing things.

**Comment by Firstyear** [comment]
This was implemented as part of the cryptographic pr that we recently merged.
