### ISSUE TITLE
Automated/Scheduled backups

### ISSUE THREAD

**Issue by Firstyear** [kanidm/kanidm#25]
It would be beneficial to deployments to have an automated/scheduled backup system in the server, to avoid the need to trigger a db backup before you perform a filesystem backup.

**Comment by cuberoot74088** [comment]
How about this topic?

I think the current practice is to manually stop the server an run it with the backup command to create a json.

https://github.com/kanidm/kanidm/blob/master/kanidm_book/src/administrivia.md#method-1

The other method beeing a backup of the db file, which also requires(?) a stopped server.


Imho stopping the server is not optimal or is there some requirement that we want to do this?

Would we want to create something to produce the (preferred) json backup from a running server? It could also be an api to trigger that action, which could unload the scheduling task an might be interessting for on-demand backups.

Another idea was to create a temporary read only replicate and do a backup with this instance. Is this already doable?

Any other thoughts on that?

**Comment by yaleman** [comment]
@Firstyear has said in the past that doing a backup live should be possible without issue... but this is something that'd have to be tested.

A read-replica backup would be the easiest, once replication's done :) That's a big chunk of work that's yet to be done, though.

**Comment by Firstyear** [comment]
Yes, this is possible live. At the moment we only do backups offline just because we didn't have enough parts in place for configuration and scheduling. Now most of the frameworks are in place, and backups can be performed in a read transaction. It's just a matter of wiring it together basicly.
