### ISSUE TITLE
Group/person rename should be easier to access

### ISSUE THREAD

**Issue by Firstyear** [kanidm/kanidm#2501]
Currently we don't make this easy to access. We should improve the CLI to accomodate this.

**Comment by johanfleury** [comment]
What is the current way of renaming a group or account? I got hit by the uniqueness constraints from 1.1.0-rc.16 and had to rollback to rc.15, but I can’t find a way to rename groups.

I’m sure there’s a good reason for this change and this is not the right place to talk about it, but I must say it feels weird to have to prefix your groups or accounts (e.g. with `grp_`) to avoid having duplicate names.

**Comment by Firstyear** [comment]
@johanfleury It happened because oauth2 client credentials were merged, which necessitated turning oauth2 clients into "accounts". Because of that the oauth2_rs_name now became "name" and can potentially conflict with other entries.

For now the following steps can be used as admin/idm_admin from rc1.5:

Put this into `/tmp/group.json`

```
[
    { "purged": "name" },
    { "present": ["name", "NEW GROUP NAME"] }
]
```

Run `kanidm raw search '{"eq":["name", "OLD GROUP NAME"]}'` to search the group.

Confirm it's the group you wish to rename

Run `kanidm raw modify '{"eq":["name", "OLD GROUP NAME"]}' /tmp/group.json`


Very sorry about the issue. I plan to make this easier in future, and if it comes up for others I'll backport a fix.
