### ISSUE TITLE
OpenLDAP sync critical extension

### ISSUE THREAD

**Issue by dvv** [kanidm/kanidm#2502]
Hi!

I'm exploring `kanidm-ldap-sync` and ran into the following:
```
kanidm_ldap_sync: state=Refresh
kanidm_ldap_sync: ldap_sync_base_dn="dc=example,dc=com" cookie=None mode=RefreshOnly filter=Or([Equality("objectclass", "person"), Equality("objectclass", "posixgroup")])
syncrepl: ldap3_client::syncrepl: critical extension is not recognized
kanidm_ldap_sync: Failed to perform syncrepl from ldap e=UnavailableCriticalExtension
kanidm_ldap_sync: Sync completed with error e=LdapSyncrepl
```
Slapd said:
```
Feb  9 12:09:26 foo slapd[341193]: slap_global_control: unrecognized control: 1.3.6.1.4.1.42.2.27.8.5.1
Feb  9 12:09:26 foo slapd[341193]: get_filter: conn 1487 unknown attribute type=sudoHost (17)
Feb  9 12:09:26 foo slapd[341193]: get_ssa: conn 1487 unknown attribute type=sudoHost (17)
Feb  9 12:09:26 foo slapd[341193]: message repeated 4 times: [ get_ssa: conn 1487 unknown attribute type=sudoHost (17)]
Feb  9 12:09:31 foo slapd[341193]: <= mdb_equality_candidates: (displayName) not indexed
```

These are loaded:
```
moduleload syncprov.la
overlay syncprov
```
and I can read with `ldapsearch`.

I wonder what could be the cause and is there a fix on kanidm side (for slapd side's config is not under my control)?
Maybe some attribute mappings would do?

TIA

**Comment by Firstyear** [comment]
This is telling you that something about syncprov on openldap isn't loaded or configured correctly. You can test directly with:

```
ldapsearch -H ldaps://<ldapserver uri> -D <binddn> -w <password> -x -b <basedn> -E\!sync=ro
```

This lets you do a content sync as a test to check it's working.

**Comment by dvv** [comment]
I see. Thank you!

**Comment by Firstyear** [comment]
Did you end up getting to the cause of the problem? Did the test command help?

**Comment by dvv** [comment]
Nope so far. I fed this barebone command to admins. Thank you!

**Comment by Firstyear** [comment]
Okay, let's re-open this until we have a resolution, I'm curious about the outcome here as this could serve as a way to improve our documentation.

**Comment by dvv** [comment]
I'm curious what's the purpose of using the extension? Will it allow for password import?

**Comment by Firstyear** [comment]
We use this because it allows openldap to send us "diffs" of only the entries that changed. that way overtime, you can maintain the sync connector to run both systems in parallel while migrating. This is all documented in the migration/sync chapters.

Without this, we'd need to fully import the entire ldap db every few minutes/seconds.

**Comment by Firstyear** [comment]
Also yes, it allows us to import passwords from openldap

**Comment by Firstyear** [comment]
Resolved as we now ignore missing extensions.
