### ISSUE TITLE
Include code_challenge_methods_supported field in .well-known/openid-configuration for better compatibility

### ISSUE THREAD

**Issue by shelvacu** [kanidm/kanidm#2506]
**Is your feature request related to a problem? Please describe.**

I was trying to integrate kanidm with nextcloud using https://apps.nextcloud.com/apps/oidc_login and it assumes that the `openid-configuration` metadata will have the `code_challenge_methods_supported` key if PKCE is supported. This is *not* to spec, but I suspect this isn't the only piece of software with such an assumption, and [google seems to think it's a good idea to include it](https://accounts.google.com/.well-known/openid-configuration).

**Describe the solution you'd like**

Include a `code_challenge_methods_supported` key in the metadata with the value as specified in rfc8414.

**Describe alternatives you've considered**

Fixing the oidc_login app: I may submit a PR, but I think it would be a good idea for kanidm to do this regardless

**Additional context**

[The spec specifically says](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata) `Additional OpenID Provider Metadata parameters MAY also be used.` which I think is permission enough to do this.

rfc8414's metadata and OIDC's metadata seem so similar I almost wonder if would make sense to combine them and just send the same json for both.

**Comment by Firstyear** [comment]
I need to check but I think there was some metadata that wasn't quite the same between them? We could share some elements though. For now I'll add code challenge methods though.
