### ISSUE TITLE
kanidm cli cannot logout an expired session without re-login

### ISSUE THREAD

**Issue by jinnatar** [kanidm/kanidm#2507]
### I did this
```
kanidm logout --name admin    
2024-02-09T20:33:34.674973Z ERROR kanidm_cli::common: Session has expired for admin@idm.example.com - you may need to login again.
Would you like to login again? no
```

### I expected the following
The `admin` user is logged out and removed from `~/.cache/kanidm_tokens`. Instead a logout can only succeed if I first login again.

### Kanidm version details

- Output of `kanidm(d) version`: `kanidm 1.2.0-dev`, `kanidmd 1.1.0-rc.16`
- Are you running it in a container? If so, which image/tag?: yes, `1.1.0-rc.16`
- If not a container, how'd you install it:
- Operating System / Version (On Unix please post the output of `uname -a`): `Linux $host 6.1.0-16-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.67-1 (2023-12-12) x86_64 GNU/Linux`

### Any other comments
:3

**Comment by Firstyear** [comment]
kanidm session cleanup will remove expired sessions.

But we should make this nicer :)

**Comment by yaleman** [comment]
Probably need to change it to check if it's expired before doing the login phase... and I swear automagically cleaning up any expired sessions should be a first-phase thing in any exec of `kanidm` 😄
