### ISSUE TITLE
Does Kanidm support anonymous authentication

### ISSUE THREAD

**Issue by akashlama1998-icloud** [kanidm/kanidm#2557]
Like how Firebase Auth, AWS Cognito, etc. have anonymous authentication which can be used to login a user without asking them for their personal information (usually used in ECommerce sites like Amazon where they don't ask for logging in upfront but still let the user to use the app), does kanidm has that feature as well?

**Comment by yaleman** [comment]
No, it's an identity platform, designed to have users created for authentication purposes.

**Comment by Firstyear** [comment]
Yes, this would be up to your application to have an anonymous function, or may optionally allow login via oauth2/oidc backed to kanidm.
