### ISSUE TITLE
Replace mdbook-template with mdbook-alerts

### ISSUE THREAD

**Issue by yaleman** [kanidm/kanidm#2572]
**Is your feature request related to a problem? Please describe.**

Templates are janky and break too easily (though, they're crabby) - it could be worth replacing them with https://github.com/lambdalisue/rs-mdbook-alerts

**Describe the solution you'd like**

Replace the templates in the book with github-flavoured alerts, which are easier to read in code, and less fragile.

**Describe alternatives you've considered**

Cake

**Additional context**

**Comment by harshalmittal4** [comment]
Hello, 
attaching example - 

mdbook-template - 
1. 
![Screenshot 2024-03-03 at 7 45 45 PM](https://github.com/kanidm/kanidm/assets/24206326/a12c3e4d-45e4-496a-a055-46b01bc2853d)
2. 
![Screenshot 2024-03-03 at 7 45 56 PM](https://github.com/kanidm/kanidm/assets/24206326/97282ef2-13ad-46e8-a5a5-7d9851eb5132)


mdbook-alert -
1. 
![Screenshot 2024-03-03 at 7 44 26 PM](https://github.com/kanidm/kanidm/assets/24206326/44e9d2a3-1051-44f5-aff4-ac9dc409d802)
2. 
![Screenshot 2024-03-03 at 7 45 29 PM](https://github.com/kanidm/kanidm/assets/24206326/a3fa841b-4864-45eb-9063-0f34897e91eb)

Is this fine ? Please let me know

**Comment by Firstyear** [comment]
@yaleman I'll leave this one to you :)

**Comment by yaleman** [comment]
I like the look of it, and it should mean the markdown renders in Github code view as well, please PR your changes @harshalmittal4
