### ISSUE TITLE
Make Server startable without server.toml if mandatory environment variables are set.

### ISSUE THREAD

**Issue by nikjoesta** [kanidm/kanidm#2577]
### Description:
I am confused by how the environment variables are load to overwrite the config. I wanted to create a docker-compose file with all config read from environment variables.

### Expected Behavior:
The Server can be started without server.toml and without bogus entries like:

``` yaml
domain = ""
origin = ""
db_path = ""
```

### Actual Behaviour
The server can only be started if server.toml exists and contains at least the entries domain, origin, db_path like described above. Otherwise it complains like:

``` log
Unable to parse config from '"/data/server.toml"': Error { inner: ErrorInner { kind: Custom, line: Some(0), col: 0, at: Some(0), message: "missing field `db_path`", key: [] } }
```

### Possible Solution
Check first if mandatory environment variables are set, then load server.toml then overwrite it with environment variables.

### Alternative Solution (works also as manual workaround now)
Create server.toml on startup if it doesn't exist and fill it with:
``` yaml
domain = ""
origin = ""
db_path = ""
```

### Additional info
Code is in [server/core/src/config.rs](https://github.com/kanidm/kanidm/blob/master/server/core/src/config.rs) ~ Line 146

What do You think? I would say it is not that complicated to implement and would make deployment over docker a bit easier. I can also help implement it. I am relatively new to Rust though. But this sounds manageable.

**Comment by yaleman** [comment]
This makes sense given the recent support for environment variable configuration.

**Comment by Firstyear** [comment]
I think my condition on this is that the "minimum required set of env vars" must all be present *or* the server.toml is present. I don't want there to be some kind of state where one or env vars is present but the servec fails to start, we need to clearly state "You must set env vars A, B, C or have server.toml."

**Comment by yaleman** [comment]
Yep, I was going to go with:
- try and parse the specified file
- pull any env vars
- if x fields are missing regardless of where they were supposed to come from, bail

**Comment by Firstyear** [comment]
Seems reasonable to me.
