### ISSUE TITLE
Blank front page in Chrome based browsers from version 122/123 onwards (zstd compression failure)

### ISSUE THREAD

**Issue by jinnatar** [kanidm/kanidm#2593]
### I did this
Visited https://idm.example.com/ on Chrome Android version 123 (current Beta). The issue also repeats on _some_ users using version 122, as apparently the feature flag for zstd (`enable-zstd-content-encoding`) is enabled for some people as an experiment. It's on-by-default starting with 123 and causes the browser to send a header advertising support for Zstandard compression:
`Accept-Encoding: gzip, deflate, br, zstd`

### I expected the following
HTML to be served to my browser. Unfortunately that does not happen and instead a blank page is rendered. If one digs deep enough into it via dev tools the following error message can be observed deep in the bowels of the network tracing: `net::ERR_ZSTD_WINDOW_SIZE_TOO_BIG`

Kanidmd has support for zstd encoding via tower-http, but at least the current version of it pinned in the project does not produce output that Chrome is willing to accept, likely due to their imposed 8MiB memory limit.

### Kanidm version details

- Output of `kanidm(d) version`: `kanidmd 1.1.0-rc.16`
- Are you running it in a container? If so, which image/tag?: `1.1.0-rc.16`
- If not a container, how'd you install it:
- Operating System / Version (On Unix please post the output of `uname -a`): `Linux $hostname 6.1.0-16-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.67-1 (2023-12-12) x86_64 GNU/Linux`

### Any other comments
This was discussed in chat and updating tower-http to a newer version is a very painful exercise. It's also unclear if that would address the issue. Due to other issues with zstd support right now, the best plan may be to drop support for it. This would however necessitate anyone with Chrome using users to update to a newer version.

A stop-gap solution is to alter the incoming `Accept-Encoding` header via a reverse proxy layer to either remove `zstd` from it, or just drop the header entirely. This way kanidmd does not perform compression which triggers the issue. An example for Traefik is included below (in consul tag format):
```
"traefik.http.middlewares.drop-encoding.headers.customrequestheaders.Accept-Encoding=",
"traefik.http.routers.idm.middlewares=drop-encoding",
```

**Comment by yaleman** [comment]
Looks like Chrome's failing to handle valid `zstd` compressed responses, we've removed it as a supported compression in the current dev build (for other reasons 😄 )

**Comment by Firstyear** [comment]
I'm going to remove zstd from stable branch.

**Comment by Firstyear** [comment]
Fixed via https://github.com/kanidm/kanidm/commit/d407844e6a7e38f2a44d5aba181ee23054bf25e0

**Comment by jyio** [comment]
Ugh... I'm going to blame Chrome because it also fails [this other test case](https://www.daniel.priv.no/tools/zstd-browser-test/), but it sort of grinds my gears that Kanidm is being forced to yield.

*Thank you* for prioritizing compatibility. In the interim, this stop-gap works for Caddy 2:
```
request_header Accept-Encoding zstd[^,]* "identity"
```

**Comment by Firstyear** [comment]
Our current support policy only applies to the latest version, so we can't help you with an older version. We would advise you to upgrade your instance if possible :) 

See:

* https://kanidm.github.io/kanidm/stable/support.html
* https://kanidm.github.io/kanidm/stable/server_updates.html

**Comment by johanfleury** [comment]
I upgraded recently, thank you. I just wanted to add that for the record in case you ever wanted to try again with zstd.
