### ISSUE TITLE
account-policy privilege-expiry is silently capped

### ISSUE THREAD

**Issue by dvv** [kanidm/kanidm#2619]
### I did this

```
kanidm group account-policy privilege-expiry idm_all_accounts 86400
```
### I expected the following

The r/w session for a user lasts for 86400 seconds.
In fact it expires in 3600 seconds.
It is counter-intuitive even it's good to cap the r/w session duration.

### Kanidm version details

- Output of `kanidm(d) version`: the current master
- Are you running it in a container? If so, which image/tag?: `make build/kanidmd`
- Operating System / Version (On Unix please post the output of `uname -a`): 5.15.0-92-generic #102-Ubuntu SMP Wed Jan 10 09:33:48 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Any other comments

The unconditional limit is set [here](https://github.com/kanidm/kanidm/blob/9d05b797ed8b6e7ecfff94c25f50e73c12fef037/server/lib/src/idm/accountpolicy.rs#L98
), `kanidm group account-policy privilege-expiry` setting is silently ignored, `MAXIMUM_AUTH_PRIVILEGE_EXPIRY` is an arbitrary-chosen internal constant, is not admin-controllable and can't be tuned without source hacking.

Wonder if it worth to control such constants kinda:
```
kanidm system account-policy max-privilege-expiry 3600
```

TIA

**Comment by Firstyear** [comment]
Not a bug - we set a maximum cap for a reason. People can adjust the value in whatever range they want, but we set a cap of 1 hour for a reason.

**Comment by Firstyear** [comment]
As a reminder, kanidm is an opinionated project - that means we make decisions that admins *can't change* specifically so that admins can not accidentally harm their environments or their users who depend on them.

**Comment by dvv** [comment]
Truly valid reason, thank you!
I drafted #2622 for some notes on this in book, please consider.
