### ISSUE TITLE
How to create a sync account for LDAP?

### ISSUE THREAD

**Issue by profgiuseppe** [kanidm/kanidm#2629]
Hello, I'm trying to create a sync account for configuring a sync between kanidm and and existing openLDAP.
However, I was not able to create it, I tried different combination of user performing the creation (admin and idm_admin) and account name (either existing and non-existing).

I'm using the following syntax (where <my domain> is the domain configured in the "domain" variable of server.toml):

`kanidm system sync create -d --name idm_admin@<my domain> sync`
`kanidm system sync create -d --name idm_admin@<my domain> sync@<my domain>`

The debug information shows a "HTTP Error: 403 Forbidden AccessDenied" error.

Do you have any suggestion on where the issues may be? WIthout this I can't create the sync token for the configuration.

My instance of kanidm is configured to provide posix accounts via PAM.
I'm using kanidm 1.2.0-dev 3bf16d4253 installed using the debian packages built form the source repo.

Thanks

**Comment by Firstyear** [comment]
```
# kanidm system sync create -D admin ldapsync
Success

# kanidm system sync get -D admin ldapsync
---
class: object
class: sync_account
# not actually a private key, it's the key id. 
jws_es256_private_key: 5693545c9ecae9d7321638b18573e3ea944871d80612a3ffa4ad881a24b70cb8
name: ldapsync
uuid: 12daaee0-3b69-4516-b050-177b4d20e743
```

The "account id" needs to not exist before you start, it's the name of the sync agreement. 

If it happens with the `admin` account still, please send the debug logs from the operation  :)

**Comment by profgiuseppe** [comment]
Thanks, my mind got stuck into the domain mapping and I probably didn't try to use simple account names.
It worked nicely.

**Comment by Firstyear** [comment]
All good, glad that solved it.
