### ISSUE TITLE
Error creating oauth2

### ISSUE THREAD

**Issue by pando85** [kanidm/kanidm#2638]
### I did this
I just try to create a new oauth2.

### I expected the following

Successful creation

### Kanidm version details

container: `kanidm/server:1.1.0-rc.16`

### Any other comments
The error was:
```
86ca1f7f-0ea6-489d-ae4e-ac958c488bc2 INFO        │  ┝━ ｉ [info]: allowed create of 1 entries ✅ | event_tag_id: 11                                                       
86ca1f7f-0ea6-489d-ae4e-ac958c488bc2 INFO        │  ┝━ ｉ [info]: regenerating oauth2 basic secret | event_tag_id: 10                                                     
86ca1f7f-0ea6-489d-ae4e-ac958c488bc2 INFO        │  ┝━ ｉ [info]: regenerating oauth2 token key | event_tag_id: 10                                                        
86ca1f7f-0ea6-489d-ae4e-ac958c488bc2 INFO        │  ┝━ ｉ [info]: regenerating oauth2 es256 private key | event_tag_id: 10                                                
86ca1f7f-0ea6-489d-ae4e-ac958c488bc2 ERROR       │  ┝━ 🚨 [error]: Account or group missing name, unable to generate spn!? InvalidEntryState entry_id = Some(928ba        
c6c-c0c2-4c6f-b0ee-d35675c2be08) | event_tag_id: 1                                                                                                                        
86ca1f7f-0ea6-489d-ae4e-ac958c488bc2 ERROR       │  ┕━ 🚨 [error]: Create operation failed (pre_transform plugin), InvalidEntryState | event_tag_id: 1                    
86ca1f7f-0ea6-489d-ae4e-ac958c488bc2 ERROR       ┝━ 🚨 [error]:  | latency: 3.08157ms | status_code: 500 | kopid: "86ca1f7f-0ea6-489d-ae4e-ac958c488bc2" | msg: "err      
or handling request"                                                                                                                                                      
86ca1f7f-0ea6-489d-ae4e-ac958c488bc2 ERROR       ┕━ 🚨 [error]: response failed | classification: Status code: 500 Internal Server Error | latency: 3 ms
```
I don't understand what happen :S
Thanks :)

**Comment by yaleman** [comment]
That's odd, does it have the same name as a group? Because that *might* explain it?

**Comment by Firstyear** [comment]
> That's odd, does it have the same name as a group? Because that _might_ explain it?

No, then you would have a duplicate value error and refint triggers. 

This error specifically is from https://github.com/kanidm/kanidm/blob/master/server/lib/src/plugins/spn.rs which makes me think you have a migration issue because the oauth2_rs_name should be name now in rc.16. 

Alternately, you somehow found a way to make an empty string the oauth2rs name? 

Can you do a `kanidm system oauth2 get` on the entry in question?

**Comment by pando85** [comment]
Ou, thanks for your clues.
I found the problem. I was using client version 1.1.0-rc.15 in this pc. Installation upgrade fails for kanidm cli tool using AUR packages and orca makes the upgrade fail there. I didn't realize that CLI version was outdated... blalblabla.

Thank you very much.

**Comment by Firstyear** [comment]
Oh perfect, glad you solved it.
