### ISSUE TITLE
Schema Violation in validation of modify_pre_apply when upgrading from beta-13 to rc-16

### ISSUE THREAD

**Issue by daenney** [kanidm/kanidm#2643]
### I did this

Upgraded from 1.1.0-beta.13 to 1.1.0-rc.16 using the Debian packages built according to https://kanidm.github.io/kanidm/stable/packaging_debs.html. These were built by checking out the associated Git tag.

On startup, I get:

```
53ffd570-735e-4466-b085-c88b7271da48 WARN     ┝━ 🚧 [warn]: access control has no defined targets - this will do nothing! | name: "idm_acp_hp_sync_account_manage_priv"
53ffd570-735e-4466-b085-c88b7271da48 INFO     ┕━ migrate_13_to_14 [ 631µs | 1.55% ]
53ffd570-735e-4466-b085-c88b7271da48 WARN        ┝━ 🚧 [warn]: starting 13 to 14 migration. | event_tag_id: 2
53ffd570-735e-4466-b085-c88b7271da48 ERROR       ┕━ 🚨 [error]: Schema Violation in validation of modify_pre_apply InvalidClass(["account_policy"]) | event_tag_id: 1
00000000-0000-0000-0000-000000000000 ERROR    🚨 [error]: Unable to setup query server or idm server -> SchemaViolation(InvalidClass(["account_policy"]))
00000000-0000-0000-0000-000000000000 ERROR    🚨 [error]: Failed to start server core!
```

### I expected the following

For the server to start

### Kanidm version details

- Output of `kanidm(d) version`: `kanidmd 1.1.0-beta.13 1fb34a91e3` to `kanidmd 1.1.0-rc.16 7567514044`
- Are you running it in a container? If so, which image/tag?: No
- If not a container, how'd you install it: Debian packages
- Operating System / Version (On Unix please post the output of `uname -a`): `Linux idm 6.1.0-18-cloud-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.76-1 (2024-02-01) x86_64 GNU/Linux`

**Comment by daenney** [comment]
I'm operating under the assumption that it's possible to upgrade multiple version with the idea that the migrations for all versions would be included. That might be wrong on my part. I can upgrade to beta-15 first if that's what's expected.

**Comment by Firstyear** [comment]
You should be upgrading one version at a time, we don't test any other way.

**Comment by daenney** [comment]
I managed to upgrade to rc-15 first, though I had to upgrade to dbf476fe5ea2c120dff9a85e552be9f898c69ce7 since otherwise the packages fail to build due to an angry clippy.

That upgrade was successful, but upgrading to rc-16 from there is still throwing an error:

```
Mar 12 16:37:37 idm kanidmd[19039]: c9ff8d9e-1dd6-4822-a613-8f039ecf68dd INFO     ┕━ migrate_domain_4_to_5 [ 5.06ms | 1.92% ]
Mar 12 16:37:37 idm kanidmd[19039]: c9ff8d9e-1dd6-4822-a613-8f039ecf68dd INFO        ┝━ ｉ [info]: Removing orphaned oauth2 session | o2_session_id: 416e4814-9d15-4279-a9e6-9330277d937e | parent_id: Some(1d5d7e2c-98a0-415a-874f-0258023bd349)
Mar 12 16:37:37 idm kanidmd[19039]: c9ff8d9e-1dd6-4822-a613-8f039ecf68dd ERROR       ┝━ 🚨 [error]: oauth2_consent_scope_map kitchenpad@idm.4096.se - not found in the list of valid attributes for this set of classes ["account", "memberof", "object", "service_account"] - valid attributes are ["account_expire", "account_valid_from", "api_token_session", "class", "description", "directmemberof", "displayname", "entry_managed_by", "jws_es256_private_key", "last_modified_cid", "mail", "memberof", "name", "name_history", "oauth2_session", "primary_credential", "spn", "ssh_publickey", "user_auth_token_session", "uuid"] | event_tag_id: 1
Mar 12 16:37:37 idm kanidmd[19039]: c9ff8d9e-1dd6-4822-a613-8f039ecf68dd ERROR       ┕━ 🚨 [error]: Schema Violation in validation of modify_pre_apply AttributeNotValidForClass("oauth2_consent_scope_map") | event_tag_id: 1
Mar 12 16:37:37 idm kanidmd[19039]: 00000000-0000-0000-0000-000000000000 ERROR    🚨 [error]: Unable to setup query server or idm server -> SchemaViolation(AttributeNotValidForClass("oauth2_consent_scope_map"))
Mar 12 16:37:37 idm kanidmd[19039]: 00000000-0000-0000-0000-000000000000 ERROR    🚨 [error]: Failed to start server core!
Mar 12 16:37:37 idm kanidmd[19039]: Logging pipeline completed shutdown
```

**Comment by daenney** [comment]
I'm getting the impression it's no longer OK having a service account in a group with regular users?

**Comment by Firstyear** [comment]
Service accounts are allowed in the group, that's fine. 

The issue is a duplicate of https://github.com/kanidm/kanidm/issues/2596

There is a backported fix for rc-16 which you may be missing?

**Comment by daenney** [comment]
Right yes, I built from the tag, I forgot about the branch. Let me try that.

**Comment by daenney** [comment]
That fixes it indeed. Thanks for all the help! I've jotted these things down for the next upgrade so hopefully shouldn't make this mistake again.

**Comment by Firstyear** [comment]
> That fixes it indeed. Thanks for all the help! I've jotted these things down for the next upgrade so hopefully shouldn't make this mistake again.

Well, we've learnt from this issue and what it caused, so we have improved our migration testing framework ( https://github.com/kanidm/kanidm/pull/2576 ) and we have a new approach to certain upgrade processes ( https://github.com/kanidm/kanidm/discussions/2607 ) 

So hopefully next upgrade will avoid all of these issues :)
