### ISSUE TITLE
Shouldn't GET particular resource return 404 "nomatchingentries"?

### ISSUE THREAD

**Issue by dvv** [kanidm/kanidm#2678]
### I did this

`GET /v1/person/no-such-spn-name-uuid`, received `200 null`

### I expected the following

`GET /v1/person/no-such-spn-name-uuid`, to receive `404 "nomatchingentries"`

### Kanidm version details

latest master

**Comment by Firstyear** [comment]
Closing as we plan to replace most forward facing apis with scim that handles this better.
