### ISSUE TITLE
Several API inconsistencies IMO

### ISSUE THREAD

**Issue by dvv** [kanidm/kanidm#2679]
### I did this

`GET /v1/group/g1/_attr/member2`, received `400 "emptyrequest"`
`PUT /v1/group/g1/_attr/member2`, received `500 {"invalidattributename":"member2"}`

### I expected the following

`GET /v1/group/no-such-spn-name-uuid/_attr/member2`, to receive `404 "nomatchingentries"`
`GET /v1/group/existing-spn-name-uuid/_attr/member2`, to receive `400 {"invalidattributename":"member2"}`
`PUT /v1/group/existing-spn-name-uuid/_attr/member2`, to receive `400 {"invalidattributename":"member2"}`

### Kanidm version details

latest master

**Comment by yaleman** [comment]
Requesting `member2` should get you a 400 invalid attribute response regardless if the name/UUID would be found, because schema is validated before entry existence.

(ie, `GET /v1/group/no-such-spn-name-uuid/_attr/member2` should give you a 400)

The PUT response needs fixing though, as noted.
