### ISSUE TITLE
Invite/welcome links

### ISSUE THREAD

**Issue by tacerus** [kanidm/kanidm#2689]
**Is your feature request related to a problem? Please describe.**

Currently administrators create accounts for new accounts with an initial passphrase which is then transmitted to the user.

This relies on:
- a secure channel for transmission of the passphrase between the administrator and the user - especially the (possibly novice) user treating the communication as confidential / not saving it unencrypted
- users actually following up with being requested to change the given passphrase immediately

**Describe the solution you'd like**

It would be nice if accounts could be created with "invite links" - instead of setting an initial passphrase, the system sends a URL (ideally with an expiration date) to the users email address which the user can then visit to finalize the creation of their account while being asked to set an initial passphrase (and possibly also to add SSH keys, once possible in the UI) themselves.

**Describe alternatives you've considered**

Only add a public SSH key and have the user login to some machine to then set a passphrase, but it would require login to the client without a passphrase.

**Additional context**

n/a

**Comment by yaleman** [comment]
There's already the credential reset link which prompts the user to set up their credentials?

`kanidm person credential create-reset-token username`

**Comment by tacerus** [comment]
Oh! I'm sorry, I missed this - now with your snippet I found it: https://kanidm.github.io/kanidm/stable/accounts/authentication.html?highlight=create-reset-token#onboarding-a-new-person--resetting-credentials.

Thank you! :)
