### ISSUE TITLE
Excessive session creation makes replicated secondary instances' memory blow up

### ISSUE THREAD

**Issue by tumbl3w33d** [kanidm/kanidm#2693]
### I did this

I have a replicated (active-passive, two nodes) kani setup. My custom app used a service account (username + password) to regularly (every 10 minutes per env of which I currently have 3) contact the kani api to ask about things. I used the init session path instead of api tokens. I also properly logout after every contact, however, I don't reuse sessions, but create a new one every time.

### I expected the following

I expected kani to cleanup revoked sessions and it does, but there's a problematic side effect that (the following is my understanding) for revoked sessions there's at least a tombstone (so the information that the session is gone) replicated to other instances and these are not being "garbage collected" (in the same interval or ever) for reasons.

### Kanidm version details

Official rc.16 container running on latest docker on Debian 11.

### Any other comments

![image](https://github.com/kanidm/kanidm/assets/1982589/ec8e151c-382b-4377-b4e7-c36b1cc7bcfd)

The blue instance is the passive replica and you see, as described before, the primary has a regular cleanup and stays alive while the secondary hits the system limit at some point and gets killed by the oom killer. This causes a restart and the same thing repeats over and over.

I implemented the use of api tokens now and will observe if this solves the issue on my end.

### Workaround

Don't use sessions for such things. Make use of api tokens (my choice) or at least recycle your sessions.

**Comment by yaleman** [comment]
None of this is really related to tombstones, it'll be the in-memory cache of things expanding further than it should... how much memory is it using? 100% is a bit vague.

**Comment by Firstyear** [comment]
@yaleman I already debugged with them privately :)

**Comment by tumbl3w33d** [comment]
Yeah, sorry @yaleman , I should have mentioned that I talked to @Firstyear before creating this issue and while this still might be confusing gibberish, it's better than what you would have seen without @Firstyear 's influence. 😀

Update for the effect of using api tokens instead of the session:
![image](https://github.com/kanidm/kanidm/assets/1982589/e3f9793f-4ed6-4624-8c65-994e55fd4346)
