### ISSUE TITLE
PostgreSQL LDAP Authentication with Kanidm - "1.1" Attribute Issue

### ISSUE THREAD

**Issue by xadcoh** [kanidm/kanidm#2695]
**Is your feature request related to a problem? Please describe.**

I'm encountering an issue while configuring PostgreSQL to use Kanidm for LDAP authentication. PostgreSQL authentication fails when specifying the "1.1" attribute in the query

pg_hba.conf entry:

```
host all all 0.0.0.0/0 ldap ldapserver="kanidm.example.com" ldaptls=0 ldapbasedn="dc=idm,dc=example,dc=com" ldapbinddn="spn=postgresql@idm.example.com,dc=idm,dc=example,dc=com" ldapbindpasswd=password ldapport=636 ldapscheme=ldaps "(spn=$username@idm.example.com)"
```

Kanidm Logs:

The Kanidm logs indicate a successful LDAP search attempt for "postgresql@idm.example.com" but with an empty set of entries when the "1.1" attribute is specified. Here's a relevant excerpt:

```
c7a14097-f1e5-4a39-ad8e-1b961c4181c0 INFO     ldap-request [ 411µs | 4.45% / 100.00% ] uat: Some(LdapBoundToken { spn: "postgresql@idm.example.com", session_id: 2b85273c-a0fd-439c-a486-f5fc6209ea91, effective_session: UnixBind(eedea12d-0f56-47af-b036-6d0df83559ed) }) | protomsg: LdapMsg { msgid: 2, op: SearchRequest(LdapSearchRequest { base: "dc=idm,dc=example,dc=com", scope: Subtree, aliases: Never, sizelimit: 0, timelimit: 0, typesonly: false, filter: Equality("spn", "username@idm.example.com"), attrs: ["1.1"] }), ctrl: [] }
c7a14097-f1e5-4a39-ad8e-1b961c4181c0 INFO     ┝━ ｉ [info]: LDAP client | event_tag_id: 10 | client_ip: ::ffff:<server_ip> | client_port: 44806
c7a14097-f1e5-4a39-ad8e-1b961c4181c0 INFO     ┕━ handle_ldaprequest [ 393µs | 95.55% ]
c7a14097-f1e5-4a39-ad8e-1b961c4181c0 INFO        ┝━ ｉ [info]: Attempt LDAP Search for postgresql@idm.example.com | event_tag_id: 3
c7a14097-f1e5-4a39-ad8e-1b961c4181c0 INFO        ┝━ ｉ [info]: LDAP Search Request LDAP Attrs | event_tag_id: 3 | attr: ["1.1"]
c7a14097-f1e5-4a39-ad8e-1b961c4181c0 INFO        ┝━ ｉ [info]: LDAP Search Request Mapped Attrs | event_tag_id: 3 | attr: Some({"1.1"})
c7a14097-f1e5-4a39-ad8e-1b961c4181c0 INFO        ┝━ ｉ [info]: LDAP Search Filter | event_tag_id: 3 | filter: And([Equality("spn", "username@idm.example.com"), Not(Or([Equality("class", "classtype"), Equality("class", "attributetype"), Equality("class", "access_control_profile")]))])
c7a14097-f1e5-4a39-ad8e-1b961c4181c0 INFO        ┝━ ｉ [info]: search | event_tag_id: 10 | initiator: User( anonymous@idm.example.com, 00000000-0000-0000-0000-ffffffffffff ) (9f1f11f9-7456-459a-8b2d-ba0c2471aa71, read only)
c7a14097-f1e5-4a39-ad8e-1b961c4181c0 INFO        ┝━ ｉ [info]: reduced to empty set on all entries ❌ | event_tag_id: 11
c7a14097-f1e5-4a39-ad8e-1b961c4181c0 INFO        ┕━ ｉ [info]: LDAP Search Success -> number of entries | event_tag_id: 3 | nentries: 1
```
ldapsearch:

```
ldapsearch -H ldaps://kanidm.example.com -b "dc=idm,dc=example,dc=com" -D "spn=postgresql@idm.example.com,dc=idm,dc=example,dc=com" -W "(&(name=username)(!(|(class=classtype)(class=attributetype)(class=access_control_profile))))" "1.1"
```

Issue:

The problem arises with the "1.1" attribute in request. Excluding or replacing it with "*" or "+" allows successful authentication through ldapsearch.

Investigation:

Unfortunately, I haven't found any configuration options within the PostgreSQL auth-method to address this behavior.

Request for Help:

I'd appreciate any insights or suggestions on how to resolve this issue and enable user authentication with the "1.1" attribute.

**Describe the solution you'd like**

I'm not sure how to address this

**Describe alternatives you've considered**

Was thinking about using PAM or RADIUS

**Additional context**

I'm using kanidm 1.1.0-rc16 and postgresql 12.18

**Comment by yaleman** [comment]
It looks like it’s asking for the 1.1 OID (uid), maybe try specifying spn as the ldapsearchattribute value

On 2024-04-08 01:39 Andrey Okhotnikov wrote:
> 
> 
> *Is your feature request related to a problem? Please describe.*
> 
> I'm encountering an issue while configuring PostgreSQL to use Kanidm for LDAP authentication. PostgreSQL authentication fails when specifying the "1.1" attribute in the query
> 
> pg_hba.conf entry:
> 
> `host all all 0.0.0.0/0 ldap ldapserver="kanidm.example.com" ldaptls=0 ldapbasedn="dc=idm,dc=example,dc=com" ***@***.***,dc=idm,dc=example,dc=com" ldapbindpasswd=password ldapport=636 ldapscheme=ldaps ***@***.***)"
`
> Kanidm Logs:
> 
> The Kanidm logs indicate a successful LDAP search attempt for ***@***.***" but with an empty set of entries when the "1.1" attribute is specified. Here's a relevant excerpt:
> 
> `c7a14097-f1e5-4a39-ad8e-1b961c4181c0 INFO     ldap-request [ 411µs | 4.45% / 100.00% ] uat: Some(LdapBoundToken { spn: ***@***.***", session_id: 2b85273c-a0fd-439c-a486-f5fc6209ea91, effective_session: UnixBind(eedea12d-0f56-47af-b036-6d0df83559ed) }) | protomsg: LdapMsg { msgid: 2, op: SearchRequest(LdapSearchRequest { base: "dc=idm,dc=example,dc=com", scope: Subtree, aliases: Never, sizelimit: 0, timelimit: 0, typesonly: false, filter: Equality("spn", ***@***.***"), attrs: ["1.1"] }), ctrl: [] }
> c7a14097-f1e5-4a39-ad8e-1b961c4181c0 INFO     ┝━ ｉ [info]: LDAP client | event_tag_id: 10 | client_ip: ::ffff:<server_ip> | client_port: 44806
> c7a14097-f1e5-4a39-ad8e-1b961c4181c0 INFO     ┕━ handle_ldaprequest [ 393µs | 95.55% ]
> c7a14097-f1e5-4a39-ad8e-1b961c4181c0 INFO        ┝━ ｉ [info]: Attempt LDAP Search for ***@***.*** | event_tag_id: 3
> c7a14097-f1e5-4a39-ad8e-1b961c4181c0 INFO        ┝━ ｉ [info]: LDAP Search Request LDAP Attrs | event_tag_id: 3 | attr: ["1.1"]
> c7a14097-f1e5-4a39-ad8e-1b961c4181c0 INFO        ┝━ ｉ [info]: LDAP Search Request Mapped Attrs | event_tag_id: 3 | attr: Some({"1.1"})
> c7a14097-f1e5-4a39-ad8e-1b961c4181c0 INFO        ┝━ ｉ [info]: LDAP Search Filter | event_tag_id: 3 | filter: And([Equality("spn", ***@***.***"), Not(Or([Equality("class", "classtype"), Equality("class", "attributetype"), Equality("class", "access_control_profile")]))])
> c7a14097-f1e5-4a39-ad8e-1b961c4181c0 INFO        ┝━ ｉ [info]: search | event_tag_id: 10 | initiator: User( ***@***.***, 00000000-0000-0000-0000-ffffffffffff ) (9f1f11f9-7456-459a-8b2d-ba0c2471aa71, read only)
> c7a14097-f1e5-4a39-ad8e-1b961c4181c0 INFO        ┝━ ｉ [info]: reduced to empty set on all entries ❌ | event_tag_id: 11
> c7a14097-f1e5-4a39-ad8e-1b961c4181c0 INFO        ┕━ ｉ [info]: LDAP Search Success -> number of entries | event_tag_id: 3 | nentries: 1
`
> ldapsearch:
> 
> `ldapsearch -H ldaps://kanidm.example.com -b "dc=idm,dc=example,dc=com" -D ***@***.***,dc=idm,dc=example,dc=com" -W "(&(name=username)(!(|(class=classtype)(class=attributetype)(class=access_control_profile))))" "1.1"
`

**Comment by Firstyear** [comment]
It's a bug in our side:

https://www.rfc-editor.org/rfc/rfc4511#section-4.5.1.8

"""
A list containing only the OID "1.1" indicates that no
         attributes are to be returned.  If "1.1" is provided with other
         attributeSelector values, the "1.1" attributeSelector is
         ignored.  This OID was chosen because it does not (and can not)
         correspond to any attribute in use.
"""
