### ISSUE TITLE
Changing Claim Value Join doesn't change the `oauth2_rs_claim_map`

### ISSUE THREAD

**Issue by playhardgopro** [kanidm/kanidm#2701]
Hi!
I guess I get a strange behavior, but I am not sure. Could you, please, make it clearer for me?:)
### I did this
When I changed the claim value join to `csv`, I received:
```
"oauth2_rs_claim_map": [
            "claim_1:idm_admins@example.com:,:\"some_value,another_value\"",
        ],
```
After that I changed it to `array` and received:
```
"oauth2_rs_claim_map": [
            "claim_1:idm_admins@example.com:;:\"some_value,another_value\"",
        ],
```
The join changed, but the values are still joined as `csv`(`,`)
### I expected the following
I expected to receive something like:
```
 "oauth2_rs_claim_map": [
            "claim_1:idm_admins@example.com:;:\"some_value;another_value\"",
        ],
```
Shouldn't the separator in the values be the same as the `join`?

### Kanidm version details

- Output of `kanidm(d) version`: `kanidm 1.2.0-dev`
- Are you running it in a container? If so, which image/tag?: no
- If not a container, how'd you install it: actually, I don't know, I just use web API to our Kanidm instance :)
- Operating System / Version (On Unix please post the output of `uname -a`):

### Any other comments
Thank you in advance!:)

**Comment by yaleman** [comment]
Can you please show us how it was configured on the command line? 

I'm guessing you specified "some_value,another_value" which likely got caught as a single entry.

**Comment by playhardgopro** [comment]
I have ran these:
```
kanidm system oauth2 update-claim-map-join frontend-test-public claim_42 array >/dev/null
kanidm system oauth2 get frontend-test-public | grep claim_42
kanidm system oauth2 update-claim-map-join frontend-test-public claim_42 ssv >/dev/null
kanidm system oauth2 get frontend-test-public | grep claim_42
kanidm system oauth2 update-claim-map-join frontend-test-public claim_42 csv >/dev/null
kanidm system oauth2 get frontend-test-public | grep claim_42
```
And have received:
```
oauth2_rs_claim_map: claim_42:test@example.com:;:"another_value,some_value,value_3,value_4,value_5"
oauth2_rs_claim_map: claim_42:test@example.com: :"another_value,some_value,value_3,value_4,value_5"
oauth2_rs_claim_map: claim_42:test@example.com:,:"another_value,some_value,value_3,value_4,value_5"
```
I expected [to receive something like these](https://kanidm.github.io/kanidm/stable/integrations/oauth2.html?highlight=claim%20value#custom-claim-maps)
```
oauth2_rs_claim_map: claim_42:test@example.com:;:"another_value;some_value;value_3;value_4;value_5"
oauth2_rs_claim_map: claim_42:test@example.com: :"another_value some_value value_3 value_4 value_5"
oauth2_rs_claim_map: claim_42:test@example.com:,:"another_value,some_value,value_3,value_4,value_5"
```
I am not sure about the case with `array` (`;`) :)

**Comment by playhardgopro** [comment]
Sorry, I don't have an access to our Kanidm instance :(
I can only provide you the curl request which I send to add values
```
curl 'https://idm.example.com/v1/oauth2/frontend-test-public/_claimmap/claim_42/test' \
  -H 'Accept: application/json' \
  -H 'Authorization: Bearer add_your_token' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json' \
  -H 'Origin: https://idm.example.com' \
  -H 'Referer: https://idm.example.com/apps/frontend-test-public/claims' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-origin' \
  --data-raw '["some_value","value_1","value_2"]'
```
I will try to provide you more details after getting the access to our Kanidm CLI

**Comment by playhardgopro** [comment]
```
kanidm system oauth2 update-claim-map frontend-test-public claim_43 idm_admins a b c # created
# oauth2_rs_claim_map: claim_43:idm_admins@example.com:;:"a,b,c"
kanidm system oauth2 update-claim-map-join frontend-test-public claim_43 csv # changed
# oauth2_rs_claim_map: claim_43:idm_admins@example.com:,:"a,b,c"
```

**Comment by yaleman** [comment]
ok, that's what I was going for, confirmation of how it was done so we can try and replicate/trace it 😄

**Comment by Firstyear** [comment]
I think the confusion is how we display the joiner on the cli. When we "get" the entry, we always display them as a csv. This is because of something you noted yourself. 

> I am not sure about the case with `array` (`;`) :)

Simply, displaying the array became tricky to work out how to do nicely. 

So we display it as `:<joiner>:<csv of values>`. 

But I will assure you, that the content in what we sent to the oauth2 client is formatted as you would expect. :)
