### ISSUE TITLE
Clarify error message when group doesn't exist while adding scope map 

### ISSUE THREAD

**Issue by joostrijneveld** [kanidm/kanidm#2710]
**Is your feature request related to a problem? Please describe.**

When following [the instructions about creating an OAuth integration](https://kanidm.github.io/kanidm/master/integrations/oauth2.html), I was directed to issue the follow command:

```
kanidm system oauth2 update-scope-map <name> <kanidm_group_name> [scopes]...
kanidm system oauth2 update-scope-map nextcloud nextcloud_admins admin
```

However, the group `nextcloud_admins` did not exist yet. I was presented with the following somewhat cryptic error message:

`2024-04-18T12:33:30.065096Z ERROR kanidm_cli: Item not found:" NoMatchingEntries" "8267f859-f59e-4947-8cb7-372f382802c4"`

**Describe the solution you'd like**

I'd much appreciate a descriptive error message that tells me the group `nextcloud_admins` did not exist.

**Describe alternatives you've considered**

None; I have no idea what the returned UID represents.

**Additional context**

None

**Comment by Firstyear** [comment]
Hmmmm i'm not 100% sure how'd we handle this one. NoMatchingEntries is telling you here "nothing meets the criteria you requested" in this case, the absence of a group.

The UUID it gives you is a key that looks up the operation in the logs so you can find things. 

maybe we need a specific error translation in the oauth2 path given our ongoing work to make errors more specific? But that has it's own challenges ...

**Comment by yaleman** [comment]
Another problem is that it doesn't tell you if it's the group or the OAuth2 client it can't find, either. 

It *does* need a more human error either way.
