### ISSUE TITLE
build: Add feature switches for conditional vendoring of dependencies

### ISSUE THREAD

**Issue by CyberTailor** [kanidm/kanidm#2744]
**Is your feature request related to a problem? Please describe.**

`webauthn-rs-core` crate is not comptaible with LibreSSL (see https://github.com/kanidm/webauthn-rs/issues/402) and fails to build against it. OpenSSL 1.1 is also unsupported.

**Describe the solution you'd like**

Add a feature switch to depend on `openssl/vendored`.

**Describe alternatives you've considered**

Fix build with LibreSSL or make WebAuthn functionality optional (controlled with a feature switch).

**Additional context**

A feature switch controlling vendoring `libsqlite3-sys` could also be added.

**Comment by Firstyear** [comment]
You already can build this with `cargo build --features openssl/vendored` (but if I recall, vendored openssl is still 1.1 for some reason).

**Comment by CyberTailor** [comment]
It's not possible because "openssl" crate is not a workspace member (see https://github.com/rust-lang/cargo/issues/13199)

```
$ cargo build --release -p daemon --features openssl/vendored
error: none of the selected packages contains these features: openssl/vendored
```

**Comment by Firstyear** [comment]
As mentioned, even if you did vendor openssl it would fail as we require openssl 3 today. We are considering changing crypto providers however.
