### ISSUE TITLE
kanidm cli logs on debug level

### ISSUE THREAD

**Issue by tumbl3w33d** [kanidm/kanidm#2745]
### I did this

`kanidm version`

### I expected the following

Only the output of the client version.

### What actually happened

I received a debug log in addition.

### Kanidm version details

Version is 1.2.0, built from [AUR](https://aur.archlinux.org/packages/kanidm-clients) which I needed to patch (the PKGBUILD) because it builds much more than the client and failed compiling orca.

Executing it on `6.1.85-1-MANJARO #1 SMP PREEMPT_DYNAMIC Wed Apr 10 20:05:44 UTC 2024` 

### Any other comments

``` bash
kanidm version
kanidm 1.2.0
2024-05-03T13:19:42.466573Z DEBUG kanidm: Using 16 worker threads
```

**Comment by tumbl3w33d** [comment]
I've just built the rc.16 client and it has the same behavior. Maybe it was always like that and I just never noticed or used the `version` command at all. 🤷‍♂️

**Comment by Firstyear** [comment]
Still something that should be easy to cleanup I think.
