### ISSUE TITLE
Comparing Kanidm with other services

### ISSUE THREAD

**Issue by digitalethics** [kanidm/kanidm#2746]
Thank you for working on this project. Is it possible to add [Authelia](https://www.authelia.com/), [Zitadel](https://zitadel.com/) and [Authentik](https://goauthentik.io/) to the [comparison](https://kanidm.com/comparisons/) site to better understand the architectural, security, and usability decisions behind Kanidm? There's also another new Rust-based project called [Rauthy](https://github.com/sebadob/rauthy).

**Comment by Firstyear** [comment]
I'd be happy to add this soon :)

**Comment by digitalethics** [comment]
Here's another [comparison](https://docs.google.com/spreadsheets/d/16Ya5KsmEpczTmoTk5J-1e2MOyuUqXIiPuj7rPfPrHAI/htmlview) chart I came across that includes different services.
