### ISSUE TITLE
Package binaries for AUR

### ISSUE THREAD

**Issue by thechubbypanda** [kanidm/kanidm#2750]
**Is your feature request related to a problem? Please describe.**

It takes a serious amount of time to compile the kanidm client even on a fast machine. This must be done by everyone who installs it.

**Describe the solution you'd like**

Build supplementary packages on the AUR that just download pre-built binaries instead of compiling from source.

e.g. `kanidm-clients` -> `kanidm-clients-bin`

Obviously, the expectation would not exist for the `-git` versions as they will change far more than the "release" versions.

**Describe alternatives you've considered**

N/A

**Additional context**

Current AUR packages:

![image](https://github.com/kanidm/kanidm/assets/33595996/4f5b5a82-5e5c-4bdc-9a76-a6320513f1a5)

**Comment by yaleman** [comment]
We don't maintain the AUR packages, please contact the maintainers on AUR.
