### ISSUE TITLE
forward_auth support in kanidm

### ISSUE THREAD

**Issue by CEbbinghaus** [kanidm/kanidm#2774]
**Is your feature request related to a problem? Please describe.**

Kanidm looks to be a great replacement of OpenLDAP as it supports LDAP enough to allow most applications to query users. It's goal is to replace Authelia & co though as not just an IDM but Authentication/Authorization provider. This doesn't seem possible to me at the moment as I predominately use Authelia for forward_auth which kanidm does not seem to have.

**Describe the solution you'd like**

The ideal solution would be for kanidm to fully support http forward auth, This means keeping track of user sessions through cookies and verifying the user session before responding with a successful status code. A minimal example of a rust based forward auth implementation can be found [here](https://github.com/nosduco/nforwardauth). 

**Describe alternatives you've considered**

Continuing to use Authelia but connect to kanidm via LDAP. This seems VERY silly as kanidm aims to replace authelia.

**Additional context**

Caddy & Traefik both support forward auth which make integration fairly easy. Additionally forward auth is often times required as many self hosted services do not provide OAuth/OIDC functionality.
- [Caddy Forward Auth](https://caddyserver.com/docs/caddyfile/directives/forward_auth)
- [Traefik Forward Auth](https://doc.traefik.io/traefik/middlewares/http/forwardauth/)

**Comment by yaleman** [comment]
Can anyone point at a spec/RFC that actually outlines what the auth server is doing for these things, because I'd really rather have something to target instead of some vague implementation details across a bunch of backends.

I've tried to [work it out in the past](https://github.com/kanidm/kanidm/issues/2407) and it all looks vaguely terrifying from an "actually doing something secure" perspective, compared to something like oauth-proxy and friends.

**Comment by pando85** [comment]
Hello @CEbbinghaus ,

I have this working with Kanidm through Nginx and [oauth2-proxy](https://oauth2-proxy.github.io/oauth2-proxy/). It is pretty straightforward.

I don't know if I understood well but asking to use Kanidm as a proxy doesn't make any sense to me because it is an IDM and the functionality is completely different. I would prefer to have tools with clear responsibilities and not mesh with them.

**Comment by yaleman** [comment]
> I don't know if I understood well but asking to use Kanidm as a proxy doesn't make any sense to me because it is an IDM and the functionality is completely different. I would prefer to have tools with clear responsibilities and not mesh with them.

It doesn't require Kanidm to act as a proxy, but to respond to auth requests from the proxy.

**Comment by pando85** [comment]
> It doesn't require Kanidm to act as a proxy, but to respond to auth requests from the proxy.
Ok, so that's something in the middle. I was checking the Traefik docs and that was the confusion for me.

Anyway something like oauth2-proxy will help @CEbbinghaus .

**Comment by CEbbinghaus** [comment]
@pando85 oauth2-proxy looks like either another element in the chain or a replacement to Caddy neither of which are desirable to me. Additionally oauth2-proxy does not support forward auth which is a problem since it doesn't solve my problem at all. forward_auth will forward a http request to a specified endpoint of another http service which in turn verifies whether or not this user should be allowed to access the server. The way this is traditionally done is by storing a cookie which holds the session and just verifying that the cookie is valid. If the authentication succeeds it will respond with some additional parameters in the http response which usually include `Remote-User`, `Remote-Email` & similar. Those are then used by the service being protected to identify the user and load their data.

The danger with forward auth lies entirely outside of the authentication as anyone that can bypass the reverse proxy can just attach the `Remote-User` & `Remote-Email` headers themselves and the service would be none the wiser. This is why both Caddy & Traefik clean all incoming requests of any `Remote-XXX` headers.

**Comment by yaleman** [comment]
> The way this is traditionally done is by storing a cookie which holds the session and just verifying that the cookie ...

where does this cookie come from? cross-domain cookies aren't really a thing in modern browsers, and you'd have to somehow trick the calling application to pull it from the IDP in the first place?

OAuth2-Proxy doesn't need forward auth because it acts as an OAuth2 client, a well defined and standardised protocol.

**Comment by CEbbinghaus** [comment]
its not a cross-domain cookie to the best of my knowledge. its a cookie on the root domain (e.g example.com) rather than on the specific subdomain being accessed (e.g service.example.com). Which also allow a single cookie to authenticate any of the services that use forward auth.

oauth2-proxy does not need forward auth to know whether or not a user should be allowed to access a certain services. but it does not (to my knowledge) communicate to the services being proxied who the user is that is accessing it (which is aht the `Remote-User` & co headers are for). forward_auth is as much authentication as identification and involves more than just the proxy & auth server.

I haven't been able to find an official spec even after having asked around in the Authelia community. It seems to be very much designed by consensous with Traefik & Authelia being the leading 2. It all was inspired by nginx's [http auth request](https://nginx.org/en/docs/http/ngx_http_auth_request_module.html) module which has the little quirk of considering any non 200 status as a fail condition. Whereas both Traefik & Authelia treat it as the response to send back to the user.

The rough flow goes as following:
```
Successful Auth
User -> Proxy <-> Auth (200)
          \-> Service (`Remote-User`: Bob, `Remote-Email`: bob@bobmail.com)

Unsuccessful Auth
User <-> Proxy <-> Auth (302)
// the server can return any non 200 code. but returning a redirect to auth.example.com allows the auth server to set the example.com cookie.
// Assuming the user was able to successfully log in and the cookie set it would then redirect back to the original service.
```

I'll put together a proper flow diagram at some point and I want to write up something about how forward_auth could be specified. But its far too convenient a process for kanidm to ignore as so many different services support it.

**Comment by yaleman** [comment]
Without any kind of spec to work with that'd a huge blocker for design/implementation, because that's just a deep rabbit hole of troubleshooting and mess... but hey, if someone can write up a design that looks workable and supportable, then it might get into the (very, very long) queue of planned work.

But then we get to the fact that Kanidm doesn't use/support cookie authentication, let alone setting a root-domain cookie, so that's another change to the *entire* architecture which would be required.

Looks like oauth2-proxy [does support forward-auth](https://oauth2-proxy.github.io/oauth2-proxy/configuration/overview/#configuring-for-use-with-the-nginx-auth_request-directive), for what it's worth.

**Comment by Firstyear** [comment]
> its a cookie on the root domain (e.g example.com) rather than on the specific subdomain being accessed (e.g service.example.com). Which also allow a single cookie to authenticate any of the services on any of the subdomains that use forward auth.

That's a pretty scary prospect. Part of what makes Oauth2/OIDC good is that you have tokens bound to a specific client so disclosure of one token doesn't impact other services. We call this 'blast radius' to work out how damaging a leak of a credential might be. 

Having a single cookie to authenticate any subdomain makes for a terrifyingly huge blast radius if that was ever disclosed. 

It would be great if you could write up something around how this works so we could actually perform a security assessment first - while forward auth may be convenient we still need to do our due diligence before we promise to add it.

**Comment by CEbbinghaus** [comment]
I added a blog post to website going over some of the basics it's not in depth enough to be considered close to a spec. Hoping to get something more concise in writing soon but I hope it clears up some stuff

https://beta.cebbinghaus.com/Blog/forward_auth/

(it's worth noting that the way the authentication server validates the request is not specified and probably won't be part of the spec. Cookie auth is the simplest and most common but anything could be used instead)

**Comment by Firstyear** [comment]
With this "forwarded" request, won't that mean Kanidm has to catch-all routes and then answer them for the request? Won't it also mean that there are application data being sent to Kanidm? Or can it be scoped under a route or something?

**Comment by CEbbinghaus** [comment]
The forwarded request is forwarded to a specific route. so the request would be sent to `/api/auth` for example this is the configuration that would be used within Caddy for Authelia:
```ca
forward_auth authelia:9091 {
   uri /api/verify?rd=https://auth.example.com/
   copy_headers Remote-User Remote-Groups Remote-Name Remote-Email
}
```
the `/api/verify` route is the one that actually verifies and if it fails (e.g user is not logged in) it will then forward to the `auth.example.com` url to log the user in. That forward will then include the original request in a query parameter which the auth server redirects back to once the login succeeds so you are instantly redirected back to the page you came from. 

The reverse proxy provides [these headers](https://doc.traefik.io/traefik/middlewares/http/forwardauth/#forward-request-headers) for the auth service to know what the original request was aimed at:
HTTP Method | X-Forwarded-Method
-- | --
Protocol | X-Forwarded-Proto
Host | X-Forwarded-Host
Request URI | X-Forwarded-Uri
Source IP-Address | X-Forwarded-For

**Comment by henobi** [comment]
Hello,

I also wanted to use Kanidm with Forward Auth and therefore created this middleware project: https://github.com/espresso-lab/oidc-forward-auth-middleware

**Comment by Firstyear** [comment]
That's actually a really nice solution I think here. Would you mind if we reference that in our documentation?

**Comment by henobi** [comment]
Sure! Please do so :) We would be really happy to see that it‘s helpful.

**Comment by Firstyear** [comment]
@alexvonme Is this something you'd like to look at adding to our documentation?

**Comment by CEbbinghaus** [comment]
Please note also that OIDC/OAuth forward auth services already exist: [traefik forward auth](https://github.com/thomseddon/traefik-forward-auth). This Issue is in particular to have forward_auth support natively in kanidm. Happy with adding OAuth forward_auth providers to the docs and leave this issue open for a future native implementation.

**Comment by alexvonme** [comment]
@CEbbinghaus we've been discussing how to best add this, and I'd appreciate your addition especially. Unfortunately, I'm not comfortable with forward_auth myself, so your extension of the docs will likely be better.

**Comment by yaleman** [comment]
So to summarise:

* there's no official spec that anyone can point to
* Traefik already supports external-OIDC forward auth, and
* there are numerous other solutions to solve this problem.
 
I still can't understand why forward auth is something Kanidm could/should/would implement let alone a way that it would be supportable or in line with the project's goals of correct and secure before everything else. 

@alexvonme please just refer people to the current known options for auth-in-front-of-a-web-app (oauth2-proxy, mod_auth_openidc, Traefik forward auth, @henobi's middleware) and also note that until an **_official_** spec is surfaced that we can't implement it.

**Comment by ds-sebastian** [comment]
I had a lot of trouble with this as `oauth2-proxy` has a lot of issues with Traefik and `traefik forward auth` does not seem to support PKCE.

@henobi's middleware works great as I've been using if for awhile now with no issues! If using Traefik, I also recommend [this plugin](https://github.com/sevensolutions/traefik-oidc-auth/releases) which supports PKCE as well.

**Comment by sammcj** [comment]
I can recommend [sevensolutions/traefik-oidc-auth](https://github.com/sevensolutions/traefik-oidc-auth) as well, it seems more reliable and simpler than [ItalyPaleAle/traefik-forward-auth](https://github.com/ItalyPaleAle/traefik-forward-auth) - the only thing it doesn't seem to work with kanidm with is domain based forwarding so you have to manually add a redirect URL for every app (e.g. `kanidm system oauth2 add-redirect-url tfa https://myapp.my.domain/oidc/callback`)

**Comment by CEbbinghaus** [comment]
Coming back to this now that I am actually setting up OAuth ForwardAuth, and I must say. I feel shaken to my core. TLDR;
* Not only is there no spec, but **everybody** does it differently. Way less coherent than I had thought originally
* **NONE** of the above solutions work. Not a single one...

To expand on the above a bit, The base implementation of "secure website behind proxy" is functional in almost every single case. So as far as authenticating a dashboard goes the various forward_auth implementations work about equally well. **However** this starts breaking down real fast when you want to introduce user management. As pointed out earlier in this thread I had been operating under the assumption that the `Remote-User, Remote-Email, Remote-Name, etc...` headers were standard since those are the headers provided by Authelia, Turns out however that this is not the case and instead every single Forward-Auth Provider (Authelia, oidc-forward-auth-middleware, etc...) have their own implementation. The most common "standard" I have found is setting `X-Forwarded-User` which only contains the username. But given this "username" is determined by the `sub` value of the JWT for kani it contains the UUID which is not the most user friendly, It makes for a *sub* par (pun intended) experience. 

Authelia on the other hand provides a ton of properties including username, email & groups which can be used to provide more functionality within the application, Although After double checking I am almost certain that all of the usecases I have would be covered by just having the `X-Forwarded-User` contain the username, But there is still value in the email albeit not for me.

Unfortunately it isn't quite as coherent as I thought, But this is **only** regarding the data returned by the auth service for use by the backed application. The flow of authorizing a user to access a service without that service needing to know which user it is is A+ and very standard across the ecosystem.

PS @Firstyear I have been hacking around trying to make https://github.com/espresso-lab/oidc-forward-auth-middleware work for my purposes and I'm unsure if this particular implementation is something we want to encourage in our docs.

* [Nonce is being discarded and not checked later](https://github.com/espresso-lab/oidc-forward-auth-middleware/blob/main/src/main.rs#L53)
* [AccessToken is blindly trusted and not verified allowing for token substitution](https://github.com/espresso-lab/oidc-forward-auth-middleware/blob/main/src/main.rs#L148-L160)
* (unsure if problem) [pkce & csrf tokens are saved on client as cookies](https://github.com/espresso-lab/oidc-forward-auth-middleware/blob/main/src/main.rs#L59-L70)

If I am not mistaking this leaves the proxy vulnerable, Please do correct me if I am wrong.

Thanks for coming to my Ted Talk <3 (I will be back soon. I promise)

**Comment by Firstyear** [comment]
> Coming back to this now that I am actually setting up OAuth ForwardAuth, and I must say. I feel shaken to my core. TLDR;
> 
>     * Not only is there no spec, but **everybody** does it differently. Way less coherent than I had thought originally

Yes - the lack of spec and coherency has been why we don't want to touch this. 
 
> 
>     * [Nonce is being discarded and not checked later](https://github.com/espresso-lab/oidc-forward-auth-middleware/blob/main/src/main.rs#L53)

nonce is an oidc concept, and for all intents and purposes, it's ineffective as a security measure. So it not being checked doesn't matter. 

> 
>     * [AccessToken is blindly trusted and not verified allowing for token substitution](https://github.com/espresso-lab/oidc-forward-auth-middleware/blob/main/src/main.rs#L148-L160)

This is to the OAuth2 spec - the root of trust isn't the token, it's https when you do the token exchange. OAuth2 intentionally makes tokens opaque, the client has no idea what is in them and you don't need to verify their content at all. It's a blob you slap around to give you access to things.

> 
>     * (unsure if problem) [pkce & csrf tokens are saved on client as cookies](https://github.com/espresso-lab/oidc-forward-auth-middleware/blob/main/src/main.rs#L59-L70)

The pkce secret being set as a cookie in the users browser is fine - the point of pkce is to prove that the same client that did the authorisation request (what you linked to here) is the same client which does the token exchange [which is done here](https://github.com/espresso-lab/oidc-forward-auth-middleware/blob/main/src/main.rs#L275)

> 
> If I am not mistaking this leaves the proxy vulnerable, Please do correct me if I am wrong.

Sorry to say, I don't see anything obviously vulnerable in the proxy here :)

**Comment by yaleman** [comment]
Oh look, it's almost exactly how I said it'd go with that unspec'd mess.  🙄 

- "[AccessToken is blindly trusted and not verified allowing for token substitution](https://github.com/espresso-lab/oidc-forward-auth-middleware/blob/main/src/main.rs#L148-L160)" - it looks like the `token_response` is the result of getting a refresh token from the oauth server based on the refresh token, so I'd say it's fine

**Comment by CEbbinghaus** [comment]
Re the access token being trusted, I was basing that on this section in the openidconnect docs:
```rs
// Verify the access token hash to ensure that the access token hasn't been substituted for
// another user's.
if let Some(expected_access_token_hash) = claims.access_token_hash() {
    let actual_access_token_hash = AccessTokenHash::from_token(
        token_response.access_token(),
        id_token.signing_alg()?,
        id_token.signing_key(&id_token_verifier)?,
    )?;
    if actual_access_token_hash != *expected_access_token_hash {
        return Err(anyhow!("Invalid access token"));
    }
}
```
https://docs.rs/openidconnect/latest/openidconnect/#example

Good to hear that nothing is wrong with that implementation. I ended up forking and iterating it anyways to add id_token support and add user details such as username/email/displayname/groups depending on the claims [my changes](https://github.com/espresso-lab/oidc-forward-auth-middleware/compare/main...CEbbinghaus:oidc-forwardauth:Improve-Security)

But if there is no risk in the current implementation, I may move back to using cookies since it allows for a fully stateless service.

<sub>P.S Appreciate the info, seems I will need to do more learning, but finding good documentation is hard.</sub>

**Comment by yaleman** [comment]
yeah since it's comparing based on `token_response` then it should be fine as far as I've seen.

**Comment by Firstyear** [comment]
> Re the access token being trusted, I was basing that on this section in the openidconnect docs:

This is more about the client side swapping out the token it looks like.

**Comment by Firstyear** [comment]
> P.S Appreciate the info, seems I will need to do more learning, but finding good documentation is hard.

Yep, OAuth2 is a tough one, but we're always happy to help <3

**Comment by daenney** [comment]
For what it's worth, Rauthy has an implementation of this and the author went to quite some length to keep this as secure as possible. The [Advanced Forward Auth](https://sebadob.github.io/rauthy/work/forward_auth.html#advanced-forward-auth) section explains how it works, and some constraints that apply to it. Maybe that can serve as inspiration.

**Comment by CEbbinghaus** [comment]
@daenney I had a read of that article, but it doesn't seem any more special than most implementations,  one part of note is that they separate out the forward_auth validation and registration into two different routes handled by the reverse proxy. But whether that actually improves security is questionable in my mind, as all routes would be forwarded to the reverse proxy in any case.

**Comment by yaleman** [comment]
It's still a terrible protocol with better options for solving the problem, regardless of how many ways you slap band-aids on the problem.

**Comment by Firstyear** [comment]
I agree. I still believe we should not support forward auth.
