### ISSUE TITLE
Support OIDC client_ids of OwnCloud Desktop, Android, iOS

### ISSUE THREAD

**Issue by pmeiyu** [kanidm/kanidm#2802]
### Client_ids of OwnCloud Desktop, Android, and iOS are different from OCIS-web. Those client_ids cannot be configured in Kanidm.

I have an OCIS instance. The OCIS-web OIDC sign in process works well with Kanidm. But desktop, Android, iOS clients cannot sign in, because they have different client_ids. Those client_ids contain capital characters but Kanidm always converts client_ids into lower case if I manually create those client_ids.

OwnCloud client_ids are published here: https://doc.owncloud.com/server/next/admin_manual/configuration/user/oidc/oidc.html#client-ids-secrets-and-redirect-uris
| Source | Client ID |
|---------|-----------|
| Server/Web | as specified in config.php |
| Desktop | xdXOt13JKxym1B1QcEncf2XDkLAexMBFwiT9j6EfhhHFJhs2KM9jbjTmf8JBXE69 |
| Android | e4rAsNUSIUs0lF4nbv9FmCeUkTlV9GdgTLDH1b5uie7syb90SzEVrbN7HIpmWJeD |
| iOS | mxd5OQDk6es5LzOzRvidJNfXLUZS2oN3oUFeXPP8LpPrhx3UroJFduGEYIBOxkY1 |

An Authelia configuration example for OwnCloud clients can be found here: https://helgeklein.com/blog/owncloud-infinite-scale-with-openid-connect-authentication-for-home-networks/#sso-via-authelia-owncloud-openid-connect-authentication

Kanidm error log:
```
request [ 2.05ms | 55.76% / 100.00% ] method: POST | uri: /oauth2/authorise | version: HTTP/1.1
┝━ handle_oauth2_authorise [ 908µs | 18.04% / 44.24% ]
│  ┝━ validate_client_auth_info_to_ident [ 538µs | 26.20% ]
│  │  ┕━ ｉ [info]: A valid limited session value exists for this token | event_tag_id: 10
│  ┕━ � [warn]: Invalid OAuth2 client_id (xdXOt13JKxym1B1QcEncf2XDkLAexMBFwiT9j6EfhhHFJhs2KM9jbjTmf8JBXE69) Have you configured the OAuth2 resource server? | event_tag_id: 2
┝━ � [error]: Unable to authorise - Error ID: 0e094e48-40a0-499d-9721-927b8d1b7631 error: invalid_client_id | event_tag_id: 1
┕━ � [warn]:  | latency: 2.065619ms | status_code: 400 | kopid: "0e094e48-40a0-499d-9721-927b8d1b7631" | msg: "client error"
```

Kanidm configuration
``` sh
kanidm system oauth2 create-public ocis OCIS https://cloud.example.com
kanidm system oauth2 update-scope-map ocis idm_all_persons openid profile email
kanidm system oauth2 update-claim-map-join ocis roles array
kanidm system oauth2 update-claim-map ocis roles admins ocisAdmin
kanidm system oauth2 update-claim-map ocis roles idm_all_persons ocisUser
```

**Comment by yaleman** [comment]
The client id is [stored and compared in a case-insensitive manner](https://github.com/yaleman/kanidm/blob/be398bc49e488a05b84451512b31facffca8ae8f/server/lib/src/constants/schema.rs#L312), so lower-casing it should be irrelevant. 

What redirect url are you specifying for the "alternate" sources, you don't list it in your description, if they're not `https://` then they should be rejected currently.

**Comment by Firstyear** [comment]
It looks like they are `app://` or `oc://` urls. Also pretty nasty because these are protected clients it allows an admin to disable PKCE (over using a public client instead). Additionally it looks like they expect it all on one config too.

**Comment by pmeiyu** [comment]
Copied from OwnCloud

| Source | Redirect URI |
| -------- | ------------- |
| Desktop ≤ 2.8 | http://localhost |
| Desktop ≥ 2.9 | http://127.0.0.1 |
| Android | oc://android.owncloud.com |
| iOS | oc://ios.owncloud.com |

**Comment by Firstyear** [comment]
@yaleman I think the only reasonable way to proceed here will be to allow an allow list of extra redirect urls that *are not* http or https. Perhaps we even have to check them as a certain scheme. But we then use / allow them behind the "allow-localhost-redirect" toggle.

**Comment by Firstyear** [comment]
Or we make another toggle of "allow app redirects"

**Comment by yaleman** [comment]
I'd say a toggle for alternate URIs (not localhost/http/https, but parses as a URI) might suit this.

**Comment by Firstyear** [comment]
Would we want the URI to be specified precisely? Or just any redirect value that is a valid URI but excluding http/https locations? I'm trying to think of abuse patterns it could lead to here ....

**Comment by Firstyear** [comment]
Saying all this, owncloud won't work here anyway because they have a hardcoded client secret that appear to expect to be able to set on the oidc provider, which we obviously will never allow. So that might be a barrier to this anyway.

**Comment by yaleman** [comment]
> Would we want the URI to be specified precisely? Or just any redirect value that is a valid URI but excluding http/https locations? I'm trying to think of abuse patterns it could lead to here ....

The admin should be registering the URIs either way, which is up to them to abuse, and within the spec?

**Comment by Firstyear** [comment]
As in, they are allowed to register supplemental redirect URL's, if and only if they are a oc:// or app:// prefix? I think we should allow list uri schemes. 

But like I said, I think it's a bit pointless here because owncloud expects a static client secret, which we don't support.

**Comment by Firstyear** [comment]
Yeah fair. Okay, so the admin has to list the supplemental uris, and they can't be http/https. I think that's okay.

But like I said - it'll never work with owncloud because they aren't use a public oidc client, they are staticlly embedding a preshared client secret.

**Comment by pmeiyu** [comment]
> But like I said - it'll never work with owncloud because they aren't use a public oidc client, they are staticlly embedding a preshared client secret.

If this is the only obstacle, I may try to compile OwnCloud clients from source code and replace client secrets.

**Comment by yaleman** [comment]
Closing this as it'll be handled under #2818
