### ISSUE TITLE
Release 1.2.2 didn't update Cargo.lock

### ISSUE THREAD

**Issue by bjornfor** [kanidm/kanidm#2815]
### I did this
I tried to update from 1.2.1 to 1.2.2 in [nixpkgs](https://github.com/nixos/nixpkgs), but it fails to build because Cargo.lock is out-of-date compared to Cargo.toml.

### I expected the following
The files being in sync.

### This happened instead
The files not being in sync, breaking the default build setup in nixpkgs:

> [...build output...]
>  error: the lock file /build/source/Cargo.lock needs to be updated but --frozen was passed to prevent this
> If you want to try to generate the lock file without accessing the network, remove the --frozen flag and use --offline instead.
> [...failed...]

I tried building in a dev shell and noticed that cargo wants to update lots of "1.2.1" strings to "1.2.2" in Cargo.lock.

### Kanidm version details

1.2.2

**Comment by yaleman** [comment]
This should fixed by https://github.com/kanidm/kanidm/pull/2809 (which also bumps everything to 1.2.3)

**Comment by bjornfor** [comment]
Thanks!
