### ISSUE TITLE
Support multiple signed-in accounts

### ISSUE THREAD

**Issue by Kladki** [kanidm/kanidm#2824]
### Is your feature request related to a problem? Please describe

Sometimes A user might want to be able to be signed into multiple different accounts, such as for different access levels, [plural users](https://morethanone.info/), separate work and person accounts, etc.

### Describe the solution you'd like

The ability to be signed into multiple accounts in a single browser, while also having a prompt to select account and/or login to a new account when authorizing apps. 

### Describe alternatives you've considered

Using separate browsers / container tabs, but that can become tedious, especially on mobile.

**Comment by Firstyear** [comment]
There are a few use cases here but we aren't sure they fully apply to Kanidm.

Something to keep in mind is that we do want privilege separation to exist, so if a user can swap between account A and account B without re-authentication in between, then there is no separation, you may as well have assigned all the privileges to the single account. So to change between accounts, if we were to implement this, then we would enforce authentication for each switch.

With regard to access levels, I think that this could be done without whole separate accounts. You could have roles that you acquire and release in a session while retaining a single account presence. This way each role change could be accompanied by authentication challenges, else the session may as well just have full access all the time, which as above we don't want.

I can see why work vs personal matters in the context of say a google account or a github account, but in the places where Kanidm is currently used (businesses or homelabs etc), there isn't an overlap where a person has a separate work and personal instance, so I think this is less compelling for us. 

Currently I think it's unlikely we'll add fast account switching for the above reasons, we would rather have the account able to acquire and release privileges/roles as required. We would need to put in a fair bit of thought to make that happen.

**Comment by cosmoswafer** [comment]
How about using two different browsers, which is what I’m currently doing.

**Comment by Firstyear** [comment]
Closing today because we think this use case isn't supportable. We are happy to reconsider if there is a compelling use case for the feature.
