### ISSUE TITLE
Identity Brokering with Device Flow - Zero trust in console from multiple idps

### ISSUE THREAD

**Issue by ClientIco** [kanidm/kanidm#2861]
### Is your feature request related to a problem? Please describe

I am evaluating kanidm and are worried by the idea that that a subset of oidc v1 is said to be fully implemented as per RFC 6749. (https://datatracker.ietf.org/doc/html/rfc6749)

**I did see on the main documentation (https://kanidm.github.io/kanidm/stable/supported_features.html) that only these features are implemented:**
```
[RFC6749 OAuth 2.0 Authorisation Framework](https://www.rfc-editor.org/rfc/rfc6749)

    Authorisation Code Grant
    Client Credentials Grant
    RBAC scope mapping
```
and 
```
    [OpenID Connect Core 1.0](https://openid.net/specs/openid-connect-core-1_0.html)

    RBAC claim and scope mapping
    PII scope claim requests
    ES256 id_token signatures
```

This indicate to me that kanidm cannot be used as an IDP (Identity Provider) in other systems ? 
This indicate to me that kandim cannot utilize other IDP, meaning it cannot allow for example keycloak to be and identity provider ?

If this assessment is correct which I would like someone to concretely verify, the next part of my assessment was device flow to allow zero trust in console that might not be running sssd or the kanidm client utils.

The idea would have been to provider from total different company/identity provider access to certain linux resource via kanidm - In freeIPA Oauth2 creates a user that is aliased and allows the fronting OIDC(Keycloak/Authentic) application to broker in other idps -

Combined with device flow one would be able to potentially obtain zero trust configuration in IOT Devices or setups where you wouldn't necessarily have kanidm client utils configured yet

### Describe the solution you'd like

I am asking if the above is part of a roadmap eventually ? If so point me to it please. If there is away to help implement that or help test, point me to that as well - I am willing to delve into rust to get this features

### Additional context

There are a few but I am comparing FreeIPA with Zitadel as oidc + SSSD as a solution. And was very impressed with kanidm. 

----

Establish a trusted connection between your central identity provider (IdP) and third party identity providers.

By using a central identity brokering service you don't need to develop and establish a trust relationship between each application and each identity provider individually.

Depending on the countries laws maintaining customers information (making you and IDP) can be costly, offloading that by doing brokering with kanidm will greatly increase uptake of this :) And kanidm is written in rust :)

**Comment by Firstyear** [comment]
> ### Is your feature request related to a problem? Please describe
> 
> I am evaluating kanidm and are worried by the idea that that a subset of oidc v1 is said to be fully implemented as per RFC 6749. (https://datatracker.ietf.org/doc/html/rfc6749)
> 
> **I did see on the main documentation (https://kanidm.github.io/kanidm/stable/supported_features.html) that only these features are implemented:**
> 
> ```
> [RFC6749 OAuth 2.0 Authorisation Framework](https://www.rfc-editor.org/rfc/rfc6749)
> 
>     Authorisation Code Grant
>     Client Credentials Grant
>     RBAC scope mapping
> ```
> 
> and
> 
> ```
> [RFC6749 OAuth 2.0 Authorisation Framework](https://www.rfc-editor.org/rfc/rfc6749)
> 
>     Authorisation Code Grant
>     Client Credentials Grant
>     RBAC scope mapping
> ```
> 
> This indicate to me that kanidm cannot be used as an IDP (Identity Provider) in other systems ? This indicate to me that kandim cannot utilize other IDP, meaning it cannot allow for example keycloak to be and identity provider ?

No? There is a reason we have limited to these things. See https://www.rfc-editor.org/rfc/rfc6819 specifically https://www.rfc-editor.org/rfc/rfc6819#section-4.4.2 for example.

We choose a subset specifically because that is the *secure* subset of the specification that is also the most deployed and relevant to applications. 

If something is missing from a potential oauth2 client, then we'd like to know about it so we can assess if we either:

* Add the feature that is missing
* Deem that feature insecure and that it should not be added and the client should be notified to change. 


> ### Describe the solution you'd like
> 
> I am asking if the above is part of a roadmap eventually ? If so point me to it please. If there is away to help implement that or help test, point me to that as well - I am willing to delve into rust to get this features

Could you describe what is actually missing for your use case? 

> ### Describe alternatives you've considered
> ### Additional context
> 
> There are a few but I am comparing FreeIPA with Zitadel as oidc + SSSD as a solution. And was very impressed with kanidm.

Thanks!

**Comment by ClientIco** [comment]
RFC 8628: OAuth 2.0 Device Authorization Grant (https://datatracker.ietf.org/doc/html/rfc8628)

Device flow is missing - You mentioned no we don't allow kanidm to be an idp or to broker and IDP? 

So no federation with KANIDM ?

**Comment by yaleman** [comment]
> Can you explicitly confirm that I cannot broker in another idp into kanidm or otherway around.

You can't broker into Kanidm. I can't state what other systems are capable of.  

> 
> Are you also saying you will never consider adding that ?
>
> So no federation with KANIDM ?

Not currently available and not on the _current_ development roadmap as there are many other things to complete.

**Comment by yaleman** [comment]
> Device flow (OAuth 2.0 Device Authorization Grant) is missing currently.

Correct. It's not available, and there are issues here in the tracker discussing its availability, it is still under discussion last I checked.

**Comment by Firstyear** [comment]
> RFC 8628: OAuth 2.0 Device Authorization Grant (https://datatracker.ietf.org/doc/html/rfc8628)
> 
> Device flow (OAuth 2.0 Device Authorization Grant) is missing currently.
> 
>     * It is used in most IOT Devices that doesn't have browsers or device with restrained input and output

Yes we know. https://github.com/kanidm/kanidm/issues/1523

We want to implement it but we have had other priorities. 

> 
> 
> You mentioned no we don't allow kanidm to be an idp or to broker and IDP? Can you explicitly confirm that I cannot broker in another idp into kanidm or otherway around.
> 
> Are you also saying you will never consider adding that ?
> 
> So no federation with KANIDM ?

Federation and broker are .... confusing terms. They can change in meaning depending who you talk to.

If what you are asking is "can Kanidm trust and accept users from external OAuth providers" then today it's "no" but we are considering it as part of https://github.com/kanidm/kanidm/issues/149


> I suspect you might have missed that I am not referencing implicit grants.

I was saying that "sometimes we don't support things because they are insecure such as implicit grants". Your original request wasn't clear what you actually wanted to achieve, so I didn't know how to answer your questions. 

Without using the words "federation" or "broker", what are you trying to do? For example, "I want to allow users to authenticate to kanidm via oauth2 to github".

**Comment by Firstyear** [comment]
Closing as both device grant and trusts are on our todo-lists already, and there has been no expansion of this tickets scope.
