### ISSUE TITLE
Misleading api-token generate response when expiry passed but no permissions

### ISSUE THREAD

**Issue by tacerus** [kanidm/kanidm#2913]
### I did this

I try to generate a token with an expiry for an account I am not the manager of:

```
$ kanidm service-account api-token generate idle-account-status test 30m
```

### I expected the following

An indication that my access was denied - for example:

```
kanidm_cli::serviceaccount: Error generating service account api token -> Http(403, Some(AccessDenied), "xxx")
```

### This happened instead

An error message which makes it sound like my expiry argument is wrong, causing me to attempt multiple variants before trying it without the expiry argument and getting a useful message indicating that permissions are the problem:

```
$ kanidm service-account api-token generate idle-account-status test 30m
2024-07-17T10:53:30.589084Z ERROR kanidm_cli::serviceaccount: Error parsing expiry (input: "30m") -> ParseFromDescription(InvalidComponent("year"))
$ kanidm service-account api-token generate idle-account-status test 30
2024-07-17T10:53:36.250939Z ERROR kanidm_cli::serviceaccount: Error parsing expiry (input: "30") -> ParseFromDescription(InvalidComponent("year"))
$ kanidm service-account api-token generate idle-account-status test 1y
2024-07-17T10:53:48.356542Z ERROR kanidm_cli::serviceaccount: Error parsing expiry (input: "1y") -> ParseFromDescription(InvalidComponent("year"))
$ kanidm service-account api-token generate idle-account-status test
2024-07-17T10:53:50.259795Z ERROR kanidm_cli::serviceaccount: Error generating service account api token -> Http(403, Some(AccessDenied), "xxx")
# aha!
```

### Kanidm version details

- Output of `kanidm(d) version`: 1.2.2
- Are you running it in a container? If so, which image/tag?: no
- If not a container, how'd you install it: package
- Operating System / Version (On Unix please post the output of `uname -a`): openSUSE Leap 15.6

### Any other comments

The syntax of at least one of the expiry arguments I tried is correct, because trying it with an account I do have permissions for works:

```
$ kanidm service-account api-token generate test-service 30m
Success:
...
```

**Comment by tacerus** [comment]
Seems in the last attempt I actually made a token called "30m" so I think my issue description is rather wrong and I should just use correct expiry syntax as documented: https://kanidm.github.io/kanidm/stable/accounts/service_accounts.html?highlight=service-account#using-api-tokens-with-service-accounts.

**Comment by yaleman** [comment]
I was going to say, if you got a success with `30m` then... 😲

**Comment by Firstyear** [comment]
Yep, you created a token with a label of 30m, not an expiry of 30 minutes. :)
