### ISSUE TITLE
OpenAPI schema incomplete

### ISSUE THREAD

**Issue by SinnySupernova** [kanidm/kanidm#2923]
### I did this
Ran [openapi codegen](https://github.com/OpenAPITools/openapi-generator) on the `openapi.json` from `/docs/v1/openapi.json` from my kanidm server instance
### I expected the following
codegen works
### This happened instead
Error: `-attribute paths.'/v1/jwk/{key_id}'(get).responses.200.content.'application/json'.schema.#/components/schemas/Jwk is missing`
### Kanidm version details

- Output of `kanidm(d) version`:
`kanidmd 1.2.3`
- Are you running it in a container? If so, which image/tag?:
from `docker images`
`kanidm/server                             1.2.3     c5647fced234   3 weeks ago     670MB`
- If not a container, how'd you install it: N/A
- Operating System / Version (On Unix please post the output of `uname -a`): N/A

### Any other comments
I've seen the previous issues, but kanidm 1.2.3 was released after they have been resolved

**Comment by yaleman** [comment]
The schema's still very much in "I hope this works" mode but should be an easy fix for someone by stubbing it in like the other stubs that have been dded.

**Comment by SinnySupernova** [comment]
This is fixed on master (and in devel docker image)
https://github.com/kanidm/kanidm/blob/9a4ca18913821d2a513c4776dd516ee1abdd18e1/server/core/src/https/apidocs/mod.rs#L285
