### ISSUE TITLE
Connecting with browser fails with PR_END_OF_FILE_ERROR when running in docker container

### ISSUE THREAD

**Issue by andoks** [kanidm/kanidm#2970]
### I did this

(documenting issue for posterity, as I was unable to find anyone else having the issue)

I was trying to set up kanidm in a docker container, but when trying to open the web-UI in firefox on the host machine, it failed with a `PR_END_OF_FILE_ERROR`

![image](https://github.com/user-attachments/assets/02fcd1d9-b0f4-4254-8e22-8d9e252e4cce)

<details>
  <summary>server.toml</summary>

#   The webserver bind address. Requires TLS certificates.
#   If the port is set to 443 you may require the
#   NET_BIND_SERVICE capability.
#   Defaults to "127.0.0.1:8443"
bindaddress = "127.0.0.1:48443"
#
#   The read-only ldap server bind address. Requires
#   TLS certificates. If set to 636 you may require
#   the NET_BIND_SERVICE capability.
#   Defaults to "" (disabled)
# ldapbindaddress = "[::]:3636"
#
#   HTTPS requests can be reverse proxied by a loadbalancer.
#   To preserve the original IP of the caller, these systems
#   will often add a header such as "Forwarded" or
#   "X-Forwarded-For". If set to true, then this header is
#   respected as the "authoritative" source of the IP of the
#   connected client. If you are not using a load balancer
#   then you should leave this value as default.
#   Defaults to false
trust_x_forward_for = true 
#
#   The path to the kanidm database.
db_path = "/data/kanidm.db"
#
#   If you have a known filesystem, kanidm can tune the 
#   database page size to match. Valid choices are:
#   [zfs, other]
#   If you are unsure about this leave it as the default
#   (other). After changing this
#   value you must run a vacuum task.
#   - zfs:
#     * sets database pagesize to 64k. You must set
#       recordsize=64k on the zfs filesystem.
#   - other:
#     * sets database pagesize to 4k, matching most
#       filesystems block sizes.
db_fs_type = "other"
#
#   The number of entries to store in the in-memory cache.
#   Minimum value is 256. If unset
#   an automatic heuristic is used to scale this.
#   You should only adjust this value if you experience
#   memory pressure on your system.
# db_arc_size = 2048
#
#   TLS chain and key in pem format. Both must be present
tls_chain = "/data/cert/chain.pem"
tls_key = "/data/cert/key.pem"
#
#   The log level of the server. May be one of info, debug, trace
#
#   NOTE: this can be overridden by the environment variable
#   `KANIDM_LOG_LEVEL` at runtime
#   Defaults to "info"
log_level = "debug"
#
#   The DNS domain name of the server. This is used in a
#   number of security-critical contexts
#   such as webauthn, so it *must* match your DNS
#   hostname. It is used to create
#   security principal names such as `william@idm.example.com`
#   so that in a (future) trust configuration it is possible
#   to have unique Security Principal Names (spns) throughout
#   the topology.
#
#   ⚠️  WARNING ⚠️
#
#   Changing this value WILL break many types of registered
#   credentials for accounts including but not limited to
#   webauthn, oauth tokens, and more.
#   If you change this value you *must* run
#   `kanidmd domain rename` immediately after.
domain = "localhost"
#
#   The origin for webauthn. This is the url to the server,
#   with the port included if it is non-standard (any port
#   except 443). This must match or be a descendent of the
#   domain name you configure above. If these two items are
#   not consistent, the server WILL refuse to start!
#   origin = "https://idm.example.com"
origin = "https://localhost:48443"
#
[online_backup]
#   The path to the output folder for online backups
path = "/data/backups/"
#   The schedule to run online backups (see https://crontab.guru/)
#   every day at 22:00 UTC (default)
#schedule = "00 22 * * *"
#    four times a day at 3 minutes past the hour, every 6th hours
schedule = "03 */6 * * *"
#   We also support non standard cron syntax, with the following format:
#   sec  min   hour   day of month   month   day of week   year
#   (it's very similar to the standard cron syntax, it just allows to specify the seconds
#   at the beginning and the year at the end)
#   Number of backups to keep (default 7)
versions = 1

</details>

### I expected the following

The connection to work, really, but if not, some kind of message in the logs

### This happened instead

The error screen above

### Kanidm version details

- Output of `kanidm(d) version`: kanidm 1.3.2
- Are you running it in a container? If so, which image/tag?: Yes, `docker.io/kanidm/server:latest` (of course switching after testing)
- If not a container, how'd you install it: N/A
- Operating System / Version (On Unix please post the output of `uname -a`): Ubuntu (Linux  5.15.0-116-generic #126-Ubuntu SMP Mon Jul 1 10:14:24 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux)

### Any other comments

The reason seems to be that I had set bindaddress to 127.0.0.1:48443, while since it is running inside a container, I needed to set it to something like 0.0.0.0:48443

**Comment by andoks** [comment]
Closing this, as I assume I found the issue (wrong bindaddress), but wanted to document it for posterity (and in case anyone else has the issue later, and searches for it)

**Comment by yaleman** [comment]
I'm genuinely curious how TLS made this harder to troubleshoot? Telnet or any other attempted connection to the port would have shown connection refused and other network config checks (like docker port mappings etc) are unaffected by this also.

**Comment by andoks** [comment]
Maybe I came on a bit strong, but for me it was mostly about another configuration that was required and could be the source of the error. I don't argue in particular for it to be changed though, I understand the argument for it.

**Comment by yaleman** [comment]
Definitely a bad error from Firefox, in context - since you should have been just getting a connection refused kind of error not "this wasn't parseable TLS"

**Comment by Firstyear** [comment]
my guess is load balancer misconfiguration - it would have been TLS in TLS that caused the issue.

**Comment by andoks** [comment]
> my guess is load balancer misconfiguration - it would have been TLS in TLS that caused the issue.

The only difference between working configuration was that I set listenaddress to 0:0:0.0:8080 instead of 127.0.0.1:8080. I did not change anything in the docker-compose configuration. I think yaleman is correct in that I was probably partly confused by the tls error in firefox.

**Comment by Firstyear** [comment]
All good though, glad you got it sorted in the end :)
