### ISSUE TITLE
Group mail address not exposed via LDAP

### ISSUE THREAD

**Issue by jceb** [kanidm/kanidm#2972]
### I did this

I configured a group email address via `kanidm group set-mail <name> <mail1> <mail2> ...`. Then I performed an `ldapsearch` and listed all available attributes by passing `'*' '+'`.

### I expected the following

See various `mail` attributes.
I do see the mail attributes when I retrieve the group object via `kanidm` CLI.

### This happened instead

Saw just the regular attributes, `dn`, `class`, ....

### Kanidm version details

- Output of `kanidm(d) version`: `1.2.3`
- Are you running it in a container? If so, which image/tag?: yes, custom built via the nixos package.
- Operating System / Version (On Unix please post the output of `uname -a`): Linux torch 6.8.12 #1-NixOS SMP PREEMPT_DYNAMIC Thu May 30 07:49:53 UTC 2024 x86_64 GNU/Linux

### Any other comments

Related to #1299 - sorry, it's taking me forever to investigate the functionality.

Here's the regular log output:

```
1a01ec1d-4804-41a8-9a09-f523ba036da5 INFO     ldap-request [ 395µs | 5.24% / 100.00% ] uat: None | protomsg: LdapMsg { msgid: 1, op: BindRequest(LdapBindRequest { dn: "dn=token", cred: LdapBindCred::Simple }), ctrl: [] }
1a01ec1d-4804-41a8-9a09-f523ba036da5 INFO     ┝━ ｉ [info]: LDAP client | event_tag_id: 10 | client_ip: ::ffff:127.0.0.1 | client_port: 40012
1a01ec1d-4804-41a8-9a09-f523ba036da5 INFO     ┕━ handle_ldaprequest [ 374µs | 94.76% ]
1a01ec1d-4804-41a8-9a09-f523ba036da5 INFO        ┝━ ｉ [info]: Attempt LDAP Bind for dn=token | event_tag_id: 10
1a01ec1d-4804-41a8-9a09-f523ba036da5 INFO        ┕━ ｉ [info]: ✅ LDAP Bind success for dn=token -> ApiToken | event_tag_id: 10
d3209fcf-0f50-439f-91c0-31d60eb72b50 INFO     ldap-request [ 216µs | 4.15% / 100.00% ] uat: Some(LdapBoundToken { spn: "user@yyy.xxx.com", session_id: 435c7831-8823-48e6-b7ee-da3e7d5e7238, effective_session: ApiToken(ApiToken { account_id: 7c37f435-9a9d-41a6-a9e0-283637c9a803, token_id: 435c7831-8823-48e6-b7ee-da3e7d5e7238, label: "ldap access", expiry: None, issued_at: 2022-12-23 14:08:20.0 +00:00:00, purpose: ReadOnly }) }) | protomsg: LdapMsg { msgid: 2, op: SearchRequest(LdapSearchRequest { base: "dc=yyy,dc=xxx,dc=com", scope: Subtree, aliases: Never, sizelimit: 0, timelimit: 0, typesonly: false, filter: Equality("name", "xxxxx"), attrs: ["*", "+"] }), ctrl: [] }
d3209fcf-0f50-439f-91c0-31d60eb72b50 INFO     ┝━ ｉ [info]: LDAP client | event_tag_id: 10 | client_ip: ::ffff:127.0.0.1 | client_port: 40012
d3209fcf-0f50-439f-91c0-31d60eb72b50 INFO     ┕━ handle_ldaprequest [ 207µs | 95.85% ]
d3209fcf-0f50-439f-91c0-31d60eb72b50 INFO        ┝━ ｉ [info]: Attempt LDAP Search for user@yyy.xxx.com | event_tag_id: 3
d3209fcf-0f50-439f-91c0-31d60eb72b50 INFO        ┝━ ｉ [info]: LDAP Search Request LDAP Attrs | event_tag_id: 3 | attr: ["cn", "email", "emailaddress", "dn", "emailalternative", "emailprimary", "entrydn", "entryuuid", "keys", "mail;alternative", "mail;primary", "objectclass", "sshpublickey", "uidnumber", "uid", "gecos"]
d3209fcf-0f50-439f-91c0-31d60eb72b50 INFO        ┝━ ｉ [info]: LDAP Search Request Mapped Attrs | event_tag_id: 3 | attr: None
d3209fcf-0f50-439f-91c0-31d60eb72b50 INFO        ┝━ ｉ [info]: LDAP Search Filter | event_tag_id: 3 | filter: And([Equality("name", "xxxxx"), Not(Or([Equality("class", "classtype"), Equality("class", "attributetype"), Equality("class", "access_control_profile")]))])
d3209fcf-0f50-439f-91c0-31d60eb72b50 INFO        ┝━ ｉ [info]: A valid session value exists for this token | event_tag_id: 10
d3209fcf-0f50-439f-91c0-31d60eb72b50 INFO        ┝━ ｉ [info]: search | event_tag_id: 10 | initiator: User( user@yyy.xxx.com, 7c37f435-9a9d-41a6-a9e0-283637c9a803 ) (435c7831-8823-48e6-b7ee-da3e7d5e7238, read only)
d3209fcf-0f50-439f-91c0-31d60eb72b50 INFO        ┕━ ｉ [info]: LDAP Search Success -> number of entries | event_tag_id: 3 | nentries: 2
0f333a86-b8b9-4b76-b1cf-8361b3c19d58 INFO     ldap-request [ 14.1µs | 76.59% / 100.00% ] uat: Some(LdapBoundToken { spn: "user@yyy.xxx.com", session_id: 435c7831-8823-48e6-b7ee-da3e7d5e7238, effective_session: ApiToken(ApiToken { account_id: 7c37f435-9a9d-41a6-a9e0-283637c9a803, token_id: 435c7831-8823-48e6-b7ee-da3e7d5e7238, label: "ldap access", expiry: None, issued_at: 2022-12-23 14:08:20.0 +00:00:00, purpose: ReadOnly }) }) | protomsg: LdapMsg { msgid: 3, op: UnbindRequest, ctrl: [] }
0f333a86-b8b9-4b76-b1cf-8361b3c19d58 INFO     ┝━ ｉ [info]: LDAP client | event_tag_id: 10 | client_ip: ::ffff:127.0.0.1 | client_port: 40012
0f333a86-b8b9-4b76-b1cf-8361b3c19d58 INFO     ┕━ handle_ldaprequest [ 3.29µs | 23.41% ]

```

**Comment by jceb** [comment]
While playing around with postfix and LDAP I learned one more thing that's relevant for the implementation of group mail attributes: the name of the group mail attribute MUST be different from the person's mail attribute, because it would otherwise be gathered into the list of results!

Here's an example of a working postfix configuration (stored in `/etc/postfix/group-test.cf`):

```
bind                     = yes
bind_dn                  = dn= token
bind_pw                  = XXXX
query_filter             = (&(class=group)(groupmail=%s))
result_attribute         = mail;primary
special_result_attribute = member
search_base              = dc=yyy,dc=xxx,dc=com
server_host              = ldaps://localhost:3636
start_tls                = no
version                  = 3
```

If the LDAP group mail attribute was called `groupmail` recipients would be looked up by querying LDAP to find the group with the matching `groupmail` attribute, then take the special `member` attribute and expand the DN into another result. Finally, the regular `result_attribute` would be taken from all results including (!!!) the group.

The following command will use the configuration return the primary mail addresses of all group members: `postmap -q <groupmail-address> ldap:/etc/postfix/group-test.cf`

**Comment by Firstyear** [comment]
I'm a bit confused here @jceb - we don't have a "groupmail" attribute - you can just assign the attribute "mail" to a group. So a search on groupmail=%s will always fail because it doesn't exist.

Following that, mail needs to be unique between groups and users so it sohuldn't be possible for a group to duplicate a mail with users.

Is there something I'm missing here?

**Comment by jceb** [comment]
Yes, the mask attribute needs to be unique between groups and users. I picked the `groupmail` attribute as an example since I didn't want to use any of the existing mail attributes because they would be the same for users.

**Comment by Firstyear** [comment]
Why does it need to be unique? Is that a limitation of the mail service?

**Comment by jceb** [comment]
The attribute name must be unique for groups, because Postfix gathers the results from all objects that were found, group + expanded users. If the existing `mail` attribute would be used, the mail address is the group would be part of the result instead of being expanded into the users mail addresses and the removed from the result.

**Comment by Firstyear** [comment]
Well that certainly complicates things.

Is there a way to configure postfix to *avoid* that behaviour? 

I'm reading https://www.postfix.org/LDAP_README.html#example_group  and mail is the attribute used on both groups and users, and it seems to work as you expect?

**Comment by jceb** [comment]
Ah, you're right! 😅 In https://www.postfix.org/ldap_table.5.html the `leaf_result_attribute` option allows to just take an attribute from the user objects. As explained in the docs, the `result_attribute` option must be set to an empty value to ensure that the group's mail address isn't included.

**Comment by Firstyear** [comment]
Yay! Does that solve your problem here then?

**Comment by jceb** [comment]
Well, yes and no - yes, the mail attribute can be the same as for person objects - no, the mail attribute isn't exposed for groups via LDAP :-)

**Comment by jceb** [comment]
Yesterday, I updated to kanidm version `1.3.2` and the issue remains that the mail attribute isn't exposed for groups.

**Comment by Firstyear** [comment]
That's okay, it should be an easy fix :)

**Comment by Firstyear** [comment]
How urgently do you need this feature btw?

**Comment by jceb** [comment]
It's not urgent. I've lived without it for some time now 😃

**Comment by Firstyear** [comment]
Would you be willing to run and test a dev build? That way we can check that it works for your use case :)

**Comment by jceb** [comment]
Yes, I can do that.

**Comment by jceb** [comment]
@Firstyear I tried version 1.3.3 without success :-/

Here's what I tried:

1. I retrieved my group and it has email addresses:

```
kanidm group get my-group
---
class: group
class: object
mail: my-group@example.com
mail: my-group@e-jc.de
member: a@idm.example.com
member: b@idm.example.com
name: my-group
spn: my-group@idm.example.com
uuid: 9646dad2-acfe-4aa9-b263-a03b50487c04
```

2. I ran ldapsearch and it returned no email attribute. I also requested the mail attribute directly without success either:

```
ldapsearch -D dn=token -y token '(name=my-group)' -LLL '*' '+'

dn: spn=my-group@idm.example.com,dc=idm,dc=example,dc=com
class: group
class: object
member: spn=a@idm.example.com,dc=idm,dc=example,dc=com
member: spn=b@idm.example.com,dc=idm,dc=example,dc=com
name: my-group
spn: my-group@idm.example.com
uuid: 9646dad2-acfe-4aa9-b263-a03b50487c04
cn: my-group
dn: spn=my-group@idm.example.com,dc=idm,dc=example,dc=com
entrydn: spn=my-group@idm.example.com,dc=idm,dc=example,dc=com
entryuuid: 9646dad2-acfe-4aa9-b263-a03b50487c04
objectclass: group
objectclass: object
uid: my-group
```

Here's the kanidm log output:

```
kanidm 65b551b9-3a30-427b-9d34-ce0fd1c6df94 INFO     ldap-request [ 542µs | 4.28% / 100.00% ] uat: None | protomsg: LdapMsg { msgid: 1, op: BindRequest(LdapBindRequest { dn: "dn=token", cred: LdapBindCred::Simple }), ctrl: ] }
kanidm 65b551b9-3a30-427b-9d34-ce0fd1c6df94 INFO     ┝━ ｉ [info]: LDAP client | event_tag_id: 10 | client_ip: ::ffff:127.0.0.1 | client_port: 36624
kanidm 65b551b9-3a30-427b-9d34-ce0fd1c6df94 INFO     ┕━ handle_ldaprequest [ 518µs | 95.72% ]
kanidm 65b551b9-3a30-427b-9d34-ce0fd1c6df94 INFO        ┝━ ｉ [info]: Attempt LDAP Bind for dn=token | event_tag_id: 10
kanidm 65b551b9-3a30-427b-9d34-ce0fd1c6df94 INFO        ┕━ ｉ [info]: ✅ LDAP Bind success for dn=token -> ApiToken | event_tag_id: 10
kanidm 41155563-eace-4c1b-873f-99886f37f30a INFO     ldap-request [ 419µs | 5.49% / 100.00% ] uat: Some(LdapBoundToken { spn: "kanidm@idm.example.com", session_id: 435c7831-8823-48e6-b7ee-da3e7d5e7238, effective_session: ApiToken(ApiToken { account_id: 7c37f435-9a9d-41a6-a9e0-283637c9a803, token_id: 435c7831-8823-48e6-b7ee-da3e7d5e7238, label: "ldap access", expiry: None, issued_at: 2022-12-23 14:08:20.0 +00:00:00, purpose: ReadOnly }) }) | protomsg: LdapMsg { msgid: 2, op: SearchRequest(LdapSearchRequest { base: "dc=idm,dc=example,dc=com", scope: Subtree, aliases: Never, sizelimit: 0, timelimit: 0, typesonly: false, filter: Equality("name", "my-group-name"), attrs: ["*", "+"] }), ctrl: ] }
kanidm 41155563-eace-4c1b-873f-99886f37f30a INFO     ┝━ ｉ [info]: LDAP client | event_tag_id: 10 | client_ip: ::ffff:127.0.0.1 | client_port: 36624
kanidm 41155563-eace-4c1b-873f-99886f37f30a INFO     ┕━ handle_ldaprequest [ 396µs | 94.51% ]
kanidm 41155563-eace-4c1b-873f-99886f37f30a INFO        ┝━ ｉ [info]: Attempt LDAP Search for kanidm@idm.example.com | event_tag_id: 3
kanidm 41155563-eace-4c1b-873f-99886f37f30a INFO        ┝━ ｉ [info]: LDAP Search Request LDAP Attrs | event_tag_id: 3 | attr: ["cn", "email", "emailaddress", "dn", "emailalternative", "emailprimary", "entrydn", "entryuuid", "keys", "mail;alternative", "mail;primary", "objectclass", "sshpublickey", "uidnumber", "uid", "gecos"]
kanidm 41155563-eace-4c1b-873f-99886f37f30a INFO        ┝━ ｉ [info]: LDAP Search Request Mapped Attrs | event_tag_id: 3 | attr: None
kanidm 41155563-eace-4c1b-873f-99886f37f30a INFO        ┝━ ｉ [info]: LDAP Search Filter | event_tag_id: 3 | filter: And([Equality("name", "my-group-name"), Not(Or([Equality("class", "classtype"), Equality("class", "attributetype"), Equality("class", "access_control_profile")]))])
kanidm 41155563-eace-4c1b-873f-99886f37f30a INFO        ┝━ ｉ [info]: A valid session value exists for this token | event_tag_id: 10
kanidm 41155563-eace-4c1b-873f-99886f37f30a INFO        ┝━ ｉ [info]: search | event_tag_id: 10 | initiator: User( kanidm@idm.example.com, 7c37f435-9a9d-41a6-a9e0-283637c9a803 ) (435c7831-8823-48e6-b7ee-da3e7d5e7238, read only)
kanidm 41155563-eace-4c1b-873f-99886f37f30a INFO        ┕━ ｉ [info]: LDAP Search Success -> number of entries | event_tag_id: 3 | nentries: 2
kanidm 88d229b0-27e8-4604-be2d-7a66489c47e6 INFO     ldap-request [ 27.5µs | 77.84% / 100.00% ] uat: Some(LdapBoundToken { spn: "kanidm@idm.example.com", session_id: 435c7831-8823-48e6-b7ee-da3e7d5e7238, effective_session: ApiToken(ApiToken { account_id: 7c37f435-9a9d-41a6-a9e0-283637c9a803, token_id: 435c7831-8823-48e6-b7ee-da3e7d5e7238, label: "ldap access", expiry: None, issued_at: 2022-12-23 14:08:20.0 +00:00:00, purpose: ReadOnly }) }) | protomsg: LdapMsg { msgid: 3, op: UnbindRequest, ctrl: ] }
kanidm 88d229b0-27e8-4604-be2d-7a66489c47e6 INFO     ┝━ ｉ [info]: LDAP client | event_tag_id: 10 | client_ip: ::ffff:127.0.0.1 | client_port: 36624
kanidm 88d229b0-27e8-4604-be2d-7a66489c47e6 INFO     ┕━ handle_ldaprequest [ 6.10µs | 22.16% ]
```

**Comment by Firstyear** [comment]
It's not in 1.3.3, it's in the devel branch.

**Comment by jceb** [comment]
Great, I tested the functionality in version 1.4.0 and it works well. For reference, here's the configuration I used:

1. Create service account `xyz` and generate access token to connect to LDAP.
2. Add service account to group `idm_mail_servers` so that the mail attribute can be read. More details are provided here: https://kanidm.github.io/kanidm/stable/access_control/intro.html
3. Add the following setting to postfix's `main.cf`: `virtual_alias_maps = ldap:/etc/postfix/ldap-groups.cf`
4. Put the following contents in `/etc/postfix/ldap-groups.cf`:

```pf
bind             = yes
# Service account: xyz
bind_dn          = dn=token
bind_pw          = xxxxxx
query_filter     = (&(class=group)(mail=%s))
# leaf_result_attribute is important so that the attribute isn't gathered from the group, which would be the case for
# the regular result_attribute setting. Explicitly set result_attribute to an empty value so no attribute from the group is used.
result_attribute =
leaf_result_attribute = mail;primary
special_result_attribute = member
search_base      = dc=idm,dc=example,dc=com
server_host      = ldaps://kanidm-svc.kanidm.svc.cluster.local:3636
start_tls        = no
version          = 3
```

5. Create a group and assign it an email address and members who have email addresses.
6. Send an email to the group's mail address, it will be delivered to the email addresses of its members.

**Comment by Firstyear** [comment]
Fantastic! I'm so glad it works for you @jceb and I really appreciate you being a long time supporter/user of the project. You know where we are if you have any other issues :)

**Comment by jceb** [comment]
Thank you for your kind words!

**Comment by helmut72** [comment]
Thanks for this issue. Is it also possible to use `idm_account_mail_read` instead of `idm_mail_servers`?

**Comment by Firstyear** [comment]
@helmut72 "it depends". idm_mail_servers specifically is setup to allow "reading of attributes that a mail server needs to function". idm_account_mail_read is for  "a person or service account to be able to read mail only".

So is the account in question a mail server service account? Or a user? That affects which you choose.

**Comment by helmut72** [comment]
@Firstyear I want to use Kanidm instead of Samba4 (LDAP only) for my mailserver stack Postfix + Dovecot to authenticate my user (with username + password) for IMAP+SMTP and also for Postfix to get attributes. This means I need to add the service account to "idm_mail_servers"?

Am I right I need to set a unix password that authenticate users for IMAP+SMTP via LDAP for now?
https://github.com/kanidm/kanidm/issues/2027#issuecomment-1710867074

... until this is implemented?
https://github.com/kanidm/kanidm/issues/41

What really confuse me is how to create a specific mail app?
https://github.com/kanidm/kanidm/blob/009200375f8a2d564164afb0b266819e32b5945a/book/src/developers/designs/application_passwords.md?plain=1#L26

_"The administrator configures two applications on their Kanidm instance. One is "mail" for a generic
SMTP+IMAP service."_

**Comment by jceb** [comment]
@helmut72 did you see at the steps outline in this comment: https://github.com/kanidm/kanidm/issues/2972#issuecomment-2453478149 - Yes, you need to add the service account to `idm_mail_servers`.

Yes, you also need to set a unix password on the user accounts so they can be authenticated via LDAP.

I'm not familiar with application passwords, yet. Not sure if you actually need to have them. I'm using the latest kanidm version without application passwords and instead with a simple unix password.

My understanding is that you COULD create an application via a custom command. I'm very interested in this feature, however, I'm not sure whether it has been implemented, yet. The design document is in place, however it's not even properly included in the latest document https://kanidm.github.io/kanidm/master/?search=application%20password

**Comment by helmut72** [comment]
Thank you all for these information. I think I don't have any blocker or question for now. Now I need to setup a test instance of my mail server. Even if it's a homelab, the running one is productive.

**Comment by Firstyear** [comment]
@helmut72 Great to hear it. 

@jceb Its waiting on me to finish up testing it and writing the CLI for it. I've been unwell lately so haven't had the time or energy :(

**Comment by jceb** [comment]
@Firstyear now worries. Thank you for the great work and I hope you'll get better in a short while. Have a blessed new year!

**Comment by Firstyear** [comment]
You too mate :)
