### ISSUE TITLE
Last release missing from GitHub releases and bad date in release notes

### ISSUE THREAD

**Issue by pando85** [kanidm/kanidm#2989]
### I did this
Read the notification about a new release from Kanidm (1.3.3)

### I expected the following
Dates are correct and the release is published on GitHub.

### This happened instead
The release date looks like a copy-paste from the previous one (1.3.2) 

### Any other comments
I don't know how your release workflow is. I just know how I used to manage this kind of things and I think that automating more parts of the process could help.

I just can speak from my experience which can be different from your perspective and it is opinionated but I want to share it with you in case it helps.

 - Format the commits following a structure. I ensure that every commit merged to master passes the [commitlint](https://github.com/conventional-changelog/commitlint) check.
 - Create a CHANGELOG.md with all the commits. This is done by  [git cliff](https://git-cliff.org/) automatically from commits but you can always tune it before uploading the file in your release commit.
 - Automatically release the version: if a new version is detected in the changelog this will tag it in your main branch and from that tag, release all artifacts and publish the version in GitHub or whatever places you need to release.
 
 I hope that some of those steps could help you to fix some of the problems with artifacts and release notes not being correctly published.
 
 I want to clarify again that I don't know the current process but that's what I observed as a user of the project. 
 
 Kind regards and keep going with this amazing project!

**Comment by Firstyear** [comment]
Opps! I didn't mark 1.3.3 as latest. Fixed now :) Thank you! 

I think some more automation would certainly help here, yes :)

**Comment by pando85** [comment]
If you need some kind of help, just define the requirements and I could prepare a PR.

**Comment by Firstyear** [comment]
@pando85 I'll leave it to @yaleman to discuss more, they are the github person more than me :)

**Comment by yaleman** [comment]
Yeah, it'd be good to see how other orgs do it, because making things just work is nice... then again it can also be a pain to maintain the automation 😡

**Comment by pando85** [comment]
I cannot speak through orgs because this is usually a couple process to their infrastructure and tools.

For GitHub related projects I look for famous open source similar tools. I cannot tell you right now good examples because there've been some time since I don't look for it because I'm really happy with my process.

From my perspective, maintainability in these small but useful tips for me that I mentioned are pretty simple. The tools used to be pretty stable and I use renovate to keep them upgraded. You can set up a conservative upgrade policy and good tests as you already have.

**Comment by yaleman** [comment]
Can you share your configs or a suggested way of setting it up, or your current process? Dependabot's doing the update-packages job so that's already sorted, but it'd save us reinventing the wheel since you seem to have it working for you?

**Comment by pando85** [comment]
I'm basing the automation on the CHANGELOG. 

From the CHANGELOG I get the body for the automatic release publish. Also, I auto tag which triggers the release workflow checking CHANGELOG changes.

And for making everything easier for me I auto-generate CHANGELOG based on commits.

I'm using currently this workflow in multiple projects (~4) that are on my GitHub but if you want to check one it could be https://github.com/rash-sh/rash , for example.
