### ISSUE TITLE
docker reports unhealthy --> CRITICAL: Connection failed: error sending request for url (https://[::]:8443/status)

### ISSUE THREAD

**Issue by svde** [kanidm/kanidm#3002]
### I did this

Docker reports container is unhealthy. Everything seems to work fine.

📜 Using config file: "/data/server.toml" 00000000-0000-0000-0000-000000000000 ERROR 🚨 [error]: CRITICAL: Connection failed: error sending request for url (https://[::]:8443/status) Logging pipeline completed shutdown

### I expected the following

docker reporting the container is healthy.

### Kanidm version details

- Output of `kanidm(d) version`:  1.3.3
- Are you running it in a container? If so, which image/tag?: kanidm/server:latest
- If not a container, how'd you install it:
- Operating System / Version (On Unix please post the output of `uname -a`):

### Any other comments

server.toml contains:
bindaddress = "[::]:8443"

**Comment by yaleman** [comment]
Actually, testing this in docker, I can't reproduce the issue...

- `bindaddress = "[::]:8443"` set in server.toml
- startup shows `Starting kanidm with configuration: address: [::]:8443,...`

exec'ing the healthcheck command (with all the startup warnings cut out)

```
docker exec -it kanidmd kanidmd healthcheck -c /data/server.toml
📜 Using config file: "/data/server.toml"
00000000-0000-0000-0000-000000000000 INFO     ｉ [info]: OK
Logging pipeline completed shutdown
```

and the status of the container shows healthy:

```
 docker ps -a | grep kanidmd
65e51d0829ae   kanidm/server:1.3.3                      "/sbin/kanidmd serve…"   16 seconds ago   Up 12 seconds (healthy)    3636/tcp, 0.0.0.0:8443->8443/tcp, :::8443->8443/tcp   kanidmd
```

Container was started with a modified `insecure_server.toml` (only changing bindaddress) from the repo's examples dir...

```bash
$ mkdir /tmp/kanidm
# make the certs
$ docker run --rm -it \
  --mount "type=bind,src=./examples/insecure_server.toml,target=/data/server.toml" \
  --mount "type=bind,src=/tmp/kanidm,target=/tmp/kanidm" \
  --name kanidmd \
  -p '8443:8443' \
  kanidm/server:1.3.3 kanidmd cert-generate
# start the server
$ docker run --rm -it \
  --mount "type=bind,src=./examples/insecure_server.toml,target=/data/server.toml" \
  --mount "type=bind,src=/tmp/kanidm,target=/tmp/kanidm" \
  --name kanidmd \
  -p '8443:8443' \
  kanidm/server:1.3.3
```

**Comment by Firstyear** [comment]
I think some platforms resolve `::` to `::1` but not all?

**Comment by svde** [comment]
I have this Port configuration :
0.0.0.0:636 --> 3636/tcp
:::636 --> 3636/tcp
0.0.0.0:8093 --> 8443/tcp
:::8093 --> 8443/tcp

Platform = am64, fedora 40, moby-engine-24.0.5-4.fc40.x86_64

**Comment by yaleman** [comment]
Port mapping configuration shouldn't matter, since it's connecting within the container itself.
