### ISSUE TITLE
Error after upgrading from 1.3.1 > 1.3.3

### ISSUE THREAD

**Issue by dan-is-not-the-man** [kanidm/kanidm#3003]
As discussed on the matrix room, see attached logs. The issue only affect the apps when you directly login into kanidm instance. When you login through the app that uses kanidm for 0auth it works or if you use ssh key distrubtion it works.

OS-Rocky linux
docker version - centos  27.1.2

![test11](https://github.com/user-attachments/assets/4034d162-deb3-4bd7-a608-c8cfac4e3d83)

1.2.3> 1.3.0 = worked 

https://paste.sethforprivacy.com/?9b17ccf533151dbf#EiWSBgAvSCn41ncACS2aejupQjQmJgVLj9NYDavw4qhk

1.3.0 > 1.3.1 = worked

https://paste.sethforprivacy.com/?e8884ba660a177b1#C4McSmB7GLu3UMfiGFBK2vw62tcFxgw4UwL2HQtoZSW2

1.3.1 > 1.3.3= :disappointed:

https://paste.sethforprivacy.com/?b5b9a216d9798f1f#3DqUXKDevjn9hUCzu8MEBkS9f1himiaWX9ca2PdaK5bG

Solution: Reindex to fix issue

```
docker run --rm -i -t -v /root/kanidm-server/data:/data \
    kanidm/server:1.3.3 /sbin/kanidmd database reindex -c /data/server.toml
```

**Comment by Firstyear** [comment]
Pastes have all expired ;_;

**Comment by Firstyear** [comment]
Given that a reindex resolved, we haven't had other reports, and we are about to release 1.4 I think we should close this. If you still have this issue, we'll reopen.
