### ISSUE TITLE
Javascript errors after server-side update blocking login. Fixed after cache invalidating

### ISSUE THREAD

**Issue by joostrijneveld** [kanidm/kanidm#3010]
### I did this

I upgraded from 1.2.3 to 1.3.2 following the upgrade flow described [here](https://kanidm.github.io/kanidm/stable/server_updates.html)

### I expected the following

For users that have previously visited an application behind version 1.2.3 to be able to have their session stored, or at least be able to log back in again after the upgrade.

### This happened instead

Users are stuck on the "Kanidm is loading, please wait..." screen. Their Javascript console shows the following error:

```
wasmloader_login_flows.js:6 Uncaught (in promise) LinkError: WebAssembly.instantiate(): Import #164 module="wbg" function="__wbindgen_closure_wrapper1416" error: function import requires a callable
await (async)  
(anonymous) @ wasmloader_login_flows.js:7
```

It appears the browser is using outdated Javascript files; network traffic shows that they're served a 304 (Request not modified). Disabling the local browser cache seems to resolve the issue, and shows them a login screen.

### Kanidm version details

- Output of kanidm(d) version: 1.3.2
- Are you running it in a container? If so, which image/tag?: yes, :latest (version 1.3.2)
- If not a container, how'd you install it:
- Operating System / Version (On Unix please post the output of uname -a): 6.10.3-arch1-2 on the docker host

### Any other comments

I previously created #3009 where I wrongly diagnosed this to be related to cookies.

**Comment by joostrijneveld** [comment]
As soon as I get the next report from a user that runs into this, I intend to `touch` all Javascript files in the docker container to see if I can properly invalidate the cache like that.

Perhaps this is an issue that can be fixed by cache busting the Javascript files (e.g., by appending the kanidm version number to the resource paths in the `<script>` tags)

**Comment by joostrijneveld** [comment]
@yaleman I now realise my edit of my previous comment may have crossed your commits, so I figured I'd post it as a separate comment: I think this is also a problem for JS files that area loaded indirectly, such as in the following snippet: https://github.com/kanidm/kanidm/blob/3eae7be0bb3697f4a55081a14cee60d6adfd9ddf/server/web_ui/pkg/wasmloader_login_flows.js#L1-L7

This SO thread offers a bunch of options, it seems: https://stackoverflow.com/questions/47675549/how-do-i-cache-bust-imported-modules-in-es6

**Comment by yaleman** [comment]
Yeah, that turns into a right pain in the arse, sigh.

**Comment by yaleman** [comment]
Given we're completely rebuilding a lot of the web UI (replacing the existing WASM mess with another implementation), the fix for the static assets should wait for after that's finished, there's no point double-implementing it.
