### ISSUE TITLE
Kanidm platform hardening tool

### ISSUE THREAD

**Issue by Firstyear** [kanidm/kanidm#303]
There are many common configuration issues on a linux system. We should have a tool that can detect and report these. IE targetpw in sudo, or non root:root on /etc/passwd, etc.

**Comment by Firstyear** [comment]
Im not sure this really still falls in scope, maybe we can remove this item? @yaleman ?

**Comment by yaleman** [comment]
Yeah, this suggestion could be a whole company in itself TBH. I'd say close it as out of scope for Kanidm - we already provide guidance for the minimum possible configs and will update that guidance as better ideas come along.
