### ISSUE TITLE
SCIM: Feature Request: make parse function public

### ISSUE THREAD

**Issue by colstrom** [kanidm/kanidm#3035]
Hi!

First off, thanks for making this crate! I appreciate the work that went into it!

If you're open to feature requests, I have a few small ones. I didn't see any specific guidance in the [Developer Guide](https://kanidm.github.io/kanidm/master/developers/index.html) on how to submit these, so if multiple issues is preferred, just let me know, and I can break it up accordingly. They're grouped here because they all seem like (relatively) small things.

1. Would it be possible to make the `scim_proto::filters::scimfilter::parse()` function public?
2. Since the crate already depends on `serde`, can `ScimFilter` implement `Serialize` and `Deserialize`?
  - I'm not sure how complicated this is with recursive types, so... please and thank you, if it's not too much work? 🙇 
3. Could `ScimFilter` implement `FromStr`? I assume this would be just calling `parse()` or something along those lines.
  - This would make it work out of the box with `clap::Arg`. Without this, it's still simple enough to just pass the `parse` function from (1) to `clap::Arg::value_parser`, so this is just a minor convenience, but it seems intuitive (to me) that `FromStr` and `parse` would... do the same thing... 🤷‍♀️ 

The goal in all of these is to make it easier for other crates to use this one.

If it helps illustrate things better, in my context, I've got an app that's taking SCIM filters in a CLI app (with `clap`) and including them in an HTTP request, and I'd just like to validate them before sending them, so that I can provide nice error messages when there are problems, rather than relying on the remote service to return a decent error message. 😉 

If there's any other information I can provide, please let me know.

Thanks!

**Comment by yaleman** [comment]
I've moved this across for tracking
