### ISSUE TITLE
Add introspection_endpoint to OIDC Discovery Endpoint

### ISSUE THREAD

**Issue by xzzpig** [kanidm/kanidm#3042]
### Is your feature request related to a problem? Please describe

I am currently using [oidc authentication](https://plugins.traefik.io/plugins/66b63d12d29fd1c421b503f5/oidc-authentication) to add OIDC support to my traefik, which requires the use of introspection_endpoint in OIDC Discovery Endpoint. However, this field is missing in Kanidm's OIDC Discovery Endpoint(https://idm.example.com/oauth2/openid/:client_id:/.well-known/openid-configuration).

### Describe the solution you'd like

Add introspection_endpoint to OIDC Discovery Endpoint.

**Comment by yaleman** [comment]
OAuth2 RFC8414 metatdata's available at `/oauth2/openid/<client_id>/.well-known/oauth-authorization-server` and includes the field you're looking for, can you try that?

**Comment by xzzpig** [comment]
Yes, there is a field for `/oauth2/openid/<client_id>/.well-known/oauth-authorization-server`. So is this field in the Oauth2 standard instead of OIDC? But if this field can be added to the `/oauth2/openid/:client_id:/.well-known/openid-configuration`? Because this plugin is written dead and only uses this URL. If not, then I can consider using other traefik oidc plugins.

**Comment by Firstyear** [comment]
oidc metadata allows extra claims to be added, so I see no issue adding these.
