### ISSUE TITLE
kanidm client tools not able to connect to kanidm when built from Cargo

### ISSUE THREAD

**Issue by khift363** [kanidm/kanidm#3048]
### I did this
I installed the kanidm client tools on RockyLinux 9 via Cargo following the instructions in the documentation. After installing several additional dependencies, the cargo build did eventually succeed.

### I expected the following
I attempted to login to the kanidm container using the kanidm client tools command 'kanidm login -D admin'

### This happened instead
`ERROR kanidm_cli::session: Error during authentication init phase: Transport(reqwest::Error { kind: Request, url: "https://idm.bigfish.in.net/v1/auth", source: hyper_util::client::legacy::Error(Connect, ConnectError("tcp connect error", Os { code: 111, kind: ConnectionRefused, message: "Connection refused" })) })`

### Kanidm version details
- Output of `kanidm(d) version`:
1.3.3, on both client and server

- Are you running it in a container? If so, which image/tag?:
Container defined through a Podman quadlet, using :latest tag.

- Operating System / Version (On Unix please post the output of `uname -a`):
`Linux bigfish 5.14.0-427.35.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Sep 12 18:24:53 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`

### Any other comments
Continuing to debug the problem, I installed an OpenSUSE Tumbleweed VM and installed kanidm client tools there via zypper. Using the same exact client config as on the main RockyLinux 9 server, the OpenSUSE VM was able to successfully connect to kanidm -- so the problem is specifically the Cargo build method.

Similarly, the web UI is up and functioning at the address.

Attempting to connect to the kanidm container via the RockyLinux server does not generate any log entries within the kanidm container. Connecting via the OpenSUSE box or via the web page does generate log entries.

There are no SELinux access control errors reported on the RockyLinux server.

Lastly, I verified that the RockyLinux server is able to resolve the DNS to the correct IP, just to ensure it was not a DNS issue. Both boxes resolve to 192.168.1.6, which is the static IP I have assigned for this route.

**Comment by yaleman** [comment]
The error

```
["tcp connect error"](code: 111, kind: ConnectionRefused, message: "Connection refused")
```

Would indicate that you need to troubleshoot why you can't connect - did you try something like a `curl "https://idm.bigfish.in.net/v1/auth" ? 

> Are you running it in a container? If so, which image/tag?:
> Container defined through a Podman quadlet, using :latest tag.

... are you running the server in a container or installing from cargo?

**Comment by khift363** [comment]
The server is in a container. Kanidm client configs is installed via Cargo, as there is no package for RockyLinux / RHEL 9.

Using curl on the RockyLinux server results in `curl: (7) Failed to connect to idm.bigfish.in.net port 443: Connection refused`. Other computers in the network instead don't get any response, including the OpenSUSE VM, so certainly unique to the RockyLinux box. But, pinging idm.bigfish.in.net from the RockyLinux box works fine and routes to the correct address, so it's not DNS...

**Comment by khift363** [comment]
This is a firewall issue; firewalld is not port forwarding any traffic originating from inside the server using the port forwarding rules that are configured. I have it configured to forward port 443 to 8443 (as Podman can't bind on 443 without root), and that works fine for external traffic but not internal traffic.

Apologies for the report. Closing issue.

**Comment by Firstyear** [comment]
@khift363 No problem, glad you got it sorted :)
