### ISSUE TITLE
Kanidm WebUI not functioning on Vanadium mobile browser

### ISSUE THREAD

**Issue by khift363** [kanidm/kanidm#3051]
### I did this
I loaded a site implementing Kanidm in mobile security hardened browser Vanadium.

### I expected the following
I expected the Kanidm site to function the same as on other browsers.

### This happened instead
The Kanidm site froze and could not authenticate. Issue is present both on authentication flows and on visiting the site directly.

### Kanidm version details
- Output of `kanidm(d) version`:
1.33

- Are you running it in a container? If so, which image/tag?:
Kanidm is running in a rootless podman container, behind an nginx reverse proxy and an oauth2-proxy container.

- Operating System / Version (On Unix please post the output of `uname -a`):
```
Linux bigfish 5.14.0-427.35.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Sep 12 18:24:53 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

### Any other comments
Vanadium is a security hardened fork of Chromium for Android that is the default browser on security focused mobile OS GrapheneOS. I suspect what is happening is that Vanadium is disabling parts of Kanidm's javascript due to security issues, but I'm unfortunately not able to easily debug the situation and Vanadium does not ship with developer tools by default. This is actually the first site I've loaded in the 6 months I've used Vanadium that didn't function properly, so it is pretty specific to Kanidm.

The site does function normally on Firefox mobile, so in the meantime I will use that as a workaround, but I would prefer to use Vanadium for all sites when possible because I do like the extra security it offers.

**Comment by khift363** [comment]
No errors are displayed in the browser. Vanadium does not ship with developer tools by default, so I am not able to provide anything further than it not working and the javascript appearing to be disabled.

**Comment by yaleman** [comment]
Then perhaps you'll need to install the dev tools, or find another way to troubleshoot? You're not giving us anything to go on other than random guesses at the moment.

**Comment by Firstyear** [comment]
Also will not be an issue next release as we change to htmx

**Comment by mannp** [comment]
> So if anybody in the future is searching the issues page trying to figure out why their Vanadium browser on GrapheneOS does not work with Kanidm, follow those steps and that should get it working for you.

Thank you, @khift363, I have had the issue for a while and hadn't got around to asking about it.
