### ISSUE TITLE
Kanidm UI 'Applications List' thumbnail not being updated by kanidm client configs command 'set-image'

### ISSUE THREAD

**Issue by khift363** [kanidm/kanidm#3052]
### I did this
I used command
```
kanidm system oauth2 set-image [application] [path to image]
```
to set the display image for the application.

### I expected the following
I expected that the 'Applications List' page in the Kanidm web ui would display this image as a thumbnail for the application.

### This happened instead
The thumbnail for the application remained the Kanidm logo.

### Kanidm version details
- Output of `kanidm(d) version`:
1.33

- Are you running it in a container? If so, which image/tag?:
Kanidm is running in a rootless podman container, behind an nginx reverse proxy and an oauth2-proxy container.

- Operating System / Version (On Unix please post the output of `uname -a`):
```
Linux bigfish 5.14.0-427.35.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Sep 12 18:24:53 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

### Any other comments
Two different images were tried -- one svg (4.3kb) and one png (17.1kb), but neither worked. I also tried specifying the filetype int he command as 'svg' or 'png', but no change either. The kanidm command to set the images returns 'Success', and checking the resource with get reveals an 'image' property with what I assume is a checksum for the image which was not present before adding the image.

The site was tested on multiple browsers including a fresh Chrome install with no extensions and all browsing data wiped before testing, and the issue was present on all setups. No errors appear in the developer console, and no error logs are generated in the kanidm container when accessing the page with the image changed.

It's possible this just isn't an implemented feature yet, as I couldn't find any documentation on it outside of the help command in kanidm client configs.

As an aside, I really like and appreciate the 'Application List' page on the Kanidm web ui -- I'm in the process of setting up a home server with a large variety of services and several different permission tiers (e.g., owner, friend, family) and I had planned to create a small landing page app that simply listed the services the user had permission to access, but the 'Applications List' does that already and quite well. Just need to be able to update the thumbnail images so it isn't just an army of crabs and it'll be pretty much golden for that use case.

**Comment by Firstyear** [comment]
Fixed next release when we change to HTMX which does support this.
