### ISSUE TITLE
How to configure kanidm to use spn as the email in oauth2 claims

### ISSUE THREAD

**Issue by xzzpig** [kanidm/kanidm#3057]
### Is your feature request related to a problem? Please describe

I am currently attempting to integrate Kanidm with [Headscale](https://github.com/juanfont/headscale) using OIDC for login. 
Unfortunately, Headscale currently uses email as the username.
However, in Kanidm, email addresses can be modified and cannot serve as a unique identifier for users.
Therefore, I hope to be able to utilize SPN as the email in Oauth2 claims for specific Oauth2 clients.

### Describe the solution you'd like

Add a configure likes `prefer-short-username`
Alternatively, adding a configuration likes `update-claim-map` that allows mapping a field on the `person` to OAuth2 claims could be a more general solution

**Comment by Firstyear** [comment]
This is clearly a bug in headscale, not kanidm. They should not be assuming email is a login identifier. OIDC makes it clear that the correct identifier of the account is "sub" and the username is "name". 

You should raise this as an issue with headscale first. Please link to this issue when you open it.

**Comment by Firstyear** [comment]
Thanks - we prefer that if there are incompatible applications that the service is fixed rather than applying hacks or work arounds in Kanidm. There are a lot of unintended consequences including security risks of these work arounds which we would prefer to avoid.
