### ISSUE TITLE
[htmx] Oauth flows don't redirect when needing to auth with passkey

### ISSUE THREAD

**Issue by ToxicMushroom** [kanidm/kanidm#3077]
### I did this
sign in via oauth on mealie, using mobile and passkey

### I expected the following
works

### This happened instead
stay stuck on kanidm

### Kanidm version details
1.4.0-dev

**Comment by ToxicMushroom** [comment]
This is because https://github.com/kanidm/kanidm/blob/master/server/core/static/pkhtml.js runs fetch with redirect following to post the passkey info. Which redirects the fetch to then fetch the outh2 resume endpoint and then in turn the final redirect target back to the client which is most likely not under the same host and thus gets blocked by our CSP, resulting in the redirect failing due to https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/connect-src.

Potential solution is to send the passkey info POST request and have the browser load the resume endpoint, browser is allowed to then follow the redirect since there is no JS involved.
![image](https://github.com/user-attachments/assets/9ef4080b-6eaa-49b1-82a8-e4125c3d791e)

**Comment by ToxicMushroom** [comment]
@yaleman do you have any thoughts on this, my workaround is a hack at best.

**Comment by yaleman** [comment]
1. You should never be using `window.location.replace` for this because you're removing Kanidm from the browser's history, which is bad.
2. Are you sure `connect-src` is blocking the _redirect_? Changing window.location shouldn't be affected by that - it might be because of using `replace` instead of `assign`?

**Comment by ToxicMushroom** [comment]
>     2. Are you sure `connect-src` is blocking the _redirect_? Changing window.location shouldn't be affected by that - it might be because of using `replace` instead of `assign`?

It's getting blocked in the fetch, I don't think it has anything to do with the location replace 
![image](https://github.com/user-attachments/assets/06334141-428a-47d5-b1d0-000b0e7ef698)

![image](https://github.com/user-attachments/assets/2d9e3d08-5f85-4d08-bc89-123158d610a7)

**Comment by Firstyear** [comment]
I love that webauthn enshrined javascript into it's operation 🙃

**Comment by yaleman** [comment]
Uh, you've broken something if connect-src is blocking the fetch from Kanidm to Kanidm...

**Comment by yaleman** [comment]
The flow in that javascript
- calls `navigator.credentials.get`
- fetch (POST) that to Kanidm
- redirects to the response.url

There's no explicable reason it should be doing a fetch to an outside URL in the code.

**Comment by Firstyear** [comment]
@yaleman This is when your oauth2 session is expired *and* your UAT.

So the flow is OAuth2 redirects to Kanidm. It's Oauth2 handler notes the expired UAT so begins a login flow. The login flow starts and the user auths with a webauthn credential. Webauthn enshrines Javascript, and the only way to post the response from it, is with a fetch POST to send the PublicKeyCredential response.

The PKC then triggers the login flow to succeed, and Kanidm returns a redirect to the location where you were "going to". This in turn re-activates the OAuth2 handler, which processes and begins the AuthorizationCode flow. The AuthCode flow then returns a redirect back to the OAuth2 client.

This is why there is a fetch here. The fetch from *webauthn* is what's causing the chain of events.

Normally in a login it's not an issue as the webauthn fetch goes to /ui/apps. But here it's a problem.

**Comment by Firstyear** [comment]
In wasm we avoided this because I think we redirected to another wasm handler, which then resumed the oauth2 flow.

**Comment by Firstyear** [comment]
So the passkeys posts to https://github.com/kanidm/kanidm/blob/master/server/core/src/https/views/login.rs#L492 which triggers https://github.com/kanidm/kanidm/blob/master/server/core/src/https/views/login.rs#L737 which returns a redirect to /ui/oauth/resume, which is https://github.com/kanidm/kanidm/blob/master/server/core/src/https/views/oauth2.rs#L51 and that calls oauth2_auth_req which itself returns a redirect.

**Comment by yaleman** [comment]
yes, so the **fetch being redirected** is the key, which wasn't clear from the information presented previously.

The fix you should need to do is set `redirect:'manual'` instead of `redirect: 'follow'`.

Don't touch the lower redirect code - that should be fixed by the redirect change... but please make that throw a user-facing error not just a console error 😄 .

**Comment by Firstyear** [comment]
And you can't hardcode /oauth2/resume either. You have to actually inspect the response and get the location from it. Because there are multiple possible locations that may need to be chased in that step.

**Comment by yaleman** [comment]
yeah by "don't touch" I mean "put it back to how it was" 😄

**Comment by ToxicMushroom** [comment]
> yes, so the **fetch being redirected** is the key, which wasn't clear from the information presented previously.

I tried to make that clear [here](https://github.com/kanidm/kanidm/issues/3077#issuecomment-2418271090) but I worded it poorly

> The fix you should need to do is set `redirect:'manual'` instead of `redirect: 'follow'`.
> Don't touch the lower redirect code - that should be fixed by the redirect change... but please make that throw a user-facing error not just a console error 😄 .

No, redirect: manual makes the response of type opaqueredirect: https://developer.mozilla.org/en-US/docs/Web/API/Response/type, response of that type don't have headers or body.

**Comment by yaleman** [comment]
Then your best bet's just to redirect the browser to the endpoint that calls `view_resume_get` which should return the proper redirect?

**Comment by ToxicMushroom** [comment]
> Then your best bet's just to redirect the browser to the endpoint that calls `view_resume_get` which should return the proper redirect?

err no since as william said this is used by oauth and normal login flows, thus multiple redirects are possible.

I made quick and dirty workaround that doesn't use fetch but uses an html form, thus solving the CSP issue and keeping the redirects intact.
I tested it with immich and works for oidc and normal login

```diff
Subject: [PATCH] example
---
Index: server/core/static/pkhtml.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/server/core/static/pkhtml.js b/server/core/static/pkhtml.js
--- a/server/core/static/pkhtml.js	(revision b6a6af78e8fdb81740de4625e13175dd57146a7f)
+++ b/server/core/static/pkhtml.js	(date 1729254229770)
@@ -1,5 +1,5 @@
 
-function asskey_login(target) {
+function asskey_login() {
     let credentialRequestOptions = JSON.parse(document.getElementById('data').textContent);
     credentialRequestOptions.publicKey.challenge = Base64.toUint8Array(credentialRequestOptions.publicKey.challenge);
     credentialRequestOptions.publicKey.allowCredentials?.forEach(function (listItem) {
@@ -8,46 +8,32 @@
 
     navigator.credentials.get({ publicKey: credentialRequestOptions.publicKey })
     .then((assertion) => {
-        const myRequest = new Request(target, {
-            method: 'POST',
-            redirect: 'follow',
-            headers: {
-                'Content-Type': 'application/json'
-            },
-            body: JSON.stringify({
-                id: assertion.id,
-                rawId: Base64.fromUint8Array(new Uint8Array(assertion.rawId), true),
-                type: assertion.type,
-                response: {
-                    authenticatorData: Base64.fromUint8Array(new Uint8Array(assertion.response.authenticatorData), true),
-                    clientDataJSON: Base64.fromUint8Array(new Uint8Array(assertion.response.clientDataJSON), true),
-                    signature: Base64.fromUint8Array(new Uint8Array(assertion.response.signature), true),
-                    userHandle: Base64.fromUint8Array(new Uint8Array(assertion.response.userHandle), true)
-                },
-            }),
+        document.getElementById("cred").value = JSON.stringify({
+            id: assertion.id,
+            rawId: Base64.fromUint8Array(new Uint8Array(assertion.rawId), true),
+            type: assertion.type,
+            response: {
+                authenticatorData: Base64.fromUint8Array(new Uint8Array(assertion.response.authenticatorData), true),
+                clientDataJSON: Base64.fromUint8Array(new Uint8Array(assertion.response.clientDataJSON), true),
+                signature: Base64.fromUint8Array(new Uint8Array(assertion.response.signature), true),
+                userHandle: Base64.fromUint8Array(new Uint8Array(assertion.response.userHandle), true)
+            },
         });
-        fetch(myRequest).then((response) => {
-            if (response.redirected) {
-                window.location.replace(response.url);
-                return;
-            } else {
-                console.error("expected a redirect");
-            }
-        })
+        document.getElementById("cred-form").submit();
     })
 }
 
 try {
     const myButton = document.getElementById("start-passkey-button");
     myButton.addEventListener("click", () => {
-        asskey_login('/ui/login/passkey');
+        asskey_login();
     });
 } catch (_error) {};
 
 try {
     const myButton = document.getElementById("start-seckey-button");
     myButton.addEventListener("click", () => {
-        asskey_login('/ui/login/seckey');
+        asskey_login();
     });
 } catch (_error) {};
 
Index: server/core/src/https/views/login.rs
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/server/core/src/https/views/login.rs b/server/core/src/https/views/login.rs
--- a/server/core/src/https/views/login.rs	(revision b6a6af78e8fdb81740de4625e13175dd57146a7f)
+++ b/server/core/src/https/views/login.rs	(date 1729254263203)
@@ -24,6 +24,7 @@
 use serde::{Deserialize, Serialize};
 use std::str::FromStr;
 use webauthn_rs::prelude::PublicKeyCredential;
+use crate::https::views::errors::HtmxError;
 
 #[derive(Default, Serialize, Deserialize)]
 struct SessionContext {
@@ -489,16 +490,31 @@
     credential_step(state, kopid, jar, client_auth_info, auth_cred, domain_info).await
 }
 
+
+#[derive(Debug, Clone, Deserialize, Serialize)]
+pub struct JsonedPublicKeyCredential {
+    cred: String
+}
+
 pub async fn view_login_passkey_post(
     State(state): State<ServerState>,
     Extension(kopid): Extension<KOpId>,
     VerifiedClientInformation(client_auth_info): VerifiedClientInformation,
     DomainInfo(domain_info): DomainInfo,
     jar: CookieJar,
-    Json(assertion): Json<Box<PublicKeyCredential>>,
+    Form(assertion): Form<JsonedPublicKeyCredential>,
 ) -> Response {
-    let auth_cred = AuthCredential::Passkey(assertion);
-    credential_step(state, kopid, jar, client_auth_info, auth_cred, domain_info).await
+    let result = serde_json::from_str::<Box<PublicKeyCredential>>(assertion.cred.as_str());
+    match result {
+        Ok(pkc) => {
+            let auth_cred = AuthCredential::Passkey(pkc);
+            credential_step(state, kopid, jar, client_auth_info, auth_cred, domain_info).await
+        }
+        Err(e) => {
+            error!(err = ?e, "Unable to deserialize credential submission");
+            HtmxError::new(&kopid, OperationError::SerdeJsonError).into_response()
+        }
+    }
 }
 
 pub async fn view_login_seckey_post(
Index: server/core/templates/login_webauthn.html
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/server/core/templates/login_webauthn.html b/server/core/templates/login_webauthn.html
--- a/server/core/templates/login_webauthn.html	(revision b6a6af78e8fdb81740de4625e13175dd57146a7f)
+++ b/server/core/templates/login_webauthn.html	(date 1729254229786)
@@ -9,9 +9,17 @@
 <script src="/pkg/pkhtml.js" defer></script>
 
 (% if passkey %)
-<button hx-disable type="button" class="btn btn-dark" id="start-passkey-button">Use Passkey</button>
+<form id="cred-form" action="/ui/login/passkey" method="POST">
+    <input hidden="hidden" name="cred" id="cred">
+
+    <button hx-disable type="button" class="btn btn-dark" id="start-passkey-button">Use Passkey</button>
+</form>
 (% else %)
-<button type="button" class="btn btn-dark" id="start-seckey-button">Use Security Key</button>
+<form id="cred-form" action="/ui/login/seckey" method="POST">
+    <input hidden="hidden" name="cred" id="cred">
+
+    <button type="button" class="btn btn-dark" id="start-seckey-button">Use Security Key</button>
+</form>
 (% endif %)
 
 (% endblock %)

```

**Comment by yaleman** [comment]
Perfect, I figured there was some jank that precluded using forms on this... forms are a way better way to solve it 😄

**Comment by Firstyear** [comment]
Probably my lack of knowledge was the preclusion :)

**Comment by yaleman** [comment]
Web stuff is hard and I haven't had time to really follow what's going on over there with you backend kids doing frontend things 😆
