### ISSUE TITLE
Home dir isn't created when `home_prefix` is set

### ISSUE THREAD

**Issue by muradbu** [kanidm/kanidm#3105]
### Is your feature request related to a problem? Please describe

I've set `home_prefix = "/home1/"` but when I login via ssh the user's home dir isn't created and I see the message: "Could not chdir to home directory /home1/pamtest: No such file or directory"

I'm using NixOS and set up kanidm-unixd like so:

```nix
  services.kanidm = {
    enablePam = true;
    clientSettings = {
      uri = "https://idm.example.com"; # obfuscated url
    };
    unixSettings = {
      default_shell = "${pkgs.bashInteractive}/bin/bash";
      gid_attr_map = "name";
      home_alias = "name";
      home_attr = "uuid";
      home_mount_prefix = "/home/";
      home_prefix = "/home1/";
      pam_allowed_login_groups = [ "node-test" ];
      uid_attr_map = "name";
    };
  };
```

### Describe the solution you'd like

The user's homedir should be created in `$home_prefix/$home_attr` respectively.

### Describe alternatives you've considered

I've tried setting an ACL to allow kanidm-unixd rwx permission on /home1: `sudo setfacl -m u:kanidm-unixd:rwx /home1`.

### Additional context

Logging in via ssh while `home_prefix` is omitted does successfully create a home dir in `/home`.

The reason I want to create homedirs in /home1 is because that's a dedicated hard drive I've mounted for user data.

```
# journalctl -xeu kanidm-unixd

Oct 14 00:07:25 nixos kanidm_unixd[217632]: 00000000-0000-0000-0000-000000000000 INFO     ｉ [info]: Server started ...
Oct 14 00:07:39 nixos kanidm_unixd[217632]: 00000000-0000-0000-0000-000000000000 INFO     ｉ [info]: User has not specified a shell, using default
Oct 14 00:07:39 nixos kanidm_unixd[217632]: 00000000-0000-0000-0000-000000000000 ERROR    🚨 [error]: Error -> Some(Ok(Error("Os { code: 2, kind: NotFound, message: \"No such file or directory\" }")))
Oct 14 00:07:39 nixos kanidm_unixd[217632]: 00000000-0000-0000-0000-000000000000 ERROR    🚨 [error]: Task client error occurred; error = Custom { kind: Other, error: "oh no!" }
Oct 14 00:07:39 nixos kanidm_unixd[217632]: 00000000-0000-0000-0000-000000000000 ERROR    🚨 [error]: Error -> Some(Ok(Error("Os { code: 2, kind: NotFound, message: \"No such file or directory\" }")))
Oct 14 00:07:39 nixos kanidm_unixd[217632]: 00000000-0000-0000-0000-000000000000 ERROR    🚨 [error]: Task client error occurred; error = Custom { kind: Other, error: "oh no!" }
```

**Comment by yaleman** [comment]
`kanidm-unixd` doesn't create the paths, it passes it off to `kanidm-unixd-tasks` which should be running as root and thus has the power to manage this. You'll need to check the logs in that process, but TBH it might not be much clearer as the logs are just dumping the error as a string - it looks like it's in the alias creation phase though.

https://github.com/kanidm/kanidm/blob/d06bc617400d1fa1dca4224a544a0c6348f86142/unix_integration/resolver/src/bin/kanidm_unixd_tasks.rs#L241-L271

**Comment by muradbu** [comment]
Thanks for your reply. `kanidm-unixd-tasks` is indeed running as root, but the logs aren't clear indeed:
```
# journalctl -xeu kanidm-unixd-tasks

Oct 14 12:20:30 nixos kanidm_unixd_tasks[225352]: 00000000-0000-0000-0000-000000000000 INFO     ｉ [info]: Server started ...
Oct 14 12:20:30 nixos kanidm_unixd_tasks[225352]: 00000000-0000-0000-0000-000000000000 INFO     ｉ [info]: Attempting to connect to kanidm_unixd ...
Oct 14 12:20:30 nixos kanidm_unixd_tasks[225352]: 00000000-0000-0000-0000-000000000000 INFO     ｉ [info]: Found kanidm_unixd, waiting for tasks ...
Oct 14 12:20:39 nixos kanidm_unixd_tasks[225352]: 00000000-0000-0000-0000-000000000000 ERROR    🚨 [error]: Error -> None
Oct 14 12:20:39 nixos kanidm_unixd_tasks[225352]: 00000000-0000-0000-0000-000000000000 INFO     ｉ [info]: Attempting to connect to kanidm_unixd ...
Oct 14 12:20:39 nixos kanidm_unixd_tasks[225352]: 00000000-0000-0000-0000-000000000000 INFO     ｉ [info]: Found kanidm_unixd, waiting for tasks ...
```

This is how I've mounted `/home1`:
```nix
  fileSystems."/home1" = {
    device = "/dev/disk/by-label/disk1";
    fsType = "xfs";
    options = [ "uquota" "gquota" "pquota" "noatime" ];
  };
```

A bit of an unrelated stretch but I did it anyway for good measure. I have `hidepid=2` mount option set for `/proc` and I just added `kanidm-unixd` to the group that is allowed to see other user's processes.

```nix
  users.groups.proc = {
    gid = 992;
    members = [ "grafana" "prometheus" "node-exporter" "kanidm-unixd" ];
  };
  boot.specialFileSystems."/proc".options = [ "nosuid" "nodev" "noexec" "hidepid=2" "gid=${toString config.users.groups.proc.gid}" ];
```

**Comment by muradbu** [comment]
Observing logs of `kanidm_unixd_tasks` while `home_prefix` and `home_mount_prefix` aren't set also doesn't show any tasks that could indicate kanidm is creating the user's home dir, while the user's home dir _does_ get created in /home.

**Comment by yaleman** [comment]
We're not NixOS people so you might have to explain what those mount/proc things are doing in actual POSIX terms... but squinting at it - have you looked at the quotas applied to the filesystem to ensure it's not blocking the tasks process from doing something?

It's getting access to the folders but can't seem to create the required symlinks and such, so something's blocking it.

**Comment by muradbu** [comment]
Sure.

In the 1st Nix code snippet of my previous reply /dev/sda1 (labeled disk1) gets formatted with xfs and mounted to /home1 with the following mount options:
- uquota: Enables user quotas on the filesystem
- gquota: Enables group quotas on the filesystem
- pquota: Enables project quotas on the filesystem
- noatime: Disables updating of file access times on the filesystem

In the 2nd, a group `proc` is created with members specified. `hidepid=2` makes it so that e.g. Bob can only see his own processes in /proc, whereas root and all members belonging to the `proc` group can see all running processes. /proc then gets mounted with options:
- nosuid: Disables the execution of setuid and setgid bits on files in this filesystem
- nodev: Prevents interpretation of character or block special devices on the filesystem
- noexec: Prevents execution of any binaries on the filesystem
- hidepid=2: Hides process information from other users
- gid=992: Allows members of the `proc` group to view all processes, bypassing the hidepid restriction

`hidepid=2` is known to cause issues with processes that require visibility of other running processes, hence why you whitelist those with a group. FWIW I've also tried completely disabling all these options.

As for quotas, I've just remounted /home1 without any mount options, effectively disabling quotas, but still no dice. I'm going to try setting up Kanidm on a separate minimal machine to try rule out issues.

**Comment by Firstyear** [comment]
You have to configure the home_prefix in your kanidm unixd config.       home_mount_prefix = "/home/"; means unixd will create alias symlinks in /home, and they point to real storage in /home1 where it tries to make the actual directory.

**Comment by muradbu** [comment]
> home_mount_prefix = "/home/"; means unixd will create alias symlinks in /home, and they point to real storage in /home1 where it tries to make the actual directory.

Yes that's my intention, for the home dirs to be created in /home1 and symlinked to /home. But the home dir doesn't get created for some reason and I can't pinpoint why.

This is the resulting kanidm unixd config which NixOS generates and it seems correct to me. So the way I understand it is this should:
- create home dir in `/home1/$uuid`
- create a symlink `/home/$name  ---> /home1/$uuid`
```
$ cat /etc/kanidm/unixd

default_shell = "/nix/store/nmyaxjl9ihqf3d7b3i60x1mj000rvm35-bash-interactive-5.2p32/bin/bash"
gid_attr_map = "name"
home_alias = "name"
home_attr = "uuid"
home_mount_prefix = "/home/"
home_prefix = "/home1"
hsm_pin_path = "/var/cache/kanidm-unixd/hsm-pin"
pam_allowed_login_groups = ["node-test"]
uid_attr_map = "name"
```

**Comment by muradbu** [comment]
I've just set up kanidm-unixd locally in a freshly installed arm64 NixOS VM and ran into the same issue where home dirs aren't created in `home_prefix = "/home1"`.

For now I'm considering mounting the HDD directly onto /home instead, and manually create admin users in an alternate dir on the rootfs, and call it a day.

**Comment by Firstyear** [comment]
I think I see the issue.

home_prefix = where the symlinks go
home_mount_prefix = where the storage is mounted.

You need to swap your argument order in the config.

**Comment by muradbu** [comment]
In that case then I think the documentation is incorrect as it contradicts what you say. In the text it says that **symlinks will go into `/home/$user_name` (so `home_prefix`, as you say)**, but in the example it is set to `home_mount_prefix`, and that directories are **mounted at `/u/` (so `home_mount_prefix`, as you also say)**, but in the example it is set to `home_prefix`. I've asked another pair of eyes to read this and he's caught that as well. The examples given are the exact opposite from your reply.

So, in congruence with your reply it should be like this, correct?:

```diff
- # Controls the prefix that will be appended to the home alias when mounting home directories. Must
+ # Controls the prefix that will be **prepended** to the home alias when mounting home directories. Must
# end with a trailing `/`. If unset, defaults to the value of the `home_prefix`.
#
# This is option is useful when implementing a networked home directory layout. A common implementation
# is to configure a networked filesystem that contains user directories mounted at `/u/` (eg /u/$user_uuid)
# and then symlink the mounted directory into /home/$user_name when the user logs in. This can be accomplished
# with a configuration that includes the following:
#
# > home_attr = "uuid"
# > home_alias = "name"
- # > home_prefix = "/u/"
+ # > home_prefix = "/home/"
- # > home_mount_prefix = "/home/"
+ # > home_mount_prefix = "/u/"
#
# Default: unset
#
# home_mount_prefix = "/home/"
```

Well I've made the changes as you said (this time using `/mnt/disk1` for the home mount instead of `/home1`) but unfortunately still run into the same issue. But it is good to know my config was wrong and I'm now a step closer.

```console
$ ssh john@192.168.64.8

Last login: Wed Oct 16 04:09:52 2024 from 192.168.64.1
Could not chdir to home directory /home/john: No such file or directory
```

And my updated unixd:
```
$ cat /etc/kanidm/unixd
default_shell = "/nix/store/1r5j1ax2fnj99g2wdp4a01m9rnbcsj50-bash-interactive-5.2p32/bin/bash"
gid_attr_map = "name"
home_alias = "name"
home_attr = "uuid"
home_mount_prefix = "/mnt/disk1/"
home_prefix = "/home/"
hsm_pin_path = "/var/cache/kanidm-unixd/hsm-pin"
pam_allowed_login_groups = ["node-test"]
uid_attr_map = "name"
```

https://kanidm.github.io/kanidm/stable/integrations/pam_and_nsswitch.html
