### ISSUE TITLE
Check for group with same name as user that might stomp user-private-group in unixd

### ISSUE THREAD

**Issue by yaleman** [kanidm/kanidm#3110]
Need to add testing around this situation

- kanidm users "testuser1", "testuser2"
- kanidm group "testuser1" containing both users
- posix attributes on all the above

What happens - group will have a different gid so won't be checked by [the security checks here](https://github.com/kanidm/kanidm/blob/20751254392d19616bfb62de73873071f4862ab5/unix_integration/resolver/src/idprovider/system.rs#L230-L252) but it's also not really in line with the user-private-group thing.

**Comment by Firstyear** [comment]
You can't make a group called testuser1 once the person exists, because they will conflict on name and it'll be denied.

**Comment by Firstyear** [comment]
Given that testuser1 can't be both a group *and* a user as it would violate uniqueness, this is impossible so we don't need to test it.

**Comment by yaleman** [comment]
I do wonder how this person seems to have managed it? https://github.com/kanidm/kanidm/discussions/3099

**Comment by Firstyear** [comment]
They didn't, the posix handler has a special handler so that if a user exists, it also projects their posix group in api calls.
