### ISSUE TITLE
feat: Password Quality & Length

### ISSUE THREAD

**Issue by johnmmcgee** [kanidm/kanidm#3116]
**Issue:** 
[Password Quality](https://kanidm.github.io/kanidm/master/accounts/account_policy.html#password-quality)

Kanidm enforces that all passwords are checked by the library "[zxcvbn](https://github.com/dropbox/zxcvbn)". This has a large number of checks for password quality. It also provides constructive feedback to users on how to improve their passwords if they are rejected.

Some things that zxcvbn looks for is use of the account name or email in the password, common passwords, low entropy passwords, dates, reverse words and more.

This library can not be disabled - all passwords in Kanidm must pass this check.

**Problem:**

In some cases there may be a desire for simple Passwords.  For example I utilize a web applicaiton that has no real security implications if someone were to figure out a password and gain access to the application as a user.   However some of my user's are unable to remember long context passwords due to health and age reasons.  Therefor the ability to set the password to something simple, such as a 8 digit code (think birthday) , is desired.

**Request:**

While i feel the current structure is great in most use cases and should be the default, I request the ability to disable the password complexity/checks and to allow setting a length to whatever is desired, which at this moment cannot seem to be set under 10 character's.

**Comment by 0xC0ncord** [comment]
I would personally rather have password policies at the global level and a per-user level. I have also run into this with a couple of my users who frequently forget their complex passwords and need me to help them reset it. I would like to continue to enforce strong passwords for all users by default, but maybe decrease these complex password requirements for one or two users who I know do not have privileged access to other resources.

**Comment by yaleman** [comment]
This is not something we're going to implement/allow. I'd suggest looking into password-less options like webauthn/passkeys if password complexity is a problem.

**Comment by Firstyear** [comment]
I agree. In addition I want to make it clear that your users are putting their trust in you - and in Kanidm - to protect and secure their accounts. We take this responsibility seriously. As should you.

Asking us to weaken password security undermines that trust your users are putting in you. 

As a result, we will never reduce the requirements on passwords given all the attacks and risks that exist today. If anything, we will increase them over time.

**Comment by johnmmcgee** [comment]
The admin should ultimately have the power to dictate the security requirements for the accounts and environment, not the idm package.  I feel this hard headed approach of forced configuration may be a deterrent for adoption of an otherwise fantastic piece of software.

**Comment by Firstyear** [comment]
Our settings and minimums are taken from source such as NIST SP800-63B, evidence of attacks on passwords as disclosed by provider like Microsoft, libraries like zxcvbn which were developed over years of study of password based attacks, and our own research against password attacks from public breach databases.

The same way that you are asked to trust cryptographers when they discuss the difference between say 512 bit rsa and 2048 bit rsa, we would ask you to trust that we have made decisions based on research and evidence from leading experts in authentication security.

We want Kanidm to provide the best experience possible, and a major aspect of that is the security of accounts that entrust their data to our software. We won't weaken our stance on this.
