### ISSUE TITLE
[HTMX] SSH keys button throws silent 404

### ISSUE THREAD

**Issue by yaleman** [kanidm/kanidm#3132]
### I did this

Clicking on clicking on SSH keys in the HTMX ui 

### I expected the following

It to work and prompt me to edit my SSH keys

### This happened instead

The UI throws a silent 404 error in the console and causes the UI to "do nothing"

### Kanidm version details

current dev as at 2024-10-22 commit 8b4d0d6eadfc599e1bf39c17f94cd5bbef5c2d82

### Any other comments

<img width="1162" alt="Screenshot 2024-10-22 at 18 23 19" src="https://github.com/user-attachments/assets/24380e97-299e-494c-aed9-fefd852df3c7">

**Comment by yaleman** [comment]
🤦🏻 turns out #3027 is a thing and I thought it was done. Leaving this open for now.

**Comment by weijiangan** [comment]
This page will be gone too in favor of it being part of credentials update flow as I understand. @firstyear

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Firstyear** [comment]
Yep, we're moving ssh keys to the credential management page.
