### ISSUE TITLE
[HTMX] When Kanidm prompts the user for auth unlock, it's not clear what's going on

### ISSUE THREAD

**Issue by yaleman** [kanidm/kanidm#3134]
When the user's unlocking their profile, they don't know why, all they get is a login prompt.

### Describe the solution you'd like

A message saying what's going on.

### Describe alternatives you've considered

Normalising random prompts for auth.

### Additional context

This is what you get now:

<img width="1217" alt="Screenshot 2024-10-22 at 19 04 37" src="https://github.com/user-attachments/assets/433d14bb-c7d8-4ad5-8274-b2b9647021df">

**Comment by yaleman** [comment]
This is what I'm going for...

<img width="1169" alt="Screenshot 2024-10-22 at 19 21 02" src="https://github.com/user-attachments/assets/e2259d26-53e6-40aa-a629-af53e5e879cf">

**Comment by Firstyear** [comment]
Funny as I went and did this just before you lmao.

**Comment by yaleman** [comment]
Will be closed by #3130 and/or #3135
