### ISSUE TITLE
idm_people_self_name_write don't work

### ISSUE THREAD

**Issue by EHEX-schildt** [kanidm/kanidm#3178]
### I did this
```bash
kanidm group remove-members idm_people_self_name_write idm_all_persons@my.domain --name admin
Successfully removed members from idm_people_self_name_write
```
```bash
kanidm group get idm_people_self_name_write --name admin
---
class: builtin
class: group
class: object
description: Builtin IDM Group denoting users that can write to their own name attributes.
entry_managed_by: idm_admins@my.domain
name: idm_people_self_name_write
spn: idm_people_self_name_write@my.domain
uuid: 00000000-0000-0000-0000-000000000048
```

### I expected the following
Users can no longer change own their name or displayname

### This happened instead
Users can still change their own name and displayname.

```bash
kanidm login --name test.user
If your authenticator is not attached, attach it now.
Your authenticator will then flash/prompt for confirmation.
Enter PIN: 
Login Success for test.user@my.domain
```

```bash
kanidm person update --displayname "Jean-Luc Picard" test.user --name test.user
2024-11-05T13:18:01.509667Z ERROR kanidm_cli::common: Privileges have expired for test.user@my.domain - you need to re-authenticate again.
Would you like to re-authenticate? yes
If your authenticator is not attached, attach it now.
Your authenticator will then flash/prompt for confirmation.
Enter PIN: 
Login Success for test.user@my.domain
Success
```
```bash
kanidm person get test.user --name idam
---
class: account
class: memberof
class: object
class: person
directmemberof: idm_all_persons@my.domain
directmemberof: idm_all_accounts@my.domain
directmemberof: group1@my.domain
directmemberof: playground@my.domain
directmemberof: group2@my.domain
displayname: Jean-Luc Picard
mail: test.user@my.domain
memberof: idm_all_persons@my.domain
memberof: idm_all_accounts@my.domain
memberof: group1@my.domain
memberof: playground@my.domain
memberof: group2@my.domain
name: test.user
passkeys: key1
spn: test.user@my.domain
uuid: d2011e39-4a61-4e42-801a-6023097e00e4
```

### Kanidm version details

- Output of `kanidm(d) version`: **kanidmd 1.4.1**
- Are you running it in a container? **Yes** If so, which image/tag?: **1.4.1**

### Any other comments

We don't want our users to change their own names to avoid impersonation.

**Comment by Firstyear** [comment]
This is intended behaviour. The displayname attribute is governed by https://github.com/kanidm/kanidm/blob/master/server/lib/src/constants/acp.rs#L1485 and the name attribute is what is affected by the https://github.com/kanidm/kanidm/blob/master/server/lib/src/constants/acp.rs#L1542 name self write access.

The intent of allowing people to disable "name changes" was to prevent people changing their *usernames*. It does not affect a persons ability to alter their displayname (how they wish to be known).

The reason to disable (user)name changes is often that incorrectly coded systems primary key on username. No such barrier exists with displayname. 

Is there a compelling use case for us to prevent a person changing their displayname when they want to change it?

**Comment by EHEX-schildt** [comment]
User Self username change is possible with no members in idm_people_self_name_write:
```bash
kanidm group get idm_people_self_name_write --name idam
---
class: builtin
class: group
class: object
description: Builtin IDM Group denoting users that can write to their own name attributes.
entry_managed_by: idm_admins@my.domain
name: idm_people_self_name_write
spn: idm_people_self_name_write@my.domain
uuid: 00000000-0000-0000-0000-000000000048
```
```bash
kanidm person update --newname "jean-luc.picard" test.user --name test.user
...
Success
```
```bash
kanidm person get jean-luc.picard --name idam
...
name: jean-luc.picard
```

**Comment by EHEX-schildt** [comment]
We don't want users to change there own username and displayname to minimize the social engineering Attack vector.

Imagine a somewhat big Company.

A trainee could change his displayname to the head of some department and try to order 
more access rights for the trainee via the service desk.

**Comment by yaleman** [comment]
I could see a use case for corporate platforms for when names are controlled by (for example) HR systems.

**Comment by Firstyear** [comment]
Yeah I'm planning to adjust the acp here today to reflect this.

**Comment by Firstyear** [comment]
Hang on, it looks like the ACP already does this? I need to work out what's wrong.
