### ISSUE TITLE
Failed to deserialize `max_age`

### ISSUE THREAD

**Issue by Jeidnx** [kanidm/kanidm#3185]
### I did this
Sent an Authorisation request to the `/ui/oauth2` endpoint with `max_age=1` in the query parameters

### I expected the following
Kanidm should verify my identity and redirect to the callback

### This happened instead
`Failed to deserialize query string: invalid type: string "1", expected i64`

### Kanidm version details

- Output of `kanidm(d) version`: 1.4
- Are you running it in a container? If so, which image/tag?: no
- If not a container, how'd you install it: NixOS
- Operating System / Version (On Unix please post the output of `uname -a`): Linux 6.6.44 GNU/Linux

### Any other comments

While looking through the source code i found a TODO comment regarding the `auth_time` claim (which needs to be sent when `max_age` is requested). I couldn't check if this claim is sent but it would be awesome if it did work.
If someone can point me in the right direction i can also try to make a PR for this. Thanks!

**Comment by yaleman** [comment]
There's some weirdness in how Axum is handling the flattened deserialisation, ref https://github.com/tokio-rs/axum/issues/1366 possibly?

Will need some testing to figure out how to prod serde and axum to play nice

**Comment by Firstyear** [comment]
They claim that skipping the flatten resolves, so maybe we just hoist the content of https://github.com/kanidm/kanidm/blob/master/proto/src/oauth2.rs#L60 into `AuthorisationRequest`.

**Comment by Jeidnx** [comment]
Thanks for the quick response and fix! You are doing awesome work, i really appreciate that.
I have tested this and i would still expect a different behavior. Sending `max_age=0` should always force the user to be re-authenticated and the `auth_time` claim to be sent on the token response. I would be willing to give this a shot, but im not sure how complex this would be to implement.
Also, should i open a separate issue for this, since this has nothing to do with the deserialization?

**Comment by yaleman** [comment]
Yep, new issue asking for it to be supported please if there isn't one. I think there's already one for the login=prompt variations which this could get grouped in with.
