### ISSUE TITLE
Streamline login flow to fewer clicks/pages

### ISSUE THREAD

**Issue by adamcstephens** [kanidm/kanidm#3193]
### Is your feature request related to a problem? Please describe

Since kanidm added another explicit button to click for webauthn, I'd like to suggest exploring ways to streamline this if possible.

### Describe the solution you'd like

I'd like to click fewer buttons to log in, and visit fewer pages. One idea could be to combine the two passkey buttons in to one. Admittedly I don't understand the full implications of this.

### Describe alternatives you've considered

Status quo.

### Additional context

not currently, but happy to answer questions or brainstorm further.

**Comment by Firstyear** [comment]
Most of the excess clicks are from two sources:

* Browsers need clicks to start webauthn flows
* We don't have the webauthn *challenge* yet when we get to https://github.com/kanidm/kanidm/blob/master/server/core/src/https/views/login.rs#L757 

There are really two kind of flows here:

* When you have to choose a mech, we could lift up the challenge into the mech selection so that selecting passkey triggers the flow directly rather than the two stage passkey -> passkey click.
* When you first login and you only have passkeys, I'm not sure if we can auto-trigger the event. I need to see what's possible here.

**Comment by mzgaljic** [comment]
I'm out of my depth here (full disclosure). I _think_ the ideal login flow would use the 'conditional webauthn UI', as described here: [Webauthn - Conditional UI](https://www.corbado.com/blog/webauthn-conditional-ui-passkeys-autofill#full-conditional-ui-example)

(link includes a full code example)

> What is Conditional UI?
> Conditional UI  represents a new mode for passkeys / WebAuthn login processes. It selectively displays passkeys in a user interface (UI) only when a user has a [discoverable credential (resident key)](https://www.corbado.com/blog/webauthn-resident-key-discoverable-credentials-passkeys), which is a type of passkey, registered with the [relying party](https://www.corbado.com/blog/webauthn-relying-party-id-rpid-passkeys) (the online service) stored in their [authenticator](https://www.corbado.com/glossary/authenticator) of a device (e.g. laptop, smartphone). The passkeys are displayed in a selection dropdown that is mixed up with autofilled passwords, providing a seamless transition between traditional password systems and advanced passkey authentication, as users see both in the same context. This intelligent approach ensures that users aren't overwhelmed with unnecessary options and can navigate the login process more seamlessly.

I believe google has implemented this already, see screenshot below. My mac's password manager suggests my google passkey (seamlessly!) as soon as I visit the login page. I do not need to:
1. manually enter my username
2. click a 'remember me' checkbox
3. click a 'login' button followed by a 'passkey' button

**That's 3 manual steps** during login (the remember me checkbox makes it 2 steps next time... which is a bit better).  It's a bit annoying if I'm being 100% honest.

![google_passkey_example](https://github.com/user-attachments/assets/e4543c44-f1be-4367-8990-4865be6631ef)

**Comment by mzgaljic** [comment]
Slightly unrelated, but when a user clicks' sign out' on the kanidm dashboard, is a confirmation dialog really needed? I'd personally suggest immediately signing the user out when they click the sign out button, as a default behavior, and adding a setting to enable a confirmation if an admin really wishes. Just my 2 cents.  :)

Signing out isn't really a destructive action, and the button isn't anywhere near the other UI elements on the dashboard (hard to click accidentally).

**Comment by Firstyear** [comment]
It also signs you out of all your oauth2 sessions, so it is destructive.

**Comment by Firstyear** [comment]
> ![google_passkey_example](https://private-user-images.githubusercontent.com/9629063/384816549-e4543c44-f1be-4367-8990-4865be6631ef.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5Mzc0NzAsIm5iZiI6MTczMjkzNzE3MCwicGF0aCI6Ii85NjI5MDYzLzM4NDgxNjU0OS1lNDU0M2M0NC1mMWJlLTQzNjctODk5MC00ODY1YmU2NjMxZWYuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMzBUMDMyNjEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Zjc3ODQ2Njc0N2VjZTg0M2VmN2JmYTI1MzViMWZjYWQ2YmRjY2Y1ZmI0ZDNlNTRiMmE0NjBlMjkzZWNjZmVjNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.F05EhXgxiy_TJttDoxRVP7lPOInvcAQebZpBE0TAOGQ)

This is conditional UI, and it has a lot of flaws and issues on a variety of platforms which is why we haven't enabled it yet.

**Comment by adamcstephens** [comment]
Thanks again ❤️
