### ISSUE TITLE
How does `map_group` work?

### ISSUE THREAD

**Issue by LukeChannings** [kanidm/kanidm#3197]
I am trying to map a Kanidm group to the local `wheel` group

I have the following in `/etc/kanidm/unixd`:

```toml
[kanidm]
pam_allowed_login_groups = ["unix-login"]

[[kanidm.map_group]]
local = "wheel"
with = "unix-admins"
```

I have a user that's a part of the `unix-login` and `unix-admins` groups, but it is not a part of `wheel`.

How is this feature meant to work?

**Comment by yaleman** [comment]
Are both the groups and the user POSIX enabled? Also ensure that both groups are in the the PAM allow list, you only have one.

**Comment by Firstyear** [comment]
You only need unix-login in the pam allow here, 

Unix-login and unix-admins need to be posix groups as mentioned.

**Comment by LukeChannings** [comment]
So, `unix-admins` wasn't a POSIX group. `unix-login` is, and I can log in with my user.

I did `kanidm group posix set unix-admins`:

```
kanidm group get unix-admins
---
class: group
class: object
class: posixgroup
gidnumber: 2005447138
member: luke@example.com
name: unix-admins
spn: unix-admins@example.com
uuid: ...
```

```
kanidm person get luke
---
class: account
class: memberof
class: object
class: person
class: posixaccount
directmemberof: idm_admins@example.com
directmemberof: idm_all_persons@example.com
directmemberof: idm_all_accounts@example.com
directmemberof: unix-login@example.com
directmemberof: minio_admins@example.com
directmemberof: unix-admins@example.com
directmemberof: minio_users@example.com
displayname: Luke
gidnumber: 123
memberof: idm_admins@example.com
memberof: idm_people_admins@example.com
memberof: idm_group_admins@example.com
memberof: idm_oauth2_admins@example.com
memberof: idm_all_persons@example.com
memberof: idm_all_accounts@example.com
memberof: idm_radius_service_admins@example.com
memberof: idm_unix_admins@example.com
memberof: idm_service_account_admins@example.com
memberof: idm_account_policy_admins@example.com
memberof: idm_people_self_name_write@example.com
memberof: idm_client_certificate_admins@example.com
memberof: idm_application_admins@example.com
memberof: idm_mail_service_admins@example.com
memberof: idm_high_privilege@example.com
memberof: unix-login@example.com
memberof: unix-admins@example.com
name: luke
unix_password: unix
```

I left `/etc/kanidm/unixd` as aforementioned, but I did also experiment with adding `unix-login` to the login groups too and that didn't help.

I'm on Kanidm version 1.4.1

When I log in as `luke@example.com` via SSH:

```
$ groups
luke@example.com unix-login@example.com unix-admins@example.com

$ getent group wheel
wheel:x:1:
$ getent group unix-admins
unix-admins@example.com:x:2005447138:luke@example.com
$ getent passwd luke
luke@example.com:x:1989515372:1989515372:Luke:/home/luke:/run/current-system/sw/bin/fish
```

**Comment by Firstyear** [comment]
Can you show the content of /etc/nsswitch.conf?

**Comment by LukeChannings** [comment]
```
passwd:    files kanidm systemd
group:     files kanidm [success=merge] systemd
shadow:    files
sudoers:   files

hosts:     mymachines resolve [!UNAVAIL=return] files myhostname dns
networks:  files

ethers:    files
services:  files
protocols: files
rpc:       files
```

**Comment by Firstyear** [comment]
kanidm has to be before files

**Comment by Firstyear** [comment]
Sorry for the short response earlier - you need `group: kanidm files` because if files is hit first, it returns the whele group data without the extensions kanidm has. nsswitch is "first match wins".

**Comment by LukeChannings** [comment]
Hmm, so after updating `nsswitch.conf` to the following:

```
passwd:    kanidm files systemd
group:     kanidm files systemd
shadow:    files
sudoers:   files
```

I still have the same problem. Is there something else I can check?

**Comment by Firstyear** [comment]
Can you show me:

```
getent passwd wheel
getent passwd unix-admins
getent passwd unix-login
```

Now after you adjusted the nsswitch values? Sorry for the delayed response.

**Comment by LukeChannings** [comment]
```
getent passwd wheel
getent passwd unix-admins
getent passwd unix-login
```

Did you mean `group`?

```
❯ getent group wheel
wheel:x:1:
❯ getent group unix-admins
unix-admins@idm.channings.me:x:2005447138:luke@idm.channings.me
❯ getent group unix-login
unix-login@idm.channings.me:x:1889707309:luke@idm.channings.me
```

Some more info:

```
❯ kanidm group get unix-login
---
class: group
class: object
class: posixgroup
gidnumber: 1889707309
member: luke@idm.channings.me
name: unix-login
spn: unix-login@idm.channings.me
uuid: 4889b959-5c6a-4d30-a41a-795970a2a52d

❯ kanidm group get unix-admins
---
class: group
class: object
class: posixgroup
gidnumber: 2005447138
member: luke@idm.channings.me
name: unix-admins
spn: unix-admins@idm.channings.me
uuid: 9959c20e-a6df-4721-a7c8-0f600788b1e2

❯ kanidm group get wheel
2024-11-19T12:04:03.084470Z  WARN kanidm_cli::group: No matching group 'wheel'
```

**Comment by Firstyear** [comment]
> I have the following in `/etc/kanidm/unixd`:
> 
> ```toml
> [kanidm]
> pam_allowed_login_groups = ["unix-login"]
> 
> [[kanidm.map_group]]
> local = "wheel"
> with = "unix-admins"
> ```

Coming back to this - is this *all* that's in your unixd config? If so that could be the issue - you are missing the "version 2" specifier. It should be:

```toml
version = '2'

[kanidm]
pam_allowed_login_groups = ["unix-login"]

[[kanidm.map_group]]
local = "wheel"
with = "unix-admins"
```

Sorry it took me so long to notice!

**Comment by LukeChannings** [comment]
That was it!

Thank you so much for your support - it's not a small thing and it is appreciated.

**Comment by Firstyear** [comment]
Im going to reopen this tomorrow as I think we should more clearly indicate when a v2 option is used in v1. We failed here by allowing the mistake to be made at all. 

Sorry for taking so long to solve this and I appreciate your patience.

**Comment by LukeChannings** [comment]
You're all doing a great job. Keep up the good work!
