### ISSUE TITLE
Add -q/--quiet switch for parsing

### ISSUE THREAD

**Issue by nlgranger** [kanidm/kanidm#3208]
### Is your feature request related to a problem? Please describe

To automate kanidm manipulation, both kanidm and kanidmd should support a quiet mode. Presently, the lowest verbosity level is info.

### Describe the solution you'd like

Support KANIDM_LOG_LEVEL=ERROR
Output all logs to stderr stream.
Default to ERROR log level when using formatted output (-o json)

### Describe alternatives you've considered

None

### Additional context

Needed for automation https://github.com/kanidm/kanidm/discussions/3155

**Comment by yaleman** [comment]
You should be using the API for automation not the CLI. The CLI JSON mode is for convenience only.

**Comment by nlgranger** [comment]
Got it, thanks.
I would suggest you make this API more visible in the doc. The design document section is not the place where I would look for it intuitively.
