### ISSUE TITLE
"Remember me" not working when coming from OAuth2 app

### ISSUE THREAD

**Issue by tumbl3w33d** [kanidm/kanidm#3210]
### I did this

Press the "login with kanidm" button of one of my connected applications. This led me to `/ui/oauth2`.

### I expected the following

I expected the username field of the login form to be filled with my username.

### This happened instead

The field is empty.

### Kanidm version details

kanidm container 1.4.2
firefox 131.0.3

### Any other comments

When visiting kani via `/ui/login` it works. There is `login_remember_me` set in local storage for both ways, but it is not considered in one of them. There is also the cookie `username` set with my name but it is bound to the path `/ui/login`. You know best which of both is relevant. Maybe one of them is redundant?

**Comment by Firstyear** [comment]
We have an unreleased fix for this :)

**Comment by Firstyear** [comment]
Fixed in 1.4.4

**Comment by EHEX-schildt** [comment]
Not working for me:
kanidm container 1.4.4
Chromium 131.0.6778.85
firefox 131.0.3
