### ISSUE TITLE
no way to re-enable unattested passkeys after setting webauthn-attestation-ca-list

### ISSUE THREAD

**Issue by Be-ing** [kanidm/kanidm#3233]
### I did this

```bash
fido-mds-tool query --output-cert-roots "desc cnt yubikey" > trusted-authenticators
kanidm group account-policy webauthn-attestation-ca-list idm_all_persons "$(<trusted-authenticators)"
kanidm group account-policy credential-type-minimum idm_all_persons any
``` 

### I expected the following
Users can register any passkey because the credential-type-minimum is below attested_passkey.

### This happened instead
Only attested passkeys are allowed to be registered.

Passing an empty string or empty JSON `{}` to `kanidm group account-policy webauthn-attestation-ca-list idm_all_persons` fails with:
```
ERROR kanidm_cli: HTTP Error: 400 Bad Request InvalidAttribute("Invalid Webauthn Attestation CA List")
```

Trying to disable authentication policy also fails:
```
$ kanidm group account-policy disable idm_all_persons
error: unrecognized subcommand 'disable'

  tip: a similar subcommand exists: 'enable'

Usage: kanidm group account-policy <COMMAND>

For more information, try '--help'.
```

### Kanidm version details

- Output of `kanidm(d) version`: 1.4.2
- Are you running it in a container? If so, which image/tag?: yes, latest
- If not a container, how'd you install it:
- Operating System / Version (On Unix please post the output of `uname -a`):
Linux alma-4gb-hel1-2 5.14.0-427.42.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Nov 1 14:58:02 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux

### Any other comments
This prevents administrators from relaxing authentication requirements. I set webauthn-attestation-ca-list to test out Kanidm's attestation functionality with my Yubikey (which worked as expected), but afterwards there is no way to use Bitwarden to register a passkey because Bitwarden doesn't do attestation.

This is unintuitive because "any" and "mfa" authentication policies allow the user to set weaker forms of authentication, but not unattested passkeys.

**Comment by Firstyear** [comment]
Interesting, I was sure I specifically tested that case, but I'll have to double check this assumption. Thanks for the report :)

**Comment by Firstyear** [comment]
I was actually going to say sorry it took so long to fix it :)
