### ISSUE TITLE
`kanidm system domain set-display-name` has no effect on login flow

### ISSUE THREAD

**Issue by boogiewoogit** [kanidm/kanidm#3234]
### I did this
`kanidm system domain set-display-name test123`

### I expected the following
In the login flow, I expected the text "test123" between the logo and the input field.

### This happened instead
It says "Kanidm" (default) where "test123" was expected.

### Discussion
Referring to https://github.com/kanidm/kanidm/issues/1996#issuecomment-2495490457, I think it could be worthwhile to at least have the option to place the "Kanidm" text somewhere else (or leave it at the "powered by Kanidm" at the bottom). As the term "Kanidm" bears no meaning to the majority of people using the login flow (general users), the prominent central position may cause some confusion as to what they're logging into.

### Kanidm version details
- `kanidm version`: `kanidm 1.4.2`
- Not running in a container
- Installed via NixOS module
- `uname -rmo`: `6.6.60 x86_64 GNU/Linux`

**Comment by yaleman** [comment]
Per the linked comment, I'm not going to support removing the Kanidm text from the login screen. Users aren't that silly that they can't understand what Kanidm is, nor any other app in the entire software ecosystem that has its name in the UI.

**Comment by tacerus** [comment]
It already says "Powered by [Kanidm](https://kanidm.com/)" in the corner, I think it makes sense to allow for the full title text to be customizable, particularly in deployments where Kanidm is used as an authentication system for non-technical users.

**Comment by boogiewoogit** [comment]
> Per the linked comment, I'm not going to support removing the Kanidm text from the login screen. Users aren't that silly that they can't understand what Kanidm is, nor any other app in the entire software ecosystem that has its name in the UI.

I know very reasonable people -- far from silly! -- who would have serious trouble understanding what Kanidm is. :)

Is there any downside to giving the option? I must be missing something here, in my mind it's a pareto improvement to the software -- admins who assess it's useful to the type of user they address can make use of it, others don't need to touch it.

**Comment by Firstyear** [comment]
@yaleman I actually agree with the issue report here - I can completely understand why a deployment would want to customise the naming and remove "kanidm" from the main login flow. It was actually my intent for this to already be done with the domain naming feature, but clearly I've missed something.

**Comment by kri164** [comment]
I did upgrade from 1.4.3 to 1.4.4 and this bug remains.

**Comment by kri164** [comment]
It is working now. Thank you.
