### ISSUE TITLE
kanidm-unixd 1.4.3 fails to start when no group maps are defined

### ISSUE THREAD

**Issue by 0xC0ncord** [kanidm/kanidm#3240]
### I did this

I updated the suite of Kanidm from version 1.4.2 to 1.4.3, and now `kanidm-unixd` will not start. It crashes with the following error:
```
Nov 25 13:53:30 petra.fuwafuwatime.moe kanidm_unixd[4145021]: 00000000-0000-0000-0000-000000000000 ERROR    🚨 [error]: You are using version="2" options in a legacy config. THESE WILL NOT WORK.
Nov 25 13:53:30 petra.fuwafuwatime.moe kanidm_unixd[4145021]: 00000000-0000-0000-0000-000000000000 ERROR    🚨 [error]: Failed to parse /etc/kanidm/unixd
Nov 25 13:53:30 petra.fuwafuwatime.moe systemd[1]: kanidm-unixd.service: Main process exited, code=exited, status=1/FAILURE
```
My `/etc/kanidm/unixd` config already has `version = '2'` specified and I have already migrated the required options. But, I am not using any group mappings on this machine. If I instead add a group map of some kind, then `kanidm-unixd` will start.

It appears that starting `kanidm-unixd` without any configured group maps at all confuses it into thinking its config file is still the old legacy version.

### I expected the following
`kanidm-unixd` should start without any group mappings configured.

### Kanidm version details

- Output of `kanidm(d) version`: `kanidmd 1.4.3`
- Are you running it in a container? If so, which image/tag?: No
- If not a container, how'd you install it: Compiled from source
- Operating System / Version (On Unix please post the output of `uname -a`):
```
Linux petra.fuwafuwatime.moe 6.8.9-gentoo-hardened1 #2 SMP Fri May  3 20:34:37 EDT 2024 x86_64 Intel(R) Xeon(R) CPU E5-2650L v4 @ 1.70GHz GenuineIntel GNU/Linux
```

**Comment by 0xC0ncord** [comment]
I found that adding `group_map = []` under `[kanidm]` in my config file is enough to work around this for now.

**Comment by Firstyear** [comment]
Sorry for this mistake, I'll backport the fix asap.
