### ISSUE TITLE
Self write email wrong group

### ISSUE THREAD

**Issue by johansmitsnl** [kanidm/kanidm#3247]
### I did this

`kanidm group add-members idm_people_self_write_mail account.name --name idm_admin`

### I expected the following

`Successfully added`

### This happened instead

```
2024-11-29T12:32:07.802781Z ERROR kanidm_cli: OperationId: "adf801e7-8b9e-47a7-838b-33a45780846c"
2024-11-29T12:32:07.802800Z ERROR kanidm_cli: Item not found: Check all names are correct.
```

### Kanidm version details

- Output of `kanidm(d) version`: `1.4.3`
- Are you running it in a container? If so, which image/tag?: `docker.io/kanidm/server:1.4.3`
- If not a container, how'd you install it:
- Operating System / Version (On Unix please post the output of `uname -a`):

### Any other comments

I found #2823 where the change is made. But on a new server install the group is called `idm_people_self_mail_write`. But when added it does not give the account permissions to make changes.

Don't know if the book is incorrect or if there is a bug in the UI?

**Comment by gbw** [comment]
The docs need to be updated. The expected group is `idm_people_self_mail_write`.

With the correct group this is working for me. 
```
kanidm person create testing "Testing Human"
kanidmd recover-account testing
kanidm group add-members idm_people_self_mail_write testing
kanidm person update testing -m testing@example.com -D testing
kanidm person get testing
```
