### ISSUE TITLE
Add code coverage and basic PR CI

### ISSUE THREAD

**Issue by droideck** [kanidm/kanidm#325]
It'll be nice to run tests on PR creation and, additionally, check the code coverage.
GitHub Actions can be used but also there are plenty of other options. :)

**Comment by Firstyear** [comment]
@pando85 Do you have any ideas here? I know you worked on the CI with github actions, so any insight into code coverage tools too?

**Comment by pando85** [comment]
I will add this when I decide how to make in rash-sh/rash#39.

**Comment by Firstyear** [comment]
Sounds awesome, thanks @pando85 :D

**Comment by Firstyear** [comment]
This exists now :)
