### ISSUE TITLE
Install: ERROR: Refusing to run - this process must not operate as root.

### ISSUE THREAD

**Issue by vDorst** [kanidm/kanidm#327]
I am trying to setup kanidm by following this guide. https://github.com/kanidm/kanidm/blob/master/kanidm_book/src/installing_the_server.md

Instead of using `docker` I am using `podman` with `kata runtime`.
Also the container has a full dual-stack network.
Running on a Fedora 32 machine.

I get in trouble with this line.
```
podman run --rm -i -t -v kanidmd:/data kanidm/server:latest /sbin/kanidmd recover_account -c /data/server.toml -n admin
```

kanidmd refuses to run as root.
```
5790b7e3fc59:/ # /sbin/kanidmd recover_account -c /data/server.toml -n admin
ERROR: Refusing to run - this process must not operate as root.
```

Which is good, but the documentation doesn't mention that.
Also the docker hub image doesn't have a user.
But also missing the tools like `adduser` or `useradd`, for creating a newuser.

What I am doing wrong?

**Comment by pando85** [comment]
I don't use postman but did you tried with `--user 1000` or whatever uid different from 0?

**Comment by Firstyear** [comment]
This is a really good point, the changes to limit access to root user came in more recently. A choice here could be either to only warn when running as root rather than hard deny, or to improve that documentation clarity. I believe that there are some issues with permissions/ownership in volumes when running as non root, so that would need to be checked too. I'm keen to make sure that peoples "first run" is very seamless/smooth, so perhaps allowing root user is the way to go, and in hardening we suggest how to use the --user options and setup the volume permissions. What do you think?

**Comment by pando85** [comment]
On my site with one warning could be enough and people could use root for developing, testing or whatever.

**Comment by vDorst** [comment]
@pando85 add `--user <someuser_on_the_host>` works.
But I am hitting the next issue `Error: unable to find user kanimd: no matching entries in passwd file`.

I am not sure if `podman` should populate the user in the /etc/passwd of the container.
I tried many runtime like `kata`, `crun` and `runc`. But all of them returns the same error.

@Firstyear 
I don't have the right knowledge to give a good suggestion about that.

In my case, use `podman` with the `kata` runtime.
The container becomes a small virtual machine.
So running as root is less of an issue in my case.

Other solution what comes in mind.

The image a by default the user `kanidm`.
So I can run the commands as `kanidm` or program drop privileges when running as root.
I think I need root to run the https server on port 443?
In my case every container gets a network accessible ipv4 and ipv6 address.

**Comment by Firstyear** [comment]
well, docker lets you re-map the ports, so you should be able to bind port 443 from the container engine to 8443. Additionally, we could use capabilities to allow non-root binding to port 443 as well.

But I think that in this case allowing it to run as root would smooth this onboarding, but we should still warn about it.

**Comment by vDorst** [comment]
`podman` does the same.

It is my setup that is different than how normal people using a container.

**Comment by Firstyear** [comment]
Ohh also, you need to use --user <uidnumber> not the username, because the /etc/nsswitch.conf in the container can't see users from the host.

**Comment by pando85** [comment]
```
Error: unable to find user kanimd: no matching entries in passwd file.
```
That's a real problem.

You could try something like this for ports: https://docs.docker.com/engine/security/rootless/#exposing-privileged-ports

**Comment by vDorst** [comment]
@Firstyear Yes you are right about `--user` switch. I need the `uid` not the `user`.

Still I get this. 
```
[root@ipa ~]# podman run --network=host --runtime=crun --rm -i -t --user 975 -v kanidmd:/data kanidm/server:latest /bin/bash
975@ipa:/> whoami
975

975@ipa:/> /sbin/kanidmd recover_account -c /data/server.toml -n admin
ERROR: Refusing to run - this process must not operate as root.

975@ipa:/> cat /etc/passwd
root:x:0:0:root:/root:/bin/bash
975:*:975:0:container user:/:/bin/sh

975@ipa:/> /sbin/kanidmd recover_account -c /data/server.toml -n admin
ERROR: Refusing to run - this process must not operate as root.
```

**Comment by Firstyear** [comment]
`-u 975:975`. The gid is still 0, which is equivalent to root.

**Comment by vDorst** [comment]
@Firstyear yes that was the issue.
Now it works.

**Comment by Firstyear** [comment]
@vDorst can you please review the changes to https://github.com/kanidm/kanidm/pull/328/files for the book chapters based on this?

**Comment by Firstyear** [comment]
Thanks @vDorst for the report, if you have any other questions, usability issues, or comments, we'd love to hear them!
