### ISSUE TITLE
Unhanded error when using credential reset token

### ISSUE THREAD

**Issue by gbw** [kanidm/kanidm#3288]
### I did this
Used a reset token and attempted to save TOTP & password. Got InvalidState. After clearing cookies TOTP and password saving was possible.

### I expected the following
TOTP & password to be saved successfully or an error message informing me to restart the flow due to timeout.

### This happened instead
InvalidState returned.
Logs:
```
723c8bb2-5c3f-45d8-b0a7-1e9f9d7f2bc7 INFO     request [ 15.5ms | 92.70% / 100.00% ] method: POST | uri: /ui/api/cu_commit | version: HTTP/1.1
723c8bb2-5c3f-45d8-b0a7-1e9f9d7f2bc7 INFO     ┝━ handle_idmcredentialupdatecommit [ 1.13ms | 7.30% ]
723c8bb2-5c3f-45d8-b0a7-1e9f9d7f2bc7 INFO     │  ┝━ ｉ [info]: Session originated from an intent token, but the intent token has initiated a conflicting second update session. Refusing to commit changes. | event_tag_id: 10
723c8bb2-5c3f-45d8-b0a7-1e9f9d7f2bc7 ERROR    │  ┕━ 🚨 [error]: Failed to begin commit_credential_update | err: InvalidState
723c8bb2-5c3f-45d8-b0a7-1e9f9d7f2bc7 ERROR    ┝━ 🚨 [error]:  | latency: 1.280185ms | status_code: 500 | kopid: "723c8bb2-5c3f-45d8-b0a7-1e9f9d7f2bc7" | msg: "error handling request"
723c8bb2-5c3f-45d8-b0a7-1e9f9d7f2bc7 ERROR    ┕━ 🚨 [error]: response failed | classification: Status code: 500 Internal Server Error | latency: 1 ms
```
### Kanidm version details

- Output of `kanidm(d) version`: `kanidmd 1.4.4`
- Are you running it in a container? If so, which image/tag?: `1.4.4`
- If not a container, how'd you install it:
- Operating System / Version (On Unix please post the output of `uname -a`): `6.1.0-28-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.119-1 (2024-11-22) x86_64 GNU/Linux`

**Comment by Firstyear** [comment]
```
Session originated from an intent token, but the intent token has initiated a conflicting second update session. Refusing to commit changes.
```

They used the reset token twice, possibly in separate tabs, which led to a conflict of the inflight sessions. Can't really do much here :(

**Comment by gbw** [comment]
Could this also happen if the browser was switched in an attempt to get passkey working?

**Comment by Firstyear** [comment]
Yep, because the session token was used on browser A which left the session open (they didn't click cancel). Then browser B starts a session, makes changes but then goes "opps, there is a session on A that's still there, something is wrong".

**Comment by gbw** [comment]
Okay that's probably what happened. Should there be better feedback to the user? i.e. Instead of InvalidState, display Token is invalid, expired, or already used.

**Comment by Firstyear** [comment]
Yes, we should probably give some better feedback here :)

**Comment by Firstyear** [comment]
@gbw Going to fix this today :)
