### ISSUE TITLE
InvalidState when accessing user credentials through web UI

### ISSUE THREAD

**Issue by coutnoah** [kanidm/kanidm#3292]
### I did this
I wanted to add a second passkey to my account and decided to add it through the web UI. After authenticating with my YubiKey to access the credentials page instead of sending me back to the credentials page it gave me an error.

### I expected the following
To be sent right to the user credential page.

### This happened instead
I got an error message indicating "InvalidState". The page URL ends with "/ui/oauth2/resume".
![image](https://github.com/user-attachments/assets/641195d3-2318-4b08-b4f7-335e70d85d6a)
Refreshing the page would keep the error open but change the Operation ID. I was able to bypass the error by going back to the apps page, then navigating to the credentials page. This seems to indicate that I authenticated successfully, but somehow an error comes up after I first authenticate with my passkey.

### Kanidm version details

- Output of `kanidm(d) version`: kanidm 1.4.4
- Are you running it in a container? If so, which image/tag?: no
- If not a container, how'd you install it: bare metal
- Operating System / Version: NixOS 24.11 (Linux 6.8.12-5-pve)

### Any other comments
I am able to replicate this every time I need to reauth for the credentials menu, so I can get additional logs.
I do get the same "InvalidState" error page when trying to use OAuth with a new Gitea server I am setting up. I am unsure if this is related, but I believe that may be due to bad configuration I still need to iron out on my end.

**Comment by coutnoah** [comment]
Maybe this issue is related #3269 & #3288. Looks like they are having authentication issue too.

**Comment by Firstyear** [comment]
@coutnoah The operation ID is the uuid in the logs related to the error and what went wrong. 

It sounds like the same issue with the cookies, did the issue occur again after a refresh?

**Comment by coutnoah** [comment]
As mentioned before refreshing the page would keep the "InvalidState" error page open but change the Operation ID. So it seems like it is stuck in that state unless I go back to the apps page, then when I go back to accessing credentials it will load (as the session for that elevated permission should be active during that time).

I can look to reproduce it and gather logs of some sort if you'd like. Although I am pretty new to Kanidm and wouldn't mind some step by step guidance to do this.
