### ISSUE TITLE
Logo/images with the Australian Coat of Arms need replacing

### ISSUE THREAD

**Issue by yaleman** [kanidm/kanidm#343]
https://pmc.gov.au/government/commonwealth-coat-arms

> Individuals can apply to PM&C for permission in writing to use the Commonwealth Coat of Arms (refer to the Guidelines for contact details). PM&C has discretion to grant permission in limited circumstances, including: for education and for Australian teams competing in international competitions.
> 
> Use of the Commonwealth Coat of Arms without permission may breach the Competition and Consumer Act 2010, the Trade Marks Act 1995 and the Criminal Code Act 1995.

**Comment by Firstyear** [comment]
Thanks for raising this @yaleman. I have contacted PM&C about this for their advice. As the logo is stylised, it may not infringe, but it is certainly better to do the correct thing by the authorities in this matter, and to find out the correct course of action. Thanks again,
