### ISSUE TITLE
hidden name history

### ISSUE THREAD

**Issue by Firstyear** [kanidm/kanidm#345]
It may be useful to have a "name history" for previous legalname/displaynames/name fields so that username changes and associations can be looked up post-fact. this is a sensitive field so should be protected by default. 

Again, knowing the use cases here would be good. From a security view, to track the history of changes, it may be better to have an audit/event system (which is already a planned feature), where as from a support or service desk view it could be useful for undoing/rolling back changes (but this could also be done via the repl changelog.). 

If this implemented the feature should have a boolean config in the domain config, disabled by default. 

If enabled, another option is to prevent re-use of an already claimed name. IE if someone is named 'a' and renames to 'b', then no other account should be able to claim the name 'a' - it effectively becomes "archived". A question is how to handle this when the account is deleted. If the name should be "forever" archieved. 

Note that an abuse prevention is needed here so that if they name changes "too much" then it is disallowed or requires admin intervention.

**Comment by MinhPhan8803** [comment]
Was the event system ever implemented? If so we might just be able to implement it for database name changes.
Wrt the claimed name, I think we may be able to track names *and* a unique user id. Then we can say that name "a" used to belong to people "c" "b" "d" such and such, without having to freeze the name.
Abuse prevention policy might also be made to be admin bound? They can specify if users can change name an indefinite number of times, or limit it to some specific value.
I'm just gathering ideas here. Also the non empty vec might prove useful here for querying name change events.

**Comment by Firstyear** [comment]
There is an easier way! 

If you have a look at https://github.com/kanidm/kanidm/blob/master/server/lib/src/server/modify.rs you'll see there are calls to "plugins" which are kind of like layered transformers. For example https://github.com/kanidm/kanidm/blob/master/server/lib/src/plugins/cred_import.rs 

On a modify operation the plugin is given the entries before and after state so you can use that to compare the name to see if it changed. If it did, you can just append the old name to a list inside the currently changing entry. You could probably also add the CID (change id) of when the name was changed too into that list so you can see "the account had name X until CID A, and then changed to it's current name".

Does that make sense?

WRT to the name changing policy, that I think could be a part of the plugin in the future which can see the name is changing and then make other decisions. But lets start simple and just have the history to start with.

**Comment by MinhPhan8803** [comment]
So from what I gather, Plugin is essentially a trait that takes in the new and old entries, and a db transaction then let you do whatever with them, is that correct?

**Comment by Firstyear** [comment]
It's more like a "transformer" during a transaction. The modify operation is already within a transaction and each plugin is allowed to alter or reject the content of the entries during that transaction. So yes, you can still edit the entries from within the plugin based on what the user has done.

**Comment by MinhPhan8803** [comment]
My take is that one possible approach is to just write a new plugin that checks if name is modified during the transaction. For the list I'm thinking of a `lazy_static!` which would survive as long as a server still run, would that be feasible?

**Comment by Firstyear** [comment]
Why would we only want it stored in memory? We want it written to the entry itself.

Remember in the modify plugin hook you get _cand: &mut Vec<EntryInvalidCommitted>, so you can just add the name to name_history on the entry itself so that it's preserved forever.

**Comment by MinhPhan8803** [comment]
Would that require a modification to the entry struct then?

**Comment by Firstyear** [comment]
What do you mean a modification to the entry struct? The entry struct doesn't need to change, you just have to update some data within it's attribute map.

**Comment by MinhPhan8803** [comment]
Wait I didn't realize `attrs` was a map, I see how this would work now. That makes a lot of sense, thanks :)

**Comment by Firstyear** [comment]
Yeah, there are examples of this in other areas of the plugins. password_import might give you some ideas and is pretty simple to read IMO. :)

**Comment by MinhPhan8803** [comment]
I will read through them :)

**Comment by Firstyear** [comment]
> I will read through them :)

Yeah, a skill is being able to read what already exists and work from there to how problems could be solved. So this is a good idea for you :)

**Comment by Firstyear** [comment]
And of course, don't think the code that already exists is perfect - i'm only human and it's probably flawed too, so if you have questions, please ask.

**Comment by MinhPhan8803** [comment]
Aight thank you!
