### ISSUE TITLE
name deny list

### ISSUE THREAD

**Issue by Firstyear** [kanidm/kanidm#346]
we have some regex at the moment for removing certain username patterns that could cause technical issues, but to supplement this we should also have a deny list of usernames that are known problematic. IE root, www-data, apache etc. Names that should never be in a directory service. 

A more "questionable" feature is a "deny pattern" feature, but that has a *lot* of risks of excluding people, so that's still very much up for discussion still.

**Comment by Firstyear** [comment]
We actually have already evolved this list in the server - the question now is if we allow user configuration to extend this list? @yaleman

**Comment by yaleman** [comment]
Can I push back on the "never allowed in a directory service" bit? Because I could see global role/permissions management being a thing for accounts like `www-data` and `apache`.

I agree with `root` not being allowed though 😄 

Thinking about how to make it configurable/usable from an admin perspective, I wouldn't want it in a config file, because ew - maybe have an account class-attribute-thing of "blocked" or "shadow" to allow them to be created/managed using the usual tooling, but not usable from the auth handlers? 🤔 I'm probably overcomplicating it though, and a list of strings in the database would do it 😁

**Comment by Firstyear** [comment]
Yeah, I think list of strings in the db. I'll have to think a bit about "where" this should go though, but it's do-able. Currently we *do* deny things like www-data and apache out of box though.

**Comment by Firstyear** [comment]
@yaleman Is this issue still needed? We now have a better solution with the unix daemon filtering names that are in /etc/passwd so that we don't name collide to system accounts. So I think that now there isn't really a need for this feature since any use who was renamed to say "root" will be allowed in Kani, and immediately won't work in a unix system. 

IMO we can close this unless there becomes another valid reason to deny names / name patterns.

**Comment by yaleman** [comment]
The main reason at this point I could see is enforcing it at a organisation level, stopping names with particular problematic terms in them (either culturally or because a team/product/division has been renamed). Is that something we could do in account policy instead?

**Comment by Firstyear** [comment]
Yeah, but then it would only apply to accounts affected by that policy, rather than globally. I guess it could be a global thing though on the global policy, but I think if you were denying problematic names, you wouldn't scope it to specific groups of users, but all users.

**Comment by yaleman** [comment]
I'd expect the ability to set global policy so environments could enforce particular policies such as this.

**Comment by Firstyear** [comment]
Okay, I think it's still seperate to account policy though. I think it should be domain wide name deny if we do this.

**Comment by yaleman** [comment]
It seems to me like it'd be *easier* to implement domain-wide settings as an account policy that has an `And()` to match every account, since we don't have to build a separate "domain-wide policy" system?

**Comment by Firstyear** [comment]
Actually it'll be harder because I was planning for account policy to be bound to groups, and there is a default policy on idm_all_persons that can be changed. But then it would mean we have to Or() the denied names between every account policy group that matches a user.

When really if there are denied names, they are denied for everyone. So similar to the PW badlist, we stuff it into the domain config object, and move on.

**Comment by yaleman** [comment]
ok, with the additional context that makes sense 😄
