### ISSUE TITLE
Using LetsEncrypt TLS certificate results in error: "unable to get local issuer certificate"

### ISSUE THREAD

**Issue by vDorst** [kanidm/kanidm#356]
Build from source Source: commit d745b15768ce0269776db339743f6516b0b5008f using the kanidmd/Dockerfile.

I am trying use a Letsencrypt certificate to secure the idm server.

First issue is that checking the certificate locally with `openssl` already fails.

```
openssl verify -show_chain -CAfile fullchain.pem cert.pem
C = US, O = Let's Encrypt, CN = R3
error 2 at 1 depth lookup: unable to get issuer certificate
error cert.pem: verification failed
```

This can be solved to add Root X3 certificate to the `fullchain.pem`.
Download root x3 and place it in `rootx3.pem`.
```
cat rootx3.pem fullchain.pem > ca.pem
openssl verify -show_chain -CAfile ca.pem cert.pem
cert.pem: OK
Chain:
depth=0: CN = <my FQDN> (untrusted)
depth=1: C = US, O = Let's Encrypt, CN = R3
depth=2: O = Digital Signature Trust Co., CN = DST Root CA X3
```

I copied the created `ca.pem`, `cert.pem` and `privkey.pem` to the container volume.
Also checked with `openssl` in the container that the certificate is valid.

```
podman run --rm -i -t -v kanidmd:/data alpine /bin/sh
/ # apk add openssl
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/x86_64/APKINDEX.tar.gz
(1/1) Installing openssl (1.1.1i-r0)
Executing busybox-1.32.1-r2.trigger
OK: 6 MiB in 15 packages

/ # cd /data/
/data # openssl verify -show_chain -CAfile ca.pem cert.pem
cert.pem: OK
Chain:
depth=0: CN = <my FQDN> (untrusted)
depth=1: C = US, O = Let's Encrypt, CN = R3
depth=2: O = Digital Signature Trust Co., CN = DST Root CA X3
```

Firefox reports that the connection is secure.
Log shows:
```
[tide::log::middleware] <-- Request received
[tide::log::middleware] Client error --> Response sent
```

When using `./kanidm login -H https://<my FQDN>:8443 -D admin` I get this error.
```
[2021-02-11T15:05:44Z ERROR kanidm_cli::login] Error during authentication init phase: Transport(reqwest::Error { kind: Request, url: Url { scheme: "https", host: Some(Domain("<my FQDN>")), port: Some(8443), path: "/v1/auth", query: None, fragment: None }, source: hyper::Error(Connect, Ssl(Error { code: ErrorCode(1), cause: Some(Ssl(ErrorStack([Error { code: 337047686, library: "SSL routines", function: "tls_process_server_certificate", reason: "certificate verify failed", file: "ssl/statem/statem_clnt.c", line: 1913 }]))) }, X509VerifyResult { code: 20, error: "unable to get local issuer certificate" })) })
```
Log shows: `[tide_rustls::tls_listener] tls error`.

I also tried `openssl s_client`.

`echo '' | openssl s_client -connect localhost:8443 -servername <my FQDN>`

```
CONNECTED(00000003)
depth=0 CN = <my FQDN>
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN = <my FQDN>
verify error:num=21:unable to verify the first certificate
verify return:1
depth=0 CN = <my FQDN>
verify return:1
---
Certificate chain
 0 s:CN = <my FQDN>
   i:C = US, O = Let's Encrypt, CN = R3
---
Server certificate
-----BEGIN CERTIFICATE-----
<SNIP>
-----END CERTIFICATE-----
subject=CN = <my FQDN>

issuer=C = US, O = Let's Encrypt, CN = R3

---
No client certificate CA names sent
Peer signing digest: SHA512
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 1879 bytes and written 388 bytes
Verification error: unable to verify the first certificate
---
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Server public key is 2048 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 21 (unable to verify the first certificate)
---
DONE
```

It seems that `CA certificate` is not send.

What I am doing wrong?

My server.toml
```
# The webserver bind address. Will use HTTPS if tls_* is provided.
# Defaults to "127.0.0.1:8443"
bindaddress = "127.0.0.1:8443"
# The read-only ldap server bind address. will use LDAPS if tls_* is provided.
# Defaults to "" (disabled)
# ldapbindaddress = "127.0.0.1:3636"
# The path to the kanidm database.
db_path = "/data/db/kanidm.db"
# If you have a known filesystem, kanidm can tune sqlite to match. Valid choices are:
# [zfs, other]
# If you are unsure about this, default to other
# zfs:
# * sets sqlite pagesize to 64k, you should set recordsize=64k on the zfs filesystem.
# db_fs_type = "zfs"
# TLS ca, certificate and key in pem format. All three must be commented, or present
tls_ca = "/data/ca.pem"
tls_cert = "/data/cert.pem"
tls_key = "/data/privkey.pem"
# The log level of the server. May be default, verbose, perfbasic, perffull
# Defaults to "default"
log_level = "default"
origin = "https://<my FQDN>"
```

**Comment by Firstyear** [comment]
Okay, I think I understand the problem.

We changed from actix to async + tide a while ago. We preferred the use of openssl to keep everything consistent, but we haven't been able to use it with tide ( https://github.com/kanidm/kanidm/issues/341 ) because openssl async uses a different asyncread/asyncwrite trait which is conflicting. IIRC the issue stems from an issue between futures-rs and tokio, but I can't remember completly.

Anyway, this means, ldaps is using openssl, and tide is using rustls. 

Now looking at the rusttls setup code, it only accepts cert and key. It's not clear from https://docs.rs/tide-rustls/0.2.0/tide_rustls/struct.TlsListenerBuilder.html#method.cert if cert here should be a chain or only the cert.

So as a result, it appears the https interface only has the leaf cert and the key, not the CA being presented.

As a result, I think this IS a bug, and necessitates the use of https://docs.rs/tide-rustls/0.2.0/tide_rustls/struct.TlsListenerBuilder.html#method.config so that we can load the full chain correctly. Alternately, I could just get over my fear, and implement tide-openssl already so that we can go back to using the SslAcceptorBuilder.

**Comment by Firstyear** [comment]
Alternately, we could alter the config to be tls_chain which has the same format as haproxy expects, and may be a bit clearer and easier to parse. Need to check what openssl supports here for that.

**Comment by Firstyear** [comment]
https://docs.rs/openssl/0.10.32/openssl/ssl/struct.SslAcceptorBuilder.html#method.set_certificate_chain_file

I'm thinking we could do both - we make it use the chain in the mean time, and improve the tls docs around that, and then work toward tide-openssl at the same time. That would solve the immediate problem, and longer term bring up back to a single crypto provider. Thoughts @vDorst ? Remember that as these are alphas I'm not likely to patch 'older' releases so for now haproxy in front may work, or you can use a devel docker release when I apply this fix.

**Comment by vDorst** [comment]
@Firstyear Thanks for explaining the issue.

Your proposed solution sound good for me.
I think providing good documentation about generation the chained certificate and maybe howto locally verify that the certificates are in the right order would be great.
For me it takes always some googling howto use Openssl to verify certificates and sorting out the issue I encounter while using Openssl. For example the Openssl could not verify because of the missing Root X3 certificate.

With the provided dockerfile I can build from GitHub source so testing out some new code should not be an issue.

**Comment by vDorst** [comment]
With your comments above I made this changes: https://github.com/vDorst/kanidm/commits/356-chained-certs
Now it works fine with a chain certificate. Both on https and ldaps connection.
