### ISSUE TITLE
[doc] Why do you want kanidm?

### ISSUE THREAD

**Issue by Firstyear** [kanidm/kanidm#359]
We should document in our introduction a "topology" of where Kanidm fits into your environment, and why you may choose to deploy it in a variety of situations.

**Comment by soloturn** [comment]
very cool, would love to understand how kanidm fits with vaults, like hashicorp vault.

**Comment by Firstyear** [comment]
This has been requested before, https://github.com/kanidm/kanidm/issues/248 :)
