### ISSUE TITLE
recover_account command missing

### ISSUE THREAD

**Issue by teroz** [kanidm/kanidm#377]
Am trying to run to follow the quickstart instructions and it seems there is no recover_account command as per the README - Am I missing something obvious

**Comment by vDorst** [comment]
https://github.com/kanidm/kanidm/blob/master/kanidm_book/src/installing_the_server.md
maybe a typo? `kanidm` instead of `kanidmd` ?

**Comment by Firstyear** [comment]
Can you please show the command line you were trying to run? I think it works here:

```
# docker run --rm -i -t kanidm/server:latest kanidmd --help
...
SUBCOMMANDS:
    backup                Backup the database content (offline)
    domain_name_change    Change the IDM domain name
    help                  Prints this message or the help of the given subcommand(s)
    recover_account       Recover an account's password
    reindex               Reindex the database (offline)
    restore               Restore the database content (offline)
    server                Start the IDM Server
    verify                Verify database and entity consistency


# docker run --rm -i -t kanidm/server:latest kanidmd recover_account --help
...
kanidmd-recover_account 1.1.0-alpha.3
Recover an account's password

USAGE:
    kanidmd recover_account [OPTIONS] --config <config-path> -n <name>
```

If you are doing this from within the source tree, you need to do:

```
cd kanidmd
cargo run -- recover_account --help
```

**Comment by teroz** [comment]
> maybe a typo? `kanidm` instead of `kanidmd` ?
> 
> You have to inside directory `<this repo>/kanidmd/` before running `cargo run -- recover_account -c ./server.toml -n admin`.
> `recover_account` is part of the Kanidm server.

Gosh that was the issue - I had discerned that I should have been running the command against the server bin - thank you @vDorst @Firstyear

**Comment by Firstyear** [comment]
@teroz No problem at all - let us know if you have any other issues :)
