### ISSUE TITLE
Created home directory is inconsistant with nss

### ISSUE THREAD

**Issue by Flakebi** [kanidm/kanidm#378]
Hi,
After the recent merge of the unixd-tasks daemon, I tried out connecting kanidm to pam and nss. I finally got it working with a few smaller problems.
The created home directory is stripped of special characters like `\` and `.`, however the `HOME` exposed by the nss daemon (and `getent passwd user`) still contains the special chars.
So, the home directory is not found e.g. for the user spn `user@example.com`, because the actually created home directory is `user@examplecom`.

Stripping in the tasks daemon happens here:
https://github.com/kanidm/kanidm/blob/b620a8209c26920917dfff0f3558297f6f3a1030/kanidm_unix_int/src/tasks_daemon.rs#L127-L128

**Comment by Firstyear** [comment]
Yes, I should process these both the same way. 

I think there is an issue that the replace(".") should actually only relpace the first dot.
