### ISSUE TITLE
Cannot change loginshell via kanidm account posix set

### ISSUE THREAD

**Issue by Flakebi** [kanidm/kanidm#379]
I tried changing the posix shell of a user by executing `kanidm` again, but it doesn’t work.

Steps to reproduce:
```bash
kanidm account create testuser testuser
kanidm account posix set --shell /bin/sh testuser
kanidm account posix set --shell /bin/bash testuser
# Fails with Error -> Http(400, Some(SchemaViolation(InvalidAttributeSyntax("loginshell"))), "5b62715c-023a-450f-a4e0-8e684cdaafcf")
```

I ended up deleting the loginshell with raw commands: `kanidm raw modify '{"eq":["name","testuser"]}' mod.json`
mod.json:
```json
[
    { "purged": "loginshell" }
]
```

**Comment by Firstyear** [comment]
Yep, this is certainly a bug :) I'll resolve this and #378 early next week.
