### ISSUE TITLE
Add fall back shell option

### ISSUE THREAD

**Issue by Firstyear** [kanidm/kanidm#392]
If the shell doesn't exist, we should have a fallback option available.

**Comment by cuberoot74088** [comment]
Hi @Firstyear,

would this be simply `/bin/sh`?
And the fall back would need to be set/provided by the `unixd`?

**Comment by Firstyear** [comment]
I think this would be configurable in the `/etc/kanidm/unixd` config, but would default to `/bin/sh`. The actually fallback would have to be injected here : https://github.com/kanidm/kanidm/blob/master/kanidm_unix_int/src/cache.rs#L267 

The reason is that when we are logging in we cache the usertoken on first access in pam, but then when the pam session is opened we are now using that cached version. So about line 267 we need to check that the shell in the user token exists, and if not, we over-write it with our fallback option. Does that help?

**Comment by Firstyear** [comment]
I think we'd also need to move this logic: https://github.com/kanidm/kanidm/blob/master/kanidm_unix_int/src/cache.rs#L648 for this to work properly.

**Comment by cuberoot74088** [comment]
Well, with some help (I think), I could give it a try.

**Comment by cuberoot74088** [comment]
A first question would be, should we better default to `/bin/sh` instead of `/bin/bash`, which is currently mentioned in several places?

**Comment by Firstyear** [comment]
Of course, we'd be happy to have you try this! I think we should default to /bin/sh as you say. If you want start to make a PR with the code changes, and we are always have to review, help and answer questions. Thank you!

**Comment by cuberoot74088** [comment]
Great, let's give it a try. :grinning: 

Regarding the change to `/bin/sh`, I would propose to create a new issue to have a cleaner PR as it will touch several places.

For the check _does the user_shell exists_, I am thinking of using something like `Path::new(user_shell).exists()` and do the shell assignment given on the outcome.

If I understand this correctly, we would need to update the `token.shell` property(?). Like here https://github.com/kanidm/kanidm/blob/master/kanidm_unix_int/src/cache.rs#L277

but as far as I can see, the `update_account` would not update the `shell` only a few other things.
https://github.com/kanidm/kanidm/blob/master/kanidm_unix_int/src/db.rs#L307

How should this be done in the best way? Extend this or create an new _update_shell_ function?

Seems like it would be best to extend and add it here 
https://github.com/kanidm/kanidm/blob/master/kanidm_unix_int/src/db.rs#L334
like this `UPDATE account_t SET shell=:shell, ...`

Best regards

**Comment by Firstyear** [comment]
> Great, let's give it a try. 😀
> 
> Regarding the change to `/bin/sh`, I would propose to create a new issue to have a cleaner PR as it will touch several places.
> 
> For the check _does the user_shell exists_, I am thinking of using something like `Path::new(user_shell).exists()` and do the shell assignment given on the outcome.

Sounds reasonable to me. 

> 
> If I understand this correctly, we would need to update the `token.shell` property(?). Like here https://github.com/kanidm/kanidm/blob/master/kanidm_unix_int/src/cache.rs#L277
> 
> but as far as I can see, the `update_account` would not update the `shell` only a few other things.
> https://github.com/kanidm/kanidm/blob/master/kanidm_unix_int/src/db.rs#L307
> 
> How should this be done in the best way? Extend this or create an new _update_shell_ function?

The database is storing a full blob of the account. If you look at the db code, the UnixUserToken is serialised and then stored as is - there aren't special columns. See here:

https://github.com/kanidm/kanidm/blob/master/kanidm_unix_int/src/db.rs#L333

Notice we store "token" after we serialise it here: https://github.com/kanidm/kanidm/blob/master/kanidm_unix_int/src/db.rs#L308 

When we need to access it, we deserialise and load it with https://github.com/kanidm/kanidm/blob/master/kanidm_unix_int/src/cache.rs#L166

So since there is only one place where we call update account https://github.com/kanidm/kanidm/blob/master/kanidm_unix_int/src/cache.rs#L166 then we only need to adjust the token's shell property once at the time we go to persist it. This means that every subsequent "cached" call, will benefit from our adjustment at this point. So I still think we should do the check in https://github.com/kanidm/kanidm/blob/master/kanidm_unix_int/src/cache.rs#L259 rather than adding new functions. :) 

Does that help?
