### ISSUE TITLE
Trouble committing to fork?

### ISSUE THREAD

**Issue by QnnOkabayashi** [kanidm/kanidm#395]
Hello, I'm new to the open source community and trying to get started. I was able to create my own fork, but I think one of the configuration files is blocking me from committing changes to the fork because it detects changes in files, even though I haven't modified them at all. An example is 
```
Diff in local/path/to/kanidm/kanidmd_web_ui/src/login.rs at line 98:
                 ConsoleService::log(format!("next -> {:?}", state).as_str());
                 true
             }
-            LoginAppMsg::DoNothing => {
-                false
-            }
+            LoginAppMsg::DoNothing => false,
         }
     }
```
even though I never knowingly modified this file. 

The modifications I made were to `kanidm/kanidm_rlm_python/entrypoint.py`, and I also added my own directory with some contents, `kanidm/kanidm_rlm_rust/`. Neither of these should impact the other files it says there are differences in.

How can I get around this?

**Comment by victorcwai** [comment]
This is probably due to running `cargo fmt`. 
I guess some of the code changes are not yet formatted in #391? @Firstyear 

However it should not prevent you committing changes in `kanidm/kanidm_rlm_python/entrypoint.py`.

**Comment by Firstyear** [comment]
I think @victorcwai is spot on here - likely it's that you are using a cargo/rust version greater than 1.47. Sadly I have to pin to 1.47 due to a limitation within linux distributions involving firefox. I'm trying to work to resolve this but for now, you can either:

* avoid running cargo fmt
* set an override with rustup with:

```
cd kanidm
rustup override set 1.47.0
```

Hope that helps!

**Comment by QnnOkabayashi** [comment]
> rustup override set 1.47.0

This fixed my issue, thank you!
