### ISSUE TITLE
Caching for password badlist

### ISSUE THREAD

**Issue by victorcwai** [kanidm/kanidm#397]
As per discussion in #159 and #394, implement a cache for password badlist in memory since it will be frequently accessed.
Then we can pass the cached map of badlist by reference rather than by value.

**Comment by victorcwai** [comment]
Hey @Firstyear I got some free time and wanna continue on this. 

I think the cache should be refreshed when users run `badlist_preprocess.rs` (e.g. make a API call that will update the cache).
Not sure how to implement it though. A global singleton with `RwLock` that stores the pw_badlist `Set`?

**Comment by Firstyear** [comment]
A lot of the machinery you need is here: https://github.com/kanidm/kanidm/pull/409/files 

We can not use a rwlock - because this is concurrently readable, we need either CowCell or one of the concread types. 

During any write, a list of uuid's to invalidate is maintained. 

Likely the easiest approach here is to have a CowCell<HashSet<String>>, and when the server_config uuid is invalidated through a write (such as badlist preprocess), during a commit, you can then refresh the content of the hashset.

Perfect world this would be in the idm server, but I think until I do some refactoring, this has to be on the query server structure. There are plenty of other ARCache and CowCell examples in this.

**Comment by victorcwai** [comment]
So... I have been reading the fun stuff about the memory containers and concurrency in Rust.

Right now I am trying to do this via ``Arc<CowCell<HashSet>>``:
I init the ``Arc<...>`` in ``QueryServer``, then pass it to ``QueryServerReadTransaction`` and ``QueryServerWriteTransaction``.

We access the cache via ``QueryServerReadTransaction`` and ``QueryServerWriteTransaction``. We call ``pw_badlist_cache.read()`` to read the cache.  If it is empty, then we read from DB and call ``pw_badlist_cache.write()`` to update the cache.

During any write, we empty the cache if ``UUID_SYSTEM_CONFIG`` is in the list of uuid's to invalidate.

I wonder if this approach is okay though, since I am quite a noob in this area. :-))

**Comment by Firstyear** [comment]
It's pretty close. During the read or write, you always open the associated transaction type. (ie read or write). This is related to how the locking works in these calls, where you can't mix  a write inside a read, and a read inside a write.

To "prime" the set, you would during the initial write txn for setup read the full content of the badlist into the set and commit it.

Then only in writes would you replace the content of the set with the updated content if UUID_SYSTEM_CONFIG changes.

Remember, this isn't a cache, as much as "an in memory copy of the full set of badlisted passwords". 


PS: I might actually refactor some parts around the idms / qs  code today to make it cleaner to achieve this.

**Comment by Firstyear** [comment]
Relates #62

**Comment by victorcwai** [comment]
> During the read or write, you always open the associated transaction type. (ie read or write). This is related to how the locking works in these calls, where you can't mix a write inside a read, and a read inside a write.

Ahh okay. I see that when you create a transaction, you always pass the associated transaction type to it. 
For example, ``classes: CowCellWriteTxn<...>`` in ``SchemaWriteTransaction``.
But if I put something like ``pw_badlist_set: CowCellWriteTxn<HashSet>`` in ``QueryServerWriteTransaction``, it would mean blocking all the other ``QueryServerWriteTransaction`` right?

> PS: I might actually refactor some parts around the idms / qs code today to make it cleaner to achieve this.

Thanks for the info!

**Comment by Firstyear** [comment]
> > During the read or write, you always open the associated transaction type. (ie read or write). This is related to how the locking works in these calls, where you can't mix a write inside a read, and a read inside a write.
> 
> Ahh okay. I see that when you create a transaction, you always pass the associated transaction type to it.
> For example, `classes: CowCellWriteTxn<...>` in `SchemaWriteTransaction`.
> But if I put something like `pw_badlist_set: CowCellWriteTxn<HashSet>` in `QueryServerWriteTransaction`, it would mean blocking all the other `QueryServerWriteTransaction` right?

Have a look at https://github.com/kanidm/kanidm/blob/master/designs/architecture.rst - it may help explain. The tl;dr is that there is only ever one write thread/transaction at a time, not many. So this is actualy correct :) 

> 
> > PS: I might actually refactor some parts around the idms / qs code today to make it cleaner to achieve this.
> 
> Thanks for the info!

No problem, happy to help!

**Comment by victorcwai** [comment]
Hmm I am not sure how to retrieve the updated badlist in the commit function (in IdmServerProxyWriteTransaction). 

I tried to do a search for **after** `self.qs_write.commit(au)` via:
```
let badlist_entry = self
        .qs_write
        .internal_search_uuid(au, &UUID_SYSTEM_CONFIG)
        .map_err(|e| {
            ladmin_error!(au, "Failed to retrieve system configuration {:?}", e);
            e
        })?; 
```
But that wouldn't be possible since `self.qs_write.commit()` takes ownership of `self.qs_write`.

**Comment by Firstyear** [comment]
Does this code example help? 

```
1520 of kanidmd/src/lib/idm/server.rs

pub fn commit(...) -> Result<...> {
    lperf_trace_segment!(...
        || {
            self.mfareg_sessions.commit();
            if self.qs_write.get_changed_uuids().contains(&UUID_SYSTEM_CONFIG) {
                self.reload_password_badlist(au)?;
            };
            self.qs_write.commit(au)
        }
}
```

**Comment by victorcwai** [comment]
Oh I forgot that you can see the updated `UUID_SYSTEM_CONFIG` entry even before calling commit.

So inside `reload_password_badlist()` I can call `self.qs_write.internal_search_uuid(au, &UUID_SYSTEM_CONFIG)` to get the updated `UUID_SYSTEM_CONFIG` entry, right?
Or is there some ways to retrieve the entry from `self.qs_write` without performing search again, like `self.qs_write.get_be_txn().xxx`?

**Comment by Firstyear** [comment]
Of course, you want to be updating this before you call the commit so that if sometthing goes wrong we can roll back. That's the point of this being a transactional system after all! 

For now you can re-search the UUID_SYSTEM_CONFIG, and since it was modified in this operation it will be in the transaction write cache so it should be fast to retrieve. Alternately, you could have a hook in the modification paths that extracts what you need at modification time to avoid the extra search, but for now, lets do the simple and correct method (just do the search).
