### ISSUE TITLE
Tests unstable on kanidm_client

### ISSUE THREAD

**Issue by yaleman** [kanidm/kanidm#416]
This is happening across v1.47 and v1.49, I can't quite work out *why* but it's not always failing - even across multiple runs either using sccache or not.

The 503 missing kopid thing... seems like it should mean something? :)

```
     Running target/release/deps/default_entries-7eb40b22c54e5279

running 11 tests
test test_default_entries_rbac_admins_ha_accounts ... FAILED
test test_default_entries_rbac_group_managers ... FAILED
test test_default_entries_rbac_admins_schema_entries ... FAILED
test test_default_entries_rbac_admins_access_control_entries ... FAILED
test test_default_entries_rbac_anonymous_entry ... FAILED
test test_default_entries_rbac_account_managers ... FAILED
test test_default_entries_rbac_admins_group_entries ... FAILED
test test_default_entries_rbac_admins_recycle_accounts ... FAILED
test test_default_entries_rbac_radius_servers ... FAILED
test test_default_entries_rbac_people_managers ... FAILED
test test_default_entries_rbac_users ... FAILED

failures:

---- test_default_entries_rbac_admins_ha_accounts stdout ----
thread 'test_default_entries_rbac_admins_ha_accounts' panicked at 'called `Result::unwrap()` on an `Err` value: Http(503, None, "missing_kopid")', kanidm_client/tests/default_entries.rs:515:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- test_default_entries_rbac_group_managers stdout ----
thread 'test_default_entries_rbac_group_managers' panicked at 'called `Result::unwrap()` on an `Err` value: Http(503, None, "missing_kopid")', kanidm_client/tests/default_entries.rs:299:14

---- test_default_entries_rbac_admins_schema_entries stdout ----
thread 'test_default_entries_rbac_admins_schema_entries' panicked at 'called `Result::unwrap()` on an `Err` value: Http(503, None, "missing_kopid")', kanidm_client/tests/default_entries.rs:388:14

---- test_default_entries_rbac_admins_access_control_entries stdout ----
thread 'test_default_entries_rbac_admins_access_control_entries' panicked at 'called `Result::unwrap()` on an `Err` value: Http(503, None, "missing_kopid")', kanidm_client/tests/default_entries.rs:340:14

---- test_default_entries_rbac_anonymous_entry stdout ----
thread 'test_default_entries_rbac_anonymous_entry' panicked at 'called `Result::unwrap()` on an `Err` value: Http(503, None, "missing_kopid")', kanidm_client/tests/default_entries.rs:586:14

---- test_default_entries_rbac_account_managers stdout ----
thread 'test_default_entries_rbac_account_managers' panicked at 'called `Result::unwrap()` on an `Err` value: Http(503, None, "missing_kopid")', kanidm_client/tests/default_entries.rs:267:14

---- test_default_entries_rbac_admins_group_entries stdout ----
thread 'test_default_entries_rbac_admins_group_entries' panicked at 'called `Result::unwrap()` on an `Err` value: Http(503, None, "missing_kopid")', kanidm_client/tests/default_entries.rs:499:14

---- test_default_entries_rbac_admins_recycle_accounts stdout ----
thread 'test_default_entries_rbac_admins_recycle_accounts' panicked at 'called `Result::unwrap()` on an `Err` value: Http(503, None, "missing_kopid")', kanidm_client/tests/default_entries.rs:528:14

---- test_default_entries_rbac_radius_servers stdout ----
thread 'test_default_entries_rbac_radius_servers' panicked at 'called `Result::unwrap()` on an `Err` value: Http(503, None, "missing_kopid")', kanidm_client/tests/default_entries.rs:611:14

---- test_default_entries_rbac_people_managers stdout ----
thread 'test_default_entries_rbac_people_managers' panicked at 'called `Result::unwrap()` on an `Err` value: Http(503, None, "missing_kopid")', kanidm_client/tests/default_entries.rs:547:14

---- test_default_entries_rbac_users stdout ----
thread 'test_default_entries_rbac_users' panicked at 'called `Result::unwrap()` on an `Err` value: Http(503, None, "missing_kopid")', kanidm_client/tests/default_entries.rs:229:14


failures:
    test_default_entries_rbac_account_managers
    test_default_entries_rbac_admins_access_control_entries
    test_default_entries_rbac_admins_group_entries
    test_default_entries_rbac_admins_ha_accounts
    test_default_entries_rbac_admins_recycle_accounts
    test_default_entries_rbac_admins_schema_entries
    test_default_entries_rbac_anonymous_entry
    test_default_entries_rbac_group_managers
    test_default_entries_rbac_people_managers
    test_default_entries_rbac_radius_servers
    test_default_entries_rbac_users

test result: FAILED. 0 passed; 11 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '-p kanidm_client --test default_entries'
```

**Comment by Firstyear** [comment]
Missing kopid generally means the returned header was *not* from kanidm since the `k[anidm]op[eration]id` isn't there. 

Can you run again but uncomment line 59 of kanidm_client/tests/common.rs?

You can also just test one test, IE `cargo test test_default_entries_rbac_users` to help keep the output a bit clearer.

PS: It could be worth check if you have anything listing on ports 18080 and near by since that's what we try to dynamically allocate.

**Comment by yaleman** [comment]
Yep, it's bailing straight up on the first part of the test uWu

Nothing's listening on the ports - it's the only process running in the container at the time. (opensuse_tumbleweed currently)
```
fn test_default_entries_rbac_users() {
    run_test(|mut rsclient: KanidmClient| {
        rsclient
            .auth_simple_password("admin", ADMIN_TEST_PASSWORD)
            .unwrap();
```

logs: https://gist.github.com/yaleman/41aef64738b37603a538406f7b1cce39

I have... a spooky idea but I'm still working it out - looks like it's starting up too slowly in another thread, maybe?

**Comment by Firstyear** [comment]
There is a signal channel there in `kanidm_client/tests/common.rs` line 76 to avoid this. I guess in theory it *cooouuulllddd* still race between line 76 vs 84 to 96. 

You could check the race theory by putting a sleep before line 90.

It's also probably worth as another idea, putting an eprintln() of the addr between 90 and 91, and then sleeping for say .... an hour, and that way you can poke about at the addr and port and see what it's actually returning. 

Again, it does look like it's started, that log shows the post-startup purge tasks running, and the missing kopid + result 503 makes me think something odd is going on.

**Comment by yaleman** [comment]
After playing around with this a *lot* I can't reliably reproduce or fix it. Blerp.

**Comment by Firstyear** [comment]
Can you rerun with line 27 of kanidm_client/tests/common.rs uncommented? The only way I think this could happen is if in `to_tide_response` the serialisation to the body fails (lines 121, 139 of kanidmd/src/lib/core/https.rs) since that would cause the map call to "not" inject the event id.

A possibility is to have a duplicate .map_err call to inject the header to the err path as well.

**Comment by Firstyear** [comment]
@yaleman Is this still happening? I can't reproduce it on macos/linux :(

**Comment by yaleman** [comment]
Yeah, I can't reproduce this one tonight on either my M1 mac or SUSE,  (rustc 1.49) - I'll try running it through on the multi-builder as this tended to make it worse...

**Comment by Firstyear** [comment]
What is multi-builder?

**Comment by yaleman** [comment]
Still getting these failures in Debian buster and Ubuntu bionic. :S OpenSUSE tumbleweed passes (other than the webauthn thing in the other report). Waiting on the rest of the build to finish...

Multi-builder's my [build-it-on-docker multi-distro thing](http://github.com/yaleman/kanidm-builder/). Basically boot a docker instance with the required base OS, run `cargo test --release --workspace && cargo build --release --workspace` then copy files out to s3 (with a lot more going on).

**Comment by yaleman** [comment]
Update: these tests failed on leap 15.2 / 15.3 as well. Passed fine on tumbleweed. Curiouser and curiouser.

**Comment by Firstyear** [comment]
Can you tell me more about the environment so I can try to reproduce? IE docker on mac, which arch, what steps you took to setup the env?

**Comment by yaleman** [comment]
Docker's running on opensuse tumbleweed (in a vm on Proxmox)... given that it's working for other things, the nesting virtualizations _shouldn't_ be an issue?

I'll run through the example for Ubuntu focal. There's a makefile that does all the steps in this repo: https://github.com/yaleman/kanidm-builder

It builds a docker image based on this Dockerfile https://github.com/yaleman/kanidm-builder/blob/main/Dockerfile_ubuntu_focal which installs some base packages and copies some build scripts over.

Running the image runs: 
 - rustup (v1.49) via the [rust install script](https://github.com/yaleman/kanidm-builder/blob/main/install-rust.sh)
 - then the [build kanidm script](https://github.com/yaleman/kanidm-builder/blob/main/build_local_arch.sh) which clones the repo fresh, starts up sccache and runs `cargo test --release` then if it succeeds, `cargo --release --workspace --bins`.

The environment variables are set from here: https://github.com/yaleman/kanidm-builder/blob/main/template.env  (with super-secret internal-to-my-network details filled out)

**Comment by yaleman** [comment]
As discussed elsewhere, the build env has `HTTP_PROXY=<my network proxy>` so I'm testing without that now - this *was* set in the opensuse tests though...

**Comment by yaleman** [comment]
Can confirm - un-setting the environment variable `HTTP_PROXY` fixes it in Ubuntu/Debian.

**Comment by Firstyear** [comment]
Okay, in that case I think the fix is to add a builder option for proxy env vars to the client, then in tests we hardcode that to never use proxies. I'll write this up shortly.

**Comment by pando85** [comment]
Hello guys. I want to add here that this could be an environment problem and not related with Kanidm. I think it could be easily fixed using the `NO_PROXY` environment variable.

**Comment by Firstyear** [comment]
@pando85 I think @yaleman tested this and found it didn't work in his env. Regardless, even so, we should never need the user to "change their environment" for the tests to work correctly, so I think the no_proxy in the client during tests is a more reliable fix than asking people to commit to workarounds.

**Comment by yaleman** [comment]
^ Yep, didn't fix it in my testing.
