### ISSUE TITLE
unstable test test_server_rest_webauthn_mfa_auth_lifecycle

### ISSUE THREAD

**Issue by yaleman** [kanidm/kanidm#430]
This one periodically fails too... *OpenSSL BN generated invalid arrays* seems to be the relevant thing.

I've tried to catch a backtrace but it's another one of those flaky-failers.

```shell
---- test_server_rest_webauthn_mfa_auth_lifecycle stdout ----
[webauthn_authenticator_rs::softtok] OpenSSL BN generated invalid arrays
thread 'test_server_rest_webauthn_mfa_auth_lifecycle' panicked at 'Failed to register to softtoken: OpenSSL', kanidm_client/tests/proto_v1_test.rs:937:14
```

**Comment by Firstyear** [comment]
Most likely it's a RNG failure, that we were unable to fill the bignum arrays in time or with a correct/sufficient value, which causes this. Really, the error is actually in https://github.com/kanidm/webauthn-authenticator-rs/blob/main/src/softtok.rs#L24 somewhere.

**Comment by Firstyear** [comment]
https://github.com/kanidm/webauthn-authenticator-rs/pull/2

**Comment by Firstyear** [comment]
Going to close this as there is now a PR that resolves.
