### ISSUE TITLE
Mail attribute handling

### ISSUE THREAD

**Issue by Firstyear** [kanidm/kanidm#461]
We need to be able to set mail attributes, but we also need a way to tag which mail addr is primary, display those tags in ldap, and have correct parsing of mail addrs  https://www.mailboxvalidator.com/resources/articles/acceptable-email-address-syntax-rfc/

**Comment by Firstyear** [comment]
Relates #459

**Comment by yaleman** [comment]
This could be handy for validation - https://docs.rs/validator/0.13.0/validator/fn.validate_email.html

> Validates whether the given string is an email based on the [HTML5 spec](https://html.spec.whatwg.org/multipage/forms.html#valid-e-mail-address). [RFC 5322](https://tools.ietf.org/html/rfc5322) is not practical in most circumstances and allows email addresses that are unfamiliar to most users.

I agree with the comment on the RFC - truly RFC-compliant emails are horrible things and unlikely to be used except in trolling... I'm not sure how often ones outside the HTML5 spec are actually used...

**Comment by Firstyear** [comment]
@yaleman Can I resolve this? We have email address handling mostly in place now.

**Comment by yaleman** [comment]
Yep, I think that one's 
 sorted. I was able to set up email for OAUTH2 use OK.
