### ISSUE TITLE
Cleanup `kanidm_client` bool/return values

### ISSUE THREAD

**Issue by QnnOkabayashi** [kanidm/kanidm#472]
In `kanidm_client`, there are many functions that return `Result<bool, ClientError>`, yet the `bool` is never used on `Ok`. We should change these to `Result<(), ClientError>` to decrease confusion. Inspired by @Firstyear's comment:

> It represents past williams mistakes. I thought that there would be a case where you could set and it would be Ok() but change nothing (false), but I think we never indicate that so it should be cleaned up. That could be a new issue from this (cleanup kanidm_client bool/return values).
> _Originally posted by @Firstyear in https://github.com/kanidm/kanidm/pull/465#discussion_r647877749_

**Comment by Firstyear** [comment]
@QnnOkabayashi did you want to do this one? Or do you want me to fix it?

**Comment by QnnOkabayashi** [comment]
I was gonna fix it Monday
