### ISSUE TITLE
`DbValue` serde renames

### ISSUE THREAD

**Issue by QnnOkabayashi** [kanidm/kanidm#473]
The field names in `kanidmd/src/lib/be/dbvalue.rs` types are very short to minimize information that is serialized, but this makes it much more confusing for new contributors. We can use `serde` macros to have the structs serialized with much shorter names, while allowing us to use more human readable code. I imagine it would use something like `#[serde(rename = "x")]` in the struct definition.

For example, the `DbValueV1` type could be rewritten to something like:
```rust
#[derive(Serialize, Deserialize, Debug)]
pub enum DbValueV1 {
    ...
    #[serde(rename = "BO")]
    Bool(bool),
    #[serde(rename = "SY")]
    SynType(usize),
    #[serde(rename = "IN")]
    IdxType(usize),
    ...
}
```

And in `DbValueCredV1` for example, the 1-letter variable names completely obfuscate the meaning, and should be changed. 

```rust
#[derive(Serialize, Deserialize, Debug)]
pub struct DbValueCredV1 {
    #[serde(rename = "t")]
    pub this_starts_with_t: String,
    #[serde(rename = "d")]
    pub dunno_what_this_is: DbCredV1,
}
```

(I have no idea what most of these are short for. Hence the issue here.)

**Comment by QnnOkabayashi** [comment]
I think `serde` renaming could actually come in handy in a lot more places too. `kanidmd/src/lib/value.rs` defines the `SyntaxType` and `IndexType`, which have methods to convert their variants to and from unique `usize`s. This causes a lot of clutter, and is only used in one place (according to VSCode) for serialization. Someone might have to dig around more here, though. Also, although fieldless `enum`s can be casted to `usize`s, we don't want anything to break if the fields are reordered.

For example:
```rust
pub enum SyntaxType {
    #[serde(rename = "0")] UTF8STRING,
    #[serde(rename = "1")] Utf8StringInsensitive,
    ...
    #[serde(rename = "16")] DateTime,
    #[serde(rename = "17")] EmailAddress,
}
```

**Comment by Firstyear** [comment]
There is also repr(usize) potentially that we could use too.

**Comment by QnnOkabayashi** [comment]
> There is also repr(usize) potentially that we could use too.

True, but as you mentioned before this could potentially screw up things if the `enum` is reordered when things are already stored in the db. Can we just assume that this won't happen? If possible, could we rename them to shorter string variations like I proposed for `DbValueV1` above?

I do agree that renaming them in numeric ascending order does seem silly though...
