### ISSUE TITLE
Additional fragile tests for `kanidm_client::asynchronous`

### ISSUE THREAD

**Issue by QnnOkabayashi** [kanidm/kanidm#486]
When working on https://github.com/kanidm/kanidm/pull/479, we ran into an issue where everything passed the type checker, but the server was sending information that did not reflect changes to the client, causing a runtime panic. This was solved by fixing the function on the server end, but we only had to change 1 function to make it pass the tests, even though the issue that had to be fixed seemed to appear in many other functions.

Solution: make tests for each of the functions in `kanidmd/src/lib/core/https.rs` that sent `bool`s in the `Ok`, which should now send `()`. The tests should check for the proper type received on the client side, since this is a runtime issue that can't be statically type checked. The follow functions were changed and should be tested:
1. `json_rest_event_delete_id`
2. `json_rest_event_post_id_attr`
3. `json_rest_event_put_id_attr`
4. `json_rest_event_delete_id_attr`
5. `account_post_id_ssh_pubkey`
6. `account_delete_id_ssh_pubkey_tag`
7. `account_post_id_person_extend`
8. `account_post_id_unix`
9. `account_put_id_unix_credential`
10. `account_delete_id_unix_credential`
11. `group_post_id_unix`
12. `recycle_bin_revive_id_post`

To replicate the error, try adding a `.map(|()| true)` after the `await` calls in these functions, like how it was here in an old commit:
https://github.com/kanidm/kanidm/blob/ea34dc08a9d8369b7ab7a49b9facdc5716ceb808/kanidmd/src/lib/core/https.rs#L885-L898
Making more tests wouldn't hurt either.

**Comment by Firstyear** [comment]
> Making more tests wouldn't hurt either.

More tests are always better :)

**Comment by QnnOkabayashi** [comment]
I just ran through all the functions listed and each of them already have at least one test detecting this issue when running the latest master commit. I swear this wasn't the case when I made this post, but I guess it's not an issue now :)
