### ISSUE TITLE
Extend kanidm_tools to create and reset backup codes in CLI

### ISSUE THREAD

**Issue by victorcwai** [kanidm/kanidm#495]
See https://github.com/kanidm/kanidm/pull/469#issuecomment-868157709.

**Comment by cuberoot74088** [comment]
Hi @victorcwai,
thanks bringing backup codes to kanidm. :+1: 
Are you planning to work on the CLI integration? If you don't mind, I might give it a try. Because I would like to be able to use backup codes :wink:

**Comment by victorcwai** [comment]
Hi, sure feel free to to implement it. Looks like you already have a great start. 👍
