### ISSUE TITLE
System-level configuration - extending minimum password length

### ISSUE THREAD

**Issue by yaleman** [kanidm/kanidm#498]
This is currently a const in `kanidm::constants::PW_MIN_LENGTH` but should be configurable in the DB/config as people have their own ideas as to what minimums should apply :)

**Comment by Firstyear** [comment]
I think this would be part of a password-security policy system which rather than being system-level, sohuld be flexible enough to have different roles/categories of rules that can apply such as pw_min_length, maybe even stricter zxcvbn requirements, enforcing MFA etc. 

By default we'd ship a "default" policy that applies globally, but then other policies can be used too.

**Comment by Firstyear** [comment]
You know, I think the more I think about this, the more I don't want to allow this to be configured. Passwords are a continual source of vulnerabilities, and we have alternative authentication methods that are easier and more secure. 

I think allowing people to go below our minimums isn't really okay.

I think the only way I'd do this would be to allow having a longer value. But even then, if people are setting longer values, then they should just be swapping to a more secure auth type anyway - or we should be improving our minimums. Which again comes back to why would we want this configurable anyway?

**Comment by yaleman** [comment]
> I think the only way I'd do this would be to allow having a longer value.

Wait, we have a max length somehow? 😄 

I think this was originally logged when the responses from password setting weren't clear *what* the minimum should be.

**Comment by Firstyear** [comment]
As in, the only policy i'd allow a user to set would be to make a pw min length "larger" than our min length. I wouldn't let it go lower.

Yeah, we now flag this clearly on pw changes in the UI's what the requirements are.

**Comment by yaleman** [comment]
Maybe we refocus this to "allow enforcing longer password lengths" ? 😄

**Comment by Firstyear** [comment]
I think this is actually achieved by #1122 and setting a default policy on idm_all_accounts.
