### ISSUE TITLE
Password complexity phrasing

### ISSUE THREAD

**Issue by yaleman** [kanidm/kanidm#500]
> Are we doing phrasing now?

Ref comments in #499, it'd be good to have some standardised wording around password complexity, probably prompting the user with the requirements *before* they attempt a password change.

This'd apply to web and cli interfaces, too.

**Comment by cuberoot74088** [comment]
yes, would be great to know the requirements _before_.
Would it even be possible to output some indicator, when the password requirements are met? Where is the check done right now?

**Comment by Firstyear** [comment]
We need to actually rewrite the error handling around passwords because internally we get details from zxcvbn about this. We could apply the same rules client side so that we can show these errors better there first instead.

I guess the issue is: Do we have the server emit better error messages here so that all clients benefit, or do we have the client pre-check before sending and applies the same rules?

**Comment by yaleman** [comment]
As long as the client can somehow infer the requirements from the server that'd make sense. It's possible that clients would be connecting to multiple kanidm instances with their own requirements.

**Comment by Firstyear** [comment]
Hmmm ... that's a good point. That a future account policy setting may affect those requirements. I'm a bit unsure about how far I want to go down that route though. I'd rather kanidm be opinionated-and-correct than allow every which-what configuration. IE I don't want to ever allow forced password rotation or silly requirements like "must have a number and symbol". zxcvbn will accept a fully alpha char password if it's long enough for example. IE the requirements will always be about what is *actually* best practice, for modern PW security, not what some 20 year out dated backwater auditor thinks it should be.


Which means the question is how far do we allow these requirements to wiggle, while still communicating what's going on to the user? 

My thinking is initially that having the server errors be clearer is probably the more sustainable long term route here at the least.

**Comment by Firstyear** [comment]
@yaleman Isn't this kind of done now? We can certainly polish it, but it's all in place.

**Comment by yaleman** [comment]
It's ugly but it works... I'll poke at this over the weekend and do some human errors.

```
cred update (? for help) # : pass
New password: [hidden]
Confirm password: [hidden]
TooShort(10)
```

**Comment by Firstyear** [comment]
Yeah, we can probably implement std::fmt::Display for this to make it more human?

**Comment by yaleman** [comment]
That's the plan :D
