### ISSUE TITLE
TOTP app compatibility 

### ISSUE THREAD

**Issue by yaleman** [kanidm/kanidm#501]
Testing the CLI TOTP registration process this morning I couldn't get it to work with Authy's iOS app, which I'm guessing is a SHA512 support issue? Still researching.

Here's a few checks

❌ Authy iOS (v24.5.1)
✅ Okta iOS (v6.5.0)
✅ Google Authenticator (v3.2.0)

**Comment by yaleman** [comment]
I've put a support request in with Twilio/Authy to find out what they say.

**Comment by Firstyear** [comment]
I suspect that this is due to sha512/sha256. There isn't a "huge reason" to use sha512 by default, so we can change to 256.

**Comment by cuberoot74088** [comment]
Hi @yaleman, thanks for looking into this.
I have tried this under android with 

:heavy_check_mark:  Google authenticator (v5.10)
:heavy_check_mark:  Microsoft Authenticator (v6.2105.3263)

I can read the qr code and generate some number, but verification fails for me :cry:   #506

**Comment by Firstyear** [comment]
Updated to sha256 by default, @cuberoot74088 's issue isn't due to sha256 I think.

**Comment by yaleman** [comment]
Authy doesn't support 512, official response here:

```
Thank you for contacting Authy Support at Twilio, I'll be happy to assist you with this matter.

Currently, Authy uses SHA-2 and 256-bit keys.

Please refer - https://www.twilio.com/docs/authy/two-factor-authentication-developer-best-practices for more details.
```

**Comment by Firstyear** [comment]
Good thing we changed our default then :)

**Comment by yaleman** [comment]
... And it still doesn't work with Authy. Scanning the QR code or copy-pasting direct.

```
Alternatively, you can manually enter the following OTP details:
Account Name: yaleman
Issuer: yaleman@<hostname>
Algorithm: SHA256
Period/Step: 30
Secret: BPNT2RF4ATCZS
--------------------------------------------------------------
Enter a TOTP from your authenticator to complete registration:
TOTP: 377991
Error Completing -> TotpVerifyFailed(00000000-60da-f02b-097b-dade956d96ce, TotpSecret { accountname: "yaleman", issuer: "yaleman@<hostname>", secret: [11, 219, 61, 68, 188, 4, 197, 153], algo: Sha256, step: 30 })
```

**Comment by cuberoot74088** [comment]
Hmm, I think this could be the same problem as in #506

**Comment by Firstyear** [comment]
@yaleman The bug is in authy. It's disregarding the algorithm parameter of https://github.com/google/google-authenticator/wiki/Key-Uri-Format and always defaulting to sha1. That's why the code that is in the app isn't working because it's not correct.

To work this out, I just installed authy, setup a test where I captured the secret, and then attempted each algo/time point, with a bit of variation, and found that sha1 at that exact time point was the code from the app.

@cuberoot74088 This is your issue too - I used your provided sample information in #506 and can confirm that your app is also disregarding the algorithm flag we are sending, and is always and only using SHA1. 

Which app are you using @cuberoot74088 ?

**Comment by cuberoot74088** [comment]
@Firstyear I am using Google authenticator on Android.

**Comment by Firstyear** [comment]
Okay, that's listed in the page linked as a broken authenticator that always forces sha1. So I think this is an app bug, not a kanidm bug, we are correctly emitting the qr code/configuration uri.

**Comment by cuberoot74088** [comment]
I agree. Seems like Google Auth and Microsoft Auth only use sha1, no config option. [Here](https://password-managers.bestreviews.net/best-totp-apps-for-two-factor-authentication-2fa/) I found a hint that Sophos Auth should do it ... I can give it a quick try.

**Comment by cuberoot74088** [comment]
it works with Sophos Authenticator

> Algorithm: SHA512
> Period/Step: 30
> Secret: OJVIJBCPXJUNO
> 
> Enter a TOTP from your authenticator to complete registration: 
> TOTP: 824608
> TOTP registration success.
>

**Comment by Firstyear** [comment]
FreeOTP works too.

So now the question is what to do? 

Should we have a safety barrier here that indicates the user has a broken app, and confirm if they want to continue with it even if it uses a worse algo? Or should we flag it as broken and then reject the enrollment still? Either way we need the error message to reflect that the authenticator app is using the wrong algo here.

**Comment by cuberoot74088** [comment]
So it is not a kanidm bug! :+1: 

But how to continue here? I think the mentioned apps are quite popular ... Create some "bug"(?) reports there? Should we have a config option per TOTP? So you could request a sha1, sha256, or sha512 algo for it?

**Comment by cuberoot74088** [comment]
Are we able to reason about the algo used by the App? I like the idea of the proposed error message on the "wrong algo". We could point out to use FreeOTP, as you said. How bad would it be to support sha1 here?

**Comment by yaleman** [comment]
Another response from Authy support, after I brought up the issue with them... when they said they support SHA256, it's only Twilio partners and not TOTP in general.

> Hi James,
> 
> Thank you for following up.
> 
> Unfortunately, we do not support SHA512 tokens and you can not add SHA256 tokens. The Google Authenticator tokens (QR codes) that you can add are SHA-1 and the Authy native tokens - SHA256 (just for Twilio partners).
> 
> I can see that we do have an internal feature request opened for the engineering to consider it for the future improvements of the app and I have added your ticket to it. Unfortunately, I can not provide an ETA as this depends on the roadmap and the priorities. 
> 
> If we do decide to support SHA-512 and SHA256 for Google Authenticator tokens then we will provide an update on our Blog. https://authy.com/blog/
> 
> I am going to close this ticket for now, but if you have any questions in the future, please don't hesitate in letting us know.
> Warm Regards,
> 
> Sahana Sindhe
> Technical Support Engineer

**Comment by Firstyear** [comment]
Okay here's my thinking. I think that the best thing for Kani is to offer "the best experience by default". So I think we should:

* Continue to offer sha256 tokens.
* When the verification is performed we check it against the sha256:
*   If that fails, we check if the app is a using sha1 instead.
*   we present this to the user to consent to the sha1 token + app with 'weakened' security.
*   the user can then accept/deny the registration of the token.
*   if accepted, we convert the token in registration to SHA1 and then persist that to the account. 

This seems to be the best compromise between strong defaults, and positive user experience with "bad behaving applications". 


Thoughts?

**Comment by yaleman** [comment]
This seems sensible to me, it's a few more calls to the backend and some support code to go "uh, try and downgrade" and as we discussed, SHA1's... still *fairly* secure in context. 

Is kanidm currently storing the type of hash on registration?

**Comment by cuberoot74088** [comment]
I like the approach of "the best experience by default" and sticking to sha256 from our side.
In case sha1 was used by the users app, I would inform the user about that, i.e.,

> Your App generated a code using sha1 and not, as requested, the kanidm default algorithm sha256. If you want to use a sha1, please try again and add `--algo sha1` option to your call.

With that, I would let that call fail. The user would know why and can decide if he wants to switch to sha1. It is not so smooth for the user, but I think you would avoid some auto-magic stuff in the server, that might bit you a bit later in time. Moreover, it makes it more clear to choose the algo, which is obviously an option, although not yet widely supported and leaves room to change our default.
In any case, I think, the chosen algo needs to be stored somehow in kanidm. And given that, you request the token+algo and store exactly this, if it is verified correctly - no magic switch. You get what you asked for. ;-)

That would mean, we need to add a new `--algo <sha1|sha256|sha512>` option here. Might be more work that "magic conversion" but more transparent and sustainable?

What do you think?
