### ISSUE TITLE
Failed to run `kanidm account credential status` after TOTP creation.

### ISSUE THREAD

**Issue by yaleman** [kanidm/kanidm#502]
Looks like the user has to re-login after setting up TOTP, there's no mention of it needing to be a thing.

Maybe invalidate the local token if it was used, or make a clearer message that any existing logins need to be re-done?

```
$ cargo run --bin kanidm -- account credential status yaleman --name yaleman
    Finished dev [unoptimized + debuginfo] target(s) in 0.31s
     Running `target/debug/kanidm account credential status yaleman --name yaleman`
Error displaying credential status -> JsonDecode(reqwest::Error { kind: Decode, source: Error("invalid length 2, expected tuple variant CredentialDetailType::PasswordMfa with 3 elements", line: 1, column: 101) }, "defc15b3-a324-47e5-b26a-acfee534e8a1")
```

**Comment by Firstyear** [comment]
To clarify what the steps were to recreate - you had an account with password only, configured a totp, and then check the credential status? Is that correct?

**Comment by yaleman** [comment]
Yep, that's correct. Apologies for not providing clearer reproduction steps.

**Comment by cuberoot74088** [comment]
Works for me using e134fa5b4083e98909d3c29402d0a95d4bc8b3fb  

> kanidm account credential status test --name test
> 
> uuid: 26a81958-3812-4f0a-86bc-f7b7be95e276
> claims:
> password: set
> totp: enabled
> backup_code: enabled
> webauthn: no authenticators
