### ISSUE TITLE
Upgrade failure: during restores duplicate entries may be created

### ISSUE THREAD

**Issue by Firstyear** [kanidm/kanidm#511]
During an upgrade, a condition was hit where it became possible to have restores break duplicating entries and potentially mis-indexing content. This is a major issue as restores should always work, and upgrades should not break. 

The situation was that due to running a git master version, an entry had an incorrect syntax for an attribute. After backing up the server, and then restoring with this entry removed from the backup, the server became inconsistent and would not start correctly. 

Starting from a fresh db and restoring did NOT work.

**Comment by cuberoot74088** [comment]
I have used my tiny db with latest master and the version in #512  - everything is working for me. From #512 it sounds like the issue was a corrupted backup file.

**Comment by Firstyear** [comment]
I assure you , the issue was NOT a corrupted backup file :)
