### ISSUE TITLE
WebUI - enter key submission of login fields

### ISSUE THREAD

**Issue by yaleman** [kanidm/kanidm#518]
When logging in, pressing enter doesn't submit the username/TOTP/password fields, which requires the user to keep changing input methods.

It should be solve-able with something along these lines: http://stackoverflow.com/questions/18160342/ddg#18160418

```javascript
$('#username').keypress(function (e) {
 var key = e.which;
 if(key == 13)  // the enter key code
  {
    $('input[name = usernamebutton]').click();
    return false;  
  }
});
```

This uses the existing jquery code already included.

**Comment by Firstyear** [comment]
I'm already looking at the webui atm and was planning to fix this :)
