### ISSUE TITLE
Should kanidm logout prompt for token when multiple tokens exist?

### ISSUE THREAD

**Issue by yaleman** [kanidm/kanidm#548]
Currently `kanidm logout` will assume `anonymous` when run without a `--name` command and return ` No sessions for anonymous` even if other tokens exist.

This feels like a least-surprise/annoyance issue, I should be able to push this through the already existing "please select a token" path if that makes sense?

**Comment by Firstyear** [comment]
Yeah, I think this should prompt for which token. :)
