### ISSUE TITLE
WebUI: Implement AuthMech Selection

### ISSUE THREAD

**Issue by cuberoot74088** [kanidm/kanidm#552]
This is a reminder and to make it more transparent.

Given you have multiple multi-factor-authentication MFA mechanisms configured (totp, backup codes, webauthn) you can use them with the CLI to login - everything works. Currently however, not yet in the web interface as it is not implemented. It will only work if there is exactly one MFA mechanism configured.

See 

- #547
- #517, https://github.com/kanidm/kanidm/pull/517#issuecomment-875174532

**Comment by Firstyear** [comment]
Hoping to look at this before next release :)
