### ISSUE TITLE
`num_enum` for primitive conversion runtime types

### ISSUE THREAD

**Issue by QnnOkabayashi** [kanidm/kanidm#582]
There are a few areas that rely converting enums to and from primitive types, like in `tracing_tree::EventTag`.

https://github.com/kanidm/kanidm/blob/573e346476bb0034991eb614c681c834e1e5c9b4/kanidmd/src/lib/tracing_tree/event_tag.rs#L56-L103

We should be using the [`num_enum`](https://lib.rs/crates/num_enum) crate, which removes this boilerplate and also ensures consistency. I know that this might not apply to values stored in a db because changing the enum might make the db inconsistent, but for runtime-only types (like `EventTag`) this would definitely be a good idea.

**Comment by Firstyear** [comment]
This is a good idea :)
