### ISSUE TITLE
Nginx integration

### ISSUE THREAD

**Issue by erictapen** [kanidm/kanidm#600]
I'm struggling to understand how I'd integrate kanidm into my existing Nginx setup.

Currently I host multiple applications that come without any authentication/authorisation at all (e.g. the Gollum wiki) and proxy them behind Nginx as an reverse proxy. Nginx authenticates users via the [`auth_basic` directive](https://nginx.org/en/docs/http/ngx_http_auth_basic_module.html).

I want to replace this with a solution where the user opens the site, is redirected to some plain login portal where they can authenticate themself against my kanidm db and then, after succesful authentication get redirected back to the Wiki.

Could I directly replace the HTTP basic auth with using the Oauth2 functionality of kanidm or would I need something like [oauth2-proxy](https://github.com/oauth2-proxy/oauth2-proxy), e.g. for the login portal?

**Comment by Firstyear** [comment]
I think you'll need to look at the auth request module here: https://developer.okta.com/blog/2018/08/28/nginx-auth-request or https://www.nginx.com/blog/validating-oauth-2-0-access-tokens-nginx/ . I personally haven't set this up, but it looks like what you need. 

This allows nginix to recognise when a browser session is not-yet authenticated, it will redirect to kanidm for oauth2, and then will allow this proceed. Note that as we have only just added support for rfc7662 you may need to use the devel docker image instead of latest which contains this functionality (I personally run the devel images as do some others, so they are well tested :) ) 

Hope that helps!

**Comment by erictapen** [comment]
Thank you for your reply.

I read the first blog post and am currently working on setting up vouch-proxy to do the job.

**Comment by yaleman** [comment]
@erictapen I'd be curious to hear back how you went with it, maybe even with an example configuration file? I'm starting to collect them so they can be added as examples for implementation.

**Comment by erictapen** [comment]
After a couple evenings of tinkering I managed to do my first login on Gollum Wiki!
My current setup is

```
Gollum Wiki <-> Vouch Proxy <-> Nginx
                     ^
                     |
                     v
                   Kanidm
```

Unfortunately I currently depend on current Kanidm master for OIDC support and https://github.com/vouch/vouch-proxy/pull/310 for vouch-proxy to interact with Kanidm properly. So it's not really a stable setup. But as soon as both changes are merged and behind releases, I could writeup an example config.

**Comment by Firstyear** [comment]
I'm working to provide the username/email claims soon, so any thing else you found in your testing and feedback would be most welcome! 

As well, feel free to commit to PR for https://github.com/kanidm/kanidm/blob/master/kanidm_book/src/oauth2.md since that will be part of the next release :)

**Comment by Firstyear** [comment]
@erictapen The email claims are available, can you retest with latest git?

**Comment by erictapen** [comment]
I just retested with latest master (f252d91e13a6c358f1495c5965f0028bcbd85c15) and I'm not able to login into Gollum wiki, using the setup described in https://github.com/kanidm/kanidm/issues/600#issuecomment-975980940.

The failure I'm seeing is that the login flow seems to work correctly, until the last step. When I confirm "Consent to Proceed to Gollum Wiki" it only reloads the same page again, sending me into a loop.

Following are the log outputs that are produced by both vouch-proxy (0.36.0) and kanidm during one iteration of the loop.

```
Feb 21 12:54:16 myserver vouch-proxy[71347]: {"level":"info","ts":1645444456.7481236,"msg":"|302|  780.772µs /auth","statusCode":302,"request":25,"latency":0.000780772,"avgLatency":0.006720321,"ipPort":"[::1]:35070","method":"GET","host":"login.erictapen.name","path":"/auth","referer":"https://auth.erictapen.name/"}
Feb 21 12:54:16 myserver vouch-proxy[71347]: {"level":"info","ts":1645444456.805817,"msg":"OpenID userinfo body: {\"iss\":\"https://auth.erictapen.name/oauth2/openid/gollum\",\"sub\":\"a375c9a0-1031-4c8b-89c2-eaa18a12263f\",\"aud\":\"gollum\",\"exp\":1645447705,\"nbf\":1645444456,\"iat\":1645444456,\"auth_time\":null,\"amr\":[\"generatedpassword\"],\"azp\":\"gollum\",\"name\":\"Kerstin Humm\",\"preferred_username\":\"kerstin@erictapen.name\",\"scopes\":[\"login\"]}"}
Feb 21 12:54:16 myserver vouch-proxy[71347]: {"level":"info","ts":1645444456.8082035,"msg":"|302| 22.580441ms /auth/Mgqn7DGBXVnOgR9TSICDC78W8oksKr/","statusCode":302,"request":26,"latency":0.022580441,"avgLatency":0.007330325,"ipPort":"[::1]:35072","method":"GET","host":"login.erictapen.name","path":"/auth/Mgqn7DGBXVnOgR9TSICDC78W8oksKr/","referer":"https://auth.erictapen.name/"}
Feb 21 12:54:16 myserver vouch-proxy[71347]: {"level":"warn","ts":1645444456.914187,"msg":"no User found in jwt"}
Feb 21 12:54:16 myserver vouch-proxy[71347]: {"level":"info","ts":1645444456.9174342,"msg":"|401| 3.569382ms /validate","statusCode":401,"request":27,"latency":0.003569382,"avgLatency":0.007191031,"ipPort":"[::1]:35080","method":"GET","host":"wiki.erictapen.name","path":"/validate","referer":"https://auth.erictapen.name/"}
Feb 21 12:54:16 myserver vouch-proxy[71347]: {"level":"info","ts":1645444456.9537787,"msg":"|302| 1.075062ms /login","statusCode":302,"request":28,"latency":0.001075062,"avgLatency":0.006972604,"ipPort":"[::1]:35082","method":"GET","host":"login.erictapen.name","path":"/login","referer":"https://auth.erictapen.name/"}
```

```
Feb 21 12:54:16 myserver kanidmd[67753]: 9822f889-5e58-48b3-aa9e-f253c1af3c59 2022-02-21T11:54:16.622790209+00:00 TRACE    tide-request [ 2.81ms | 100.000% ]
Feb 21 12:54:16 myserver kanidmd[67753]: 9822f889-5e58-48b3-aa9e-f253c1af3c59 2022-02-21T11:54:16.622925040+00:00 INFO     ┝━    [security.info]: Request received | src: "[::1]:36848" | http.host: "auth.erictapen.name" | http.method: "POST" | path: "/oauth2/authorise/permit"
Feb 21 12:54:16 myserver kanidmd[67753]: 9822f889-5e58-48b3-aa9e-f253c1af3c59 2022-02-21T11:54:16.625661814+00:00 INFO     ┕━    [request.info]: --> Response sent | status: 200 - OK
Feb 21 12:54:16 myserver kanidmd[67753]: f2e2d924-af9d-414b-9cd3-ad6da10c2202 2022-02-21T11:54:16.800712413+00:00 TRACE    tide-request [ 635µs | 100.000% ]
Feb 21 12:54:16 myserver kanidmd[67753]: f2e2d924-af9d-414b-9cd3-ad6da10c2202 2022-02-21T11:54:16.800727133+00:00 INFO     ┝━    [security.info]: Request received | src: "[::1]:36856" | http.host: "auth.erictapen.name" | http.method: "POST" | path: "/oauth2/token"
Feb 21 12:54:16 myserver kanidmd[67753]: f2e2d924-af9d-414b-9cd3-ad6da10c2202 2022-02-21T11:54:16.801347858+00:00 INFO     ┕━    [request.info]: --> Response sent | status: 200 - OK
Feb 21 12:54:16 myserver kanidmd[67753]: 4b8d8bec-f421-497b-a875-523bbc06269e 2022-02-21T11:54:16.804411485+00:00 TRACE    tide-request [ 363µs | 100.000% ]
Feb 21 12:54:16 myserver kanidmd[67753]: 4b8d8bec-f421-497b-a875-523bbc06269e 2022-02-21T11:54:16.804420202+00:00 INFO     ┝━    [security.info]: Request received | src: "[::1]:36858" | http.host: "auth.erictapen.name" | http.method: "GET" | path: "/oauth2/openid/gollum/userinfo"
Feb 21 12:54:16 myserver kanidmd[67753]: 4b8d8bec-f421-497b-a875-523bbc06269e 2022-02-21T11:54:16.804775133+00:00 INFO     ┕━    [request.info]: --> Response sent | status: 200 - OK
Feb 21 12:54:16 myserver kanidmd[67753]: cb4ad2cc-f437-4b48-9046-ded0cb79cc10 2022-02-21T11:54:16.988951900+00:00 TRACE    tide-request [ 176µs | 100.000% ]
Feb 21 12:54:16 myserver kanidmd[67753]: cb4ad2cc-f437-4b48-9046-ded0cb79cc10 2022-02-21T11:54:16.988972361+00:00 INFO     ┝━    [security.info]: Request received | src: "[::1]:36864" | http.host: "auth.erictapen.name" | http.method: "GET" | path: "/ui/oauth2"
Feb 21 12:54:16 myserver kanidmd[67753]: cb4ad2cc-f437-4b48-9046-ded0cb79cc10 2022-02-21T11:54:16.989130533+00:00 INFO     ┕━    [request.info]: --> Response sent | status: 200 - OK
Feb 21 12:54:17 myserver kanidmd[67753]: 2aa242f7-bf93-4643-89d3-3dfaf622fe19 2022-02-21T11:54:17.147521881+00:00 TRACE    tide-request [ 451µs | 100.000% ]
Feb 21 12:54:17 myserver kanidmd[67753]: 2aa242f7-bf93-4643-89d3-3dfaf622fe19 2022-02-21T11:54:17.147541744+00:00 INFO     ┝━    [security.info]: Request received | src: "[::1]:36866" | http.host: "auth.erictapen.name" | http.method: "GET" | path: "/v1/auth/valid"
Feb 21 12:54:17 myserver kanidmd[67753]: 2aa242f7-bf93-4643-89d3-3dfaf622fe19 2022-02-21T11:54:17.147973576+00:00 INFO     ┕━    [request.info]: --> Response sent | status: 200 - OK
Feb 21 12:54:17 myserver kanidmd[67753]: e0ef4cc0-eec3-4c61-a5d2-0dd0207fda79 2022-02-21T11:54:17.194284967+00:00 TRACE    tide-request [ 895µs | 100.000% ]
Feb 21 12:54:17 myserver kanidmd[67753]: e0ef4cc0-eec3-4c61-a5d2-0dd0207fda79 2022-02-21T11:54:17.194304537+00:00 INFO     ┝━    [security.info]: Request received | src: "[::1]:36868" | http.host: "auth.erictapen.name" | http.method: "POST" | path: "/oauth2/authorise"
Feb 21 12:54:17 myserver kanidmd[67753]: e0ef4cc0-eec3-4c61-a5d2-0dd0207fda79 2022-02-21T11:54:17.195178459+00:00 INFO     ┕━    [request.info]: --> Response sent | status: 200 - OK
```

Using vouch-proxy from https://github.com/vouch/vouch-proxy/pull/310 and kanidm from current master still works flawlessly.

**Comment by Firstyear** [comment]
About the only way we could fix this is to add username as a claim duplicating preferred usecrname but I'd rather not ....

**Comment by Firstyear** [comment]
@erictapen Did vouch-proxy ever update to resolve this?

**Comment by Firstyear** [comment]
@erictapen Okay, I think since it's specifically a vouch-proxy bug (they are incorrectly using claims in oidc) rather than a kanidm issue, I'd like to close this :)

**Comment by daedric** [comment]
if someone like me stumble upon this issue, the current version (0.37) does work:

You need to `extend` an account with an email address and add the email scope.

```
$> kanidm account person extend XXX --mail "xxxx"
```
I've in my vouch-proxy scopes: `scopes = [ "login" "openid" "read_user" "profile" "email"];`
and then it works :)

**Comment by yaleman** [comment]
thanks for the update @daedric!

**Comment by Firstyear** [comment]
@daedric Is that something we could add to the book in https://github.com/kanidm/kanidm/blob/master/kanidm_book/src/integrations/oauth2.md ?

**Comment by daedric** [comment]
@yaleman thanks but is it more of an @erictapen success :)
@Firstyear maybe it is more of a "faq" issue since from what I understood it is not a standard behavior from vouch-proxy?
In any case, I'd be glad to do a PR :)

**Comment by Firstyear** [comment]
> @yaleman thanks but is it more of an @erictapen success :) @Firstyear maybe it is more of a "faq" issue since from what I understood it is not a standard behavior from vouch-proxy? In any case, I'd be glad to do a PR :)

That would be great, especially around the minimum versions required for it to work :)
