### ISSUE TITLE
❌ error site when requesting /ui/oauth2

### ISSUE THREAD

**Issue by erictapen** [kanidm/kanidm#601]
Working on #600 currently I'm debugging the case of a site only displaying ❌. Kanidm logs (`log_level` is `verbose`) are very sparse in that regard. `auth.erictapen.name` is my kanidm instance. I'm running latest `master` (a993eb9cf35e75e853b453adab5848188471c339).

```
TRACE    tide-request [ 382µs | 100.000% ]
INFO     ┝━ 💬 [request.info]: Request received | src: "[::1]:54666" | http.host: "auth.erictapen.name" | http.method: "GET" | path: "/ui/oauth2"
INFO     ┕━ 💬 [request.info]: --> Response sent | status: 200 - OK

```

The url I'm requesting in my browser is `https://auth.erictapen.name/ui/oauth2?client_id=gollum&redirect_uri=https%3A%2F%2Flogin.erictapen.name%2Fauth&response_type=code&scope=login&state=<redacted>`.

It looks like I'm running into `State::ErrInvalidRequest` in `kanidmd_web_ui/src/oauth2.rs`. I see that some error cases are logged via `ConsoleService::log()`. Is there any way to see these log messages?

**Comment by yaleman** [comment]
I'm looking at this issue as well trying to integrate with oauth2 - the yew [ConsoleService::log()](https://docs.rs/yew/0.18.0/yew/services/struct.ConsoleService.html) is supposed to send it to the user's browser - the page that drops to ❌ doesn't log state though...

**Comment by Firstyear** [comment]
I think I know what the error is.

**Comment by Firstyear** [comment]
@QnnOkabayashi An some point this issue is highlighting we need to be able to set the tracing level at runtime because currently we don't map the log levels from kani into tracing levels, but I can't find the correct apis to actually call to set that level? It seems to be baked in in spans? Can you advise on this?
