### ISSUE TITLE
Runtime-configurable log levels

### ISSUE THREAD

**Issue by QnnOkabayashi** [kanidm/kanidm#604]
We should be able to dynamically configure log levels at runtime for spans based on the configuration. To reduce configuration complexity, filters at the lowest level will apply to all higher levels.

**Comment by yaleman** [comment]
@Firstyear would you consider this done/implemented?

All the spans get logged based on level currently etc.

**Comment by Firstyear** [comment]
Well my thinking was to make it so that a admin could say "okay, let's mark the account of yaleman so that all their operations flag to debug, but everyone is info". That way specific user items could have targetted log level raises. But I think it may not be possible to actually achieve.

**Comment by yaleman** [comment]
🤔 that'd be the kind of thing we could handle in the new logging framework

**Comment by yaleman** [comment]
Actually that's covered in #263 - closing this one as it's runtime logging, rather than per-user-thingie-logging.
