### ISSUE TITLE
WebUI - error message on invalid username

### ISSUE THREAD

**Issue by yaleman** [kanidm/kanidm#609]
The web UI returns the following error when an invalid username is entered in the login flow:
```
An error has occured 😔

invalid type: string "nomatchingentries", 
expected struct AuthResponse at line 1 column 19
```

**Comment by yaleman** [comment]
Moved the original "user enumeration through login prompts" discussion to https://github.com/kanidm/kanidm/discussions/610

**Comment by Firstyear** [comment]
I think this could be a clearer message than it currently it is :)
