### ISSUE TITLE
Make `kanidmd domain_name_change` cheap if the name stays unchanged

### ISSUE THREAD

**Issue by erictapen** [kanidm/kanidm#622]
The context is that at https://github.com/NixOS/nixpkgs/pull/143134 @Flakebi and I are currently working on making kanidm easily deployable on NixOS. At NixOS we are very commited to declarative configuration. That goes smoothly for kanidm's TOML config, but not for `domain_name`, which [is considered database state](https://github.com/kanidm/kanidm/pull/617#issuecomment-978350062).

For cases like this, we usually make stuff configurable non-theless, but make the stateful nature of the change transparent to the end user. E.g. it is possible to automatically create databases for a Postgresql cluster by setting [`services.postgresql.ensureDatabases.mydb = [ "mydb ];`](https://search.nixos.org/options?channel=21.05&from=0&size=50&sort=relevance&type=packages&query=services.postgresql.ensureDatabases). Contrary to usual NixOS configuration, the database is not going to vanish if the line is removed from the config, therefore the "ensure" in the name.

For kanidmd we'd like to introduce an option `services.kanidm.ensureDomainName`, which would be only settable if `services.kanidm.config.settings.role != "ReadOnlyReplica"`. The easiest implementation would be to execute `kanidmd domain_name_change` at every service startup. But for that to work out, the implementation should just check if the name didn't change and then do nothing. The way I read the code that is currently not the case.

Alternatively you could provide a fast way to query the current domain_name via a kanidmd command? This way we could write a shell one-liner that executes the change only if the current name is different from the set one.

**Comment by yaleman** [comment]
I've added prechecks in #624 for the domain name change thing - it wasn't checking beforehand 😄

**Comment by erictapen** [comment]
Thanks!

**Comment by Firstyear** [comment]
@erictapen No problem, I think this is a really good idea for it to be a stateful command and to be cheap on that change. I still think my only concern here would be when you have two replicas (in the future) if you haven't deployed this change to both then they will "fight" about what state the domain name will be in. But that's a risk no matter what we do I think ... I think this solves your issue and if we hit that problem, we'll address it then.
