### ISSUE TITLE
how to combine "dynamicuser" with secure permissions for SSL certificates in non container deployments

### ISSUE THREAD

**Issue by darix** [kanidm/kanidm#637]
there is no user i can give access to the file via ACL e.g. and i am not sure storing certs as `u=rw,go=r` is the best idea.

**Comment by darix** [comment]
same problem applies to the packages config file

```
-rw-r-----    1 root     root                     2472 Jan  7 23:05 /etc/kanidm/server.toml
```

which ends up in "permission denied"

my usual solution would be `root:kanidm` with `u=rw,g=r,o=`

**Comment by yaleman** [comment]
This prompted me to ponder doing this properly so I tweaked my systemd startup script.

Given that the StateDirectory's owned by the DynamicUser, this should mitigate the risks of `chmod 444`'ing the cert files.

```
[Unit]
Description=kanidm, the IDM for rustaceans
After=network-online.target
Wants=network-online.target


[Service]
Type=simple
ExecStartPre=cp -uf /etc/kanidm/fullchain.pem /var/lib/kanidm/
ExecStartPre=cp -uf /etc/kanidm/privkey.pem /var/lib/kanidm/
ExecStartPre=chmod 444 /var/lib/kanidm/fullchain.pem
ExecStartPre=chmod 444 /var/lib/kanidm/privkey.pem

ExecStart=/usr/local/sbin/kanidmd server --config=/etc/kanidm/kanidmd.toml
Restart=on-failure
RestartSec=15s
WorkingDirectory=/var/lib/kanidm
DynamicUser=yes
StateDirectory=kanidm

[Install]
WantedBy=multi-user.target
```

**Comment by darix** [comment]
world readable files is not "correct"

my override file


```
[Service]
DynamicUser=no
User=kanidm
Group=kanidm
AmbientCapabilities=CAP_NET_BIND_SERVICE
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
```

**Comment by yaleman** [comment]
"Correct" would take into account the full path permissions, surely? 😄 

I've updated my previous solution to limit things further. The new update has `440` for the cert files and still using DynamicUser. 

There's some inherent protections in the systemd DynamicUser. The directory permissions enforced by it mean that without sudo/root, only the created user will be able to access them - `/var/lib/private` is `700` and owned by `root:root`. 

The kanidm database files are still world readable in that directory, either way...

**Comment by Firstyear** [comment]
Well, a big part is that it's hard to effectively check "what we own or not". We've previously discussed changing these checks in the past, but in this case I think that word readable *is* the answer since the upper directories in a dynamicuser environment are where the permissions are enforced.

**Comment by darix** [comment]
I would normally not put config data like certificates into the same directory as the data managed by the daemon.

**Comment by yaleman** [comment]
Alternatively, you could put them in the tempdir that is generated for the dynamicuser...?

**Comment by Firstyear** [comment]
@darix What's an actionable suggestion for this issue then? From my view this seems like a system configuration issue, not a bug in the project, so what is the outcome you want from reporting this? What changes could we consider?

**Comment by Firstyear** [comment]
Closing due to no response.
