### ISSUE TITLE
Does kanidm provide a website for demonstration

### ISSUE THREAD

**Issue by baoyachi** [kanidm/kanidm#640]

**Comment by yaleman** [comment]
Not at this time, but there's docker instances you can use to quickly spin one up!

**Comment by Firstyear** [comment]
Yep, as @yaleman said, there is no demo site, but it's very easy to start with  :)

**Comment by baoyachi** [comment]
oh. See.

**Comment by Firstyear** [comment]
https://kanidm.github.io/kanidm/
