### ISSUE TITLE
Changes to release process

### ISSUE THREAD

**Issue by Firstyear** [kanidm/kanidm#646]
Semi-relates to #645 

There are a small number of admin changes to the release process we need to make:

* Change release date by 1 month, to 1st may, causing a +1 to all the release months (agreed on in chat by community)
* Change from tagged releases to release branches (allows patch backports for N-1).
* Change current docs generation to have a "dev" and "release" stream, since currently docs are from master. (@yaleman can you pretty pls help here?)

**Comment by yaleman** [comment]
So like.. multiple available versions of docs? That could get fiddly on github pages :S

**Comment by Firstyear** [comment]
Yeah, that's what I was thinking.

**Comment by pando85** [comment]
I don't know if it is too much for what are you looking for but I have this done:
https://rash.sh/docs/rash/v1.7.0/

https://github.com/rash-sh/rash/blob/master/.github/workflows/pages.yml
https://github.com/rash-sh/rash-sh.github.io

I forked https://github.com/rook/rook.github.io .

Just for sharing.

**Comment by yaleman** [comment]
@pando85 that looks cool, but I'm *so* confused by how many different pieces you're pulling together!

**Comment by pando85** [comment]
mdbook + github pages. I just created a custom mdbook because I want to have some documentation automatically generated from code to avoid repetition, but if we stop that it could be simpler.

Also, if you don't want to set up a web page probably you can simplify it a lot more.

**Comment by yaleman** [comment]
Yep, we've already got cargo docs + mdbook (for the main site) in the repo - it generates https://kanidm.github.io/kanidm/

I've got some ideas around pushing more code-related docs back into the code, and keeping the book for "high level" things... but that'll take some pondering.

**Comment by Firstyear** [comment]
I think we could make the book build part of the release process, rather than a github action since a released version should not be changing much.

**Comment by Firstyear** [comment]
@yaleman given this is coming up, where could we commit a copy of the book content so that it's served online? IE so that we have "latest" and "stable"?

**Comment by yaleman** [comment]
🤔 I couldn't figure out a really simple way of doing that at the time, I'll have a play tonight... I have ideas

**Comment by yaleman** [comment]
Seems to be working, so that's a thing. Someone really needs to push all the various code bits up to crates.io so the docs are done automagically 😁

**Comment by Firstyear** [comment]
> Seems to be working, so that's a thing. Someone really needs to push all the various code bits up to crates.io so the library docs are done automagically 😁

I do the crates.io docs release as part of the normal release so that's all good :)

**Comment by yaleman** [comment]
Argh I just realised you're stopping tagging, which breaks the docs automation 🙄

**Comment by Firstyear** [comment]
@yaleman No, I'll tag the first commit on the branch too. Should still work.

**Comment by Firstyear** [comment]
I think with the doc changes we are good to close this now? Since I'll apply these changes to the process in the next release?

**Comment by yaleman** [comment]
Seems good to me, I still have a bunch of fixing on the docs, but they're getting there.
