### ISSUE TITLE
Self-service 'person' attribute modification

### ISSUE THREAD

**Issue by euank** [kanidm/kanidm#648]
Currently, the canned access control policies don't include one for self-modification of your own email attribute.

The closest we have is this one:

https://github.com/kanidm/kanidm/blob/58fb559262163d9fcd748a8dda0e53ae41b9f266/kanidmd/src/lib/constants/acp.rs#L117-L122

I think I want to have self-service email modification, which naturally leads me to the questions:

1. Should there be a policy, perhaps `idm_self_acp_extend_person_mail`, to allow this?
2. Is there currently a way to create that without compiling it into the server binary?

Grepping around, I don't see an existing api (yet, I assume it'll be implemented at some point?), so I assume I just have to bake in any policies I want for now; is that understanding correct?

Thanks for the project btw, it's been great to play around with so far!

---

(new title, more issue description)

Self-service editing any person attribute via `kanidm account person set <self>` appears to not work.

See the first several comments below for more info on that.

**Comment by yaleman** [comment]
> 2. Is there currently a way to create that without compiling it into the server binary?

Not currently, I think @Firstyear has some ideas about implementation.

**Comment by Firstyear** [comment]
ACP allow modification, but it has to be done manually right now. Currently you can do this with:

```
kanidm login -D admin
kanidm raw modify '{"eq": ["uuid", "00000000-0000-0000-0000-ffffff000021"]}' changes.json
```

Where changes.json contains:

```
[
    { "present": ["acp_modify_removedattr", "mail"] },
    { "present": ["acp_modify_presentattr", "mail"] }
]
```

This will change the current definition of the self write access control to extend it to allow self write of mail. This IS upgrade safe, where during a migration we will NOT remove custom added attributes like this, we only assert the attributes that we supply are present. 

In the future we want to make access controls easier to supply and edit, but I'm considering an improvement to how they are currently definined, but I also plan to do on-upgrade migration so hopefully your use case will continue to work :) 


Hope that helps!

**Comment by Firstyear** [comment]
Oh you can also show the current set of access controls that exist with:

```
kanidm raw search '{"eq": ["class", "access_control_profile"]}'
```

You'll need to be logged in as admin to see these as well.

**Comment by Firstyear** [comment]
Hey @euank did you get a chance to try this out?

**Comment by euank** [comment]
Thanks a ton for the help, and thanks for following up!

I ran the above, but I ended up hitting an issue (and only just now got back to digging into it enough to give more info).

The issue I've running into is that it seems like the default self-write permissions aren't enough for the `_person/_extend` API to work.

Specifically, doing the following on a freshly created test account gives me the below error:

```
$ kanidm account person set testaccount --legalname "test" -D testaccount
Error -> Http(403, Some(AccessDenied), "e740a1cb-128d-4a0a-8598-fbab3d3f9ab5")

# server logs
(some extra 'search' logs prior to the write omitted)
....
e740a1cb-128d-4a0a-8598-fbab3d3f9ab5 2022-03-29T04:13:16.060869332+00:00 INFO     ┝━ 🔓 [security.access]: search attr decision | decision: true
e740a1cb-128d-4a0a-8598-fbab3d3f9ab5 2022-03-29T04:13:16.060873890+00:00 INFO     ┝━ 🔓 [security.access]: allowed 1 entries ✅
e740a1cb-128d-4a0a-8598-fbab3d3f9ab5 2022-03-29T04:13:16.060921877+00:00 INFO     ┝━ 🔓 [security.access]: Requested present set | requested_pres: {"class", "legalname"}
e740a1cb-128d-4a0a-8598-fbab3d3f9ab5 2022-03-29T04:13:16.060925890+00:00 INFO     ┝━ 🔓 [security.access]: Requested remove set | requested_rem: {"legalname"}
e740a1cb-128d-4a0a-8598-fbab3d3f9ab5 2022-03-29T04:13:16.060927853+00:00 INFO     ┝━ 🔓 [security.access]: Requested class set | requested_classes: {"person"}
e740a1cb-128d-4a0a-8598-fbab3d3f9ab5 2022-03-29T04:13:16.060935932+00:00 INFO     ┝━ 🔓 [security.access]: requested_pres is not a subset of allowed
e740a1cb-128d-4a0a-8598-fbab3d3f9ab5 2022-03-29T04:13:16.060937752+00:00 INFO     ┝━ 🔓 [security.access]: {"class", "legalname"} !⊆ {"displayname", "legalname", "mail", "name", "primary_credential", "radius_secret", "ssh_publickey", "unix_password"}
e740a1cb-128d-4a0a-8598-fbab3d3f9ab5 2022-03-29T04:13:16.060948869+00:00 INFO     ┝━ 🔓 [security.access]: denied ❌
e740a1cb-128d-4a0a-8598-fbab3d3f9ab5 2022-03-29T04:13:16.061075540+00:00 WARN     ┕━ ⚠️  [request.warn]: Client error --> Response sent | status: 403 - Forbidden
```

I can see that "mail" and "legalname" are both present in the allowed write set there, so that seems good! But "class" isn't, and from my reading of the code, it wants to also make sure that "class" contains "person" (contains person? is person?)

https://github.com/kanidm/kanidm/blob/3f7c692a7c5b54505b317b39be78d0d40aaafd8e/kanidmd/src/lib/actors/v1_write.rs#L973-L974

I can easily add a rule to allow setting "class", just like with "mail" above, but I'm not sure if that's right. Presumably letting an unprivileged user create other "class"es than "person" would be a security issue.
Maybe the access control policy can specify the "class=person" is a valid modification attribute, but not any other class?

The above's all based on speculation on my part. I don't think I have a deep enough understanding of kanidm to really know the right thing to do.

Is the "person extend" api meant to be usable in a self-service fashion? Am I missing something else here?

Thanks again for the help so far!

**Comment by Firstyear** [comment]
Ahhh I think the person has to "already be a person" for them to have this ability. Seems like a quirk of the way the cli is currently written I think that it's hitting that little trap. 

So you need to do "kanidm account person set -D idm_admin testaccount" first (which should setup the account to now be an account AND a person, then the "testaccount" should be able to go from there.

If that doesn't work, then it's a bug in the way the cli is working whichh I need to fix :)

**Comment by euank** [comment]
Having to make em a person first makes sense, but I still run into the same error after I do. The server logs for making a self-service change are identical after running the above idm_admin command, or after setting person attributes via idm_admin.

From my reading of the code, the same APIs called either way (`_person/_extend`), and that code just unconditionally adds a modification for `Modify::Present("class, person")`, so it at least makes sense to me why that's happening in both cases.

Maybe the server can figure out that the person bit's done and omit it in that case? Maybe the person API should really be split into a create person / modify person pair, rather than always putting in an implicit create person?

Anyway, I'll update the issue title to more accurately reflect this bug since it's a little different what the title currently says.

**Comment by Firstyear** [comment]
Yep, it's definitely a bug I think. I think in the CLI we need to seperate "extending an account to be a person" and "setting values of a person". So  Ithink the current _extend api has to stay "as is" because that actually does the class extension, but I think we need to add a person set or similar api. On the cli if I changed it to be:

```
kanidm account person extend <name> // the initial setup
kanidm account person set --mail blah // set a value
```

I think given this is intended to be self service, maybe we should consider exposing it under:

```
kanidm self set --mail ....
```

What do you think? Do you have any thoughts or suggestions on what seems nicer?

**Comment by euank** [comment]
I agree that moving it under `self` makes a lot of sense.

It also mirrors the current pair of commands we have of:

```
kanidm self set_password
kanidm account credential set_password <name>
```

Though if we keep adding things to the `self` namespace, it might get crowded enough that we want to have subcommands, like `self credential set_password`.

On the flip side, we already have a lot of stuff under `account` which is self-service by default and requires the name:

```
kanidm account credential register_{webauthn,totp} <name>
kanidm account credential {status,generate_backup_codes} <name>
kanidm account ssh {add_publickey,list_publickeys,delete_publickey} <name>
(etc etc)
```

I feel like a UX that would make a lot of sense to me would be to have most of the subcommands under `account` also exist under `self`, and under `self` they don't require the `<name>` attribute (automatically substituting in the authed user's name).

There are a few `account` commands that don't make sense under `self` (like create, list, maybe delete), so it seems like if we do take this approach, we'd need a mechanism to flag specific subcommands as shared or not.

All that said, I'm certain that you have more context than me, so your judgement on what makes the most sense is more likely to be right.
The short term thing to do is probably to just assert that some particular structure for self-service commands makes sense, figure out where the mail & legalname setters fit within that, and then fix those before tackling the broader restructuring work.

I'm also willing to give implementing this a try, as my spare time allows.

**Comment by Firstyear** [comment]
Please do give it a go! I'm happy to review and help out. I'm in the middle of another pretty big bit of work (self-service credential update + user onboarding) but I'll look at this after that if you haven't gotten to it by then :)

**Comment by euank** [comment]
With #667 being merged, I'll close this. My initial use-case, of self-service mail setting, now works with the above change + raw ACP modification.

The two followups I have are:

1. Update docs and/or default ACPs to make it clear how to make mail self-service.
2. Better CLI usage for self-service stuff, i.e. `self` commands for setting mail/legalname

For 1, I'll just open a PR modifying the ACP, and we can discuss there whether that's the right default or not. If it's not, I can turn it into a docs PR for how to make such a modification.

For 2, I'll file a separate issue to discuss some options there. I spent a little more time writing code on that, and I want a second opinion. I'll save the details for that issue.

**Comment by Firstyear** [comment]
Well, I'd rather not have "docs" on manually editing acps, as I'd rather proper cli tools to create and manage these. But I'm also considering rewriting a bit of their internals so I don't want to expose that yet. I think there is already an issue open to allow an admin to modify these though? 

And yes, the self command needs a bit of work, I think we should have an issue to talk about what it could look like. I think it would be nice if it was different to the account/person commands since it can be more focused.

**Comment by euank** [comment]
On the `self` stuff, I filed https://github.com/kanidm/kanidm/issues/668 with my current thoughts and with two questions I think we can start with.

Let me know if you have any thoughts or think there's a better place to start than that!

For 1, self-service mail, I agree documenting `raw` commands seems fraught. I think there still might be a reasonable thing to do in the meanwhile though!

I think that having `mail` be self-service-able in the default self-write ACP probably isn't right since some organizations may wish user emails to always be the organization's officially assigned mail or such, and those should only be editable by people-managers, not self. If we can just put it in the default though, that's an easy thing we could do now

If we don't want it in the default though, we can add a new acp for "self_write_mail", add some docs about granting that ACP to users who should be able to edit their own mail, and that should solve my original issue for anyone else who wants that functionality.

It would be preferable to have a proper way to create/edit ACPs, but it also seems perfectly reasonable to ship a canned one for "self-edit email address" since that seems like it'll be a relatively common one to want.

**Comment by Firstyear** [comment]
Yeah, I think you're correct, lets have a self_write_mail where if you are a member of some group, then you get that ability to self write. How does that sound? 

The main reason I want to avoid the acp update for now, is I want to restructure how they work internally to improve performance, since acp eval is currently a big chunk of our search path performance.
