### ISSUE TITLE
Could not run from source (kanidm v1.1.0-alpha.7)

### ISSUE THREAD

**Issue by Geo-7** [kanidm/kanidm#654]
Hi,
```
rustc --version
rustc 1.61.0-nightly (1d9c262ee 2022-03-26)
```
Based on this: [guide for developers](https://github.com/kanidm/kanidm/blob/master/DEVELOPER_README.md).
I created insecure keys & certs then:
```
cd kanidmd
cargo run -- recover_account -c ./server.toml -n admin
```
gives error:
```error: a bin target must be available for `cargo run` ```
then I :
```
chmod +x builder.sh
./builder.sh
```
also gives error:
```
error: failed to load source for dependency `concread`

Caused by:
  Unable to update https://github.com/kanidm/concread.git#9fc6e864

Caused by:
  can't checkout from 'https://github.com/kanidm/concread.git': you are in the offline mode (--offline)
```

1. removing "--offline" from kanidmd/builder.sh does not help
2. cargo build in parent folder dose not help either
3. downloading concread and try to build with RUSTFLAGS="-C target-feature=+avx2,+avx" cargo build --features=concread/simd_support gives error "error: none of the selected packages contains these features: concread/simd_support"
4. Installing https://github.com/MatanyaLoewenthal/rinstall and then ```rinstall apply install.yml``` gives error: ```thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/lib.rs:22:63 ```
5. remove "--offline" and "" and ./builder.sh and "cargo run -- recover_account -c ./server.toml -n admin" gives error "error: a bin target must be available for `cargo run`" 
6. try to cargo build in kanidmd folder dose not help

I think [guide for developers](https://github.com/kanidm/kanidm/blob/master/DEVELOPER_README.md) needs an update

**Comment by yaleman** [comment]
@Geo-7 thanks for calling this out, I'm guessing it relates to recent changes in the build workflow. I'll sort the docs in the next day or two, apologies for the inconvenience!

**Comment by Geo-7** [comment]
> @Geo-7 thanks for calling this out, I'm guessing it relates to recent changes in the build workflow. I'll sort the docs in the next day or two, apologies for the inconvenience!

Thanks for your quick response :) .

**Comment by Firstyear** [comment]
@yaleman is this related to the update concread ticket? I can get that done asap if yes.

**Comment by yaleman** [comment]
@Firstyear I don't think so, it looks like since some past re-organisation the docs are pretty out of date - they mention MSRV of 1.49.0 for starters 😄

**Comment by Firstyear** [comment]
@Geo-7 I've merged @yaleman's changes, would you mind re-testing with them? If that doesn't work let us know again and we're happy to help :)

**Comment by Geo-7** [comment]
> @Geo-7 I've merged @yaleman's changes, would you mind re-testing with them? If that doesn't work let us know again and we're happy to help :)

Sure, I'll inform you ASAP.

**Comment by Geo-7** [comment]
Thank you all, It is working now.
There is only one little warning, I do not know if you want to fix it in insecure_generate_tls.sh or not.
```2022-03-28T04:25:58.555424Z  WARN kanidm_client: permissions on /tmp/kanidm/ca.pem may not be secure. Should be readonly to running uid. This could be a security risk ...
2022-03-28T04:25:58.555485Z  WARN kanidm_client: /tmp/kanidm/ca.pem should be owned be root:root to prevent tampering ```

**Comment by yaleman** [comment]
That one's fine as-is, it's just a startup warning.

**Comment by Firstyear** [comment]
Yeah, it's a security hardening suggestion :) There are some ways we need to make that check a bit clearer though.
