### ISSUE TITLE
How to make PAM settings presistant?

### ISSUE THREAD

**Issue by vDorst** [kanidm/kanidm#662]
Every time I update my openSUSE tumbleweed and it updates PAM or some packages around it.
It rewrites the `/etc/pam.d/*` to default. So it overwrites all the kanidm-settings which is a pain.

How to make the kanidm settings presistant?

**Comment by Firstyear** [comment]
It's missing parts of the docs, I've put in a PR to clarify. Have a look and see if it helps :)
