### ISSUE TITLE
WebUI / Leap 15.3 / kanidm_tools 1.1.0-alpha.7

### ISSUE THREAD

**Issue by obel1x** [kanidm/kanidm#673]
I installed kanidm on Leap 15.3 and it seems to work by cmdline.

When i login into webui either with admin or with idm_admin, the page looks strange. I guess the Page should contain data, but i do only see "section title" and a table containing two rows having (with header) like:

"1,001 | random | data | placeholder | text | -- | -- | -- | -- | --"

on the left side, there is "Account" selectable, but when clicked, not really much happens.

i checked user demo_group and the data does not seem to be related.

Maybe some data missing, so the UI does not work like this?

**Comment by Firstyear** [comment]
Yes, the UI is a placeholder right now.

@yaleman I think we should make the config.toml default to noUi to avoid issues like this, so that in dev we can present them. Alternately we feature gate the UI because it's still such a WIP. What do you think? We keep the login/oauth pages though.

**Comment by obel1x** [comment]
you won the price for fastest answer - thank you  Ok, i read other threads asking about features there, so i guessed it would work. i am closing this for now

**Comment by Firstyear** [comment]
Gonna re-open because it is a valid issue! We shouldn't show placeholders like this, and I'd like @yaleman's thoughts :)

**Comment by obel1x** [comment]
ok. So my thoughts: delivering the webui- feature in "preview" mode is a good thing, as it can show how it could look like. Maybe add some header like / "Section title - Non functional WebUI right now" to make this intuitive

**Comment by yaleman** [comment]
If these things don't work then it's just styles failing to load IIRC - you can't login without the WASM stuff loading..

**Comment by cuberoot74088** [comment]
I agree with @yaleman about the "preview warning". 
Probably a stupid question, would the oauth2 flow still work without ui?

**Comment by yaleman** [comment]
@Firstyear I'll take this on over the weekend unless you have a desperate need to write HTML

**Comment by Firstyear** [comment]
@yaleman I don't need any distractions, because I really want to get credential on boarding done ahaha. So I'll leave it to you :)
