### ISSUE TITLE
kanidm-unix daemon returns parse error when the real issue is the CA key

### ISSUE THREAD

**Issue by matthew-salerno** [kanidm/kanidm#725]
### I did this
I tried running the kanidm-unix daemon. I got `ERROR kanidm_unixd: Failed to parse /etc/kanidm/config` 
This error was not caused by failure to parse, but strace reveals it was caused by permission denied on the CA key. Adding read permissions to the key fixed it.

### I expected the following
I expected the error to tell me the CA key could not be read.

### Kanidm version (and git commit)
1.1.0-alpha.7 c8468199fcdff481e3efe67516337b368de22f11

### Operating System / Version
Centos 9
Linux infra-2 5.14.0-52.el9.x86_64 #1 SMP PREEMPT Tue Feb 1 16:41:44 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Other notes
Ironically 
`permissions on /path/to/key may not be secure. Should be readonly to running uid. This could be a security risk ...` is still created when this happens. In fact this seems to be another bug on its own so I'll spin up a new issue

**Comment by yaleman** [comment]
I've updated the comment in the source - it's *supposed* to log errors when it fails to read the cert, but we've made changes to log handling over time and is throwing an `error!()` but that isn't bubbling up far enough by the looks of it.

**Comment by yaleman** [comment]
This *could* be similar to the issue with CA trust in #655

**Comment by Firstyear** [comment]
@yaleman It looks like a similar thing, we have tidied up a lot about tracing in alpha.8 compared to this, so I think this is resolved next release.

**Comment by Firstyear** [comment]
```
2022-05-01T03:02:11.289885Z ERROR kanidm_client: Unable to read metadata for /tmp/ca.crt - Os { code: 2, kind: NotFound, message: "No such file or directory" }
2022-05-01T03:02:11.289953Z ERROR kanidm_unixd: Failed to parse /etc/kanidm/config
```

From latest, so I think this can be resolved :)

**Comment by Firstyear** [comment]
@yaleman  @matthew-salerno This has been fixed up in the latest release, can we close this? :)

**Comment by yaleman** [comment]
Sure, this one's been fixed as far as I can tell.
