### ISSUE TITLE
permissions on /path/to/key may not be secure

### ISSUE THREAD

**Issue by matthew-salerno** [kanidm/kanidm#726]
### I did this
I ran `RUST_LOG=debug /usr/sbin/kanidm_unixd` and received the warning:  
```permissions on /my/key.crt may not be secure. Should be readonly to running uid. This could be a security risk ... ```  
Despite my permissions being set to 644. 

### I expected the following
I expected not to get the warning 

### Kanidm version (and git commit)
1.1.0-alpha.7 c8468199fcdff481e3efe67516337b368de22f11
[kanidm(d) --version]

### Operating System / Version
Centos 9
Linux infra-2 5.14.0-52.el9.x86_64 #1 SMP PREEMPT Tue Feb 1 16:41:44 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Any other comments
I noticed that the daemon does not do this for the config files, which use a different mechanism with your `file_permissions_readonly` helper function from `utils.rs`, whereas the part responsible for this message, uses `!ca_meta.permissions().readonly()` on line [115](https://github.com/kanidm/kanidm/blob/c8468199fcdff481e3efe67516337b368de22f11/kanidm_client/src/lib.rs#L115) in kanidm_client.

**Comment by yaleman** [comment]
What user were you running it as? I can see a possible logic issue where if you were running it as root, it shouldn't throw the warning.

The intention is that the file is read-only to the user running the daemon.

**Comment by Firstyear** [comment]
> Despite my permissions being set to 644.

Can you provide the ls -al  of the key.crt so we know what user owns it and what group owns it, and the uid:gid of the user you are trying to launch kanidm_unixd as?

You're probably right about the different path for the readonly check though, there are a lot of limitations in the rust "readonly()" check that we've learnt about :)

**Comment by Firstyear** [comment]
@yaleman It looks like they are running alpha.7, so this actually has already been resolved in latest and we are about to release it. I found one place that was a little inconsistent on a review, but this should be working in alpha.8

**Comment by Firstyear** [comment]
```
2022-05-01T03:01:04.209077Z  WARN kanidm_client: /tmp/ca.crt should be owned be root:root to prevent tampering
2022-05-01T03:01:04.209150Z  WARN kanidm_client: permissions on /tmp/ca.crt may not be secure. Should be set to 0o644. This could be a security risk ...
```

Permission check is different now, should clear this up :)

**Comment by matthew-salerno** [comment]
Thanks for forcing me to double check permission, it looks like I'm doing something wrong that's specific to redhat servers. I think I'm supposed to be using a tool generated key from somewhere else. I have no idea why I was getting that error, my best guess is I accidently forgot to leave root from a few previous operations  I was doing. I'm getting contradictory results now alongside different errors but my initial issue seems to be no longer relevant now that I'm following this issue down the rabbit hole.
