### ISSUE TITLE
Orca documentation/examples

### ISSUE THREAD

**Issue by yaleman** [kanidm/kanidm#728]
Plz can haz? Even just a simple "this command makes it go" because... the structopt things are confusing and I want to see if I'm making kani slow 😅

**Comment by Firstyear** [comment]
It's not so simple, orca "takes over" your database and assumes it can reset it and write arbitrary content. 

If you want a simple crash course, we could make a readme for the tool, but I'd rather leave it a bit quiet atm given it's still a work in progress.

Anyway, orca works in a few steps.

1. (Optional) preprocess an anonymised 389-ds access log (created from an external tool) into an orca data set.
2. Create an orca config which defines the targets you want to be able to setup and load test. See example_profiles/small/orca.toml
3. setup the kanidm/389-ds instance from the orca data set. You can see an example of this in example_profiles/small/data.json. This will reset the database, and add tons of entries etc. 
4. Run one of the metrics, based on that data set. For example `orca run -p  example_profiles/small/orca.toml [ds|kanidm|kanidm_ldap] search-basic

Currently the only metric we have is search-basic, which basicly just checks overall ability to do searches. I planned to add other tests based on write performance and different kinds of metrics.

**Comment by yaleman** [comment]
Sweet, this is entirely for speed-testing dev, so being able to blow up the DB's fine. 😄 I'll give that a go, thanks 😄
