### ISSUE TITLE
Import users from slapd

### ISSUE THREAD

**Issue by Firstyear** [kanidm/kanidm#734]
Develop tooling to help import users from slapd - see openldap_to_ds for prior work in this area

**Comment by mweinelt** [comment]
I tried getting the FreeIPA exporter to work with slapd, which led me to 

```
$ kanidm-ipa-sync -i ipasync.conf 
2023-06-06T13:15:49.593130Z ERROR kanidm_ipa_sync: Unsure how to handle refreshDeletes=True
2023-06-06T13:15:49.595217Z ERROR kanidm_ipa_sync: Sync completed with error e=Preprocess
```

I also had to remove filter parts, that lead to a filter including `(?expr)` pieces. Slapd does not seem to like those and returned no results.

slapd[72334]: conn=1003 op=0 BIND dn="cn=kanidm,dc=darmstadt,dc=ccc,dc=de" mech=SIMPLE bind_ssf=0 ssf=256
slapd[72334]: conn=1003 op=0 RESULT tag=97 err=0 qtime=0.000006 etime=0.065301 text=
slapd[72334]: conn=1003 op=1 SRCH base="ou=people,ou=accounts,dc=darmstadt,dc=ccc,dc=de" scope=2 deref=0 filter="(|(&(objectClass=person)(?objectClass=ipantuserattrs)(objectClass=posixAccount))(&(objectClass=groupOfNames)(?objectClass=ipausergroup)(!(?objectClass=mepmanagedentry))(!(cn=admins))(!(cn=ipausers)))(&(?objectClass=ipatoken)(?objectClass=ipatokentotp)))"
slapd[72334]: conn=1003 op=1 syncprov_op_search: got a search with a cookie=(null)
slapd[72334]: conn=1003 op=1 syncprov_search_response: cookie=rid=000,sid=002,csn=20220415194814.647229Z#000000#000#000000;20230605210722.820545Z#000000#001#000000;20230606131229.016435Z#000000#002#000000
slapd[72334]: conn=1003 op=1 SEARCH RESULT tag=101 err=0 qtime=0.000017 etime=0.000919 nentries=0 text=
slapd[72334]: conn=1003 fd=19 closed (connection lost)


After that I saw kanidm-ipa-sync do a search and get a reasonable number of users back.

```
conn=1030 op=1 SEARCH RESULT tag=101 err=0 qtime=0.000047 etime=0.002589 nentries=95 text=

```

The `refreshDeletes` issue above remains and needs more investigation.

**Comment by Firstyear** [comment]
Okay I think we'll need to clone the ipa exporter to a seperate tool. The way openldap is handling syncrepl is "confusing at best" and I've had to do a few experiments to work it out. 

It appears that on any entry *add* it sends a full refresh of all content with "refresh deletes=false". Similar it also sends a full list of the uuids with present_uuids and relies on a uuid being absent to imply deletion. 

So I'm going to need to change the way the scim sync works to handle these cases. 

Also remember that the way that freeipa/389-ds sync repl works is different to openldap so it's not a straight drop in. I have to work on this atm anyway, so I'll start on this. Will be done within a few days <3
