### ISSUE TITLE
docs - explain the Makefile options for developers

### ISSUE THREAD

**Issue by kellinm** [kanidm/kanidm#768]
**Documentation for Makefile usage**

As a developer, it would be handy to have documentation of options for the `Makefile` and a general theory of what's expected.

For example, I'm curious what [the `ARGS` reference is to a `redis` cache](https://github.com/kanidm/kanidm/blob/ec7c3cc6238459e7098c0ae948f4fb21fb27439e/Makefile#L7).

**Describe the solution you'd like**

Identify whether it is preferable to update `DEVELOPER_README.md` or create a new document with a clear name such as `BUILDING_CONTAINERS.md` and document the various options available to build a `kanidmd` container image.

**Describe alternatives you've considered**

There's the Star Wars method - `use the source, Luke` - which is what I used my first time through the process.

**Comment by yaleman** [comment]
I'd say the developer readme would be the best case at the moment, until we get to a point where the [book page](https://kanidm.github.io/kanidm/master/DEVELOPER_README.html) gets unreadable. 

The Makefile's a bit of a jumble at the moment, where I've hacked in docs/container build things...

The current value in `ARGS` is remnants of @Firstyear being the main dev and using [sccache](https://github.com/mozilla/sccache) as a compilation cache, but could be replaced with any developer-specific build-time arguments.

**Comment by Firstyear** [comment]
Yep, I've commented on the PR about what we can do to help change this to work for you. :)
