### ISSUE TITLE
system oauth2 create error response needs humanizing

### ISSUE THREAD

**Issue by yaleman** [kanidm/kanidm#803]
Just another :uwu: fix

Output:

```shell
kanidm system oauth2 create thing "name" example.com
2022-06-02T23:36:32.442716Z ERROR kanidm_cli::oauth2: Error -> Http(500, Some(InvalidAttribute("Invalid Url (whatwg/url) syntax")), "a2cfd6c5-d3a5-4e0c-b66a-bd7319c5db4c")
```

**Describe the solution you'd like**

More human-readable error for this one, like "Invalid origin specified: Invalid Url (whatwg/url) syntax"

I'll look into unpacking the error :smile:

**Comment by Firstyear** [comment]
Hey, at least it contains something semi-human inside! It's progress :P

**Comment by yaleman** [comment]
No judgement! Just acknowledgement of a thing I need to remind myself to do 😄
