### ISSUE TITLE
service_documentation field in oauth2 openid-configuration is incorrect

### ISSUE THREAD

**Issue by yaleman** [kanidm/kanidm#804]
### I did this

```shell
curl -v https://idm.example.com/oauth2/openid/:clientid:/.well-known/openid-configuration \
| grep service_documentation
```

### I expected the following

A valid URL in the field service_configuration (ie, https://kanidm.github.io/kanidm/stable/oauth2.html)

I got:

```
  "service_documentation": "https://kanidm.github.io/kanidm/oauth2.html",
```

### Kanidm version

```
kanidmd --version 
daemon 1.1.0-alpha.8
```
Valid as of 0b3fc8caf0c1d47c8d23f65fd16b87db64424033

### Operating System / Version

Opensuse Tumbleweed

### Any other comments

Code is here:

```
kanidmd/idm/src/idm/oauth2.rs
45:    static ref URL_SERVICE_DOCUMENTATION: Url =
46-        Url::parse("https://kanidm.github.io/kanidm/oauth2.html")
47-            .expect("Failed to parse oauth2 service documentation url");
```

**Comment by Firstyear** [comment]
Yeah, I think this shuold be pretty easy to resolve :)

**Comment by yaleman** [comment]
Yep, just keeping notes about the things I wanna fix 😄
