### ISSUE TITLE
kanidmd auto-built container doesn't have the web ui files

### ISSUE THREAD

**Issue by yaleman** [kanidm/kanidm#810]
### I did this

Ran the container

### I expected the following

The WebUI to be available

### Kanidm version (and git commit)

(the latest one as at naow)

`ghcr.io/kanidm/kanidmd@sha256:7ac44b5ef710fabe3c5dd260cb35c1764b97b1834a3b30957df159b9cd572abe`

### Any other comments

I'm the one that didn't package it, awks.

**Comment by Firstyear** [comment]
I forgive you <3

**Comment by yaleman** [comment]
Or maybe I did and the paths are all bent, but the container can't find the path 😄
