### ISSUE TITLE
recover_account  doesn't print password to stdout, and making it output in JSON

### ISSUE THREAD

**Issue by yaleman** [kanidm/kanidm#825]
**Is your feature request related to a problem? Please describe.**

I'm trying to reset the password as part of doing some automation, and the CLI's outputting both logs and the password output to stderr, which makes that harder.

**Describe the solution you'd like**

Ideally, an option to return the password/message as a JSON object like this (but on a single line):

```shell
kanidmd recover_account -n admin -c kanidmd --output json
```

Results in:

```json
{
  "result" : "success",
  "action" : "recover_account",
  "user" : "admin",
  "new_credential" : "<password>",
}
```

**Describe alternatives you've considered**

Implementing k8s secrets push from the `recover_admin` command, which .. is an integration far too deep into a particular ecosystem.

**Additional context**

Crabz R0ol. 🦀 ❤️

**Comment by Firstyear** [comment]
We probably also need it to mute logs by default in this mode.

**Comment by yaleman** [comment]
I was thinking we could/should force them to stderr somehow?

**Comment by Firstyear** [comment]
> I was thinking we could/should force them to stderr somehow?

I think it already is? 

https://github.com/kanidm/kanidm/blob/master/kanidmd/score/src/lib.rs#L530

**Comment by yaleman** [comment]
Oh I meant all the *other* logs 😄

**Comment by Firstyear** [comment]
Ahh yeah. They would go to stderr if I finally got off my ass and went to tracing-forest proper, we're still using the dev-version intree.
