### ISSUE TITLE
Content-Security-Policy Headers "interpreting self as a hostname"

### ISSUE THREAD

**Issue by yaleman** [kanidm/kanidm#849]
### I did this

Added the CSP headers in #740 

### I expected the following

Not making things worse 😄 The current one has a "self" entry without single quotes.

### Kanidm version (and git commit)

current - `kanidmd --version` is broken too!

### Operating System / Version

all

### Any other comments

Error from firefox:

```
Content Security Policy: Interpreting self as a hostname, not a keyword. If you intended this to be a keyword, use ‘self’ (wrapped in single quotes).
```

**Comment by Firstyear** [comment]
Where is the self ending up? That's a weird one ....

**Comment by yaleman** [comment]
The current headers are pretty permissive, including `https:` and `self` but they should just have `'self'` with the single quotes.
