### ISSUE TITLE
credential reset failed

### ISSUE THREAD

**Issue by Leoyzen** [kanidm/kanidm#873]
### I did this

kanidm account credential reset --name admin idm_admin  

### I expected the following

admin recovery success

### Kanidm version (and git commit)

1.1.0.beta-8

[kanidm(d) --version]

1.1.0.beta-8

### Operating System / Version

docker

### Any other comments

log shows internal error with status 500.

```
10a55e37-f1bd-43cd-87a3-5dfda54b9614 2022-06-28T15:34:32.366807473+00:00 INFO     ┝━    [security.info]: Request received | src: "192.168.1.6" | http.host: "idm.xxx.com:8443" | http.method: "POST" | path: "/v1/credential/_exchange_intent"
10a55e37-f1bd-43cd-87a3-5dfda54b9614 2022-06-28T15:34:32.367009378+00:00 INFO     ┝━    [security.info]: Rejecting Update Session - Intent Token does not exist (replication delay?)
10a55e37-f1bd-43cd-87a3-5dfda54b9614 2022-06-28T15:34:32.367040402+00:00 ERROR    ┝━ 🚨 [admin.error]: Failed to begin exchange_intent_credential_update | err: Wait(OffsetDateTime { utc_datetime: PrimitiveDateTime { date: Date { year: 2022, ordinal: 179 }, time: Time { hour: 15, minute: 37, second: 2, nanosecond: 366836200 } }, offset: UtcOffset { seconds: 0 } })
10a55e37-f1bd-43cd-87a3-5dfda54b9614 2022-06-28T15:34:32.367067873+00:00 ERROR    ┕━ 🚨 [request.error]: Internal error -> Response sent | status: 500 - Internal Server Error
```
I think maybe it related to time zone setup? (I'm using UTC+8 which now is 2022/06/28 23:37:02.

**Comment by yaleman** [comment]
If you're trying to reset the password for a user, please use the `account credential update` flow.

`account credential reset` consumes the result of the `create_reset_link` output, apologies if this was confusing.

**Comment by yaleman** [comment]
Or `kanidmd recover_account idm_admin` - I'm currently updating the docs around this in #871

**Comment by Firstyear** [comment]
@Leoyzen Yeah, it looks like you are trying to do the initial "account recovery" but using the credential reset flow which requires you to have done some other steps. Check out https://kanidm.github.io/kanidm/stable/server_configuration.html#default-admin-account

**Comment by yaleman** [comment]
I'm going to change the last verb of `account credential reset` to `use_reset_link` - unless someone comes up with a better verb 😄

**Comment by Firstyear** [comment]
It's not really using the "full link" but a "token" so use_reset_token? Or use_reset_pass? 

If we make it "use_reset_link" we should make it capable of identifying when someone pastes the URL in full, and then to trim out the token from that so that we are tolerant to people really pasting the full link.

**Comment by yaleman** [comment]
I'd totally support both to avoid confusion and also increase the possibility of me crying over parsers.

**Comment by Firstyear** [comment]
Heh, fair.

**Comment by yaleman** [comment]
I've created #875 to track the change

**Comment by Leoyzen** [comment]
I've already done using "account credential recover_account admin", and it still not works.

These are steps:

1. setup docker container and server.toml
2. `/sbin/kanidmd recover_account -n admin -c /data/server.toml`
3. `/sbin/kanidmd recover_account -n idm_admin -c /data/server.toml`
4. go to https://xxx:8443, and neither admin nor idm-amin can't be login. It shows `Account is temporarily locked`

Logs here

```
76678db1-bc8f-4816-ad6a-6fd21412f4f0 2022-06-29T03:00:08.376636369+00:00 INFO     ┝━    [security.info]: Request received | src: "192.168.1.4" | http.host: "xxxxx.xxx:8443" | http.method: "POST" | path: "/v1/auth"
76678db1-bc8f-4816-ad6a-6fd21412f4f0 2022-06-29T03:00:08.376715230+00:00 INFO     ┝━    [security.info]: Begin auth event | sessionid: None | req: AuthRequest { step: Init("admin") }
76678db1-bc8f-4816-ad6a-6fd21412f4f0 2022-06-29T03:00:08.376777506+00:00 INFO     ┝━    [security.info]: Initiating Authentication Session | entry: Entry<EntrySealed, _> { state: EntryCommitted { id: 102 }, valid: EntrySealed { uuid: 00000000-0000-0000-0000-000000000000 }, attrs: {"class": ValueSetIutf8 { set: {"account", "memberof", "object"} }, "description": ValueSetUtf8 { set: {"Builtin System Admin account."} }, "directmemberof": ValueSetRefer { set: {00000000-0000-0000-0000-000000000019, 00000000-0000-0000-0000-000000000020, 00000000-0000-0000-0000-000000000030} }, "displayname": ValueSetUtf8 { set: {"System Administrator"} }, "last_modified_cid": ValueSetCid { set: [Cid { ts: 1656430173.326481928s, d_uuid: 39251113-42f3-443c-bfe7-e84e12238987, s_uuid: f7d64ffe-99f6-4202-b0e9-6f237af046b2 }] }, "memberof": ValueSetRefer { set: {00000000-0000-0000-0000-000000000004, 00000000-0000-0000-0000-000000000008, 00000000-0000-0000-0000-000000000009, 00000000-0000-0000-0000-000000000010, 00000000-0000-0000-0000-000000000011, 00000000-0000-0000-0000-000000000012, 00000000-0000-0000-0000-000000000015, 00000000-0000-0000-0000-000000000016, 00000000-0000-0000-0000-000000000017, 00000000-0000-0000-0000-000000000019, 00000000-0000-0000-0000-000000000020, 00000000-0000-0000-0000-000000000025, 00000000-0000-0000-0000-000000000026, 00000000-0000-0000-0000-000000000027, 00000000-0000-0000-0000-000000000028, 00000000-0000-0000-0000-000000000029, 00000000-0000-0000-0000-000000000030, 00000000-0000-0000-0000-000000001000} }, "name": ValueSetIname { set: {"admin"} }, "spn": ValueSetSpn { set: [("admin", "xxxxx.xxx")] }, "uuid": ValueSetUuid { set: [00000000-0000-0000-0000-000000000000] }} } | uuid: 00000000-0000-0000-0000-000000000000
76678db1-bc8f-4816-ad6a-6fd21412f4f0 2022-06-29T03:00:08.376854867+00:00 INFO     ┝━    [security.info]: Account is softlocked, or has no credentials associated.
76678db1-bc8f-4816-ad6a-6fd21412f4f0 2022-06-29T03:00:08.376855848+00:00 INFO     ┝━    [security.info]: Authentication Session Unable to begin
76678db1-bc8f-4816-ad6a-6fd21412f4f0 2022-06-29T03:00:08.376880603+00:00 INFO     ┝━    [security.info]: Sending auth result | res: Ok(AuthResult { sessionid: 00000000-62bb-c038-1673-df142e571c73, state: Denied("Account is temporarily locked"), delay: None })
76678db1-bc8f-4816-ad6a-6fd21412f4f0 2022-06-29T03:00:08.376900434+00:00 INFO     ┕━    [request.info]: --> Response sent | status: 200 - OK

```

**Comment by Leoyzen** [comment]
The keypoint is `Account is softlocked, or has no credentials associated.` and I don't know what it means even searching issues and source code.

**Comment by Firstyear** [comment]
Are you persisting your database? You don't seem to have a volume listed in your commands, so it could be that your database is being reset between each command. You need to mount it to /data ...

**Comment by Leoyzen** [comment]
@Firstyear Of cause it is persisted. Here is the screenshots.
![图片](https://user-images.githubusercontent.com/5518468/176348274-55407d44-9ed9-43a9-a7bc-2b99eba7bfd3.png)

**Comment by Firstyear** [comment]
Can you screen shot the whole process from an empty container and include all the log outputs?

**Comment by yaleman** [comment]
Also, a dump of the environment variables and which specific docker container, please

**Comment by yaleman** [comment]
If you're recovering the account while kanidmd's running (ie, you've `docker exec`'d into it, that can cause issues.

**Comment by Firstyear** [comment]
Oooooooooooooo Yes, that would do it as well actually, since you'd change whats on disk but not in the ARC. We need to do process detection and prevent running when kanidmd already exists to prevent this.

**Comment by Leoyzen** [comment]
@yaleman @Firstyear yeah, it's the problem....I'm changing the password while the server instance is running.

Restart the server solved the problem.

**Comment by yaleman** [comment]
Glad we found the cause! #876 will hopefully guard against this one 😄
