### ISSUE TITLE
ensure that only one kanidmd is running at the same time

### ISSUE THREAD

**Issue by yaleman** [kanidm/kanidm#876]
### I did this

Ran kanidmd recover_account while kanidmd was running in another process.

### I expected the following

Password recovery - but it doesn't work until server restart, and can lead to db corruption

### Any other comments

- check for kanidmd
- maybe check for the db temp files too?

Ref comments in #873

**Comment by Firstyear** [comment]
Well, it's worse than that, it actually crould introduce DB/schema/other corruption. We need to actually refuse to run/open the db while another proc has it open.

**Comment by trissylegs** [comment]
SQLite has an exclusive access mode. Via:
```sqlite3
PRAGMA main.locking_mode=EXCLUSIVE; 
```

Meaning sqlite will grab the file lock and never let go of it.

https://www.sqlite.org/pragma.html#pragma_locking_mode

**Comment by yaleman** [comment]
IIRC backups are handled because it's all done in a transaction or something like that, I know I called it out at the time..

**Comment by Firstyear** [comment]
Backups are done in a read-txn so we don't need exclusive mode. The main issue here is what happens across a container boundary or similar. Also what happens in a crash?

**Comment by yaleman** [comment]
As in what happens if we take a pragma lock and the process?

**Comment by Firstyear** [comment]
there may actually be a way to do this, so we don't block at all, but the run of the admin tool can indicate in the DB that the next read/write need to cache flush and proceed. I think we could add a PID marker of "last write", and if that differs from our current PID we use this to trigger an update of the PID marker, and issue a cache flush. 

For now I think I set the DB into exclusive mode so it should start to fail on conflict now anyway.
