### ISSUE TITLE
Windows service support.

### ISSUE THREAD

**Issue by trissylegs** [kanidm/kanidm#94]
Windows services are executables that respond to certain windows messages appropriately.
Mostly that they Stop when asked to.

Microsoft prefers you to use .NET for this. They provide a bunch of useful libries and docs, but not so much for native.. I think we should run natively for the service. But a service installer (a necessary thing). Could be .NET.

**Comment by Firstyear** [comment]
This is a good idea I think - today I pass in a lot of options via cli (structopt), for configuration of the server or other actions like initial account recovery etc. Having a .NET wrapper that can wrap and give a good native experience there, and translate through to structopt or other would be great.

**Comment by NiryaAestus** [comment]
Hmm it seems they don't have such obviously favorable support in .net now. Either it's .NET Framework which currently get's very little love. (Especially ASP.NET).  

I found the service documentation for C++. The win32 is fairly comprehensive. Just not so search able the c# ones. MS apis use C style C++ so they tend to be callable from Rust.
https://docs.microsoft.com/en-us/windows/win32/services/service-functions

**Comment by NiryaAestus** [comment]
Oh and there is this: https://github.com/mullvad/windows-service-rs

**Comment by JJJollyjim** [comment]
Btw, someone has already wrapped this in a nice api based on the winapi crate: https://github.com/mullvad/windows-service-rs

**Comment by JJJollyjim** [comment]
Uh yes what you said :P

**Comment by JJJollyjim** [comment]
It also covers the installer API

**Comment by JJJollyjim** [comment]
Also, oof: https://github.com/retep998/winapi-rs/blob/0.3/RabbitCode.md

**Comment by NiryaAestus** [comment]
I suppose having a single binary handle: 
* Running as a console app
* Installing the service
* Being the service 
* Reconfiguring the service. 
Is not bad. This is literally what we do at work. Just used to MS docs splitting them up. (And we're failrly unorthodox at work sometimes)

**Comment by NiryaAestus** [comment]
So something like this:

    # Runs in console
    PS> kanidmd --console 
    # Create windows service with default Service Name using itself as executable.
    PS> kanidmd --win-service-install
    # Explicitly set service name and description
    PS> kanidmd --win-service-install "--win-service-name=Kanidm Daemon" "--win-service-description=Some description"
    # Explictly set to autostart
    PS> kanidmd --win-service-install --win-service-mode=Autostart
    # Remove all services installed as this particular binary. (A single binary can be installed a several services)
    PS> ./kanidmd --win-service-remove-all "--image=./kanidmd"

Or have some seperate "kinidmctl" for installing. Either way it seems easy enough for a system admin.
(And is probably usable via PowerShell remote management)

**Comment by yaleman** [comment]
See  #1906
