### ISSUE TITLE
Credential update modal - error on cancel

### ISSUE THREAD

**Issue by yaleman** [kanidm/kanidm#966]
### I did this

Click the blue cred update button in the security tab, then click cancel.

It reliably comes up with an error.

### I expected the following

Simple cancel and return to the UI.

### Kanidm version (and git commit)

Current head (container image 8ebdeed1aa02)

### Operating System / Version

Server: opensuse tumbleweed on linux, browser is edge/safari.

### Any other comments

<img width="774" alt="Screen Shot 2022-08-02 at 19 48 52" src="https://user-images.githubusercontent.com/168188/182345969-8e855922-a2fa-42d4-9c55-e20141c7fccf.png">

I like dogs, they're great.

**Comment by yaleman** [comment]
I think I know what this is, it's trying to send a "cancel the session" request but we haven't started one.

**Comment by Firstyear** [comment]
The moment you click to update the credential you should have started the session to update though?

**Comment by Firstyear** [comment]
Could this be related to the session id / token not being persisted properly over say a reload?

**Comment by yaleman** [comment]
Click this
<img width="553" alt="image" src="https://user-images.githubusercontent.com/168188/182827836-33544399-8b55-4ca4-9166-1f63f1a2a174.png">

Then click cancel - one hasn't started updating a credential yet as far as I can tell? ... then again, if I do the "add a passkey" process, then hit cancel, I get the same error.

b3dadaec-c229-4ac4-a2cf-ebef03a5d70f 2022-08-04T10:48:14.298760+00:00 ERROR    │  ┝━ 🚨 [request.error]: modify: empty modify request
b3dadaec-c229-4ac4-a2cf-ebef03a5d70f 2022-08-04T10:48:14.298797+00:00 ERROR    │  ┝━ 🚨 [request.error]:  | error: EmptyRequest
b3dadaec-c229-4ac4-a2cf-ebef03a5d70f 2022-08-04T10:48:14.299002+00:00 ERROR    │  ┕━ 🚨 [admin.error]: Failed to begin commit_credential_cancel | err: EmptyRequest
b3dadaec-c229-4ac4-a2cf-ebef03a5d70f 2022-08-04T10:48:14.299380+00:00 WARN     ┕━ ⚠️ [request.warn]: Client error --> Response sent | status: 400 - Bad Request

**Comment by Firstyear** [comment]
Nah, the token is there and it's in the inspector of network traffic. It looks like it's being lost somehow or not deserialised properly which means there is no token/body in the server so it (rightly) rejects the op

**Comment by yaleman** [comment]
Yeah, that's what I was looking at last night, I'm poking around in there at the moment and ... might find it ... 😆

**Comment by Firstyear** [comment]
It's there in the wireshark to the server, and it's correct json.

**Comment by Firstyear** [comment]
I'd say next we need to look at `505     let session_token: CUSessionToken = req.body_json().await?;` in kanidmd/score/src/https/v1.rs

**Comment by Firstyear** [comment]
Okay, I know what it is. It's a difference between when you use the credential update with an intent token vs not. Let me dig into the internals.
