### ISSUE TITLE
"version" output for all clients

### ISSUE THREAD

**Issue by yaleman** [kanidm/kanidm#989]
It'd be handy to be able to run `kanidmd version` and get the version (and git commit, at compile). 

This'd help with identifying which specific code you're running, to work out how @yaleman managed to break it this time.

**Describe the solution you'd like**

Where possible for all CLI programs, run `<program> version` (or `<program> --version` for the unixd-related ones?) and get something like:

```shell
$ kanidmd version
1.1.0-alpha.9 (7e617a63)
```

Bin list:

- [x] kanidmd
- [x] kanidm
- [x] kanidm_unixd
- [x] kanidm_cache_clear
- [x] kanidm_cache_invalidate
- [x] kanidm_ssh_authorizedkeys
- [x] kanidm_ssh_authorizedkeys_direct
- [x] kanidm_unixd
- [x] kanidm_unixd_status
- [ ] kanidm_unixd_tasks
- [ ] orca
- [x] kanidm_test_auth?

Note:

The [git-version](https://crates.io/crates/git-version) crate supports showing the commit, but it only works when you're running it from within a git repository. It'd take some modifications to `build.rs` or other ... build-time curiosities to make it work.

**Comment by Firstyear** [comment]
git-version has "fallback: If all else fails, this string will be given instead of reporting an error.". So we can embed something in there like the cargo/crate version I think. I think that's accessible via let version = env!("CARGO_PKG_VERSION"); per https://doc.rust-lang.org/cargo/reference/environment-variables.html

**Comment by yaleman** [comment]
Updated OP to mention how git-version works (it only works if you're actually in the repository) and updated the list.
